### ISSUE TITLE
H2H Fixtures wrong data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1007]
The H2H for this fixture had incorrect information, the teams drawn and the information displayed showed a victory.

https://scores.betarena.com/pt/futebol/casa-pia-gil-vicente-18560230

![Image](https://user-images.githubusercontent.com/37311649/214649174-f22796fa-6648-4823-9498-e840f70c7537.png)

**Comment by migbash** [comment]
**NOTES**

> Everything is correct, and as expected - it was not a draw, `Gil Vicente` won in penalties in `AP` which are not shown due to missing design of showing penalties on the `H2H`. So `UI` is correctly shown. 

> `Sportmonks` - `2016/10/16` Fixture -> https://soccer.sportmonks.com/api/v2.0/fixtures/1091072

> `Sofascore` https://www.sofascore.com/casa-pia-ac-gil-vicente-fc/kkbspCo

**Comment by jonsnowpt** [comment]
@migbash 

Simple change here:

The winning team keep the current font color, the losing team gets a lighter color: 

color: #8C8C8C;

**Comment by migbash** [comment]
**NOTES**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

It's not showing the winner:


![Image](https://user-images.githubusercontent.com/37311649/219130237-bd441440-14ad-4ae4-8e99-82b13f05d04a.png)
