### ISSUE TITLE
Tournaments fixtures missing Baiano 1

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1009]
🐛 Introduction:

The Baiano tournament fixtures are missing.

📝 Details:

The tournament is active and has fixtures happening, which can be checked here:

https://www.sofascore.com/en-us/tournament/soccer/brazil/baiano/374

🔍 Steps to Reproduce:

https://scores.betarena.com/pt/futebol/brasil/baiano-1

🤔 Expected Behavior:

Fixtures should be available and updated.

💥 Actual Behavior:

The fixtures widget is not available.

💡 Additional Information:

-

**Comment by migbash** [comment]
**NOTES**

- [x] backend
- [x] frontend -> `update for loaded variable correct update`

**Comment by jonsnowpt** [comment]
@migbash 

We are missing the standings information:

https://betarena-scores-platform.herokuapp.com/pt/futebol/brasil/baiano-1

**Comment by migbash** [comment]
**NOTES** 

> @jonsnowpt `Baiano 1` is not `domestic`, but a `domestic_cup`:

![Image](https://user-images.githubusercontent.com/20924663/219005746-27c23cf5-518b-41bf-b70b-cf0894904ae0.png)

**Comment by jonsnowpt** [comment]
@migbash 


The dometic_cup standings we already add them to the leagues, since we added the group stages.

**Comment by migbash** [comment]
> @jonsnowpt standings back up. Please check.

> @jonsnowpt domestic leagues only fixtures have their `standings (fixtures)` widget shown.

**Comment by jonsnowpt** [comment]
@migbash 

All domestic cups disappeared from the platform, including PROD.
