### ISSUE TITLE
Featured Match - Add "Watch the Match" information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1010]
🐛 Introduction:

To avoid the timer continuing to count on the Featured Match widget, we will change the behavior when the timer reaches "0".

📝 Details:

![Image](https://user-images.githubusercontent.com/37311649/214656293-d636e771-a07a-4bc9-afed-6eb0a890e370.png)

When the counter reaches "0" show the CTA to watch the match.

The screen may vary depending on the voting.

💡 Additional Information:

Translations added on:

`widget_featured_match_translations` [data]

**Comment by migbash** [comment]
**NOTE**

> Updated
