### ISSUE TITLE
Tournaments content is not updating

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1017]
🐛 Introduction:

Several tournaments do not have the SEO content updated.

📝 Details:

The content is updated at the final of each round; these changes are not being reflected on the platform.

🔍 Steps to Reproduce:

Visit, for example:

https://scores.betarena.com/football/australia/a-league

The content on the platform is dated from 16/01 when in the database is from 23/01.

![Image](https://user-images.githubusercontent.com/37311649/214789158-1125a81d-a061-49a8-8884-3772d88d0433.png)

🤔 Expected Behavior:

All tournaments should reflect the content available on the Database.

💥 Actual Behavior:

The content is outdated and not reflecting the content added to the database.

**Comment by migbash** [comment]
**NOTES**

> https://scores.betarena.com/football/australia/a-league - content was for `16/01` when `DB` is updated on `23/01` - noticed on `26/01`
> https://scores.betarena.com/pt/futebol/portugal/liga-portugal - content for `25-01-2023, 08:54 UTC` when DB is updated on `27-01-2023, 04:02 UTC` noticed on `31/01`
