### ISSUE TITLE
Wallet Connect for Dapp use on MetaMask

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1020]
🐛 Introduction:

The MetaMask wallet connection is working on the Desktop version but does not work on the MetaMask app has a Dapp. It seems that to get this working; we need to add Wallet Connect into the loop.

📝 Details:

The goal is to allow the Dapp to work on the MetaMask App; for this, we have the following resources:

https://forum.moralis.io/t/authentication-in-mobile-app/20949/2

https://docs.moralis.io/authentication-api/how-to-sign-in-with-walletconnect

This requirement was confirmed by the Moralis support guys.

🔍 Steps to Reproduce:

Enter the MetaMask App, and using the browser, try to access scores. Betarena and then Connect.

🤔 Expected Behavior:

Connect the MetaMask wallet.

💥 Actual Behavior:

Nothing happens.

💡 Additional Information:

We already have an account on Wallet Connect and a Betarena Project. Access details are available upon request.

**Comment by migbash** [comment]
**NOTES**

> WalletConnect not working with the `tutorial` from Moralis.

> Depreciated packages and not working `npm modules` from `WalletConnect` with a `V2` migration are required to get the code working, however, no `NEW🎖️` guide exists on `V2` Wallet connect support.

![Image](https://user-images.githubusercontent.com/20924663/219303844-8779532c-af81-4a1b-b8a2-a65a8dc9b8f9.png)

> Asking around forums [discord-link](https://discord.com/channels/819584798443569182/1073581868261326888/1073581868261326888) and other sources, can't seem to get it working either.

> Aim to get this sorted with `mobile` connection, and find a solution.

**Comment by jonsnowpt** [comment]
@migbash 

Did you submit a request to Moralis support?

**Comment by migbash** [comment]
@jonsnowpt Yes, but no response as of yet. I will follow up.

**Comment by jonsnowpt** [comment]
@migbash 

You have a chat available on the client area. They were very fast with me.

**Comment by migbash** [comment]
@jonsnowpt yes, but no response yet. Waiting to hear - used the `chat` feature also.

**Comment by migbash** [comment]
**NOTES**

> https://www.npmjs.com/package/@walletconnect/web3-provider
> https://docs.moralis.io/authentication-api/integrations/firebase-nodejs#authenticate-by-walletconnect-evm
> https://docs.walletconnect.com/2.0/javascript/web3wallet/wallet-usage
> https://docs.walletconnect.com/2.0/web3modal/html-js/installation
> https://forum.moralis.io/t/authentication-in-mobile-app/20949/7
> https://forum.moralis.io/t/authentication-in-mobile-app/20949/2
> https://forum.moralis.io/t/web3-mobile-phone-interactive-wallet-to-web-site-and-smart-contract/15429

**Comment by jonsnowpt** [comment]
@migbash 

Not working on Connect wallet in the user settings section.

**Comment by jonsnowpt** [comment]
@migbash 

The Button size is now incorrect:

![Image](https://user-images.githubusercontent.com/37311649/220320290-ea395568-c38c-4335-9456-27edee19ce6a.jpeg)
