### ISSUE TITLE
Users wallets not being added to Moralis users

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1024]
🐛 Introduction:

All registrations made through MetaMask should add a user on Firebase AUTH and Moralis. This is not happening at this time.

📝 Details:

Yesterday we had a user registered through MetaMask, we can see the user registration on Firebase AUTH, but no user has been added to Moralis.

🔍 Steps to Reproduce:

Register through MetaMask and check if the user is added to both platforms.

🤔 Expected Behavior:

Registration with the wallet should be added to Firebase AUTH and Moralis Users.

💥 Actual Behavior:

User registration is only adding users to the Firebase AUTH.

💡 Additional Information:

-

**Comment by migbash** [comment]
**NOTES**

> No errors found in the `Firebase | Extensions` for the `Moralis Auth` application logs...

![Image](https://user-images.githubusercontent.com/20924663/215175618-6bb0f227-d13f-44c4-a0ca-0c6b48072f50.png)
