### ISSUE TITLE
500 error at the Uruguay Primera Division page 

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1038]
🐛 Introduction:
Uruguayan tournament page is down.

📝 Details:

We receive a 500 error when visiting the page of Primera Division - Uruguay.

🔍 Steps to Reproduce:

Access the tournament page link:

https://scores.betarena.com/football/uruguay/primera-division

🤔 Expected Behavior:

It should contain the complete page with the tournament standings.

💥 Actual Behavior:

A 500 error is occurring and we do not have access to the page.

💡 Additional Information:

**Comment by jonsnowpt** [comment]
@nogueiravitorr 

Working at this time!
