### ISSUE TITLE
Missing standings and top players at Costa Rica tournament

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1039]
🐛 Introduction:

Standings are missing on the Costa Rica championship page.

📝 Details:

When visiting the Costa Rica Championship on Scores, information such as the standings and the list of top players is missing.

🔍 Steps to Reproduce:

Access the tournament page link:

https://scores.betarena.com/football/costa-rica/primera-division

🤔 Expected Behavior:

Should contain information about the standings and top players.

💥 Actual Behavior:

There is no information about the team rankings and the top player list.

💡 Additional Information:

**Comment by jonsnowpt** [comment]
Resolved.
