### ISSUE TITLE
Add FR Language

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1040]
update the `GraphQL` on `frontend / cache` for the addition of new `langauge` queries

**Comment by migbash** [comment]
**NOTES**

- [ ] re-run manually all `fixtures` to add new language translation
- [ ] re-run manually all tournaments
- [ ] re-run manually all pages and seo
- [ ] re-run manually all `hasura` links-map
- [ ] re-run manually all cache `related`
- [ ] validate

**Comment by migbash** [comment]
@jonsnowpt `Deployed to DEv`

**Comment by jonsnowpt** [comment]
@migbash 

A sport seems to be missing:

![Image](https://user-images.githubusercontent.com/37311649/220301309-62188e94-3d08-4f5f-9a0e-1e1f06bad02c.png)
![Image](https://user-images.githubusercontent.com/37311649/220301310-808b2e10-7adf-4a0b-a644-2164a2e891c9.png)

**Comment by migbash** [comment]
@jonsnowpt `scores_header_fixtures_information > other_sports (first sport) `[0]` value must match the name of:
`scores_header_translations > sports (first array value) `[0]` in here. Should be `Ice Hockey` - not `Hockey glace`.

**Comment by jonsnowpt** [comment]
@migbash 

Corrected.
