### ISSUE TITLE
Fixtures Blur image

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1042]
The top image has a blur that should not have:

https://betarena-scores-platform.herokuapp.com/football/arouca-santa-clara-18560254

![Image](https://user-images.githubusercontent.com/37311649/218799265-a7a5e6ea-8d88-4b2b-a920-14c2ba2f3938.png)

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt This is due to the selected image export from Figma in `.png` format - at a `0.25x` scale **~60kB**. Exporting at the default `x1.0` with no resolution drop is still the same **~600kB** as the `.svg` was... what to do ?

**Comment by jonsnowpt** [comment]
@migbash 

Image attached with 166kb.

In this cases, you can use:

https://imagecompressor.com/




![Image](https://user-images.githubusercontent.com/37311649/218974798-a9407fb8-ff7c-456c-aa3d-0155127f83e2.png)
