### ISSUE TITLE
DASHBOARD issues to review

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1044]
- [x] 1. Its allows username without any letters, min 3 characters;
- [x] 2. The username must be unique, should be verified if it already exists;
- [x] 3. Username can't have spaces or special characters;
- [x] 4. Connect with Metamask not working; `⏸️ pending`
- [x] 5. Users should never be able to access the settings without the login: https://betarena-scores-platform.herokuapp.com/u/settings/en
- [x] 6. Uploading a photo and how to center it does not work correctly; we must be able to reduce the size of the image, and also, what we add to the center of the circle does not save correctly.
- [x] 7. Limit the size of the photo to 1MB;
- [x] 8. I recommend to organize the photos and user media on Firebase Storage by ID;
- [x] 9. Registration type is not being added to the Firestore;
- [x] 10. Language is not being set on the Firestore neither inside the platform;
- [x] 11. The connect popup should fill up the margins;
- [x] 12. The connect popup is not centered on Firefox;

### 11:

![Image](https://user-images.githubusercontent.com/37311649/218807348-3c115512-f99f-4243-b3c6-e22edacba84b.png)

### 12:

![Image](https://user-images.githubusercontent.com/37311649/218807847-5f0a1e3e-7693-4ed3-9fc8-2d5e87d16060.png)

**Comment by migbash** [comment]
**NOTES**

> Need more information on 
- `6.` => as to how it should work exactly, and what are the issues experienced.
- `8.` => what should be organised on the storage as ?

**Comment by jonsnowpt** [comment]
@migbash 

6. I think the best way to describe is that you replicate how Github profile photo works;
8. userID => all media files;

**Comment by migbash** [comment]
**NOTES**

> `8.` already based off `UID`

![Image](https://user-images.githubusercontent.com/20924663/219027876-d2cda49e-3580-441f-b399-471b77ff71de.png)

**Comment by jonsnowpt** [comment]
@migbash 

In this case, it is pretended to be inside a folder (with the user ID). This is because since we are expecting the user to have lots of media files we need to avoid having thousands of files on one folder that will make difficult to manage through the GUI interface and difficult to associate the media to each user.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. MetaMask connect asking for Coinbase wallet again, the same issue we had before on registration;
- [ ] 2. https://betarena-scores-platform.herokuapp.com/u/dashboard/en is getting an internal error without login; I think it should be a 404;
- [ ] 3. The error messages are being shown in a popup and should be inside the layout;
- [ ] 4. We need to allow the underscore character: "_", also the usernames should be limited to 15 characters. The error messages should specify the issue and be translated. Please prepare the EN, and I will translate to other languages.
- [ ] 5. The profile photo still have issues.
- [ ] 6. Changing the language is not working correctly and also does not have any effect when accessing the platform neither being saved on Firestore;
- [ ] 7. Avoid seeing the "undefined" and profile status change, after logout the user should be immediately sent to the home;


### 3:

![Image](https://user-images.githubusercontent.com/37311649/219361202-14b9686c-218a-4446-9f3f-69e6deeef259.png)
![Image](https://user-images.githubusercontent.com/37311649/219361203-1f42abc1-9ca2-4342-a6ca-15af68bba0c0.png)


### 5:

https://user-images.githubusercontent.com/37311649/219362908-32321099-3851-4025-826b-68480d8f12b2.mp4


### 6:

![Image](https://user-images.githubusercontent.com/37311649/219364121-e6a5f01c-aab2-47ec-8617-777afdae80ff.png)


### 7:

https://user-images.githubusercontent.com/37311649/219364893-819612b3-2933-4a7e-8fb9-581f8e823f9b.mp4

**Comment by migbash** [comment]
`5.` related to #1058

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Redirect users when trying to access the profile section without the login;
- [ ] Translations are not working;

**Comment by migbash** [comment]
@jonsnowpt added `error` translations for `profile-page` => `userame_update_error_msg`

**Comment by jonsnowpt** [comment]
@migbash 

All translated and expressions added.

**Comment by jonsnowpt** [comment]
@migbash 

We need a solution to the profile issue until Monday for the release.

**Comment by migbash** [comment]
@jonsnowpt `🚀 deployed | DEV`

**Comment by jonsnowpt** [comment]
@migbash 

Missing translation:

![Image](https://user-images.githubusercontent.com/37311649/219655961-f8a608ff-fe58-4497-9e1b-c897e56f1341.png)

Also added the following expressions that were missing:

```
  "profile":"Profile",
  "logout":"Logout",
```

**Comment by jonsnowpt** [comment]
@migbash 

Added the translations to: 

`scores_header_translations + data`

**Comment by migbash** [comment]
@jonsnowpt `deployed on DEV`

**Comment by jonsnowpt** [comment]
@migbash 

We need to revert the image size limit to 10MB; if not no one will be able to send profile photos from their mobile device.

**Comment by jonsnowpt** [comment]
@migbash 

It's deforming the uploaded photo:

![Image](https://user-images.githubusercontent.com/37311649/220160338-91d07fe2-85c5-46f9-a6eb-5aa25d86dd84.jpeg)

**Comment by migbash** [comment]
@jonsnowpt `Deployed to DEV`
