### ISSUE TITLE
Fixture standings FORM inverted position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1048]
🐛 Introduction:

The form on the standings should have the latest fixtures on the right side.

📝 Details:

At this time, the form is showing the latest fixtures on the left side; we need to invert it to the right side.

🔍 Steps to Reproduce:

Visit:

https://scores.betarena.com/football/arsenal-manchester-city-18535272

Check the form:

![Image](https://user-images.githubusercontent.com/37311649/219003987-1ff8d1b8-73b0-4cee-bf96-99ac054fd9df.png)

🤔 Expected Behavior:

The form should have the latest fixtures on the right side, from left to right, and not the opposite.

💥 Actual Behavior:

Form at this time is showing from right to left.

**Comment by migbash** [comment]
**NOTE**

> Updated
