### ISSUE TITLE
Missing Champions League standings

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1057]
🐛 Introduction:

Standings are missing on the Champions League page.

📝 Details:

When visiting the UCL page on Scores, the group standings are missing. 

![image](https://user-images.githubusercontent.com/122905593/219239295-1e4f7641-f40d-4d84-ae32-26277424872c.png)

🔍 Steps to Reproduce:

Access the tournament page link:

https://scores.betarena.com/football/europe/champions-league

🤔 Expected Behavior:

The information from the group stage should be displayed, even if we don't have it from round of 16 onwards.

💥 Actual Behavior:

There is no information about the stadings in the competition. 

💡 Additional Information:

**Comment by jonsnowpt** [comment]
@nogueiravitorr 

Solved.
