### ISSUE TITLE
Create an `NPM Package` for `Typescript` types and interfaces

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1063]
**NOTES**

> The project has grown quite large very quickly. And to keep up with the `development` speed, with the `cache` and `frontend` sharing exactly the same `types` and `interfaces` - with being dependent on one another. Copying over constantly the `updated` interfaces and types slows development and is not ideal.

> SOLUTION: create an `NPM Package` with all the `types` and `interfaces` used by both `cache` and `scores-platform` for better management. As we have hundreds of different `types`.

---

@jonsnowpt https://docs.npmjs.com/creating-an-organization

**Comment by jonsnowpt** [comment]
@migbash 

Can it be public packages?

**Comment by migbash** [comment]
**NOTES**

> 🟢 `Live` on https://www.npmjs.com/package/@betarena/scores-lib, with it's repo on https://github.com/Betarena/scores-lib

> Utilized by the `scores (frontend)` and `cache` - sharing identifcal `declarations` and `methods` - easing up development.

**Comment by migbash** [comment]
**NOTES**

> Version labelled as major => `0.7.0` is release and is being tested - with bugs and fixes being made to bring it correctly, but issue can be closed as completed as groundwork is laid and no further tectonic shifts in the code structure/implementation have to be made, only corrections and add further documentation.
