### ISSUE TITLE
Missing Match Pages for "Paulista A1" League on Scores Platform

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1065]
🐛 Introduction:

In the scores platform, there are no match pages available for the league "Paulista A1" in any language
📝 Details:

No match pages available for the league "Paulista A1" : https://scores.betarena.com/pt/futebol/brasil/paulista-a1
- Not past matches nor future matches

🔍 Steps to Reproduce:

League page: https://scores.betarena.com/pt/futebol/brasil/paulista-a1
Choose any match from the Matches section, can be past or future

🤔 Expected Behavior:

Should open the match page, with the scores and stats

💥 Actual Behavior:

![image](https://user-images.githubusercontent.com/114171785/220163841-fdc0b1cf-f291-46ba-b3be-ca656046fbe5.png)

**Comment by jonsnowpt** [comment]
Solved!
