### ISSUE TITLE
Redirect Error on Scores Platform: 404 Page Not Found when Navigating Back to Football or Continent Pages

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1074]
🐛 Introduction:
Looks like a problem with the redirects on the scores platform

📝 Details:
When we open a match, and then try to go back to the football or continent page, we get this: "404
Uh-oh! This page does not exist!"

🔍 Steps to Reproduce:
 - Open any match page (example: https://scores.betarena.com/football/nantes-juventus-18723742)
 - Click the "Football", or the "Europe"button on the top left

🤔 Expected Behavior:
 - Expected to return to the desired page

💥 Actual Behavior:
![image](https://user-images.githubusercontent.com/114171785/220885530-74eea51a-a117-4845-950d-3a4da7d3f28c.png)

**Comment by jonsnowpt** [comment]
@Acard0so I have opened a similar issue.
