### ISSUE TITLE
Tournaments content not in Sync

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1079]
The tournaments cache data is not showing the Hasura data (This issue was reviewed before):

![Image](https://user-images.githubusercontent.com/37311649/221042713-e49e2615-6d64-48e1-a3f8-c703b4f08e83.png)

https://scores.betarena.com/pt/futebol/espanha/la-liga

![Image](https://user-images.githubusercontent.com/37311649/221042823-b0119c5a-88ea-452f-9828-47571c7fa0fe.png)

**Comment by migbash** [comment]
Related #1081 - `duplicate`
