### ISSUE TITLE
🔥 Hot Fix - Firestore Config

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1080]
Take a look at the Slack instructions I shared.

https://betarena.slack.com/archives/D02B1UHEECS/p1677229928721929

**Comment by migbash** [comment]
**NOTES**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

Sent you an update about this.

**Comment by migbash** [comment]
**NOTES**

> Updated
