### ISSUE TITLE
🔥 Hot Fix - Tournaments SEO and Fixtures SEO content (CACHE)

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1081]
Add to the cache the FR content. Endpoints:

```
scores_tournaments
historic_fixtures 
```

**Comment by migbash** [comment]
**NOTES**

> `scores_tournaments` is not in my control to update, must be via another service running @jonsnowpt 

![Image](https://user-images.githubusercontent.com/20924663/221369295-6dd85b9d-fa7e-4bc5-86a9-a93c58a007fe.png)

> `hiostoric_fixtures` updated to `show FR` SEO About Content

**Comment by jonsnowpt** [comment]
@migbash 

Still not showing:

https://scores.betarena.com/fr/football/juventus-torino-18546377

About the tournaments, I did not understand the remark. Can you clarify?

**Comment by jonsnowpt** [comment]
The tournaments on Hasura are already correctly updated:


![Image](https://user-images.githubusercontent.com/37311649/221377841-5e98cb02-7404-48a6-950c-7cc324f15281.png)

**Comment by jonsnowpt** [comment]
@migbash 

Still not in sync, and this content was sent at 4 am:

https://scores.betarena.com/fr/football/northern-ireland/championship


![Image](https://user-images.githubusercontent.com/37311649/221423962-b2f7a0d7-ce92-46b2-b65b-4ecd713d36bf.png)

**Comment by migbash** [comment]
**NOTES**

@jonsnowpt that content was sent at `04:12` - updated to run `CRON` at `05:00` to give it more time to update correctly and on time.

![Image](https://user-images.githubusercontent.com/20924663/221521864-e5272583-242a-43c8-b3b9-72e21e017853.png)
