### ISSUE TITLE
🔥 Hot Fix - FR Betting sites

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1084]
FR betting sites are not loading in the Scores platform:

![Image](https://user-images.githubusercontent.com/37311649/221647711-416767a6-98b6-48f5-bd62-4d0a2a7ba34b.png)

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt ⚠️ Missing the `scores_header_translations > bookmakers_countries` translations for `FR`. Missing for all languages, needs to be added.

![Image](https://user-images.githubusercontent.com/20924663/221655515-30bd5ad6-fd3e-4d5e-bba6-86b972e257c9.png)

**Comment by migbash** [comment]
@jonsnowpt should be `live`
