### ISSUE TITLE
Livescore v2 Review

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1085]
- [x] 1. The tournaments and fixtures SEO content is showing IDS and not the link itself as it should;
- [x] 2. Image elements do not have explicit width and height
- [ ] 3. ~~Missing source maps for large first-party JavaScript~~
- [ ] 4. ~~Low-speed performance~~
- [x] 5. Preloader not respecting the live score horizontal size;
- [x] 6. Analytics event not working
- [x] 7. Livescore not respecting different languages;
- [x] 8. Livescore not respecting the betting sites for each GEO;
- [x] 9. When a day is selected on the calendar, the calendar should be highlighted;
- [x] 10. Confirm if the fixtures on the Livescore respect the endpoint `leagues_supported_filter`(league_id = all supported fixtures in the livescore table, before the check more = featured_livescore_leagues)
- [x] 11. "Check more games" should be "Show less" when opened, and the mouse pointer should be the hand;
- [x] 12. "Check more games" should not be available on Live games;
- [x] 13. When "All" or "Live" are selected should be orange like on Figma;
- [x] 14. Missing tournament flag (27 Feb.) | `⏸️ pending` | `✅ resolved`
- [x] 15. The no-follow is inverted, it should be in the bookmaker, not our internal link
- [x] 16. Dark theme the time of the match when finished is different, also the border around the tip
- [x] 17. Dark theme the border of the preloader should be different
- [x] 18. Dark theme The calendar border should be dark
- [x] 19. Dark theme the current day should have the distinctive color
- [x] 20. Bottom borders do not seem to be in the correct position
- [x] 21. HT fixture the color should be red since the fixture is live;
- [ ] 22. ~~The Live Score seems to get the platform to go offline because of usage~~ | `❗️ anomaly (on-hold)`
- [x] 23. There are no "0" min in the fixtures. Also, the minutes are not updating on the LIVE tab.

### 1.

![Image](https://user-images.githubusercontent.com/37311649/221907995-75334a3b-94a7-46d3-9e15-105ec5cbbdd9.png)

### 2.

![Image](https://user-images.githubusercontent.com/37311649/221908659-9f6ff0c9-d352-4a4c-adeb-78add2e44405.png)

### 3.

![Image](https://user-images.githubusercontent.com/37311649/221909144-f57807ab-ec61-4a5d-81b9-075943ac5241.png)

### 4.

![Image](https://user-images.githubusercontent.com/37311649/221910006-e660a8c8-a7fd-4c01-95ae-3653e71bcd87.png)

![Image](https://user-images.githubusercontent.com/37311649/221910398-43c7ad87-7c70-4a8e-9612-46d60e728712.png)

### 5.

![Image](https://user-images.githubusercontent.com/37311649/221911387-fd8afbba-17b8-4291-b18d-a19c7b56147a.png)

### 6.

![Image](https://user-images.githubusercontent.com/37311649/221912042-a52e80c6-eb17-4796-81df-3e9e17eaa46d.png)

### 9.

![Image](https://user-images.githubusercontent.com/37311649/221912639-32b2be4a-976f-4d97-bb2b-7828e70c6c07.png)

### 11.

![Image](https://user-images.githubusercontent.com/37311649/221913922-98a3a895-2bf5-4c27-a1b9-ccbb29b69c6a.png)

### 13.

![Image](https://user-images.githubusercontent.com/37311649/221915448-fddab5c3-20cf-4b40-bd31-099bc813cae4.png)

### 14.

![Image](https://user-images.githubusercontent.com/37311649/221916286-6c7034f0-41a9-479a-b43d-cf1e6124322c.png)

### 15.

![Image](https://user-images.githubusercontent.com/37311649/221916978-faa92a57-1d97-4f48-a0ff-73606f81acc2.png)

### 16.

![Image](https://user-images.githubusercontent.com/37311649/221918448-2b13d071-1bae-4eed-b48f-917df31610fd.png)

### 17.

![Image](https://user-images.githubusercontent.com/37311649/221918798-4fe32dac-0ce2-4f75-a3cc-ae58ed37dd42.png)

### 18.

![Image](https://user-images.githubusercontent.com/37311649/221919005-2a6a9251-25a6-4308-ad82-5ffad87291a6.png)

### 20.

![Image](https://user-images.githubusercontent.com/37311649/221919616-50c603de-015d-4619-bb79-55b770fd7e47.png)

### 21.

![Image](https://user-images.githubusercontent.com/37311649/221924100-ba7a004e-a6a0-49c2-bf95-e15a2ae24aae.png)

### 22.

![Image](https://user-images.githubusercontent.com/37311649/221991412-fad1e6ad-8437-4d3b-9a1e-cd68b61af03a.png)

### 23.

![Image](https://user-images.githubusercontent.com/37311649/222139484-debdfffa-5343-48ec-8ac0-965acdbde7eb.png)

**Comment by migbash** [comment]
> @jonsnowpt for `14. Missing tournament flag (27 Feb.)` there is no data on the `iso2` or an `image`...

![Image](https://user-images.githubusercontent.com/20924663/222213942-690f7056-06a3-435e-bebe-95409fe45155.png)

> What do do ?

**Comment by jonsnowpt** [comment]
@migbash 

Use this flag for "null" values:

https://www.betarena.com/images/flags/EN.svg

**Comment by jonsnowpt** [comment]
@migbash 


- [ ] 7. Spanish "Check more games" is not translated;
- [ ] 8. FR betting sites are getting an error
- [ ] 10. Incorrect fixtures per day, Benfica for example, is not playing Saturday (Playing Friday)
- [ ] 11. Still missing the mouse pointer correctly on hover 
- [ ] 15, Still getting the "no-follow" on the fixture link;
- [ ] 20. bottom borders should have more space on the top.


### 10.

![Image](https://user-images.githubusercontent.com/37311649/222456568-d28a97a1-3553-405f-b47d-a48622d67778.png)


### 15.

![Image](https://user-images.githubusercontent.com/37311649/222457411-c292c12f-421b-4d3d-af68-e2d54dc23eac.png)

**Comment by migbash** [comment]
@jonsnowpt `7.` is missing the translation from the `scores_general_translation` for `ES`

**Comment by jonsnowpt** [comment]
@migbash 

Added.

**Comment by migbash** [comment]
@jonsnowpt `8.` betting sites are have been updated `(cache missing data)`. However, for the `leagues_filtered_country` - `FR` is missing when changing layouts. Needs to be added as it exists in the `navbar` - otheriwse the `default` will be used (`EN`).

**Comment by jonsnowpt** [comment]
@migbash 

Added.
