### ISSUE TITLE
Match Pages in English Instead of French When Accessing from Scores Platform in French

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1086]
🐛 Introduction:

When we are in the main scores platform page, in the French language, and we open any match page, it redirects to it, but in the English version, instead of the FR one

📝 Details:

Specifically, when accessing the main scores page in the French language and then clicking on any match to open its dedicated page, the page is displayed in English instead of French.

This issue is likely to cause confusion and inconvenience to users who prefer to navigate the platform in the French language. It can also lead to difficulties in finding the necessary information, as the page's content may not be easily understandable if displayed in a language the user is not familiar with.

🔍 Steps to Reproduce:

   1 - Open the scores platform in FR (https://scores.betarena.com/fr)
   2 - Click any match page

🤔 Expected Behavior:

   - Expected to get to the match page, with FR content

💥 Actual Behavior:

   - We are redirected to the match page, in English

**Comment by jonsnowpt** [comment]
@Acard0so 

Added in another issue.
