### ISSUE TITLE
Lang selection behavior change

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1089]
🐛 Introduction:

At this time, the lang change on the front of the platform is not affecting the Firestore language, creating issues when changing the language and browsing the platform.

📝 Details:

If the FR language is selected in the profile section and we change it on the platform home page and access a fixture it will redirect the fixture incorrectly.

🔍 Steps to Reproduce:

- Define a language in the profile section;
- Change it on the Homepage;
- Visit a fixture;

🤔 Expected Behavior:

Change the language in any section, get the same behavior, and correct link redirection.

💥 Actual Behavior:

Incorrect link redirect when browsing the fixtures in the platform.

💡 Additional Information:

Also, when a user visits the platform it should be redirected to his defined language (Firestore) and not be kept in the new language.

**Comment by migbash** [comment]
**NOTES**

> updated

**Comment by jonsnowpt** [comment]
@migbash 

Not working correctly.

The Live-Score is not changing the fixtures links accordingly.

**Comment by jonsnowpt** [comment]
@migbash 

Still need adjustments.

**Comment by migbash** [comment]
**NOTES**

> updated

> @jonsnowpt deployed to 🚀 DEV
