### ISSUE TITLE
Incidents - Team Names change to 3 letters abbreviation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1091]
Change the incidents team name to the 3-letter abbreviation:

![Image](https://user-images.githubusercontent.com/37311649/222238183-7c1ab3e5-b524-4314-accb-98b304521657.jpg)

**Comment by migbash** [comment]
**🟧 UPDATE**

- [ ] Necessary update to `scores-lib` for `short-name` data for **target** widgets.

**Comment by migbash** [comment]
via Hubstaff
User: Miguel Bacharov

Project: scores - https://app.hubstaff.com/projects/2983891
Date Range: 06/06/24 - 06/06/24
Work session total: 0:00:04
Billable: Yes

Grand total: 0:00:04
