### ISSUE TITLE
Missing ALT on images in several pages in the platform

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1094]
🐛 Introduction:

We have thousands of pages with image elements without alt="" information.

📝 Details:

The lack of `alt` information brings issues to the SEO of the platform, and the missing data should be added to the platform.

🔍 Steps to Reproduce:

Get information on the last audit of the platform:

131.446 images without `alt` info.

https://app.ahrefs.com/site-audit/3374534/34/data-explorer?columns=link_type%2Cnofollow%2Csource.url%2Csource_info.code%2Ctarget.url%2Ctarget_info.code%2Ctarget_info.no_crawl_reason%2Calt%2Csource_info.is_canonical%2Csource_info.is_noindex%2Ctarget_info.is_internal&filterId=6bdcf57238044fc10509c3bcfc8eca24&issueId=c64d9be3-d0f4-11e7-8ed1-001e67ed4656&lt=true

![Image](https://user-images.githubusercontent.com/37311649/222467494-f25022ac-be8c-4292-ab97-580116215be3.png)

🤔 Expected Behavior:

All images should have `alt` information available.

💥 Actual Behavior:

131.446 images without `alt` info.

**Comment by migbash** [comment]
**NOTE**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

Checking this later on PROD

**Comment by jonsnowpt** [comment]
Working.
