### ISSUE TITLE
Live Score V2 Mobile Review

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1096]
- [x] 1. Livescore width cant change when navigating through different days; it should be a fixed size depending on the resolution, and the team names should be cut with "..." if there is not enough space to show them;
- [x] 2. Confirm the spaces and sizes; the mobile spaces must be precise as in the design to get the most space available for the team names
- [x] 3. The font size of the tournaments and the time of the matches are not correct
- [x] 4. The calendar size should be identical to the width of the live score, like on Figma

### 1.

![Image](https://user-images.githubusercontent.com/37311649/222516605-a5f8abad-abb8-4089-984b-a8efd9f28fa4.png)

### 2.

![Image](https://user-images.githubusercontent.com/37311649/222517307-cac56a5c-7a60-4e34-be60-8a5689103901.png)
![Image](https://user-images.githubusercontent.com/37311649/222517308-f10c851b-7a55-4db7-a7ff-47904762cfc3.png)
![Image](https://user-images.githubusercontent.com/37311649/222517309-b54e5bcd-e8fd-4d0d-8093-d7ff773ea1c3.png)

### 4.

![Image](https://user-images.githubusercontent.com/37311649/222519016-b33ccdb3-54a8-41bd-8071-256aa54fe358.png)
![Image](https://user-images.githubusercontent.com/37311649/222519015-0240a4e4-7fca-4fbb-8810-f99f84408629.png)

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 2. The space from the betting site icon to the scores is still incorrect
- [ ] 9. The sizes are different on the All and Live
- [ ] 10. The blinking red icon should only be visible when live fixtures are happening
- [ ] 11. Change the Font Weight for the team names and scores to "500" on mobile


### 9.

![Image](https://user-images.githubusercontent.com/37311649/222784356-145f05fd-871b-4812-945e-00a93fe0dc18.png)

**Comment by migbash** [comment]
> @jonsnowpt updated

**Comment by jonsnowpt** [comment]
@migbash 

The header is not darkened with the calendar selection:

![Image](https://user-images.githubusercontent.com/37311649/223430872-675620d0-0ab6-451e-87b6-1091d61a140e.png)

**Comment by migbash** [comment]
> @jonsnowpt updated

**Comment by migbash** [comment]
> @jonsnowpt updated

**Comment by jonsnowpt** [comment]
@migbash 

Still not ok, check the FIGMA example:

![Image](https://user-images.githubusercontent.com/37311649/223509248-66f4307a-28ae-4e21-8c43-9a11db53236b.png)

**Comment by jonsnowpt** [comment]
@migbash 

Still the same.

**Comment by jonsnowpt** [comment]
Completed!
