### ISSUE TITLE
Missing World Cup Matches and SEO content

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1099]
🐛 Introduction:

The World Cup tournament is missing the fixtures and SEO content.

📝 Details:

At this time, and since the WC is over, we still should have all information about the fixtures and the SEO content.

🔍 Steps to Reproduce:

Visit: 

https://scores.betarena.com/fr/football/world/world-cup

![Image](https://user-images.githubusercontent.com/37311649/223085209-d2191a8f-7907-4add-ba6d-6540d3cae3e7.png)

🤔 Expected Behavior:

Able to see matches and SEO content.

💥 Actual Behavior:

There is no information about the fixtures or SEO content.

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt `fixtures` not showing because they only show for the `current-season`, and it appears something changed on `Sportmonk` that made this latest `world-cup` not the latest season...

<p float="left">
<img
src="https://user-images.githubusercontent.com/20924663/224988020-87820ea8-6ee0-4cec-9cb3-2f0ab946d7e3.png"
/>
<img
src="https://user-images.githubusercontent.com/20924663/224988400-a4a6d210-f31b-45f3-b923-793dc4560d63.png"
/>
</p>

**Comment by jonsnowpt** [comment]
@migbash 

I can see the fixtures here:

https://soccer.sportmonks.com/api/v2.0/seasons/:SEASON_ID?include=results

The SEO for FR needs to be manually sent; Im going to ask for this.

**Comment by jonsnowpt** [comment]
@migbash 

Still sorting it out!

**Comment by jonsnowpt** [comment]
Resolved.
