### ISSUE TITLE
🔥 Hot Fix - Firebase - live Updates issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1108]
🐛 Introduction:

Real-time updates on fixtures incidents, scores, and other events should update in real-time.

📝 Details:

Currently, when using the PWA live score updates on the live score table, fixtures and other platform parts with real-time updates stop updating.  Making it necessary to refresh the page or restart the PWA.

🔍 Steps to Reproduce:

Use the mobile version of the platform with the PWA and Safari browser. These issues were detected on both versions.

🤔 Expected Behavior:

Real-time updates when the browser is opened or when coming back to the browser to check updates, the same for the PWA version.

💥 Actual Behavior:

PWA stops updating, and in the mobile version in the browser, the same happens with less intensity.

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt require more information as cannot replicate the issue.

**Comment by jonsnowpt** [comment]
@migbash 

Added the video recordings and logs to Slack, which does not seem to be catching any issues, but it still gets stuck in updating the real-time data.

**Comment by jonsnowpt** [comment]
@migbash 

Sentry has a few errors with my IP; maybe it helps to sort out this issue:

`IP: 95.136.72.210`

**Comment by jonsnowpt** [comment]
@migbash 

Detected error:

![Image](https://user-images.githubusercontent.com/37311649/226603378-aa707e5a-13b4-4f5e-aca8-1806cdb6340a.png)


`Blocked a frame with origin "https://scores.betarena.com" from accessing a frame with origin "https://betarena-ios.firebaseapp.com". Protocols, domains, and ports must match.`

**Comment by jonsnowpt** [comment]
@migbash 

I changed a setting on Cloudflare and for now, this error is not being shown.

**Comment by migbash** [comment]
**NOTES**

> Addition of `Content Security Policy` for the application has been added, as the initially thought issue, due to it's effect on `Safari` strict security. Improving the `Ensure CSP is effective against XSS attacks` point of `Lighthouse`.

**Comment by jonsnowpt** [comment]
@migbash 

The issue persists, and we lose the WebSocket connection.

![Image](https://user-images.githubusercontent.com/37311649/227716753-cc5db758-8b98-438e-95f4-f7af265b8a8b.png)


```
There are several reasons why Firebase WebSockets might stop working. Here are some possible causes:

Network issues: Firebase WebSockets rely on a stable network connection between the client and the Firebase servers. If there is a network outage, poor network performance, or a disruption in connectivity, the WebSocket connection may stop working.

Server issues: Firebase WebSockets rely on the Firebase Realtime Database servers to function properly. If there are any issues with the servers, such as maintenance, downtime, or an outage, the WebSocket connection may stop working.

Connection limits: Firebase imposes connection limits for Realtime Database and Firestore, which can cause WebSocket connections to stop working if these limits are exceeded. If you have multiple clients connecting to the same database, it's important to manage the connections properly and ensure that you are not exceeding the connection limits.

Authentication issues: If there are any issues with the Firebase Authentication service, this can affect WebSocket connections. For example, if a user's authentication token expires or becomes invalid, the WebSocket connection may stop working.

Client-side issues: Issues with the client-side code, such as bugs or incorrect configuration settings, can also cause WebSocket connections to stop working.

To troubleshoot this issue, you can try the following:

Check the Firebase status page to see if there are any known issues or outages.

Check your network connection and ensure that there are no issues with connectivity.

Check your client-side code and ensure that it is properly configured and functioning as expected.

Monitor the Firebase connection limits to ensure that you are not exceeding them.

Check the Firebase Authentication service and ensure that there are no issues with authentication.

If none of these solutions work, you can contact Firebase support for further assistance.
```

In our case, the probable culprit should be a code issue.

**Comment by jonsnowpt** [comment]
https://github.com/Betarena/scores/issues/1108#issuecomment-1483387974

@migbash 

Has this been sent to `PROD`?

**Comment by jonsnowpt** [comment]
@migbash 

Maybe this technique might be useful:

`Keep connections alive using server-side techniques: To keep Firebase WebSocket connections alive from the server-side, you can use techniques such as sending keep-alive messages or using WebSocket ping/pong frames. By sending periodic messages to the client, you can ensure that the WebSocket connection stays open and prevent it from being closed due to inactivity.

Here is an example of how to use server-side techniques to keep Firebase WebSocket connections alive. In this example, we use a Cloud Function to send keep-alive messages to the client every 30 seconds:`


```javascript

const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

exports.keepAlive = functions.database.ref('/keepAlive').onUpdate((change, context) => {
  // Get the Firebase Realtime Database instance
  const database = admin.database();

  // Get the current timestamp
  const timestamp = new Date().getTime();

  // Update the "lastSeen" value for each connected client
  database.ref('/status').once('value', (snapshot) => {
    const status = snapshot.val();

    for (const key in status) {
      if (status.hasOwnProperty(key)) {
        const client = status[key];

        // Only update the "lastSeen" value if the client is connected
        if (client.connected) {
          database.ref(`/status/${key}/lastSeen`).set(timestamp);
        }
      }
    }
  });

  // Schedule the next keep-alive message in 30 seconds
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 30000);
  });
});


`


```
In this code, we define a Cloud Function that is triggered whenever the /keepAlive value is updated in the Firebase Realtime Database. When this function is triggered, it updates the lastSeen value for each connected client in the /status node of the database. This keeps the WebSocket connection alive by sending messages to the client every 30 seconds.

Note that this code assumes that you have a /status node in your Firebase Realtime Database that tracks the status of each connected client, and that you are updating this node whenever clients connect or disconnect. You may need to adjust the code to fit your specific use case.
```

**Comment by jonsnowpt** [comment]
Firebase updates do not work correctly when closing the devices and getting back to them later.

https://user-images.githubusercontent.com/37311649/235976813-04780754-fcfc-4a56-b84d-f31201ca4f06.MP4

**Comment by jonsnowpt** [comment]
![Image](https://github.com/Betarena/scores/assets/37311649/c7fb34f8-02f9-4fd7-bad8-ed6677dd87eb)

**Comment by jonsnowpt** [comment]
@migbash 

Still not working.

Desktop issues also:

![Image](https://github.com/Betarena/scores/assets/37311649/13c17d55-8b65-481b-87a8-aa04c0a60e81)
![Image](https://github.com/Betarena/scores/assets/37311649/6eff69c0-eb56-4fb1-ba4d-f646ae93470a)

**Comment by jonsnowpt** [comment]
@migbash 

It stopped and Im unable to click anything, the script was broken.

![Image](https://github.com/Betarena/scores/assets/37311649/d704c171-f74b-486c-9407-a50d46b6965d)
https://github.com/Betarena/scores/assets/37311649/2e26e323-174d-4f1c-9dae-ef400f9cc073

**Comment by meropis** [comment]
Some more information I'd like to put forward if it helps is that:
1. In order to help with debugging, this error persists for any browser that uses the webkit renderer. You can install a browser such as `epiphany` on linux where you can debug and test far more easily than loading up an IOS emulator etc;
2. If you are running a localhost development environment you'll find that when the error is thrown, if you have an existing auth object saved you can simply hot reload the environment (I use vite) and the auth will work correctly, even in an iframe;
3. CSP errors are fixable in most cases by using `window.postMessage` to make calls to external windows e.g. iframes. This is apparently not a possibility for this error after testing on my end. It is possible that someone with more experience may be able to find a way to pass the auth redirect back using `postMessage` and avoiding the CSP error, but I was unable to implement this.
I hope some of that will help in some way.

**Comment by jonsnowpt** [comment]
Thanks @meropis 

It seems that the issue was on iOS and Firebase. In the new iOS 17 the issue ceased to exist.
