### ISSUE TITLE
Footer - Accessibility Issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#111]
Lists do not contain only <li> elements and script supporting elements (<script> and <template>).

List items (<li>) are not contained within <ul> or <ol> parent elements.
![Screenshot 2022-01-05 at 13 08 19](https://user-images.githubusercontent.com/37311649/148222569-19df1c7e-9c8c-4021-94a0-f0b399460d30.png)

**Comment by migbash** [comment]
Corrected the `fix` for the `<li>` items - reflected in the next `PR`

**Comment by jonsnowpt** [comment]
@migbash 

Still getting an error here:

<img width="897" alt="Screenshot 2022-01-06 at 11 36 24" src="https://user-images.githubusercontent.com/37311649/148377211-9a2f828f-856a-41b3-84b4-0e87c53b8b89.png">

**Comment by migbash** [comment]
Updated and fixed - reflected in the `dev` -> `main` pull-request
