### ISSUE TITLE
Live Score Review V4

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1111]
- [x] 1. Tournaments font size different on "ALL" and "LIVE"

### 1.

![Image](https://user-images.githubusercontent.com/37311649/223717575-c60d9cd0-d270-47d3-a8e8-ac16efd27a6f.png)
![Image](https://user-images.githubusercontent.com/37311649/223717574-08a0316a-2085-497c-b5c0-8b11363ad975.png)

**Comment by migbash** [comment]
**NOTE**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

Still different:

![Image](https://user-images.githubusercontent.com/37311649/224793737-1890214f-1bf7-48c8-9d70-09f6a5fe715a.png)
![Image](https://user-images.githubusercontent.com/37311649/224793736-c9e3fc36-2039-4f76-a903-259e4bdd5a43.png)

**Comment by migbash** [comment]
**NOTE**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

Correct size, wrong position.

**Comment by migbash** [comment]
**NOTE**

> Updated

> @jonsnowpt deployed to 🚀 DEV
