### ISSUE TITLE
🔥 Hot Fix - Dates error on Scores platform

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1113]
🐛 Introduction:

We have a problem with dates on the Scores platform. This issue depends on the location of the user accessing it.

📝 Details:

Today is March 9th, and in the image, as you can see, it's showing March 8th on the live score.

![image](https://user-images.githubusercontent.com/122905593/224023297-bfd63ac9-6e90-4c29-b2e6-0f50502d15b3.png)

🔍 Steps to Reproduce:

Access the Livescore on the Scores platform and notice the error; if you're not from Brazil, this error may not be reproduced.

https://scores.betarena.com/

🤔 Expected Behavior:

It should display the correct date for all users on the platform, regardless of location.

💥 Actual Behavior:

Currently, it's showing the wrong date on our live score.

💡 Additional Information:

It may be related to GEO localization.

**Comment by migbash** [comment]
> @nogueiravitorr are you still seeing this error? Can you send me a `screenshot` ?

> @nogueiravitorr when does it occur ? When you navigate for the first time to the `scores.betarena.com` or when you have the `tab open` in the background and simply return to it after a period of inactivity ?

**Comment by nogueiravitorr** [comment]
@migbash Yes, as I commented, I'm still seeing this error. Here's a recording I just took.

https://user-images.githubusercontent.com/122905593/225073278-abca8bd9-882d-4635-ae07-f239888c5064.mp4

Whenever I open the plataform it already appears with incorrect date. The only change over time is the calendar date.

You can notice that as soon as I open the browser, the date is -1 at the top of the site, but when I open the calendar, it appears correctly as 14/03. After some time of use, the calendar also adjusts and shows the incorrect date as 13/03.
