### ISSUE TITLE
Players Football Frontend page generation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1115]
The Frontend will consume the data sent by the `scores_football_players` endpoint by publishing the various available player's pages. The endpoint `scores_widgets_list` supply the widgets that should be added to this section. The player's pages are only generated if the status indicates "published" 

---

#### 📱 TARGET PLATFORMS

Players' pages will be available on all versions, desktop, tablet, and mobile.

---

#### 🎬 INITIAL STATE

Data used for frontend page creation (endpoint: scores_football_players & scores_endpoints_translations):

**Breadcrumbs:** 

```
sport = scores_football_players
country = scores_football_players
tournament = scores_football_players
name + team name = scores_football_players
```

Page URL

```
type = scores_football_players
name = scores_football_players
id = scores_football_players
```

**Example:** `https://scores.betarena.com/pt/jogador/teddy-teuma/829643`

* Widget List Endpoint example

```
{
  "sport": "football",
  "section": "players"
}
```

SEO

The endpoint to get the SEO data: **scores_seo_players**. Depending on the language, the following data should be loaded:

```
main_data
opengraph
twitter_card
```

Make use of the hreflang for all available languages.

```
    <link rel="alternate" hrefLang="en" href="https://scores.betarena.com/player/teddy-teuma/829643">
    <link rel="alternate" hrefLang="it" href="https://scores.betarena.com/it/giocatore/teddy-teuma/829643">
    <link rel="alternate" hrefLang="es" href="https://scores.betarena.com/es/jugador/teddy-teuma/829643">
    <link rel="alternate" hrefLang="fr" href="https://scores.betarena.com/fr/joueur/teddy-teuma/829643">
    <link rel="alternate" hrefLang="pt" href="https://scores.betarena.com/pt/jogador/teddy-teuma/829643">
    <link rel="alternate" hrefLang=""pt-BR" href="https://scores.betarena.com/br/jogador/teddy-teuma/829643">
    <link rel="alternate" hrefLang="ro" href="https://scores.betarena.com/ro/jucator/teddy-teuma/829643">
    <link rel="alternate" hrefLang="se" href="https://scores.betarena.com/se/spelare/teddy-teuma/829643">
    <link rel="alternate" hrefLang="x-default" href="https://scores.betarena.com/player/teddy-teuma/829643">
    <link rel="canonical" href="https://scores.betarena.com/player/teddy-teuma/829643">
```

### Load the correct SEO information:

All expressions inside {} should be replaced by the correct variables depending on the language, endpoint:

scores_endpoints_translations

**SEO ENDPOINT:** scores_seo_players

Variables:

```
{type} 
{name}
{team}
```

**_Example content:_**

```
EN 

main_data

{
  "title": "{name} {team} videos, transfer history and stats - Betarena",
  "noindex": "false",
  "keywords": "{name}-{team}",
  "nofollow": "false",
  "canonical": "http://scores.betarena.com/{type}/{name}/{id}",
  "description": "Profile page for {team} player {name} videos, transfer history, matches, player ratings and much more available in the profile."
}

opengraph

{
  "url": "http://scores.betarena.com/{type}/{name}/{id}",
  "type": "website",
  "title": "{name} {team} videos, transfer history and stats - Betarena",
  "images": [
    {
      "alt": "Betarena Live Score",
      "url": "https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg",
      "width": 850,
      "height": 650
    }
  ],
  "locale": "en_GB",
  "description": "Profile page for {team} player {name} videos, transfer history, matches, player ratings and much more available in the profile."
}

twitter_card

{
  "site": "@betarenasocial",
  "image": "https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg",
  "title": "{name} {team} videos, transfer history and stats - Betarena",
  "imageAlt": "Betarena Live Score",
  "description": "Profile page for {team} player {name} videos, transfer history, matches, player ratings and much more available in the profile."
}

```

---

### Other relevant information:

Only players with the status "published" should be visible. 

We can disable or enable widgets view by adding or removing them from the endpoint:

`scores_widgets_list`

---

### Versions:

This section will be available on Light and Dark Theme.

---

### Data Endpoints:

**Hasura endpoint Prod:**

```
scores_seo_players
scores_endpoints_translations
scores_football_players
scores_general_translations
```

---

#### ⚡️ CACHE

Breadcrumbs links should be visible on the SEO Cache Data.

---

### Hreflang Support:

Add alternate lang pages for search engine optimization.

---

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena-%2F-Desktop?node-id=32%3A1635&t=fg4ONoUaucQHtoNf-1

![Image](https://user-images.githubusercontent.com/37311649/224087898-05ecad65-2af3-43cc-b3d7-a1e41fdeb254.png)

**Comment by jonsnowpt** [comment]
@migbash 

Is there any player published to test?

**Comment by migbash** [comment]
@jonsnowpt all players are made available, just use any of the `scores_football_players_v2` `url` column

**Comment by jonsnowpt** [comment]
@migbash 

They shouldn't. That is the reason we have "draft" and "published."

**Comment by jonsnowpt** [comment]
@migbash 

Issues:

- [ ] 1. The document doesn't have a valid hreflang
- [ ] 2. Content is sized correctly for the viewport
- [ ] 3. Mobile issues, the title should be shorted with "..." when no space is available;
- [ ] 4. hreflang URLs are incorrect;
- [ ] 5. Different langs not working properly;



### 1. 

![Image](https://user-images.githubusercontent.com/37311649/226954147-8891985c-83e1-45d8-b430-f608c18fcbc2.png)


### 2.

![Image](https://user-images.githubusercontent.com/37311649/226954407-16d8483a-b609-4fc0-9969-6f891cf80c25.png)


### 3.

![Image](https://user-images.githubusercontent.com/37311649/226955330-16e68eb0-7bfe-45b7-98a9-5065f383ca87.png)


### 4.

![Image](https://user-images.githubusercontent.com/37311649/226956474-5e25398a-79b0-43de-8bdb-0188392607a9.png)

![Image](https://user-images.githubusercontent.com/37311649/226956502-89f67e65-6211-424e-a58d-f0a55b6da59b.png)


### 5.

![Image](https://user-images.githubusercontent.com/37311649/226957008-cdac9147-78db-41ca-b0ea-d4cd324ea093.png)

**Comment by jonsnowpt** [comment]
@migbash 


- [ ] 6. Available chars should vary depending on the screen size;
- [ ] 7. The breadcrumbs are not correctly translated;
- [ ] 8. og_url is not correct;
- [ ] 9. The HREF here should be the player's page, not the tournament;


![Image](https://user-images.githubusercontent.com/37311649/227027761-8591aac3-bfab-45ed-aad9-e402e8a8b632.png)
![Image](https://user-images.githubusercontent.com/37311649/227027760-c1c959c9-3b0a-47ae-9aa1-46266c66401c.png)
![Image](https://user-images.githubusercontent.com/37311649/227027762-2f7fe04e-6fa2-4ce5-a14f-380f11bb297d.png)
![Image](https://user-images.githubusercontent.com/37311649/227027759-24b6588b-b8e8-4444-9a73-ebfb4498fe53.png)
