### ISSUE TITLE
Week/Round Reverts Back to Present When Opening Past Match Page in New Tab

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1120]
🐛 Introduction:

When searching for a past match and opening its match page on a new tab, the Week/Round goes back to the present instead of staying in the place we searched for the match page. This may affect if we are trying to open multiple match pages because we need to always keep going back to the desired week/round.

📝 Details:

The issue occurs when a user searches for a past match and opens its match page in a new tab. Instead of staying in the same week/round that was searched for, the Week/Round reverts back to the present. This makes it difficult to open multiple match pages because the user needs to keep going back to the desired week/round.

🔍 Steps to Reproduce:

1 - Open any league (ex.: https://scores.betarena.com/football/england/premier-league)
2 - Search for a past match clicking the left arrow.
3 - Right-click on any match and select "Open in New Tab".
4 - Notice that the Week/Round reverts back to the present instead of staying in the searched week/round.

🤔 Expected Behavior:

When opening a match page in a new tab, the Week/Round should stay in the same week/round that was searched for.

💥 Actual Behavior:

When opening a match page in a new tab, the Week/Round reverts back to the present instead of staying in the searched week/round.

1 - 
![image](https://user-images.githubusercontent.com/114171785/224751822-bf1f4b58-d811-42ac-a73c-eb19205e1183.png)

2 - 
![image](https://user-images.githubusercontent.com/114171785/224752051-bbc08f9f-1474-4ad0-946f-a37e467277a8.png)

3 - open match page
![image](https://user-images.githubusercontent.com/114171785/224752212-52c53de4-ad26-4e23-b881-31f4b0410966.png)

4 - when we go back to the website
![image](https://user-images.githubusercontent.com/114171785/224752426-9696aeee-00cd-4e35-b977-00fcc2e1b001.png)

**Comment by jonsnowpt** [comment]
The same is happening on Livescore. When we select check more in a few seconds it will close again without doing anything.

**Comment by jonsnowpt** [comment]
@migbash 

Still happening.

**Comment by jonsnowpt** [comment]
@migbash 

This is happening again:

https://betarena-scores-platform.herokuapp.com/football/ecuador/liga-pro

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena.slack.com/archives/D02B1UHEECS/p1687280962935869

**Comment by migbash** [comment]
@jonsnowpt Check.

**Comment by jonsnowpt** [comment]
@migbash 

It always happens on the first try, than if I force refresh starts to work.

**Comment by migbash** [comment]
**NOTES**

> Looks like target league with noticed `fixtures` problem issue, stems from the fact that it has no `start / end` dates...

- `league-id: 1679`
- `season-id: 20961`

https://soccer.sportmonks.com/api/v2.0/seasons/20961?include=stats,rounds,stages - `no rounds` data
