### ISSUE TITLE
Create `organisation` level `labels`

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1121]
**📝 DESCRIPTION**

> To ensure replicability of `labels` of `newly` created repositories and have the same kind of `issue labels` across all `organization` repositories, it's best to set these labels at the `organization` level:

https://docs.github.com/en/organizations/managing-organization-settings/managing-default-labels-for-repositories-in-your-organization

> Use the `scores` repository as the `template (default)` for reference.

**Comment by migbash** [comment]
@jonsnowpt This is for you to do, if you wish. Please check the `link` above in the original issue comment.

Basically, the idea was to have `labels`, such as:

<img width="222" alt="image" src="https://github.com/Betarena/scores/assets/20924663/f156752b-b1fe-45cf-9d73-7951d30042d7">

Be available across `ALL` GitHub Organisation repositories, such as: `scores`, `scores-lib`, `backend`, etc... This way, when delegating an issue initially created for the `frontend`, but then assigned to the `backend`, to not have to manually enter again the `labels (shown above)` and keeping them consistent.

**Comment by migbash** [comment]
> [!Note]
> **BUMP**
> @jonsnowpt 
> The reason for this issue, because sometimes, we create an issue for `scores`, but it's intended for `apidatanarratives` for example, and after I click `transfer issue` from one _repository_ to _another_, via `GitHub`  the issue labels are lost and re-adding the approximate ones is a bit annoying.

**Comment by jonsnowpt** [comment]
@migbash 

This has been done
