### ISSUE TITLE
Frontend - Football Player Profile (football_player_profile)

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1136]
#### 📝 DESCRIPTION

This widget will be the one that resumes the player profile; probably the approach would be similar to the one we have on the tournaments.

---

#### 📸 WIDGET IMAGE

![Image](https://user-images.githubusercontent.com/37311649/225628591-c79f50d4-5ea3-475e-9349-a995ba7b6fbe.png)

---

#### 📱 TARGET PLATFORMS

Available on all versions.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Widget verification to display

Verify if available on `widgets_list`

`scores_widgets_list`

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

The Follow option should not be available for now since we do not have this feature active. This can be added into the CSS but disabled for now.

---

### Versions:

Dark and Light theme supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| scores_football_players_v2 |

---

#### 🎏 TRANSLATIONS

**Translations endpoint**

| table | columns |
| ----- | --------- |
| football_player_profile_translations | **<translations>** |

---

#### ⚡️ CACHE

If a player's data has been updated, it should be cached. Use a fallback alternative in case of issues with the cache, getting the data directly from Hasura.

`players_data_updates`

Check [#1135](https://github.com/Betarena/scores/issues/1135) 

---

#### 🔎 SEO

Players' names should be available for SEO purposes, and it is an H1.

---

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena-%2F-Desktop?node-id=32%3A1635&t=y7zNmxwfzkJC7D3X-1

**Comment by jonsnowpt** [comment]
@migbash 

Corrections:

- [ ] 1.  The name on top should be the `display_name`;
- [ ] 2. Follow should be hidden for now since it's not working at this time;
- [ ] 3. Desktop CSS - Wrong spaces on the top right info;
- [ ] 4. Displays images with incorrect aspect ratio;
- [ ] 5. Ensure CSP is effective against XSS attacks;
- [ ] 6. Missing source maps for large first-party JavaScript
- [ ] 7. Mobile CSS - Wrong spaces
- [ ] 8. Tablet CSS - Wrong spaces
- [ ] 9. Preloader wrong position;
- [ ] 10. Follow button is not translated. (We are not using the Follow button for now but in the future)
- [ ] 11. Elements starting positions change when translations change; this should not happen.


### 3. 

![Image](https://user-images.githubusercontent.com/37311649/230036601-6c38b837-0548-4da9-8f80-a6b624309d4d.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/230036713-554c7e64-5a5b-4bf1-a698-35c60a005db8.png)

---

### 4.

![Image](https://user-images.githubusercontent.com/37311649/230037483-e721b14b-fdc9-4428-b2d3-ee979d4cae24.png)

---

### 5.

![Image](https://user-images.githubusercontent.com/37311649/230037705-5923750d-0727-4bac-b64a-caca204ee4a5.png)

---

### 6.

![Image](https://user-images.githubusercontent.com/37311649/230037855-897cbb63-7379-4b7c-b81f-b0fd4a237597.png)

---

### 7.

![Image](https://user-images.githubusercontent.com/37311649/230039512-3e07016a-a07b-4361-8ab3-f3495c3fc2e5.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/230039555-6c546ee5-9ea7-47ce-9e0e-da7c8f9de767.png)

---

### 8.

![Image](https://user-images.githubusercontent.com/37311649/230040033-b3aef97d-556d-47e7-b474-ca4f441432d5.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/230040157-833a36c9-942e-43e7-8199-146f0e9b89cb.png)

---

### 9.

https://user-images.githubusercontent.com/37311649/230040756-e4ebb00b-2cf1-4ab7-898f-4b640e554449.mp4

---

### 11

https://user-images.githubusercontent.com/37311649/230041846-5400e934-8761-43a4-809f-e43562229095.mp4

**Comment by migbash** [comment]
> @jonsnowpt  `10.` Some translations are missing from the `player_fixtures_translations`

**Comment by jonsnowpt** [comment]
- [ ] 1A. Missing months translations;
- [ ] 2A. Image elements do not have explicit width and height
- [ ] 4. Is still happening 
- [ ] 3A. The date format is not correct on mobile



### 1A.

![Image](https://user-images.githubusercontent.com/37311649/230388033-906d2b13-8909-410f-bc1d-11d45bd4ac79.png)


### 2A.

![Image](https://user-images.githubusercontent.com/37311649/230388287-f17e0464-96fd-447a-8701-941eceae829d.png)


### 3A.

![Image](https://user-images.githubusercontent.com/37311649/230389532-8a3bf8ab-7aa0-4139-a16f-25f7feb41640.png)

**Comment by jonsnowpt** [comment]
- [ ]  4. Displays images with incorrect aspect ratio;
- [ ] 4A. Changing lang takes several seconds to take effect and should be faster as on other sections of the platform;


### 4.

![Image](https://user-images.githubusercontent.com/37311649/232090331-4642c81f-75de-4f9a-834c-8c644cd9f243.png)

**Comment by migbash** [comment]
**NOTES**

>  `4A.` solved with `cached` responses for `latests/manual` triggered players data (cache).

**Comment by jonsnowpt** [comment]
@migbash 

Still happening:

![Image](https://user-images.githubusercontent.com/37311649/232293410-923334ea-787e-443f-a0a1-f77655921b36.png)

**Comment by migbash** [comment]
> @jonsnowpt cannot replicate:

![Image](https://user-images.githubusercontent.com/20924663/232316167-5b45d1f7-fc97-4fc7-985d-428405b7f99c.png)

> Are you on the `DEV` doing the `lighthouse` ?

![Image](https://user-images.githubusercontent.com/20924663/232316213-b4f2b741-4271-4017-b946-e6d06ed213c0.png)

**Comment by jonsnowpt** [comment]
@migbash 

Two issues:

![Image](https://user-images.githubusercontent.com/37311649/232328707-f1949c54-eb9d-4e95-bda2-cf09dc26458c.png)

**Comment by jonsnowpt** [comment]
@migbash 

The errors persist.
