### ISSUE TITLE
Dates error on Scores Plataform

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1143]
🐛 Introduction:

There is a new issue with dates on the platform. 
I checked around midnight (Brazil time zone) and there is an error with dates around this time.

📝 Details:

When it gets close to this time in Brazil, there is a bug in the panel with the closest dates than atual day. If you look at the screen recording, you can see that some days are missing (16, 18, 20, 22, 24, 26).

https://user-images.githubusercontent.com/122905593/225926434-b7eade42-fd81-4ea0-9a7e-829773df8cc3.mp4

🔍 Steps to Reproduce:
Access the Scores platform around midnight (Brazil time) and notice that this bug with the dates occurs.

[scores.betarena.com](url)

🤔 Expected Behavior:

Currently, it's showing the wrong date around midnight (Brazil time zone) on our live score.

💥 Actual Behavior:

Currently, it's showing the wrong date on our live score.

💡 Additional Information:

It may be related to GEO localization.

**Comment by jonsnowpt** [comment]
Resolved.
