### ISSUE TITLE
Football Player Fixtures (player_fixtures)

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1158]
#### 📝 DESCRIPTION

On this widget, the user can verify all matches the player performs with specific information on how the player's performance went.

This widget is similar to the fixtures widget on the tournaments; the big difference is that is adapted to the player and not to a specific tournament. In this case, it will aggregate all tournaments that the player is playing and also include details about his performance.

---

#### 📸 WIDGET IMAGE

![Image](https://user-images.githubusercontent.com/37311649/226959096-28eb5af7-e946-4d99-99b1-55083a46ceb5.png)

---

#### 📱 TARGET PLATFORMS

Available in all variations.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Widget verification to display

Verify if available on `widgets_list`

`scores_widgets_list`

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

This widget will gather information from different endpoints.

This widget has real-time data when the fixture is happening, and the player is playing.

---

### Versions:

All themes are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| scores_football_players_v2 | data |
| historic_fixtures | data |

The front end will be gathering data from the player ID.

---

➤ **Firebase**

livescore_now

---

#### 🎏 TRANSLATIONS

**Translations endpoint**

| table | columns |
| ----- | --------- |
| player_fixtures_translations

---

#### ⚡️ CACHE

Cache logic is already available for the endpoints. If the cache is not available, use the Hasura endpoint as a fallback.

---

#### 🔎 SEO

- Fixtures links
- Tournament links

---

### Placeholder when there is no content:

If no fixtures are available, the widget should not be shown.

---

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena-%2F-Desktop?node-id=32%3A1635&t=Ij35ARbTg182AII0-1

**Comment by migbash** [comment]
@jonsnowpt 

> 1. Most fixtures are currently missing, because takes a lot of time and data consumption will spike if all are going to be updated.
> 2. Many fixtures (especially those in the past) have `rating: null`

**Comment by jonsnowpt** [comment]
@migbash 

2. All fixtures that exist since we have the fixtures section have that information.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1A. I asked the design team to add a default message when we do not have a rating to keep the design aligned;
- [ ] 2A. The fixtures should have the inverse order, at the bottom the most recent;
- [ ] 3A. Should be one goal and another penalty kick goal;


### 3A:

![Image](https://user-images.githubusercontent.com/37311649/230392097-ecbca7d5-d609-420f-bc2d-d3d4711b51f6.png)

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Fixtures not updating

**Comment by jonsnowpt** [comment]
@migbash 

This can only be tested when the backend events on Hasura are ready.

**Comment by jonsnowpt** [comment]
@migbash 

Translations of the fixtures widget not working:

![Image](https://user-images.githubusercontent.com/37311649/232292852-fda2c561-0e47-4e5c-9ee6-94b5f6982b05.png)

**Comment by migbash** [comment]
> Related #1135

**Comment by jonsnowpt** [comment]
@migbash 

Dates are not correct:

![Image](https://user-images.githubusercontent.com/37311649/232319612-ec569a19-0912-4dec-9e22-cc48bad6d419.png)
![Image](https://user-images.githubusercontent.com/37311649/232319611-fcd329da-4b93-4eb4-8562-4151f9ef045d.png)

**Comment by migbash** [comment]
**NOTES**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

Wrong fixtures:

https://betarena-scores-platform.herokuapp.com/player/erling-hland/154421

vs

https://www.sofascore.com/en-us/player/erling-haaland/839956

**Comment by migbash** [comment]
**NOTES**

> Issue of not seeing `Sofascore` fixtures match more closely, because only `lineups` are used for a `played-in` fixture check by target player. Adding `bench` data corrects this, as well as for `livescore_now` data checks.

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect.  

[Slack](https://betarena.slack.com/archives/D02B1UHEECS/p1681733239008379?thread_ts=1681733077.313059&cid=D02B1UHEECS)

**Comment by jonsnowpt** [comment]
@migbash 

Solved.

**Comment by jonsnowpt** [comment]
@migbash 

Issues mentioned in [Slack](https://betarena.slack.com/archives/D02B1UHEECS/p1681739805533579)

**Comment by jonsnowpt** [comment]
@migbash 

New issues on CSS mentioned on [Slack](https://betarena.slack.com/archives/D02B1UHEECS/p1681752247700999)

**Comment by jonsnowpt** [comment]
@migbash 

Still happening:

[Slack](https://betarena.slack.com/archives/D02B1UHEECS/p1681756907883469)
