### ISSUE TITLE
🔥 HOT-FIX Betclic odds should not be visible to Portugal

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1161]
🐛 Introduction:

Betclic was removed from the sportsbooks details and is no longer a partner for the Portuguese market.

📝 Details:

Since Betclic was removed from the available partners in Portugal, the logo and odds should not appear.

🔍 Steps to Reproduce:

https://scores.betarena.com/pt/futebol/mansfield-town-grimsby-town-18543667

![Image](https://user-images.githubusercontent.com/37311649/227030299-16e84fb1-b812-421b-b3e1-5a66a188127f.png)

🤔 Expected Behavior:

Do not show Betclic.

💥 Actual Behavior:

Showing Betclic.

**Comment by migbash** [comment]
**NOTE**

> Updated, cache needed a manual trigger.
