### ISSUE TITLE
🔥 HOT - FIX Mobile inconsistencies and slow performance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1163]
Check the issues on the video:

[Slack Message](https://betarena.slack.com/archives/D02B1UHEECS/p1679574710845779)

When accessing one of the same links on a desktop, it loads immediately:

https://scores.betarena.com/pt/futebol/denmark-finland-18712987

404 error:

https://scores.betarena.com/pt/futebol/north-&-central-america/concacaf-nations-league

https://scores.betarena.com/pt/futebol/new-zealand-china-pr-18783807

https://scores.betarena.com/pt/futebol/hong-kong-singapore-18794129

https://scores.betarena.com/pt/futebol/malaysia-turkmenistan-18792298

https://scores.betarena.com/pt/futebol/horizonte-itapipoca-18759863

**Comment by jonsnowpt** [comment]
@migbash 

Getting lots of these errors on `DEV` and `PROD`

https://scores.betarena.com/football/germania-sumu-sob-18784706

javascript ```

Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'm.odds=void 0')
(anonymous function) — _page.svelte-3af5cb7f.js:9:106755
asyncFunctionResume
(anonymous function) — _page.svelte-3af5cb7f.js:9:108316
onValue — init-68ff759c.js:167:113
Cs — init-68ff759c.js:115:4216
OC — init-68ff759c.js:164:2483
Bp — init-68ff759c.js:164:2233
Ht — init-68ff759c.js:164:2069
gh — init-68ff759c.js:165:2299
(anonymous function) — init-68ff759c.js:165:967
onDataPush_ — init-68ff759c.js:127:6838
onDataMessage_ — init-68ff759c.js:127:6747
onDataMessage_
onDataMessage_ — init-68ff759c.js:121:8412
onPrimaryMessageReceived_ — init-68ff759c.js:121:8349
(anonymous function) — init-68ff759c.js:121:6703
appendFrame_ — init-68ff759c.js:121:2402
handleIncomingFrame — init-68ff759c.js:121:2952
(anonymous function) — init-68ff759c.js:121:1664
4_page.svelte-3af5cb7f.js:9:106755


```

**Comment by migbash** [comment]
**NOTE**

> `Sentry` -> https://betarena.sentry.io/issues/4031132990/?project=6275655&query=is%3Aunresolved&referrer=issue-stream

**Comment by jonsnowpt** [comment]
We can notice in this example that even on mobile, sometimes it takes a lot of time to load on one browser and fast on another. Desktop is always fast, pointing to a code issue:


https://user-images.githubusercontent.com/37311649/227767611-6c78684d-d776-4bf5-909a-da77ba9f144a.MP4

**Comment by migbash** [comment]
**NOTES**

> Related #1147 `(duplicate)`

**Comment by jonsnowpt** [comment]
@migbash 

It's different from #1147, one is related to the time that the Live Score takes to load and this issue is related to the issue inside the fixture.

**Comment by jonsnowpt** [comment]
@migbash 

The low performance still happens with no visible change:

https://user-images.githubusercontent.com/37311649/230636233-a92f264a-32ab-4689-9abc-9fad732540e0.MP4

**Comment by jonsnowpt** [comment]
Resolved with the Firebase changes.
