### ISSUE TITLE
Featured Match Links not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1170]
🐛 Introduction:

Featured match widget - links not working

📝 Details:

The links to the match and tournament stopped working.

🔍 Steps to Reproduce:

Visit the homepage and click the links:

![Image](https://user-images.githubusercontent.com/37311649/227619632-6bceb001-9172-4869-bffb-e50bae328858.png)

🤔 Expected Behavior:

Links working.

💥 Actual Behavior:

Links are not working.

**Comment by migbash** [comment]
**NOTES**

> Pending for `issue` to be visible again.
