### ISSUE TITLE
Live Scores Bug

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1178]
📝 Details:

The match clock in the "Live" matches is showing a number on top of the actual time

![image](https://user-images.githubusercontent.com/114171785/227985263-b14b1994-0390-4ace-a8ed-8948836fdfd7.png)

🔍 Steps to Reproduce:

Go to the "Live" scores tab

🤔 Expected Behavior:

Only show the time of the match

💥 Actual Behavior:

Random number "13,5" on top of the time of the match

**Comment by jonsnowpt** [comment]
Resolved.
