### ISSUE TITLE
Fixtures H2H links not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1182]
🐛 Introduction:

When browsing past events, the top scores widget does not show the correct result.

📝 Details:

When browsing past events on the H2H widget, the top score widget does not update correctly.

🔍 Steps to Reproduce:

Visit any fixture and select the links in the H2H fixtures.

🤔 Expected Behavior:

Correct redirect to past fixtures.

💥 Actual Behavior:

Links  do not work.

**Comment by migbash** [comment]
**🔍 CAUSE**
Missing `hydration` step of data reloading when on the same `route`, a.k.a `[fixture=fixture]` in this case.

> **Note**
> Corrected, awaiting `🚀 deployment`.
