### ISSUE TITLE
🔥 HOT FIX - Live Score fixtures changing places and timer issue

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1193]
🐛 Introduction:

Fixtures change places when browsing the Live Score, and wrong information is on the timer on live fixtures.

📝 Details:

When changing days on the live score, sometimes the fixtures change the order. Also, the live fixtures have an incorrect timer view; check Figma to confirm the correct info.

🔍 Steps to Reproduce:

Visit the Live Score.

![Image](https://user-images.githubusercontent.com/37311649/228504098-a644f2ef-205b-40bb-abad-a2d19a5b291e.png)
![Image](https://user-images.githubusercontent.com/37311649/228504097-b6cce532-e214-49f0-afdc-4b116c819143.png)

🤔 Expected Behavior:

Fixtures should not change the order and correct timer.

💥 Actual Behavior:

Fixtures are changing the order and incorrect info on the timer.

**Comment by jonsnowpt** [comment]
@migbash 

Live score after 12am:

![Image](https://user-images.githubusercontent.com/37311649/229252245-357ceb57-8298-460e-8cd9-14a557f3177c.png)

**Comment by jonsnowpt** [comment]
@migbash 

The 00:00 to 01:00 am issue still happens.

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect.

**Comment by jonsnowpt** [comment]
@migbash 

Did you verified it?

**Comment by migbash** [comment]
**NOTES**

> Checking tonight in a bit, and finishing off.
