### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#12]
Eliminate render-blocking resources:

https://web.dev/render-blocking-resources/?utm_source=lighthouse&utm_medium=devtools

![Uploading Screenshot 2021-11-21 at 16.23.29.png…]()
62

**Comment by migbash** [comment]
Hmm... I do not seem to encounter this error on the `localhost` dev Environment`

**Comment by jonsnowpt** [comment]
Resolved.
