### ISSUE TITLE
🔥 HOT FIX 404 - Links missing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1200]
https://scores.betarena.com/football/sport-recife-abc-18734480
https://scores.betarena.com/football/fortaleza-cear-18734481
https://scores.betarena.com/football/north-&-central-america/concacaf-nations-league
https://scores.betarena.com/football/alianza-lima-athletico-pr-18809139
https://scores.betarena.com/football/the-strongest-river-plate-18809138
https://scores.betarena.com/football/argentinos-juniors-independiente-del-valle-18809137
https://scores.betarena.com/football/gois-santa-fe-18809074
https://scores.betarena.com/football/audax-italiano-newells-old-boys-18809066
https://scores.betarena.com/football/csar-vallejo-ldu-quito-18809046
https://scores.betarena.com/football/estudiantes-mrida-san-lorenzo-18809078
https://scores.betarena.com/football/blooming-santos-18809067
https://scores.betarena.com/football/millonarios-defensa-y-justicia-18809068
https://scores.betarena.com/football/danubio-emelec-18809052
https://scores.betarena.com/football/oriente-petrolero-estudiantes-18809058
https://scores.betarena.com/football/fortaleza-palestino-18809079
https://scores.betarena.com/football/independiente-medelln-internacional-18809140
https://scores.betarena.com/football/metropolitanos-nacional-18809141
https://scores.betarena.com/football/patronato-atltico-nacional-18809142
https://scores.betarena.com/football/aucas-flamengo-18809143

**Comment by migbash** [comment]
**NOTE**

> Updated

**Comment by jonsnowpt** [comment]
@nogueiravitorr 

Please check.

**Comment by jonsnowpt** [comment]
@migbash 

Still missing:

https://scores.betarena.com/football/north-&-central-america/concacaf-nations-league

**Comment by migbash** [comment]
**NOTES**

> All `links` updated, except the `/football/north-&-central-america/concacaf-nations-league` which needs a `PR`.

**Comment by nogueiravitorr** [comment]
@jonsnowpt @migbash 

Two new leagues with missing links:

**Copa do Brasil**
https://scores.betarena.com/football/volta-redonda-bahia-18809763
https://scores.betarena.com/football/botafogo-sp-santos-18809753
https://scores.betarena.com/football/internacional-csa-18809777
https://scores.betarena.com/football/so-paulo-ituano-18809771
https://scores.betarena.com/football/fortaleza-guia-de-marab-18809779
https://scores.betarena.com/football/nova-iguau-amrica-mineiro-18809755
https://scores.betarena.com/football/coritiba-sport-recife-18809757
https://scores.betarena.com/football/fluminense-paysandu-18809773
https://scores.betarena.com/football/crb-athletico-pr-18809781
https://scores.betarena.com/football/palmeiras-tombense-18809783
https://scores.betarena.com/football/atltico-mineiro-brasil-de-pelotas-18809761
https://scores.betarena.com/football/ypiranga-erechim-botafogo-18809765
https://scores.betarena.com/football/remo-corinthians-18809775
https://scores.betarena.com/football/nutico-cruzeiro-18809759
https://scores.betarena.com/football/maring-flamengo-18809769

**Premiership - Northern Ireland**
https://scores.betarena.com/football/cliftonville-larne-18807516
https://scores.betarena.com/football/crusaders-coleraine-18807517
https://scores.betarena.com/football/carrick-rangers-dungannon-swifts-18807528
https://scores.betarena.com/football/glenavon-ballymena-united-18807529
https://scores.betarena.com/football/portadown-newry-city-afc-18807530

**Comment by migbash** [comment]
**NOTES**

> Need to deal with the `restructure` of the `#25 (cache)` issue for addition of these links, as it has been paused to prevent memory overflow issues.

**Comment by jonsnowpt** [comment]
@migbash 

This should be working by now.

**Comment by migbash** [comment]
**NOTES**

> Corrected, missing some cache updates.
