### ISSUE TITLE
🔥 HOT FIX - SEO URL Fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1215]
🐛 Introduction:

Incorrect SEO on all fixtures links.

📝 Details:

The fixtures SEO is incorrect; it is showing the Tournaments SEO.

![Image](https://user-images.githubusercontent.com/37311649/232202994-c1c50df6-967d-4391-b71c-a90bf8f0a058.png)

🔍 Steps to Reproduce:

https://scores.betarena.com/pt/futebol/palmeiras-cuiab-18791003

🤔 Expected Behavior:

Correct SEO

💥 Actual Behavior:

Incorrect SEO

**Comment by migbash** [comment]
**NOTES**

> Corrected
