### ISSUE TITLE
Livescore incorrect time and dates

### ISSUE THREAD

**Issue by nogueiravitorr** [Betarena/scores#1221]
🐛 Introduction:

The Scores homepage is having a problem with Livescore when it starts.

📝 Details:

1.As soon as it is accessed, it does not show the games of the day.
2.It is necessary to click on different dates for it to change to the current date.
3.The games are showing the wrong time for Brazil (3 hours ahead of the current time).

https://user-images.githubusercontent.com/122905593/232772817-18d1ae8f-7be0-4f70-ad47-04a5726d2db6.mp4

🔍 Steps to Reproduce:

Open the Scores homepage and access the error. 
It seems to be happening only for Brazil, if you cannot access it, please see the previous video.

https://scores.betarena.com/

🤔 Expected Behavior:

The livescore should be normal, showing all matches of the day and with the correct time.

💥 Actual Behavior:

Currently, it is not showing the games when the homepage is opened;
You have to click on different dates to show the current day;
The match times for Brazil are not correct.

💡 Additional Information:

**Comment by jonsnowpt** [comment]
@migbash 

The issue persists.

From Portugal, when accessing the fixtures of the day is correct; if we select another date and return to today's fixtures, it will show the wrong fixtures.

From Brazil, when accessing today, fixtures are incorrect.

**Comment by migbash** [comment]
**NOTES**

> Missing `dev` push to `heroku`, should be working on `DEV` now.

**Comment by jonsnowpt** [comment]
@migbash 

Still an issue in Brazil:

https://user-images.githubusercontent.com/37311649/233982044-8ec41e34-1d62-40f2-9dd7-9f035183d9c9.mp4

**Comment by migbash** [comment]
**NOTES**

> Updated, to use the `-3/0/+3` dates for the `top-row`, alongside with the data generation upon selection, to be adjusted to the users/client `timezone` based `dateTime` object, applying `timezone` offset where necessary.
