### ISSUE TITLE
Livescore "null" time values

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1224]
🐛 Introduction:

"null" information from the endpoint: `livescorenow_scoreboard`

📝 Details:

Sometimes the endpoint sends "null" time values.

🔍 Steps to Reproduce:

Check the LiveScore on the Homepage.

🤔 Expected Behavior:

Transform the current "0" when "null" occurs to "-"

💥 Actual Behavior:

Showing "0".

**Comment by migbash** [comment]
**NOTES**

> Updated
