### ISSUE TITLE
🔥 Google unable to index pages

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1231]
🐛 Introduction:

Google is unable to index the platform fixtures and other pages.

📝 Details:

Since the use of scores_lib, the platform has degraded its performance and created several unexpected issues; one of them of high severity is the inability to get correctly indexed, making the platform lose 90% of its traffic.

Error on Google:

![Image](https://user-images.githubusercontent.com/37311649/233615807-8daf202c-0186-4f4b-9bb5-28d1801d845d.png)

The page is not usable on mobile devices.

`Uncaught (in promise) Error: Rejected at wrsParams.serviceWorkers.navigator.serviceWorker.register (<anonymous>:13:648) at https://scores.betarena.com/pt/futebol/hellas-verona-bologna-18548086:59:30`

🔍 Steps to Reproduce:

Use the search console and add any fixture link.

Also, if a search is made on Google:

"site:scores.betarena.com" is possible to see that the number of pages indexed in the last 24 hours is very low.

🤔 Expected Behavior:

There must be no message stating the pages cannot be used on mobile. Also, the preview should be the mobile view. Besides, the number of indexed pages must be much higher.

💥 Actual Behavior:

Lots of pages are not being indexed, and errors on the Search console.

**Comment by migbash** [comment]
**NOTES**

> Can replicate the issue on `DEV` using the following `Google Service`

https://search.google.com/test/mobile-friendly

**Comment by jonsnowpt** [comment]
Pages tested on weekends get the same no usable on mobile response:

https://scores.betarena.com/pt/futebol/real-madrid-almera-18545407

![Image](https://user-images.githubusercontent.com/37311649/235314679-e6e73017-ae29-409e-bf1a-595ec6441692.png)

**Comment by jonsnowpt** [comment]
The errors persist:

![Image](https://user-images.githubusercontent.com/37311649/235610215-7933effc-877f-4826-84e6-d1a2b3eedc76.png)

**Comment by jonsnowpt** [comment]
The errors were settled after transferring to Heroku.
