### ISSUE TITLE
LiveScore "0" time

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1233]
🐛 Introduction:

Livescore fixtures time info goes back to "0".

📝 Details:

Sometimes the fixtures time when accessing the live score go back to "0," and we need to select between tabs to get it updated:

https://user-images.githubusercontent.com/37311649/233853175-6706410d-55f7-46f9-87a9-7ecaeb6738e1.MP4

🔍 Steps to Reproduce:

Access the live score daily with more than 200 hundred matches and try to replicate.

🤔 Expected Behavior:

Correct time.

💥 Actual Behavior:

Time shows "0," and only after a while or when changing tabs it returns to the correct information.

**Comment by migbash** [comment]
**NOTES**

> Moved `one-off` initial `real-time` DB for `livescores_now_scoreboard` into `$: if(browser) ...` instead of `onMount()`

> `side-effect` #1234 #1223;
