### ISSUE TITLE
Livescore - Red Card disappears

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1235]
🐛 Introduction:

The red card information is not being shown on the live score.

📝 Details:

The red card appears and than disappears, and checking previous fixtures, no red card is shown.

🔍 Steps to Reproduce:

Visit the live score and check fixtures with red cards.

🤔 Expected Behavior:

Show the red cards.

💥 Actual Behavior:

Not showing the red card.

**Comment by jonsnowpt** [comment]
https://user-images.githubusercontent.com/37311649/233979982-6e9fcae2-17a8-40b1-a9ad-bc8096979e9a.MP4

**Comment by migbash** [comment]
**NOTES**

> Updated to `show` the correct `redcards` for `livescores` widget.
