### ISSUE TITLE
Tournaments Videos Not Loading and Content Blocked

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1236]
🐛 Introduction:

Tournaments Videos Error - no video is loaded + Error Blocked Content

📝 Details:

When we open any tournament page that should have the video in the description, we get an error where the video section is
"Blocked Content"

🔍 Steps to Reproduce:

1 - Open tournament page that has video (example: https://scores.betarena.com/football/germany/bundesliga)
2 - Scroll down and check video section
3 - Error?

🤔 Expected Behavior:

Video loads and we can play it

💥 Actual Behavior:

![image](https://user-images.githubusercontent.com/114171785/234014186-f8ee5dee-18ec-4a3e-93c9-ffbc38c3a7d1.png)

**Comment by migbash** [comment]
**NOTES**

> `Content-Security Policy` needed updating to `allow` for `https://www.youtube.com` URL.
