### ISSUE TITLE
Livescore Fixture wrong result

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1237]
This fixture did not happen yet:

https://betarena-scores-platform.herokuapp.com/

![Image](https://user-images.githubusercontent.com/37311649/234069566-f46badca-0437-49c0-9aa0-0081d5595a2a.png)

**Comment by migbash** [comment]
**NOTES**

> Sportmonks issue -> `https://soccer.sportmonks.com/api/v2.0/fixtures/18791019`

![Image](https://user-images.githubusercontent.com/20924663/234070555-3cc39a95-908a-4c60-8dda-7c9f15d09746.png)
