### ISSUE TITLE
Review HEROKU Logs - App Crash

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1263]
Review the Heroku logs to pinpoint the crash and connection issues.

**Comment by migbash** [comment]
**NOTES**

> Looks like some `logs` that can be silenced are being logged in the console, that can contribute to the `platform` slow down on `Heroku`, where less `memory` is available. Silencing these logs, can possibly help, but unlikely when only `1GB` is available.

> Other than that, nothing much has been identified to be causing the `crashes` of the `Heroku` deployment of the `platform.

**Comment by jonsnowpt** [comment]
@migbash 

This seems to be the issue:

https://github.com/hunterloftis/heroku-node-errcodes/tree/master/h13

https://devcenter.heroku.com/articles/error-codes#h13-connection-closed-without-response
