### ISSUE TITLE
Football Player Statistics - Translations not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1275]
Translations not available:

![Image](https://user-images.githubusercontent.com/37311649/236849823-526b619f-28ff-49cc-827b-16ffec14b781.png)

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt No translations made in the `database` -> `player_statistic_info_translations`.

**Comment by jonsnowpt** [comment]
Added, missing IT and SE; I will be adding them tomorrow.
