### ISSUE TITLE
Load CSS and JS First, PRELOAD

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1278]
Since we are having issues because of CSS not being loaded, we need to load it first to try to surpass the mobility issues:

By default, SvelteKit will prioritize loading the critical CSS necessary for rendering the initial view, then load additional CSS files as needed. However, if you want to ensure that all CSS files are loaded before the page is displayed to the user, you can try a few different approaches:

Use the preload attribute: You can add the preload attribute to your CSS link tags to indicate to the browser that the file should be loaded early. For example, you might add the following code to your head section:

```
<link rel="stylesheet" href="/global.css" preload>
This will instruct the browser to prioritize loading the global.css file before other resources.
```

Inline critical CSS: You can also consider inlining the critical CSS directly into the HTML document using the style tag. This will ensure that the critical CSS is loaded before any external CSS files. For example:

```
<style>
/* critical CSS styles here */
</style>
<link rel="stylesheet" href="/global.css">
```

Combine CSS files: If you have multiple CSS files, you may want to consider combining them into a single file to reduce the number of requests made to the server. This can improve page load times and ensure that all CSS is loaded before the page is displayed. You can use a tool like PostCSS or Sass to combine your CSS files during the build process.

Keep in mind that loading all CSS files upfront can increase page load times, so it's important to test the performance impact of these changes and optimize your CSS accordingly.

**Comment by migbash** [comment]
**NOTES**

> https://github.com/Betarena/scores/issues/1231#issuecomment-1520614531
> Waiting for `PROD` release for `check` it works.

**Comment by jonsnowpt** [comment]
At this time, we have been severely affected by the blocked CSS and JS, Google seems to be unable to render our platform correctly, and this seems to be affecting our SEO results.

All other platforms and websites that I have tested, including our About page, do not have this rendering issue, nor do none of our competitors.

The goal is to have the platform rendered the same way every other platform and website so that we can revert the downtrend of visits and indexed pages.

From what I have verified, we need to preload the JS and CSS to guarantee that they are correctly loaded.

Example:

`<link rel="preload" href="[/_next/static/css/20320fd83f24bce2.css](https://www.sofascore.com/_next/static/css/20320fd83f24bce2.css)" as="style"/><link rel="stylesheet" href="[/_next/static/css/20320fd83f24bce2.css](https://www.sofascore.com/_next/static/css/20320fd83f24bce2.css)" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="[/_next/static/chunks/polyfills-5cd94c89d3acac5f.js](https://www.sofascore.com/_next/static/chunks/polyfills-5cd94c89d3acac5f.js)"></script><script defer="" src="[/_next/static/chunks/1734.92f7255c032b79a7.js](https://www.sofascore.com/_next/static/chunks/1734.92f7255c032b79a7.js)"></script><script defer="" src="[/_next/static/chunks/8676.bbd25ff98c45f4cf.js](https://www.sofascore.com/_next/static/chunks/8676.bbd25ff98c45f4cf.js)"></script><script defer="" src="[/_next/static/chunks/9106.82b1d1f887de9f45.js](https://www.sofascore.com/_next/static/chunks/9106.82b1d1f887de9f45.js)"></script><script defer="" src="[/_next/static/chunks/4292.73e7a378df0c8eb1.js](https://www.sofascore.com/_next/static/chunks/4292.73e7a378df0c8eb1.js)"></script><script defer="" src="[/_next/static/chunks/4445.df32b7368e310043.js](https://www.sofascore.com/_next/static/chunks/4445.df32b7368e310043.js)"></script><script defer="" src="[/_next/static/chunks/9398.0a203aeabdc07077.js](https://www.sofascore.com/_next/static/chunks/9398.0a203aeabdc07077.js)"></script><script defer="" src="[/_next/static/chunks/5329.6f01259d93704d98.js](https://www.sofascore.com/_next/static/chunks/5329.6f01259d93704d98.js)"></script><script defer="" src="[/_next/static/chunks/1487.145a2ecae6e41f08.js](https://www.sofascore.com/_next/static/chunks/1487.145a2ecae6e41f08.js)"></script><script defer="" src="[/_next/static/chunks/5588.b64cfbe5cb9d50e3.js](https://www.sofascore.com/_next/static/chunks/5588.b64cfbe5cb9d50e3.js)"></script><script defer="" src="[/_next/static/chunks/7854.85cf86d0de8b97fa.js](https://www.sofascore.com/_next/static/chunks/7854.85cf86d0de8b97fa.js)"></script><script defer="" src="[/_next/static/chunks/2125.bb27f4b7d4bf39e3.js](https://www.sofascore.com/_next/static/chunks/2125.bb27f4b7d4bf39e3.js)"></script><script defer="" src="[/_next/static/chunks/4468.9d5682188e2cacce.js](https://www.sofascore.com/_next/static/chunks/4468.9d5682188e2cacce.js)"></script><script defer="" src="[/_next/static/chunks/5870.c49131cd993f43f5.js](https://www.sofascore.com/_next/static/chunks/5870.c49131cd993f43f5.js)"></script><script defer="" src="[/_next/static/chunks/911.b33dfe21e2074c0f.js](https://www.sofascore.com/_next/static/chunks/911.b33dfe21e2074c0f.js)"></script><script defer="" src="[/_next/static/chunks/3649.3ee5754b321a4c8c.js](https://www.sofascore.com/_next/static/chunks/3649.3ee5754b321a4c8c.js)"></script><script defer="" src="[/_next/static/chunks/1922.6f12b1321e8e32ba.js](https://www.sofascore.com/_next/static/chunks/1922.6f12b1321e8e32ba.js)"></script><script defer="" src="[/_next/static/chunks/1294.39914f72d2f9cb68.js](https://www.sofascore.com/_next/static/chunks/1294.39914f72d2f9cb68.js)"></script><script defer="" src="[/_next/static/chunks/8974.62a1894a00a6b3ff.js](https://www.sofascore.com/_next/static/chunks/8974.62a1894a00a6b3ff.js)"></script><script src="[/_next/static/chunks/webpack-175f160ae12be9a2.js](https://www.sofascore.com/_next/static/chunks/webpack-175f160ae12be9a2.js)" defer=""></script><script src="[/_next/static/chunks/framework-79bce4a3a540b080.js](https://www.sofascore.com/_next/static/chunks/framework-79bce4a3a540b080.js)" defer=""></script><script src="[/_next/static/chunks/main-9e249db6f20d38c3.js](https://www.sofascore.com/_next/static/chunks/main-9e249db6f20d38c3.js)" defer=""></script><script src="[/_next/static/chunks/pages/_app-7435ce685dd2d028.js](https://www.sofascore.com/_next/static/chunks/pages/_app-7435ce685dd2d028.js)" defer=""></script><script src="[/_next/static/chunks/6705-9bec677bfdb78205.js](https://www.sofascore.com/_next/static/chunks/6705-9bec677bfdb78205.js)" defer=""></script><script src="[/_next/static/chunks/289-8b866c00abded4d7.js](https://www.sofascore.com/_next/static/chunks/289-8b866c00abded4d7.js)" defer=""></script><script src="[/_next/static/chunks/2468-e56e89c5c75544aa.js](https://www.sofascore.com/_next/static/chunks/2468-e56e89c5c75544aa.js)" defer=""></script><script src="[/_next/static/chunks/2712-585bbd3390b0e962.js](https://www.sofascore.com/_next/static/chunks/2712-585bbd3390b0e962.js)" defer=""></script><script src="[/_next/static/chunks/8439-47e8d52ac55a71eb.js](https://www.sofascore.com/_next/static/chunks/8439-47e8d52ac55a71eb.js)" defer=""></script><script src="[/_next/static/chunks/5521-049e502451d2ce55.js](https://www.sofascore.com/_next/static/chunks/5521-049e502451d2ce55.js)" defer=""></script><script src="[/_next/static/chunks/5082-1e12bc148b38868a.js](https://www.sofascore.com/_next/static/chunks/5082-1e12bc148b38868a.js)" defer=""></script><script src="[/_next/static/chunks/7497-d98b3adf5a744eb0.js](https://www.sofascore.com/_next/static/chunks/7497-d98b3adf5a744eb0.js)" defer=""></script><script src="[/_next/static/chunks/7263-7b40b5431ed2be35.js](https://www.sofascore.com/_next/static/chunks/7263-7b40b5431ed2be35.js)" defer=""></script><script src="[/_next/static/chunks/1773-7015a934520af413.js](https://www.sofascore.com/_next/static/chunks/1773-7015a934520af413.js)" defer=""></script><script src="[/_next/static/chunks/3885-54dbdb6efdff26e4.js](https://www.sofascore.com/_next/static/chunks/3885-54dbdb6efdff26e4.js)" defer=""></script><script src="[/_next/static/chunks/6539-c63993dcc698dd95.js](https://www.sofascore.com/_next/static/chunks/6539-c63993dcc698dd95.js)" defer=""></script><script src="[/_next/static/chunks/1153-5813f5d3c75322b0.js](https://www.sofascore.com/_next/static/chunks/1153-5813f5d3c75322b0.js)" defer=""></script><script src="[/_next/static/chunks/9945-c75c2b3cfbdd04ed.js](https://www.sofascore.com/_next/static/chunks/9945-c75c2b3cfbdd04ed.js)" defer=""></script><script src="[/_next/static/chunks/6825-ca62d04b1da2ef74.js](https://www.sofascore.com/_next/static/chunks/6825-ca62d04b1da2ef74.js)" defer=""></script><script src="[/_next/static/chunks/6296-c3e73e75ce5627b3.js](https://www.sofascore.com/_next/static/chunks/6296-c3e73e75ce5627b3.js)" defer=""></script><script src="[/_next/static/chunks/2330-7e9882be84555882.js](https://www.sofascore.com/_next/static/chunks/2330-7e9882be84555882.js)" defer=""></script><script src="[/_next/static/chunks/3999-39dc952e8fc4ae67.js](https://www.sofascore.com/_next/static/chunks/3999-39dc952e8fc4ae67.js)" defer=""></script><script src="[/_next/static/chunks/5128-8d182db635097099.js](https://www.sofascore.com/_next/static/chunks/5128-8d182db635097099.js)" defer=""></script><script src="[/_next/static/chunks/6481-1aac343e1a57cd94.js](https://www.sofascore.com/_next/static/chunks/6481-1aac343e1a57cd94.js)" defer=""></script><script src="[/_next/static/chunks/3550-e45616ea51828665.js](https://www.sofascore.com/_next/static/chunks/3550-e45616ea51828665.js)" defer=""></script><script src="[/_next/static/chunks/204-06efa2c45abeb545.js](https://www.sofascore.com/_next/static/chunks/204-06efa2c45abeb545.js)" defer=""></script><script src="[/_next/static/chunks/1241-e8825cccec9d84b9.js](https://www.sofascore.com/_next/static/chunks/1241-e8825cccec9d84b9.js)" defer=""></script><script src="[/_next/static/chunks/5580-04db3c7b3d694a53.js](https://www.sofascore.com/_next/static/chunks/5580-04db3c7b3d694a53.js)" defer=""></script><script src="[/_next/static/chunks/4953-bd9b39b50c3666fd.js](https://www.sofascore.com/_next/static/chunks/4953-bd9b39b50c3666fd.js)" defer=""></script><script src="[/_next/static/chunks/9585-78a389712eff35d9.js](https://www.sofascore.com/_next/static/chunks/9585-78a389712eff35d9.js)" defer=""></script><script src="[/_next/static/chunks/6926-5242879ff9163ccf.js](https://www.sofascore.com/_next/static/chunks/6926-5242879ff9163ccf.js)" defer=""></script><script src="[/_next/static/chunks/pages/event-351ea7d420b9ecf1.js](https://www.sofascore.com/_next/static/chunks/pages/event-351ea7d420b9ecf1.js)" defer=""></script><script src="[/_next/static/q4NVGZFwa32A1IT7BZi7B/_buildManifest.js](https://www.sofascore.com/_next/static/q4NVGZFwa32A1IT7BZi7B/_buildManifest.js)" defer=""></script><script src="[/_next/static/q4NVGZFwa32A1IT7BZi7B/_ssgManifest.js](https://www.sofascore.com/_next/static/q4NVGZFwa32A1IT7BZi7B/_ssgManifest.js)" defer=""></script><script src="[/_next/static/q4NVGZFwa32A1IT7BZi7B/_middlewareManifest.js](https://www.sofascore.com/_next/static/q4NVGZFwa32A1IT7BZi7B/_middlewareManifest.js)" defer=""></script>`


===

To preload JS and CSS resources when they are created during the build process in SvelteKit, you can use the preload property in the SvelteKit configuration file (svelte.config.js). Here's how you can do it:

Open the svelte.config.js file in the root directory of your SvelteKit project.

Inside the configuration file, locate the kit property, which contains the SvelteKit configuration settings.

Add a preload property under the kit configuration, specifying an array of JS and CSS files to preload. For example:


```
// svelte.config.js

module.exports = {
  kit: {
    // Other configuration settings...

    preload: [
      '/path/to/my-script.js',
      '/path/to/my-styles.css'
    ]
  }
};
```


Replace /path/to/my-script.js and /path/to/my-styles.css with the actual paths to your JS and CSS files that you want to preload.
By including the preload property in the SvelteKit configuration file, SvelteKit will automatically preload the specified JS and CSS resources during the build process. This ensures that the preloaded resources are fetched in advance and available for quicker loading when users visit your website.

Make sure to run the SvelteKit build command (npm run build or yarn build) to generate the optimized build files with the preloaded resources.

Note that preloading all JS and CSS resources may not always be necessary or optimal for every website. Consider carefully which resources are critical for initial page load and preloading those to strike a balance between performance and resource utilization.

**Comment by jonsnowpt** [comment]
@migbash 

Rendering seems ok, but the CSS seems to be having a few problems when accessing the platform:


![Image](https://github.com/Betarena/scores/assets/37311649/bc05f031-f598-49a1-890b-c6b9f46dff8d)

**Comment by jonsnowpt** [comment]
Working now.

**Comment by jonsnowpt** [comment]
@migbash 

Failing on `PROD`

![Image](https://github.com/Betarena/scores/assets/37311649/07d16e44-13b8-4e70-b4a7-24d4016d7b94)

**Comment by migbash** [comment]
- https://github.com/Marco-Prontera/vite-plugin-css-injected-by-js
- https://stackoverflow.com/a/71304592/8421215

**Comment by jonsnowpt** [comment]
@migbash 

We should change the approach from `modulepreload` to a .js defer load.

What seems to be happening is the time it takes to preload all .js interferes with the correct rendering of the page by the Google bot. Also, we always had a slow FCP, and probably this and the SEO load are the culprits for this first content paint seconds. Making this change could contribute to a faster initial render and help with the Google Bot rendering problems.

### Helpful links:

https://github.com/vitejs/vite/issues/5120

https://github.com/sveltejs/kit/commit/d138efe21692f5925f1e89afc0a33f42d6a1a711

### Performance comparison:

https://user-images.githubusercontent.com/427625/161763490-b71cd439-7e89-4784-83b5-8b39c01b5a75.png

**Comment by jonsnowpt** [comment]
@migbash 

The approach we are currently working on has, I suspected, getting the performance down because of the load of the big js at preload:


Version with the changes:

![Image](https://github.com/Betarena/scores/assets/37311649/e1162252-ae71-4788-be85-e4b3d6f1a1f5)


Prior version:

![Image](https://github.com/Betarena/scores/assets/37311649/2acf5f60-18eb-4cbd-8a4c-921b6d6da9f5)


The difference in the treemap:


![Image](https://github.com/Betarena/scores/assets/37311649/476fb849-ace2-4049-8948-6eeeaba2dbb6)

**Comment by jonsnowpt** [comment]
I tested a few showcase projects on the Sveltekit website and noticed that the ones that do not have the. JS on the headers is rendered correctly. The other ones fail.

On Sveltekit's official website, the.JS are on the HTML file, not in the header response:

![Image](https://github.com/Betarena/scores/assets/37311649/59e769ad-57c6-4eec-8437-4a07e9ddc4fe)
![Image](https://github.com/Betarena/scores/assets/37311649/e07f2102-7270-43ef-ab5c-76646e264c7d)
![Image](https://github.com/Betarena/scores/assets/37311649/2ed8ad29-f02c-49a5-8c47-136a0a1edb5e)

**Comment by jonsnowpt** [comment]
@migbash 

The latest solution of a single .js has resulted in getting the rendered working majority of the time. I will be closing this issue since the reported major problem is resolved and start opening other tasks to achieve the best results possible.
