### ISSUE TITLE
Football Player Statistics - No data category hidden

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1284]
Hide the category when no data is available.

![Image](https://user-images.githubusercontent.com/37311649/237195328-6e978e74-8e3e-4a09-9701-b20d157ffd20.png)

**Comment by migbash** [comment]
> @jonsnowpt What `player` (url) is this ?

**Comment by jonsnowpt** [comment]
@migbash 

For example:

https://betarena-scores-platform.herokuapp.com/pt/jogador/nicols-hernn-otamendi/1822

Premier League
