### ISSUE TITLE
Football Players Statistics - Translations Speed

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1286]
When changing from one language to another, it takes several seconds. It should be faster.

**Comment by migbash** [comment]
**NOTES**

> Slow speeds are caused (such as: `cristiano-ronaldo-dos-santos-aveiro/580` vs `nicols-hernn-otamendi/1822`), because in `Ronaldo's` case, data for the `player/fixtures` widget is `CACHED` and in `Otomendi` it is not cached... 

> Thus, `SEO` preloading data when switching languages is `slower` in `Otomendi`

**Comment by jonsnowpt** [comment]
@migbash 

I do not notice any improvement.

**Comment by jonsnowpt** [comment]
@migbash 

It's ok after the elements are cached.
