### ISSUE TITLE
Renew SSL Certificate

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1299]
For the About Betarena:

Your certificate (or certificates) for the names listed below will expire in 19 days (on 2023-05-30). Please make sure to renew your certificate before then, or visitors to your web site will encounter errors.

We recommend renewing certificates automatically when they have a third of their total lifetime left. For Let's Encrypt's current 90-day certificates, that means renewing 30 days before expiration. See https://letsencrypt.org/docs/integration-guide/ for details.

[sitemap.betarena.com](http://sitemap.betarena.com/)

For details about when we send these emails, please visit: https://letsencrypt.org/docs/expiration-emails/ In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.

For any questions or support, please visit: https://community.letsencrypt.org/ Unfortunately, we can't provide support by email.

To learn more about the latest technical and organizational updates from Let's Encrypt, sign up for our newsletter: https://mailchi.mp/letsencrypt.org/fjp6ha1gad

If you are receiving this email in error, unsubscribe at:
  http://delivery.letsencrypt.org/track/unsub.php?u=30850198&id=75d8aa276f994421accdd2ed2f095809.NUlhwpkURhagxCBB%2BVfeGsJqtGA%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dp%252A%252A%252A%252A%2540b%252A%252A%252A%252A.%252A%252A%252A
Please note that this would also unsubscribe you from other Let's Encrypt service notices, including expiration reminders for any other certificates.

Regards,
The Let's Encrypt Team

**Comment by migbash** [comment]
**NOTES**

> Updated

![Image](https://github.com/Betarena/scores/assets/20924663/237d082d-b017-438c-b5ca-92a8c1d8bbd2)
