### ISSUE TITLE
hreflang issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1301]
Page referenced for more than one language in hreflang

![Image](https://user-images.githubusercontent.com/37311649/238123262-aa9e2734-d579-4e1e-b735-8c988c961926.png)

![Image](https://user-images.githubusercontent.com/37311649/238123285-6d6a9c56-074b-45f0-a63a-a99eb3a98197.png)

https://help.ahrefs.com/en/articles/2747339-page-referenced-for-more-than-one-language-in-hreflang-error-in-site-audit

https://developers.google.com/search/docs/specialty/international/localized-versions?hl=en&visit_id=638195625563275684-3818267773&rd=1

**Comment by migbash** [comment]
**NOTES**

> By the looks of it, none of the `<link hreflang=...` can be matching, meaning have the same `outgoing` URL. Therefore `x-default` has been removed, as it is the same `url` as that of the `EN`.

**Comment by jonsnowpt** [comment]
@migbash 

We should try the other approach, add the "x-default" and remove the "en" alternate:

![Image](https://github.com/Betarena/scores/assets/37311649/a08baea8-bf54-4dc7-b7eb-8e11dd0d2cdf)


https://app.ahrefs.com/site-audit/3374534/37/data-explorer?columns=pageRating%2Curl%2Ctraffic%2Ccompliant%2ChreflangLink%2ChreflangIssues%2ChreflangGroupHash%2CincomingHreflang%2CincomingAllLinks&filterId=8ec5351853510ea2297b389b55b1e54e&issueId=c64d340d-d0f4-11e7-8ed1-001e67ed4656
