### ISSUE TITLE
Position on the field is not correct

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1317]
https://betarena-scores-platform.herokuapp.com/pt/jogador/nicols-hernn-otamendi/1822

![Image](https://user-images.githubusercontent.com/37311649/238396930-442258f4-a957-4961-9d05-c3a9cdf0dbb6.png)

**Comment by jonsnowpt** [comment]
@migbash 

Also:

https://betarena-scores-platform.herokuapp.com/player/odisseas-vlachodimos/31892

![Image](https://github.com/Betarena/scores/assets/37311649/6423db92-4400-454a-82e7-6aa34de61645)

**Comment by jonsnowpt** [comment]
@migbash 

Positions:

![Image](https://github.com/Betarena/scores/assets/37311649/8c449364-8a73-4471-ab12-9cb19012e205)

**Comment by migbash** [comment]
> @jonsnowpt Missing `Right-Midfielder`, `Left-Midfielder` and `Defensive Midfielder` and `Center Back` clear positions.

**Comment by jonsnowpt** [comment]
@migbash 

![Image](https://github.com/Betarena/scores/assets/37311649/dd0b640e-63bc-4a7c-9b68-e934420dd35f)
