### ISSUE TITLE
`Sportmonks` inconsistent `data`

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1330]
**DESCRIPTION**

> At times, the new `livescores_now_scoreboard` data contains erroneous data, for some `parameters/properties` incoming from the `source` Sportmonks.

> For example, incorrect `state` of the games, making them not be picked up by the widgets using the `livescores_now_scoreboard` data to show correct data:

<img
src="https://user-images.githubusercontent.com/20924663/239442328-40eab3cd-23a7-47a3-b08d-3d91ae37bc83.png"
width=250
/>
*Juventus vs Seville Fixture*

<img
src="https://user-images.githubusercontent.com/20924663/239442705-9acc9240-60e3-4a8a-a4d4-3af0f9b882c5.png"
width=250
/>
*Juventus vs Seville Fixture | Sportmonks Data Tested*

> This caused it to be `invisible` for the users on the `livescores-v2` widget on `homepage`. Further adding unnecessary complexity to solving other `livescores-v2` issues.

> `et` is not a `valid` Sportmonks State => https://docs.sportmonks.com/football/definitions/states/fixture-states.

> Should be either `1et` or `2et` are expected.

---

> Sportmonks Contacted.

**Comment by jonsnowpt** [comment]
@migbash 

It is. The error is on Spormonks documentation.

**Comment by migbash** [comment]
**NOTES**

> Sportmonks issue in documentation, should be `et` instead of `1et` and `2et`.

> Overall inconsistencies in the `state/status` of the fixture are still being `checked` by `Sportmonks`.
