### ISSUE TITLE
Auth + Firestore inconsitencies

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1346]
At this time, we have inconsistencies between the data on the Auth service and the Firestore DB. These inconsistencies are present in the number of registrations and the number of users present on the Firestore DB.

**Comment by migbash** [comment]
**NOTES**

> [29/06/23] `Authentication` shows `144` count, `Firestore UIDs` shows `94` count.

**Comment by jonsnowpt** [comment]
@migbash posthog is in place.

**Comment by jonsnowpt** [comment]
@migbash 

This issue happens when users register but never move forward into logging in into the platform.
