### ISSUE TITLE
Missing Live Fixture Information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1349]
The live fixture information should be present when the fixture is happening, its not shown:

https://user-images.githubusercontent.com/37311649/241796590-10265f7f-f5f6-4acc-a62a-fa3b1d18fa0d.mp4

**Comment by jonsnowpt** [comment]
@migbash 

The issue is that the real-time data takes more than 10s to appear, and needs to be much faster.

**Comment by migbash** [comment]
**NOTES**

> Related to `backend`

<img
src="https://github.com/Betarena/scores/assets/20924663/d67785ac-ccd1-4980-858c-9f3f5a730b3b"
width=350
/>

<img
src="https://github.com/Betarena/scores/assets/20924663/48ff905c-246b-47bf-a1ed-ba3818b533b8"
width=250
/>

Expected to update on `(source)` Hasura.

---

![Image](https://github.com/Betarena/scores/assets/20924663/47182117-b8a1-41c0-a161-ff6ffd534fad)

![Image](https://github.com/Betarena/scores/assets/20924663/6ccf9f99-1d33-40bf-a55e-6c14afd1e202)
