### ISSUE TITLE
Missing player profiles

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1351]
If missing, it should not be possible to click it.

https://betarena-scores-platform.herokuapp.com/player/oleksiy-kovtun/205881

https://betarena-scores-platform.herokuapp.com/player/mathias-rosenrn/84141

https://betarena-scores-platform.herokuapp.com/player/malte-amundsen/85953

https://betarena-scores-platform.herokuapp.com/player/george-abbott/37586707

https://betarena-scores-platform.herokuapp.com/player/rodrigo-huendra-almeida-mendona/37627272

**Comment by migbash** [comment]
**NOTES**

> `...player/oleksiy-kovtun/205881` has no `"teams": []`
> Cannot complete the data for `teamId > seasonId > leagueId` , therefore, cannot make up a valid SEO for `tournament-links`.

**Comment by jonsnowpt** [comment]
@migbash 

In this case, I suggest you work this out with Sportmonks since you are better positioned to explain and move forward to a resolution.

**Comment by jonsnowpt** [comment]
@migbash 

This one is missing:

https://betarena-scores-platform.herokuapp.com/player/george-abbott/37586707

I do not know what the response from Sportmonks was.
