### ISSUE TITLE
Players Performance issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1354]
When visiting the players that are not cached, it takes quite some time; on mobile, we click, and it seems that nothing is happening for a while, and this example is a fixture from yesterday that I suppose the player's information is cached.

The user will not wait or understand what's going on when there is a delay of seconds to something happen.

Access to the link should be immediate, even if the data takes a few seconds to load.

https://user-images.githubusercontent.com/37311649/242009491-20b798ff-35a4-4a7a-80d1-d86e717de385.MP4

**Comment by migbash** [comment]
**DESCIPTION**

> Check `player` and `tournaments` taking a bit too long for the user, when clicking/navigating.

**Comment by jonsnowpt** [comment]
@migbash 

Added to another task.
