### ISSUE TITLE
Lineup - TypeError: a.teams_data.find(...) is undefined

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1357]
Error:

TypeError: a.teams_data.find(...) is undefined

https://betarena-scores-platform.herokuapp.com/football/sevilla-roma-18804534

![Image](https://user-images.githubusercontent.com/37311649/242196422-7476c9ce-223d-4aff-a27a-f2245d6eda7c.png)

**Comment by migbash** [comment]
Fixed as a `side-effect` of [#154](https://github.com/Betarena/backend_betarena/issues/154)
