### ISSUE TITLE
Fixture incidents add players links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1359]
#### 📝 DESCRIPTION

We need to start adding the player's links using the current endpoint: `scores_football_players_v2`

---

#### 📸 WIDGET IMAGE

`fixture_incidents`

![Image](https://user-images.githubusercontent.com/37311649/242212230-d667b601-b71c-4ced-84e3-01e48d79da64.png)

---

#### 💠 WIDGET DATA

We need to check the ID and add the correct player links. This data is already cached; if not, it will use the fallback approach.

➤ **Hasura**

| table | columns |
| ----- | --------- |
| scores_football_players_v2 | urls |

---

➤ **Firebase**

| livescores_now | 

---

**Comment by jonsnowpt** [comment]
https://betarena-scores-platform.herokuapp.com/football/levadia-ii-paide-u21-18771847

Missing the link on the incidents.

**Comment by migbash** [comment]
@jonsnowpt Looks like `Sportmonks` have added `100,000` more players, getting closer to the `500,000` of the expected `v2 API` data amount initially expected.

> `🟩 SOLUTION` -> Need to re-run all data again. Complementary to #1373.

**Comment by jonsnowpt** [comment]
@migbash ok, they sent me an email informing me that all updates should be finished tomorrow; at that time, we can repopulate everything and then run the cache to get everything updated. I will let you know when I receive the confirmation.
