### ISSUE TITLE
Players - Jersey number null on all players

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1373]
![Image](https://user-images.githubusercontent.com/37311649/243731298-3c76e853-f25f-4d56-8b7d-b850d9e53719.png)

**Comment by migbash** [comment]
**NOTES**

> `[..]/player/mbaye-diagne/62258` - `"yersey_number": null`

```
{
"id": 353089,
"team_id": 3990,
"player_id": 62258,
"position_id": 27,
"transfer_id": 9098,
"yersey_number": null,
"detailed_position_id": 151
}
```

**Comment by jonsnowpt** [comment]
@migbash 

Let's wait for tomorrow's confirmation that everything is updated by sportmonks so that we can start the process of getting all data again.

**Comment by jonsnowpt** [comment]
@migbash 

Players' update from Sportmonks is finished; we may proceed.
