### ISSUE TITLE
Incidents - Add players links to the SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1384]
For SEO purposes we should add the players links.

**Comment by jonsnowpt** [comment]
@migbash 

All these players get an error:

https://betarena-scores-platform.herokuapp.com/football/confiana-nutico-18797699



![Image](https://github.com/Betarena/scores/assets/37311649/1a541921-1afe-4864-8485-2862105d0c18)

**Comment by migbash** [comment]
> @jonsnowpt I get no internal errors on any of them

**Comment by jonsnowpt** [comment]
@migbash 

Missing player's links on the SEO, check:



![Image](https://github.com/Betarena/scores/assets/37311649/bf28360d-e74a-424b-a8e3-f6d4b893ad3f)

**Comment by migbash** [comment]
> @jonsnowpt All players are there.

> `L. Salazar` = `Luis Ángel Salazar Cuesta`
> `Odivan` = `Odivan Koerich`
> `Paul Breitner Villero Arevalo` = `Paul Breitner Villero Arevalo`
> `Eduardo` = `Eduardo da Silva Albuquerque`

> etc.

Please check again, `full-names` are used.

**Comment by jonsnowpt** [comment]
Sorted out.
