### ISSUE TITLE
Players - Stats stopped working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1388]
All players that played in the Champions League stopped loading their stats correctly:

**Fixture:**

https://scores.betarena.com/football/manchester-city-inter-18804442

**Some of the players:**

https://scores.betarena.com/player/erling-hland/154421

https://scores.betarena.com/player/bernardo-mota-veiga-de-carvalho-e-silva/96353

https://scores.betarena.com/player/rodrigo-hernndez-cascante/186910

https://scores.betarena.com/player/federico-dimarco/129842

Identify and correct the issue.

**Comment by migbash** [comment]
**NOTES**

> Incorrect `bulk` updates data looping, when multiple players needed to be updated from various different `leagues/seasons`.

**Comment by jonsnowpt** [comment]
@migbash 

Wont happen again?

**Comment by migbash** [comment]
> @jonsnowpt No
