### ISSUE TITLE
Fixtures - Several fixtures links not working in different languages

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1391]
some fixtures with RO and other languages are getting error:

https://scores.betarena.com/ro/fotbal/manchester-city-inter-18804442 

same thing to FR
https://scores.betarena.com/fr/football/manchester-city-inter-18804442

SE the same:
https://scores.betarena.com/se/fotboll/manchester-city-inter-18804442

**Comment by migbash** [comment]
> @jonsnowpt a missing validation check from an endpoint since the `firebase migration` was re-enabled.
