### ISSUE TITLE
Tournament - Added supported tournament 1098

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1394]
The Bolivian tournament has been added to the platform:

ID: 1098

Run the necessary processes to load the country, tournament, and data.

**Comment by migbash** [comment]
**NOTES**

> Added `Bolivian` target tournament + `documentation` created inside `> How To's ?`

**Comment by jonsnowpt** [comment]
@migbash 

All fixtures are missing:

https://scores.betarena.com/pt/futebol/vaca-dez-aurora-18774208

https://scores.betarena.com/pt/futebol/atltico-palmaflor-real-tomayapo-18774215

https://scores.betarena.com/pt/futebol/nacional-potos-the-strongest-18774211

https://scores.betarena.com/pt/futebol/universitario-de-vinto-royal-pari-18774212

https://scores.betarena.com/pt/futebol/always-ready-blooming-18774209

https://scores.betarena.com/pt/futebol/bolvar-santa-cruz-18774214

https://scores.betarena.com/pt/futebol/wilstermann-oriente-petrolero-18774210
