### ISSUE TITLE
Best practices review

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#14]
![Screenshot 2021-11-21 at 16 26 46](https://user-images.githubusercontent.com/37311649/142770388-1aa6680b-22f3-4da2-a30e-0b9dca3dba45.png)

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">

**Comment by migbash** [comment]
Updated and enhanced to `100%`

![image](https://user-images.githubusercontent.com/20924663/142796336-cebfcb6e-ca6e-44d6-86df-5f39e22510f3.png)

`Reflected in the next pull-request`
