### ISSUE TITLE
Wallet login stopped working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1406]
Noticed on Firefox!

![Image](https://user-images.githubusercontent.com/37311649/246613532-c83f4d4d-1511-4164-81cf-0a9e332f67f9.png)

**Comment by migbash** [comment]
**NOTES**

> This is a `Firefox` issue, we had noticed it from the start.

> https://github.com/Betarena/scores/issues/1021

> It appears that the `window.ethereum` is no longer in the `console.log(window)` object in `Firefox`, and cannot be accessed. Looks like it's affecting other `web3` parties, such as `ledger`.

https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-x-Ledger-U2F-Issue-on-Firefox?support=true

**Comment by jonsnowpt** [comment]
@migbash 

It was working a few weeks ago. Also we unable to login via Metamask also gives an error.

**Comment by migbash** [comment]
> @jonsnowpt Looks like it's something recent, the `Auth-Component` was never changed since its creation, and the logic was exactly the same all along. Plus, `Ledger` just announced yesterday in the link above, their issues with Firefox, could be related.

> When inspecting in `devTools` with `console.log(window)` it can be seen, the `.ethereum` object is missing, which should be present in order to interact with `MetaMask`. Looks like something is happening with `Firefox` as it's restricing `MetaMask` from injecting the cirtical global object into the `window`

**Comment by jonsnowpt** [comment]
@migbash 

All other apps are working fine with Metamask, Venus, Pancake, etc. How can we get this to work?

**Comment by migbash** [comment]
**NOTES**

> Issue identified with the use of the `Content-Security Policy`.

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena.slack.com/archives/D02B1UHEECS/p1687381694730959?thread_ts=1687367656.267039&cid=D02B1UHEECS

**Comment by jonsnowpt** [comment]
@migbash 

Using Metamask mobile is still not working.
