### ISSUE TITLE
Header - Balance missing on Mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1412]
Missing from mobile:

![Image](https://user-images.githubusercontent.com/37311649/248054771-5d71c47e-3858-47fd-b5f9-3293bba68dfd.png)

![Image](https://user-images.githubusercontent.com/37311649/248054861-c3481c75-4079-48f8-b1ba-cd96057c17d6.png)

**Comment by jonsnowpt** [comment]
@migbash 

Please align the balance information:

![Image](https://github.com/Betarena/scores/assets/37311649/911d1a33-ec79-4a33-a073-0c6783cc7e4b)

**Comment by migbash** [comment]
@jonsnowpt `alignment` Corrected
