### ISSUE TITLE
Featured Match - Add players urls

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1413]
#### 📝 DESCRIPTION

Since we now have the player's URLS available, we need to add those to the best players added on the Featured Match widget.

---

#### 📸 WIDGET IMAGE

![Image](https://user-images.githubusercontent.com/37311649/248250784-2093eb40-7564-4cbe-a474-196eabdc18bf.png)

---

#### 📱 TARGET PLATFORMS

Desktop, tablet, and mobile.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| widget_featured_match_best_player | players_ids |

The player's IDs should be added to this column, and with that information, it is possible to get the player's links depending on the lang.

---

#### ⚡️ CACHE

The links should be cached the same way as the rest of the data.

---

#### 🔎 SEO

The player's links should be included in the SEO information.

**Comment by migbash** [comment]
**NOTES**

```
player_ids:
{
  local_1: <id> | null,
  local_2: <id> | null,
  visitor_1: <id> | null,
  visitor_2: <id> | null
}
```

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Players' names are not aligned correctly;
- [ ] 2. Links are undefined;

![Image](https://github.com/Betarena/scores/assets/37311649/68924f77-5b6c-4386-b24b-d0d83ac41e50)

**Comment by migbash** [comment]
**NOTES**

> 2. Links are undefined;
> This is because, currently, no new `featured-match` has been generated for most/all `geo-positions`, as no new `featured-match` have generated by `backend`. We can use the `fallback (hasura)` to generate data for `featured-match` on the fly, or wait until `backend` generates. Either way, will take same amount of time.

**Comment by jonsnowpt** [comment]
@migbash 

Need to wait to test it correctly
