### ISSUE TITLE
Tournaments - Odds missing on all tournaments

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1418]
https://scores.betarena.com/football/usa/major-league-soccer

![Image](https://user-images.githubusercontent.com/37311649/248424986-8815a4b9-cf30-42da-b247-9603d5353b3f.png)

https://scores.betarena.com/football/brazil/serie-a

![Image](https://user-images.githubusercontent.com/37311649/248425086-d4563416-d858-4e99-86d8-7412fb8387ee.png)

**Comment by jonsnowpt** [comment]
Working correctly at this time.

**Comment by jonsnowpt** [comment]
@migbash 

Missing all odds:
https://scores.betarena.com/football/brazil/serie-b

the fixtures have odds
https://scores.betarena.com/football/guarani-mirassol-18791700

![Image](https://github.com/Betarena/scores/assets/37311649/79fb7967-9c4b-4fe5-8546-cc07d2c1d2a3)

Also affecting the featured match widget:

![Image](https://github.com/Betarena/scores/assets/37311649/823d5c56-d040-4d36-acfe-32872130713d)

**Comment by jonsnowpt** [comment]
@migbash 

Happening again:

https://scores.betarena.com/football/argentina/superliga

**Comment by migbash** [comment]
**NOTES**

> ⚠️ No `odds` in `Firebase`:

![Image](https://github.com/Betarena/scores/assets/20924663/746f1946-2ac1-44b0-8cd5-7153dcb95adf)

**Comment by jonsnowpt** [comment]
@migbash 

checking.
