### ISSUE TITLE
Profile - Withdraw option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1421]
#### 📝 DESCRIPTION

We are adding a Withdraw option on the profile user section and a few methods that will allow users to withdraw funds from the Betarena platform.

![Image](https://user-images.githubusercontent.com/37311649/247607233-700ec7a7-832d-477a-ac52-f28460ae713d.png)

---

#### 📱 TARGET PLATFORMS

This option will be available on all platform versions.

---

#### 🎬 LINK

https://scores.betarena.com/u/withdraw/pt

---

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

All withdrawal options have a form associated so that we can collect user information to be able to associate the request of funds with the user account and to be able to have access to the information needed to send user funds.

We need a preloader for this and other sections; we can use the following using Black instead of blue:

https://lottiefiles.com/73801-preloader-animation

**Initial withdrawal options:**

- Paypal 
- Skrill
- Remessa Online
- Revolut
- Wired Transfer
- Wise
- Cryptocurrency

Since all information is coming from the DB, this means that we can add new withdrawal options without the need to change the front end.

---

### Versions:

All theme variations are supported.

---

#### 💠 DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| withdraw_options | id + type + form_id + provider_logo + blacklist |
| forms | id + type + type_id + form_fields_step_1 + form_fields_step_2 + gateway + form_fields_success |

### Fields description:

**withdraw_options**

```
id  = The ID of each withdrawal option
type = Gateway
form_id = The Form ID associated with this Gateway, available on forms
provider_logo = Gateway logo
blacklist = GEO countries where it's not available
```

===

```
**forms**

id = Form ID that allows us to associate the withdraw option with the correct Form
type = Description of what kind of form it is
type_id = Type of the form, withdraw, deposit, or others
form_fields_step_1 = Content and Fields of the form, including the type of field
form_fields_step_2 = In the case of multi-step form, here is where the second step data is available
gateway = What type of Gateway is associated with this form
form_fields_success = Content of the success message associated with the form
```

===

### Sending the Data:

After filling up the form, the data should be sent to the DB:

➤ **Hasura**

| table | columns |
| ----- | --------- |
| transaction_history |  id + date + asset + quantity + amount  + description + type + status + Gateway + first_name + last_name + payment_email + iban +  bic_swift +  wallet_address_erc20 + uid + payment_processor_fee|

```
id = unique identifier for each transaction.
date = Date when the transaction occurred.
asset = Specifies whether it involves fiat currency or cryptocurrency.
quantity = The quantity or amount involved in the transaction (e.g., fiat currency amount, crypto amount).
amount = The corresponding amount in BTA tokens.
description = Brief description of the transaction.
type = Indicates whether it is a deposit or withdrawal request.
status = Current status of the transaction (Completed, Pending, Processing, Canceled,  [DEFAULT STATUS PENDING]))
Gateway = Payment processor or platform used for the transaction (e.g., Stripe, Coinbase, Wise).
first_name = User First Name if available
last_name = User Last Name if available
payment_email = Email associated with the Gateway
iban = IBAN associated with the Gateway
bic_swift = BIC/SWIFT CODE associated with the payment Gateway
wallet_address_erc20 = For withdrawals, the wallet address where the funds are being or has been sent.
uid = User Unique UID
payment_processor_fee = Fee charged by the payment processor for the transaction.
```

---

#### 🎏 TRANSLATIONS

**Translations endpoint**

Within the specific Schema:

| table | columns |
| ----- | --------- |
| forms | 

The translations are included in the form json.

---

#### ⚡️ CACHE

Unavailable.

---

#### 🔎 SEO

Unavailable.

---

### Placeholder when there is no content:

Defined preloader on top.

---

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena-%2F-Desktop?type=design&node-id=32%3A1635&t=wLX73xuz9lYHGwZ7-1

**Comment by migbash** [comment]
@jonsnowpt It appears, that `provider_logo_dark`, same as from `deposit_options` is missing from `withdraw_options`. Needs to be added in.

**Comment by jonsnowpt** [comment]
@migbash 

Added.

**Comment by jonsnowpt** [comment]
> @jonsnowpt Data sent to the DB to transaction_history should be of status: Pending ?
@migbash should be status: Pending.

**Comment by jonsnowpt** [comment]
> @jonsnowpt Original cryptocurrency logo just showing the letters, and missing the Bitcoin, for the withdraw_options.

@migbash Yes, I removed the BTC icon to avoid being misunderstood.

**Comment by jonsnowpt** [comment]
> @jonsnowpt Invalid provider_logo_dark for the cryptocurrency withdraw option, showing as Coinbase, for the withdraw_options.

@migbash available now.

**Comment by jonsnowpt** [comment]
> @jonsnowpt Should cryptocurrency withdraw option have the Withdraw all available funds option ? not currently visible on the design.

@migbash it should, probably a mistake.
