### ISSUE TITLE
Balance Deposits & Withdraws

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1423]
#### 📝 DESCRIPTION

The user's wallet balances should never be edited by hand; the balances vary depending on transactions, deposits, and withdraws and also depending on the results of the competition that may allow users to get BTA prizes that will also affect their balance and the entry fees for the competitions that will also affect their balance.

This means that every variation in the balance is stated on the database tables and can be verified by our team and the users through their profile section.

---

#### :foot: Steps:

**1. Add a new user field on the Firestore users database**

On the Firestore user DB we need to add a new field:

`main_balance`

---

**2. How transactions affect the user's main wallet balance**

All transactions and associated information are present in the transactions table:

**Columns:**

| table | columns |
| ----- | --------- |
| transaction_history |

An `Invoke Trigger Event `should be added to each row in the table.

When calling this trigger, the system will check the status of the transaction, and if the status is "Processing" it should add or subtract the user (using the UID information) amount from the `main_balance` on the Firestore DV and change the status to "Completed".

**Update frequency:**

Prod = For now, the process is manual, using the `invoke trigger event`.

---

**3. Frontend connects the Balance to the `main_balance`**

At this time, we need to connect the user's balance information on the front end to their `main_balance`.

![Image](https://user-images.githubusercontent.com/37311649/249410259-6d179787-643a-4224-8b82-8c71194b96c5.png)

Since we are using a plain conversion of BTA to USD, we do not need a real-time conversion for now.

**Comment by migbash** [comment]
**NOTES**

> 🟩 `Invoke Trigger` action active.
