### ISSUE TITLE
Champions League and all tournaments missing the new season

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1435]
It seems that none of the tournaments have the new season included.

https://scores.betarena.com/football/europe/champions-league

**Comment by migbash** [comment]
**NOTES**

> Correct number of seasons (total): `10,944` - `Sportmonks (total) = 10,944`

---

**Fixture-Odds [widget]**

> `Cache` appears to be **lagging behind**. However, using direct `fallback Hasura` data shows correct data.

- `Premier League` 
> **League Id: 8**
> **NEW Season Id: 21646**

> **📌 Reason for `CACHE` inconsistency**
> No `fixtures` played yet [?]

```
***********************************
✅ - Direct Hasura (Fallback) Data
***********************************
{
  "league_id": 8,
  "seasons": [
    {
   ✅ "season_id": 21646,
      "fixtures": [ __380_items__ ],
      "weeks": [ __34_items__ ],
      "rounds": [ __38_items__ ]
     }
   ]
}

***********************************
❌ - Cache
***********************************
{
  "league_id": 8,
  "seasons": [
    {
   ❌ "season_id": 19734,
      "fixtures": [ __380_items__ ],
 ❗️❓  "weeks": [ __0_items__ ],
      "rounds": [ __38_items__ ]
     }
   ]
}

```

- `Champions League`
> **League Id: 2**
> **NEW Season Id: 21638**

> **📌 Reason for `CACHE` inconsistency**
> `New Season Fixtures` have already played, and `cache` correctly injected new data. However, the `surgical` data was injected into the existing `cache`, as a `NEW Season` object. This is incorrect, as `cache` should only hold **1** season object - the `current-season` data.

> **🟩 SOLUTION**
> Check for data in `cache` as being outdated, and re-generate data for the `entire` NEW season.

```
***********************************
✅ - Direct Hasura (Fallback) Data
***********************************
{
  "league_id": 2,
  "seasons": [
    {
  ✅ "season_id": 21638,
      "fixtures": [ __57_items__ ],
      "weeks": [ __5_items__ ],
      "rounds": [ __4_items__ ]
     }
   ]
}

***********************************
🟠 - Cache
***********************************
{
  "league_id": 2,
  "seasons": [
    {
   ❌ "season_id": 19699,
      "fixtures": [ __214_items__ ],
  ❗️❓ "weeks": [ __0_items__ ],
  ❗️❓ "rounds": [ __0_items__ ]
     },
     {
   ✅ "season_id": 21638,
      "fixtures": [ __3_items__ ],
      "weeks": [ __1_items__ ],
      "rounds": [ __1_items__ ]
     }
   ]
}
```

---

**Standings [widget]**

> `Cache` appears to be **lagging behind**. However, using direct `fallback Hasura` data shows correct data.

- `Premier League` 
> **League Id: 8**
> **NEW Season Id: 21646**

> **📌 Reason for `CACHE` inconsistency**
> [?]

```
***********************************
🟠 - Direct Hasura (Fallback) Data
***********************************
{
  "league_id": 8,
  "seasons": [
    ... __16_other_items__ ,
   {
 ✅ "season_id": 19734,
    "standings": 
    [ 
       {
          "stage_name": "Regular Season",
          "group_based": false,
          ❌ "total": 
          [
             {
                "team_logo": "https://cdn.sportmonks.com/images/soccer/teams/19/19.png",
                "team_name": "Arsenal",
                "color_code": "#8DD890",
                "points": 54,
                "position": 1,
                "games_played": 23,
                "won": 17,
                ...
              },
              ... __19_other_items__ ,
          ],
          ❌ "home": [...],
          ❌ "away": [...],
       }
    ],
   },
    {
   ✅ "season_id": 21646,
      "standings": 
      [ 
         {
            "stage_name": "Regular Season",
            "group_based": false,
            ❌ "total": 
            [
               {
                  "team_logo": "https://cdn.sportmonks.com/images/soccer/teams/9/9.png",
                  "team_name": "Manchester City",
                  "color_code": "#8DD890",
                  "points": 89,
                  "position": 1,
                  "games_played": 38,
                  "won": 28,
                  ...
                },
                ... __19_other_items__ ,
            ],
            ❌ "home": [...],
            ❌ "away": [...],
         }
      ],
     }
   ]
}

***********************************
❌ - Cache
***********************************
{
  "league_id": 8,
  "seasons": [
    {
   ❌ "season_id": 19734,
      "fixtures": [ __380_items__ ],
 ❗️❓  "weeks": [ __0_items__ ],
      "rounds": [ __38_items__ ]
     }
   ]
}


---

**Top-Players [widget]**

---

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena-scores-platform.herokuapp.com/football/indonesia/liga-1

Missing data also on current season top players and data about the season:

![Image](https://github.com/Betarena/scores/assets/37311649/ea8c2248-4912-4235-96ee-50b1c48f0e94)

**Comment by jonsnowpt** [comment]
@migbash 

Also, live are not shown on the fixtures:

![Image](https://github.com/Betarena/scores/assets/37311649/46a7672d-c2c9-42d3-b869-828a20c88856)

This was features that worked in the past.

**Comment by migbash** [comment]
**NOTES**

> `Also, live are not shown on the fixtures:` - fixed and deployed to `DEV`

**Comment by jonsnowpt** [comment]
@migbash 

Considering that the season is yet to start, there should not be stats available.

![Image](https://github.com/Betarena/scores/assets/37311649/d030fe2d-1e0b-4138-abba-5b953018f36e)

===

The provider does not have available for example the number of teams playing in the tournament?

https://betarena-scores-platform.herokuapp.com/football/england/premier-league

![Image](https://github.com/Betarena/scores/assets/37311649/b60e5d5c-1e00-4afc-885f-7dd63bee56b8)

**Comment by jonsnowpt** [comment]
@migbash 

Also top players is missing from almost every tournament:

https://betarena-scores-platform.herokuapp.com/football/republic-of-ireland/premier-division

https://betarena-scores-platform.herokuapp.com/football/estonia/meistriliiga

https://betarena-scores-platform.herokuapp.com/football/iceland/pepsideild

https://betarena-scores-platform.herokuapp.com/football/norway/eliteserien

https://betarena-scores-platform.herokuapp.com/football/argentina/superliga

https://betarena-scores-platform.herokuapp.com/football/brazil/serie-b

**Comment by jonsnowpt** [comment]
@migbash 

We are getting the "week 1" issue on fixtures again inside the tournaments:

https://betarena-scores-platform.herokuapp.com/football/republic-of-ireland/premier-division


![Image](https://github.com/Betarena/scores/assets/37311649/587f9be5-846e-425c-8f8b-776f7c3ddf50)

**Comment by jonsnowpt** [comment]
@migbash 

Standings are not updating at this time. Is it because of the data updating that's happening?

Example:

https://scores.betarena.com/football/brazil/serie-b

Botafogo should have 16 played games, not 15.

This is happening on all tournament standings.
