### ISSUE TITLE
Missing fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1440]
We are missing hundreds if not thousands of fixtures. We need a solution to guarantee that all fixtures are available.

https://scores.betarena.com/football/valmiera-olimpija-18844223

https://scores.betarena.com/football/ferencvros-k-18844221

https://scores.betarena.com/football/qaraba-lincoln-red-imps-18844227

https://scores.betarena.com/football/dinamo-tbilisi-astana-18844241

https://scores.betarena.com/football/ludogorets-kf-ballkani-18844215

https://scores.betarena.com/football/swift-hesperange-slovan-bratislava-18844231

https://scores.betarena.com/football/larne-hjk-18844225

https://scores.betarena.com/football/universitario-corinthians-18863942

https://scores.betarena.com/football/botafogo-patronato-18863936

https://scores.betarena.com/football/al-ahly-haras-el-hodood-18864423

https://scores.betarena.com/football/estudiantes-barcelona-guayaquil-18863932

https://scores.betarena.com/football/emelec-sporting-cristal-18863944

https://scores.betarena.com/football/san-lorenzo-independiente-medelln-18863946

https://scores.betarena.com/football/audax-italiano-ublense-18863934

https://scores.betarena.com/football/ask-klagenfurt-admira-18852273

https://scores.betarena.com/football/voitsberg-first-vienna-18852274

https://scores.betarena.com/football/austria-xiii-st-anna-18852275

https://scores.betarena.com/football/bad-gleichenberg-grazer-ak-18852276

https://scores.betarena.com/football/deutschlandsberger-sc-kapfenberger-sv-18852277

https://scores.betarena.com/football/kufstein-wolfsberger-ac-18852278

https://scores.betarena.com/football/mannsdorf-weiz-18852279

https://scores.betarena.com/football/favoritner-ac-hartberg-18852281

https://scores.betarena.com/football/ferlach-leoben-18852282

https://scores.betarena.com/football/haitzendorf-aut-floridsdorfer-ac-18852284

https://scores.betarena.com/football/olimpia-nacional-asuncin-18852568

**Comment by migbash** [comment]
**NOTES**

@jonsnowpt same issue as before, and already explained in #1417.

All `above` fixtures are in `+ 2 Weeks` time, the endpoint responsible hasn't picked them up yet to update the `sitemap`.

Haven't yet been discussed -> https://betarena.slack.com/archives/D02B1UHEECS/p1687867105155709?thread_ts=1687866898.777259&cid=D02B1UHEECS

**Comment by jonsnowpt** [comment]
@migbash 

Follow has discussed here:

https://betarena.slack.com/archives/D02B1UHEECS/p1688567286763599

**Comment by jonsnowpt** [comment]
@migbash 

The issue persists, with thousands of fixtures with 404 errors.
