### ISSUE TITLE
Competition Lobby Frontent page generation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1441]
For the competitions, we will have the "lobby" where the users will be able to check all available competitions besides the page per each competition.

The lobby is generated based on the `competitions_home_translations `

![Image](https://user-images.githubusercontent.com/37311649/252640994-efc3453a-5149-4ca7-b52a-4eea11c89b31.png)

---

#### 📱 TARGET PLATFORMS

The competition Home page will be available on all versions, desktop, tablet, and mobile.

---

#### 🎬 INITIAL STATE

Data used for the lobby frontend page creation (endpoint: competitions_home_translations):

**Breadcrumbs:** 

```
url = competitions_home_translations/data {title}
```

Page URL

```
url = competitions_home_translations/data {title}
```

**Example:** `https://scores.betarena.com/competitions`

SEO

The endpoint to get the SEO data: ** competitions_seo_homepage**. Depending on the language, the following data should be loaded:

```
main_data
opengraph
twitter_card
```

Make use of the hreflang for all available languages.

```
    <link rel="alternate" hrefLang="it" href="https://scores.betarena.com/it/competizioni">
    <link rel="alternate" hrefLang="es" href="https://scores.betarena.com/es/competiciones">
    <link rel="alternate" hrefLang="fr" href="https://scores.betarena.com/fr/competitions">
    <link rel="alternate" hrefLang="pt" href="https://scores.betarena.com/pt/competicoes">
    <link rel="alternate" hrefLang="pt-BR" href="https://scores.betarena.com/br/competicoes">
    <link rel="alternate" hrefLang="ro" href="https://scores.betarena.com/ro/competiții">
    <link rel="alternate" hrefLang="se" href="https://scores.betarena.com/se/tavlingar">
    <link rel="alternate" hrefLang="x-default" href="https://scores.betarena.com/competitions">
    <link rel="canonical" href="https://scores.betarena.com/competitions">
```

### Load the correct SEO information:

`competitions_seo_homepage`

**SEO ENDPOINT:** competitions_seo_homepage

**_Example content:_**

```
EN 

main_data

{"title":"Betarena Daily Fantasy Sports for Cash","noindex":"false","keywords":"Competitions","nofollow":"false","canonical":"https://scores.betarena.com/competitions","description":"Engage in thrilling new sports competitions on Betarena. Showcase your skills, win prizes, and stay updated with the latest tournament formats. Join now!"}

opengraph

{"url":"https://scores.betarena.com/competitions","type":"website","title":"Betarena Daily Fantasy Sports for Cash","images":[{"alt":"Competitions","url":"https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg","width":850,"height":650}],"locale":"en_GB","description":"Engage in thrilling new sports competitions on Betarena. Showcase your skills, win prizes, and stay updated with the latest tournament formats. Join now!"}

twitter_card

{"site":"@betarenasocial","image":"https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg","title":"Betarena Daily Fantasy Sports for Cash","imageAlt":"Competitions","description":"Engage in thrilling new sports competitions on Betarena. Showcase your skills, win prizes, and stay updated with the latest tournament formats. Join now!"}

```

---

### Versions:

This section will be available on Light and Dark Theme.

---

### Data Endpoints:

**Hasura endpoint Prod:**

```
competitions_seo_homepage
competitions_home_translations
```

---

#### ⚡️ CACHE

Fallback approach.

---

### Hreflang Support:

Add alternate lang pages for search engine optimization.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=T6PMWA2fXUQ6V4bP-1

**Comment by migbash** [comment]
> **Important**
> Target data has been moved from:
> - `competitions/competitions_home_translations` to `competitions/translation_page_home`
> - `competitions/competitions_seo_homepage` to `competitions/seo_page_home`

**Comment by migbash** [comment]
> **Warning**
> @jonsnowpt Invalid data parameters in some of the `(column) main_data` in `competitions/seo_page_home`. Please correct to valid type, using the link found in `💠 Data Handling` note in `Obsidian` for target `table > column`, marked as `(DATA)`, to validate the expected type for said `(column)`.
>
> Wrong type example:

```json
"noindex": "Falso", // incorrect
"nofollow": "Falso", // incorrect
```

**Comment by jonsnowpt** [comment]
@migbash 

Check now.

**Comment by migbash** [comment]
> **Warning**
> @jonsnowpt Invalid data for `(column) data` in `competitions/translation_page_home`, for the use of the `\n`. Should be `<br />` instead, as per usual.
