### ISSUE TITLE
Header - Add competition and "Predictor" option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1442]
For the competitions header, we need to add the icon and name of the competitions category.

This information can be gathered in the endpoint `competitions_category `

![Image](https://user-images.githubusercontent.com/37311649/252646276-d1285678-29fc-4d3b-a93f-2b0fcd61783e.png)

---

#### 📱 TARGET PLATFORMS

Teams pages will be available on all versions, desktop, tablet, and mobile.

---

SEO

Competitions category name.

---

### Versions:

This section will be available on Light and Dark Theme.

---

### Data Endpoints:

**Hasura endpoint Prod:**

```
competitions_category
competitions_category_translations
```

---

#### ⚡️ CACHE

No cache implementation for now.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=OYAWATH0TBUR0Oh9-1

**Comment by migbash** [comment]
> Competitions category name.

@jonsnowpt Where's the `category name` ?

**Comment by jonsnowpt** [comment]
Where's the category name ?

@migbash translation_category


Why is the data (column) in the (now called) category table used for ?

@migbash the administrator runs the event trigger there and it will create a new competition based on that data.
