### ISSUE TITLE
Tournaments - Missing the tips links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1444]
![Image](https://user-images.githubusercontent.com/37311649/252707293-632a9c16-6eec-4034-9d02-6f6f180a255b.png)
![Image](https://user-images.githubusercontent.com/37311649/252707292-d58acd02-b29f-4461-98aa-c0382d7f48b7.png)

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt updated. Caused by a missing event trigger on `cache`, corrected.

**Comment by migbash** [comment]
**NOTES**

@jonsnowpt updated.
