### ISSUE TITLE
Content paragraphs

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1448]
We need to have paragraphs on the content using `/n`.

![Image](https://user-images.githubusercontent.com/37311649/254829628-49ebd178-5be1-471f-a034-aeb59883b68e.png)

![Image](https://user-images.githubusercontent.com/37311649/254829627-8343a5ed-e88b-4b01-b413-0832a6210fc3.png)

**Comment by migbash** [comment]
@jonsnowpt please use `<br/>` instead of `/n`. Or wrap each `paragraph` in an appropriate `<p>...</p>` or `<span>...</span>` tags, for better `margin` and `padding` UI control of the text.

**Comment by jonsnowpt** [comment]
@migbash 

Adding them.

**Comment by migbash** [comment]
@jonsnowpt Has this been updated ?

**Comment by jonsnowpt** [comment]
@migbash 

Still working on that.

**Comment by jonsnowpt** [comment]
@migbash 

This has been done!
