### ISSUE TITLE
Balance not being updated

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1452]
![Image](https://user-images.githubusercontent.com/37311649/254874754-a14895ee-3c70-4a5d-991f-062ff9ec4507.png)

**Comment by migbash** [comment]
@jonsnowpt You mean not updated `live (real-time)` ? It should be visible on `refresh`.

**Comment by jonsnowpt** [comment]
@migbash 

It's not updating even on refresh, and yes should be in real-time.
