### ISSUE TITLE
Transaction list corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1453]
- [x] 1. Missing the bottom border before the "Please review"
- [x] 2. Only when more than ten results the "Show more" should be available;
- [x] 3. Missing the description below the Type;
- [x] 4. The hover effects on the dates are not correct;
- [x] 5. Selecting other dates does not show any transaction;

![Image](https://user-images.githubusercontent.com/37311649/254895633-62f80e60-c132-4213-9652-3291173aa6c3.png)

**Comment by migbash** [comment]
> @jonsnowpt 
> * [ ]  5. Selecting other dates does not show any transaction;

What is wrong exactly ?
And which one is wrong from the `filter` selection (below) ?

The way it works, is:

- `Last 7 Days` = The last `7 days`.
- `Last Month` = All dates from the previous month.
- `Last 6 Months` = All dates from the past 6 months, starting from `current month - 1st` date.

**Comment by jonsnowpt** [comment]
@migbash 

When we select any of the dates, no transactions are shown, and it should be visible; check the recorded session:

https://github.com/Betarena/scores/assets/37311649/450344db-15f2-4fd8-b899-6cb822b1f816

**Comment by jonsnowpt** [comment]
@migbash 

Still missing the bottom border:

![Image](https://github.com/Betarena/scores/assets/37311649/6962b4e5-2eaf-4e2a-9b0f-ec818d2652df)


Missing the hover here:

![Image](https://github.com/Betarena/scores/assets/37311649/bf99b892-dc61-4081-b9c5-01d5631995d9)


When custom is selected, the white border and darker icon should be the one highlighted:

![Image](https://github.com/Betarena/scores/assets/37311649/e1b614f9-274c-4aba-bf93-85c52a1aa973)


Allow to select a 90 days range on the custom option.

**Comment by migbash** [comment]
> @jonsnowpt 
> 
> 90 days range

As in, up to `90 Days` maximum ? Or every date selection will be of `90 Days` range instead of the currently set `7 days` ?

**Comment by jonsnowpt** [comment]
@migbash 

90 days max, user is free to select the date range he wants.

**Comment by jonsnowpt** [comment]
@migbash 

The top column data-position should be fixed and not change when data is available.

![Image](https://github.com/Betarena/scores/assets/37311649/bf154489-8167-43a6-ae02-1bb796355d8c)
![Image](https://github.com/Betarena/scores/assets/37311649/10184956-6699-478d-9592-0047764a7697)

The custom selection is not working and do not have the hover and active selection CSS set.

**Comment by jonsnowpt** [comment]
@migbash 

Still missing the border, and the top options in the top row still move when there is data.

Also, the custom selection is not higlighting the initial day.

https://github.com/Betarena/scores/assets/37311649/afd8866f-ee63-4d0b-bd1e-7a2e3e596b03
