### ISSUE TITLE
Featured Match Non-existent `1X2FT`

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#148]
Some of the games selected for specific countries and respective `sportdetails_bookmakers` do not have `1X2FT` odds available, thus crash the widget as the odds are not correct:

![image](https://user-images.githubusercontent.com/20924663/150276511-261bc712-8464-47a5-bcff-cbf96dc33b9f.png)

**Comment by jonsnowpt** [comment]
Hi!

Already reported, we will check in the next sprints, thank you!
