### ISSUE TITLE
Withdraw corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1483]
- [x] 1. Missing the mouse pointer;
- [x] 2. Withdraw options must follow the ID;
- [x] 3. Zero balance is informing of undefined;
- [x] 4. Paypal form: Logo incorrect size; on Firefox, the forms do not have the correct size; the submission button does not have the correct size;
- [x] 5. Missing the "BTA" information;
- [x] 6. The header is on top of the popup and dark background;
- [x] 7. Missing mouse pointer;
- [x] 8. Min. Allowed withdrawal is 5 BTA; add this alert to the forms;
- [x] 9. Missing hovers and mouse pointer;
- [x] 10. The forms cant accept the content like this; for value, it must be a numeric value and verified against the balance. The other fields cant accept one letter, and the IBANS and SWIFT CODES have rules.
- [x] 11. I submitted a form with the letter "s" everywhere, and my balance went to "0".

1.

![Image](https://user-images.githubusercontent.com/37311649/257553327-d877bae3-03a2-4c9d-ba17-e9516b76ecc6.png)

3.

![Image](https://user-images.githubusercontent.com/37311649/257554614-a1dc9ab2-c782-4314-aada-687072680ee5.png)

4.

![Image](https://user-images.githubusercontent.com/37311649/257555426-c6d69118-c8b3-4e80-a755-37269eb6e670.png)

5.

![Image](https://user-images.githubusercontent.com/37311649/257556733-502601c2-855e-440c-ac30-4b0e26a7ba2f.png)

6.

![Image](https://user-images.githubusercontent.com/37311649/257557000-5435c72c-c557-4002-a4e7-2c61a9c7ee5f.png)

7.

![Image](https://user-images.githubusercontent.com/37311649/257557419-48a219d8-d741-4260-a605-b45844a0abca.png)

9.

![Image](https://user-images.githubusercontent.com/37311649/257558058-08004430-8ede-4a8e-a756-0141f0f1a47d.png)

10.

![Image](https://user-images.githubusercontent.com/37311649/257558638-0c4e061b-9ea0-4a30-a62a-966e5154741b.png)

11.

![Image](https://user-images.githubusercontent.com/37311649/257559440-e77d86a7-6e2b-412d-bf34-779585b0fe58.png)

**Comment by jonsnowpt** [comment]
@migbash  2. Withdraw options must follow the ID;

`id`

**Comment by jonsnowpt** [comment]
@migbash 

3. Still getting the balance error issue:

![Image](https://github.com/Betarena/scores/assets/37311649/75c6dd2f-2183-4cd2-bbfd-eb9b3d48a5d1)

![Image](https://github.com/Betarena/scores/assets/37311649/a723e9f5-fe68-4291-8ae6-04617a269f75)

6. The header is still on top of the background, and the solution of trying to keep the popup out of the header space is making the popup very small on the most used desktop resolutions. 1366 x 768

![Image](https://github.com/Betarena/scores/assets/37311649/b3bea324-8ba0-4af3-917c-b56ea4100d3e)
![Image](https://github.com/Betarena/scores/assets/37311649/843151b1-381c-4f35-846a-83c0eccf426f)

10 and 11, I'm not able to test since the deposits are not changing the user's balances.

12. The forms are unusable on mobile at this time.

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt 10 and 11, I'm not able to test since the deposits are not changing the user's balances.

Not working via the `manual event trigger` ?

**Comment by jonsnowpt** [comment]
@migbash Not working via the manual event trigger ?

Yes

**Comment by jonsnowpt** [comment]
11. The forms continue to be unusable on mobile at this time.

![Image](https://github.com/Betarena/scores/assets/37311649/85adffa8-a7a0-451a-9109-8428fce4e677)

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt that is because your mobile is probably set to use a different **language** other than the `EN`. The `betarena_general_data/translations/withdraw_form` contains only  translations for `EN`. Please update for other languages.
