### ISSUE TITLE
Withdraw cancelation is decreasing the balance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1490]
Instead of increasing back the balance when running the trigger event on a `canceled` status, it decreases the user balance instead of correctly increasing it.

**Comment by migbash** [comment]
Related / parent => [#4](https://github.com/Betarena/firebase-services/issues/4)

**Comment by jonsnowpt** [comment]
@migbash 

At this time, the balance keeps the same when running the event trigger.

**Comment by migbash** [comment]
> @jonsnowpt what is the name of the `event name` that is expected to be inside the `transaction_history > status (column)` for when cancellation occurs ? Currently it's set to `canceled` as per initial 1st issue comment.

**Comment by migbash** [comment]
**NOTES**

> 🟩 **Adjusted** to use both `failed` and `canceled` for transaction amount rollback for target transaction.

**Comment by migbash** [comment]
**NOTES**

> 🟩 **Adjusted** - final correction made.
