### ISSUE TITLE
Transaction list "Show More"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1491]
The "Show More" option is visible when there are no more transactions to load:

![Image](https://user-images.githubusercontent.com/37311649/258654231-2e487f67-b4d7-447f-a8c7-7ac5a20cdf31.png)

**Comment by migbash** [comment]
**NOTES**

> Invalid check error for correct variable that holds the target transactions list `filtered` data.

**Comment by jonsnowpt** [comment]
@migbash 

After showing more, the "Show more" should be hidden if there is no more data to be shown.

**Comment by migbash** [comment]
> **Note**
> Active on `DEV` since `v797`.

**Comment by jonsnowpt** [comment]
@migbash 

Show more option is not visible at this time.

**Comment by migbash** [comment]
> **Note**
> Active on `DEV` since `v798`.
