### ISSUE TITLE
Withdraw "Crypto" Step 1 Translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1494]
The following translations are missing:

![Image](https://user-images.githubusercontent.com/37311649/258750117-d72ee377-67ec-41de-8343-492fc151f24b.png)

Added the expressions:

```
        "option_funds": "Levantar todos os fundos disponíveis",
        "coin":"Coin:",
```

**Comment by migbash** [comment]
NOTES

Invalid data structure / json-schema / typescript-interface for the form_success column data.

**Comment by jonsnowpt** [comment]
@migbash 

Not working.



![Image](https://github.com/Betarena/scores/assets/37311649/1468b1cd-562f-4dc4-a220-9e321aee69fc)

**Comment by migbash** [comment]
> @jonsnowpt Please provide the language translation of the issue.

**Comment by jonsnowpt** [comment]
@migbash 

Isnt this one?

![Image](https://github.com/Betarena/scores/assets/37311649/a9006bf8-dff4-48b4-ae0a-c913d4b373df)

**Comment by migbash** [comment]
@jonsnowpt Yeah, but which language is that ? Please check, I have updated `RO` maybe related to #1496.

**Comment by jonsnowpt** [comment]
@migbash the lang I was testing is "PT" and the translation was added to the JSON, but it is not reflecting on the frontend.

**Comment by jonsnowpt** [comment]
@migbash ignore, resolved now.
