### ISSUE TITLE
Withdraw Romanian issue for Crypto

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1496]
For some reason, the Romanian version of the Crypto withdraws loads incorrectly:

![Image](https://user-images.githubusercontent.com/37311649/258763718-9dd78ef1-e1f8-4561-85ae-65e3ac826667.png)

**Comment by migbash** [comment]
NOTES

This looks to have been fixed, at the time of the check / issue resolution. All correct now.

**Comment by jonsnowpt** [comment]
@migbash 

Not working; I noticed that you probably replaced the data, but you added the `EN` version, and I replaced it with the `RO`, and it's not working. If the `JSON` was changed, please confirm so that I can change it on our files to avoid replacing it with an incorrect format.

**Comment by migbash** [comment]
> @jonsnowpt The `JSON` was always the same as that of the `EN` and other languages. It was changed, but not for a long time since creation.

**Comment by jonsnowpt** [comment]
@migbash 

Ok, still having the same issue.

**Comment by migbash** [comment]
@jonsnowpt **🟩 Adjusted**

**Comment by jonsnowpt** [comment]
@migbash 

Happening to `Italian` now.

**Comment by migbash** [comment]
**NOTES**

> Invalid `IT` and `RO` json.
