### ISSUE TITLE
Mobile - Forms CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1497]
We need to change this popup approach to look more like an app and less like a website.

Check the following example:

https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/tmp%2FRPReplay_Final1691276435.MP4?alt=media&token=c3ce09c4-75e2-4623-af65-6b112f30da3e

https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/tmp%2FRPReplay_Final1691337495.MP4?alt=media&token=bd16c9c5-7c1c-46e1-bcb1-01d533f31cc5

The idea is to keep the submit buttons always visible and the form to occupy the screen and not just a web popup. 

---

This has been updated on the FIGMA file:

![Image](https://user-images.githubusercontent.com/37311649/258766354-2828c20a-5359-4474-893d-0d3246184bea.png)

**Comment by migbash** [comment]
**NOTES**

> **🟩 Feature Added**

**Comment by jonsnowpt** [comment]
@migbash 

The mobile forms are not doing the necessary form checks, enough balance, and minimum withdrawal.

---

- [ ] Also, the balance, when not available, shows a `NaN`.

![Image](https://github.com/Betarena/scores/assets/37311649/94219820-59a2-48c3-ad4b-717f6f1ecef0)

---

- [ ] The CSS for the Successful message has issues:

![Image](https://github.com/Betarena/scores/assets/37311649/10179223-ccdc-46a4-b7fe-5bb940883446)


FIGMA:

![Image](https://github.com/Betarena/scores/assets/37311649/c1203e15-f304-4483-bbf4-2b04b21abbfd)

---

- [ ] Remove the Focus feature.

**Comment by migbash** [comment]
> ... necessary form checks, enough balance, and minimum withdrawal.

@jonsnowpt Only when when there is a `NaN` balance ?

> Remove the Focus feature.

@jonsnowpt Can you show it ? Don't know which `focus` feature.

**Comment by jonsnowpt** [comment]
@migbash 

Cannot remove focus/zoom on mobile due to Lighthouse hit in score. Previously talked about in [#14](https://github.com/Betarena/scores/issues/14)

A: In this section, that is not relevant. It seems disabled on the profile fields.

**Comment by migbash** [comment]
> **Note**
> Active on `DEV` since `v796`.
