### ISSUE TITLE
Lang Detection incorrect

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1498]
The following user has "PT" as the default language, but it is not detected on the first page when entering the platform, and the profile options are also not available in the correct language.

![Image](https://user-images.githubusercontent.com/37311649/258841823-ed1d8511-9a62-4b31-8cf3-90c6222f0d1c.jpg)
![Image](https://user-images.githubusercontent.com/37311649/258841822-243eb86e-d0ab-4869-8ec4-9caff62309f1.jpg)

**Comment by jonsnowpt** [comment]
@migbash 

Still having an issue:


![Image](https://github.com/Betarena/scores/assets/37311649/51cf88bd-119b-4c7b-b052-d7a61de62ef3)

**Comment by migbash** [comment]
> Still having an issue:

@jonsnowpt Missing the transalations for `Deposit`, `Withdraw`, `Transaction History` in `betarena_prod/public/profile_translations`

**Comment by migbash** [comment]
> **Note**
> Active on `DEV` since `v800`.
