### ISSUE TITLE
Competitions - Widget competition_rules

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1500]
### 📝 Description

The competition `competition_rules` widget includes the competition rules.

### Feature target platform availability

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

---

### 📸 Feature Request Image

https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Fcompetitions%2Fcompetitions_widget_list%2Fcompetition_rules.png?alt=media&token=8e565bec-d6b3-4bac-9cb1-ab8bfea0f933

### 🎬 Initial State

The widget has a placeholder, the same way we have on the scores widgets.

---

### Widget verification to display

Verify if available on `widgets_list`

`scores_widgets_list`

Widget id:

39

---

### 💠 Feature required data

➤ **Hasura**

 betarena_prod   > competitions   > competitions_translations 

---

### ⚡️ Cache

Fallback approach.

---

### 🔎 SEO

All content.

**Comment by migbash** [comment]
> **Warning**
> Missing transaltions (a.k.a `data`) for `rules` widget
> **ACTION**
> @jonsnowpt please add to `(schema) competitions > (table) translation_page_competition`

**Comment by jonsnowpt** [comment]
@migbash 

added.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v835`.
