### ISSUE TITLE
Skrill withdraw - Removed all balance "NULL"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1502]
I made a Skrill withdrawal, and the transaction history shows "NULL"  values and removed all the user balances.

![Image](https://user-images.githubusercontent.com/37311649/259022391-682db5e8-c1db-43ba-8b07-0e159d202baf.png)

`NULL` values should not exist, and if they happen, can't change the user balance to "0".

**Comment by migbash** [comment]
@jonsnowpt can you share the `console.logs` for this issue ?

**Comment by jonsnowpt** [comment]
@migbash 

Used skrill option on the `FR` lang. Added 5 BTA to be withdrawn and added the email. Didnt get the logs at the time.

**Comment by migbash** [comment]
> **Note**
> - Operation: `B_C_PROF_M_M_1`
> - Id: `4b61a6a992d58ad0c3932b623a3a46d197946241`
> - Timestamp: `08/08/2023, 09:29:54`
> 
> 🟩 No issues detected in `Hasura Logs`

---

> **Note**
> - Operation: `B_C_PROF_M_M_1`
> - Id: `c3feb29c27749add6a5bd1e4a2e5016f59de3575`
> - Timestamp: `08/08/2023, 09:29:23`
> 
> 🟩 No issues detected in `Hasura Logs`
