### ISSUE TITLE
Deposits stopped working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1503]
The event trigger is not changing the balance at this time.

**Comment by migbash** [comment]
@jonsnowpt all appears to be working as expected in terms of the `Manual Event Trigger`, it's just that your balance went to `NULL` which affects data handling / cases, as a cause of #1502.

**Comment by jonsnowpt** [comment]
@migbash did you change the balance from null back to its correct value?

**Comment by migbash** [comment]
@jonsnowpt reverted balance to `50 BTA`.

**Comment by migbash** [comment]
@jonsnowpt Are they working now ?

**Comment by jonsnowpt** [comment]
@migbash 

No.
