### ISSUE TITLE
Popup position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1505]
When browsing between langs and profile options, sometimes the popup is positioned outside the center:

![Image](https://user-images.githubusercontent.com/37311649/259078724-dd8822e1-d05f-429b-98d3-a375376ac693.png)

**Comment by migbash** [comment]
@jonsnowpt Cannot seem to replicate issue. When does it happen exactly ? As in, for example: switching from `one-lang` to another ? Or when doing something else ?

**Comment by migbash** [comment]
Tested overnight different configurations and could not replicate issue, leaving it for now.

**Comment by jonsnowpt** [comment]
I will close it. If it happens, I will reopen the issue.
