### ISSUE TITLE
withdraw transaction not showing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1507]
After filling up the form with `45,00`, the balance changed to `NaN`, and the transaction is not being shown on the transaction history.

![Image](https://user-images.githubusercontent.com/37311649/259122134-df2b8d90-9a5b-46cf-a497-1bc2862ef056.png)

**Comment by migbash** [comment]
**NOTES**

Error log identified from `Hasura` for this `transaction`:

```bash
[
  "{\"code\":\"data-exception\",\"error\":\"invalid input syntax for type numeric: \\\"45,00\\\"\",\"path\":\"$.selectionSet.insert_transaction_history.args.objects\"}"
]
```

**Comment by jonsnowpt** [comment]
@migbash 

Still happening when using` ","` it breaks.
