### ISSUE TITLE
Balance decimals

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1508]
It should only appear if the number is not an integer.

For example:

```
100.50 BTA 
100 BTA
```

![Image](https://user-images.githubusercontent.com/37311649/259174720-062776d5-6d2b-479a-a2ea-0644f39934de.png)

Same in the forms:

![Image](https://github.com/Betarena/scores/assets/37311649/550ed563-b003-400d-a3e0-0274cf19f511)

**Comment by migbash** [comment]
@jonsnowpt so `100.50` should be shown as `100` ?

**Comment by jonsnowpt** [comment]
@migbash 

No. `100.50` should be shown `100.50`

But,

`100.00` should be shown `100`

**Comment by migbash** [comment]
> **Note**
> Active on `DEV` since `v796`.
