### ISSUE TITLE
Deposit transaction not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1512]
Deposit ID: 43

![Image](https://user-images.githubusercontent.com/37311649/259807705-573123be-a507-4c44-9d6e-be4e5392181b.png)

**Comment by migbash** [comment]
> Caused by,

```bash
Error: variable 'status' is declared as 'String!', but used where 'transaction_history_enum_status_enum' is expected:
```

> **Note**
> Corrected via `@betarena/scores-lib` since `v.1.4.7 (patch)`.
