### ISSUE TITLE
Competitions Lobby Corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1513]
- [x] 1. Incorrect font size and weight;
- [x] 2. Incorrect behavior when selecting the home logo;
- [x] 3. Add the "new" icon;
- [x] 4. Smaller height;
- [x] 5. `RO` and `SE` 404 error;
- [x] 6. Add `H1` tag to the breadcrumb;
- [x] 7. Displays images with an incorrect aspect ratio
- [x] 8. Missing the hover;
- [x] 9. Title not respecting the <br>;
- [x] 10. Missing balance information;

1. 

![Image](https://user-images.githubusercontent.com/37311649/260981454-36c549bf-b369-42a5-b98a-83b9ea4b435f.png)

2. 

https://user-images.githubusercontent.com/37311649/260982224-6b16433c-a915-41f4-82cd-85e6b866acb2.mp4

3. 

![Image](https://user-images.githubusercontent.com/37311649/260982451-c887a033-de6f-4321-b8ad-6cc24d45870d.png)

4. 

![Image](https://user-images.githubusercontent.com/37311649/260983097-fa0f9619-18be-4780-8590-b7f04dd091dc.png)

7. 

![Image](https://user-images.githubusercontent.com/37311649/260985037-020ae0d5-10f4-4569-9275-84d3ea57a342.png)

8. 

![Image](https://github.com/Betarena/scores/assets/37311649/d95799c6-3f3c-479d-9914-a6b364371e85)

9. 

![Image](https://github.com/Betarena/scores/assets/37311649/d9be368d-e0d1-49f5-91b9-06f95447d446)

10. ![image](https://github.com/Betarena/scores/assets/37311649/67151702-0548-4a6f-b979-1557a4d7f5a0)

**Comment by migbash** [comment]
@jonsnowpt In general, should the `No competitions...` view be shown when there are no `competitions` for any of the 3 (open, active, finished) status ?

**Comment by jonsnowpt** [comment]
@migbash yes but now it's probably never happen. Just if an error loading the competitions occur

**Comment by migbash** [comment]
> - [ ] 6. Add H1 tag to the breadcrumb;

@jonsnowpt Is this also that needs to be available on a target `competition` page ? As it also has the `Competition > ...` breadcrumb.

**Comment by jonsnowpt** [comment]
@migbash no, we have a title there that we can use no need to use the breadcrumbs.

**Comment by migbash** [comment]
> 9. Title not respecting the
> ;

@jonsnowpt What do you mean by this ?

**Comment by jonsnowpt** [comment]
@migbash the way the paragraph is I think. Should be:

"Nâo há competições disponiveis
/ de momento"

**Comment by migbash** [comment]
> @migbash the way the paragraph is I think. Should be:
> 
> "Nâo há competições disponiveis
> / de momento"

In that case, as with every translation it's a different sentence length, please add the `<br/>` and make the `translation` a `html` tag, using a `<p> .. </p>` so it can be correctly displayed on the `frontend`. You'd need to make the change on `competitions > (table) translation_page_home > no_competition_title: ...` on Hasura.

**Comment by migbash** [comment]
> - [ ] 2. Incorrect behavior when selecting the home logo;

@jonsnowpt Is the expected behaviour to `refresh` / `navigate to` the `competitions (lobby)` page ? And not go to the `scores` ?

**Comment by jonsnowpt** [comment]
@migbash 

Yes, it should go to scores; it's not working at this time. check the example:

https://github.com/Betarena/scores/assets/37311649/ff6838f6-4361-450e-8579-db8c2b3e09b4

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
