### ISSUE TITLE
[FEATURE]: Leagues season details and fixtures update

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1516]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

Since we are having issues with getting the season details and fixtures data correctly updated, we are using the provider API 3.0 to add a new approach that will keep all data correctly updated at the correct time.

### 📝 Feature Request Description

This approach will update:

```
All Season Details for the specified league
Update all future fixtures data for the current season ID (just specific fields)
```

### Approach:

Check the following endpoint every minute:

`{{baseUrl}}/:version/:sport/leagues?include=currentSeason`

With include: `currentSeason`

Use the `currentseason` information with the `standings_recalculated_at`

This way, we are able to identify the season id for updates and also get the information about the last time the data has been updated.

If the `standings_recalculated_at` for the specific season ID was updated after the timestamp information available on the `scores_football_seasons_details/last_update `, the data is going to be repopulated, and a new timestamp is added.

Besides that operation, we are updating specific fields on the `historic_fixtures` to guarantee that all information is correct for future fixtures.

Update the following fields for all fixtures of the season ID starting 24 hours after the `standings_recalculated_at`:

```
fixture_day
round_name
data
probabilities
valuebets
tvstations
player_ids
```

### ➕ Further context and resources (cummulative)

We can set this code to run under a corn job defined on Google Cloud Scheduler or inside Hasura.

At the end of the task, we should remove all other season details updates crons and check if some `historic_fixtures` crons should be also disabled.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
**🔸 UPDATE**

Change of target `date-range` is changed to `24h < x < 96h`.
