### ISSUE TITLE
[Bug]: Homepage Standings not updating

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The league standings on the homepage widget are not updating:

![Image](https://github.com/Betarena/scores/assets/37311649/fc9304b4-2cdd-4796-91c0-9c2d3b7e6f20)

### 🤔 Expected Behavior

Update on every standing change.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit:

https://scores.betarena.com/

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#257](https://github.com/Betarena/scores-lib/issues/257) (+ cache deplyment).
> Implemented, awaiting `🚀 deployment`.
