### ISSUE TITLE
[Bug]: Fixtures with wrong time depending on the GEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The fixture's date and time are incorrect when accessing from Portugal, the UK, and probably other GEOS. This only happens on the Mobile view:

![Screenshot 2023-08-17 at 19 06 04](https://github.com/Betarena/scores/assets/37311649/602e2d69-2236-41f8-be76-f38b9e55804d)
![Screenshot 2023-08-17 at 19 03 42](https://github.com/Betarena/scores/assets/37311649/89d3c318-80e5-42dd-8b12-ad1c47b32c77)

### 🤔 Expected Behavior

The hour should be correct on every browser and device.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit the home and fixture page on mobile.

**Comment by jonsnowpt** [comment]
It happens on both mobile and desktop versions.

**Comment by migbash** [comment]
> **Important**
> Applies to both `fixture (target)` and `competition (lobby / target)` pages.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.

**Comment by jonsnowpt** [comment]
@migbash 

Seems incorrect here:

![Screenshot 2023-09-12 at 09 24 08](https://github.com/Betarena/scores/assets/37311649/b0939daf-f7e1-4304-92ff-74d8fad184cc)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.
