### ISSUE TITLE
[Bug]: Standings Widget Error

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Standings Widget not working for all leagues. Still everyone with 0 points and 0 games

Premier League Example:

**Widget:**
![image](https://github.com/Betarena/scores/assets/114171785/a8c42e7f-eaca-475f-a365-29e8a5c0dc31)

**League Standings:**
![image](https://github.com/Betarena/scores/assets/114171785/39648cf2-2e43-490f-95cf-2d621cb040d1)

### 🤔 Expected Behavior

The Standings table widget in the main page should be up to date.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Open the [scores platform](https://scores.betarena.com/) and scroll down to the Standings widget

**Comment by jonsnowpt** [comment]
Resolved.
