### ISSUE TITLE
[Bug]: Competitions Page Breadcrumbs sport link

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The breadcrumbs sport do not have a link at the moment.

![Screenshot 2023-08-30 at 09 21 10](https://github.com/Betarena/scores/assets/37311649/a83f0f61-13b7-4338-955e-5ce4559570ea)

### 🤔 Expected Behavior

The sports link should redirect the user to the score's homepage. (for each correct language).

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition page.

**Comment by migbash** [comment]
> **Note**
> Fix implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
