### ISSUE TITLE
[Bug]: Competitions page probability not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The probability in the fixture is not working at this time:

![Screenshot 2023-08-30 at 09 28 02](https://github.com/Betarena/scores/assets/37311649/904c7350-4750-4361-a65a-3725602d7484)

### 🤔 Expected Behavior

Probability should be associated with the prediction made.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

### Anything else?

- [🎫 | Scores-Lib #226](https://github.com/Betarena/scores-lib/issues/226)

**Comment by migbash** [comment]
> Probability should be associated with the prediction made.

@jonsnowpt prediction made by the user ? Such as, if selected `no`, will only show probability for `no` outcome. Or the `probability` of the competition target for `yes` votes only ?

**Comment by migbash** [comment]
> 1X2 markets.

@jonsnowpt Those provided with the `historic_fixture.data.probability: ...` data from `Sportmonks` ? Or The `probability` from the `1x2` on `Firebase` ?

**Comment by jonsnowpt** [comment]
@migbash you can use historic fixtures no need for Firebase there.

**Comment by migbash** [comment]
@jonsnowpt 

This is meant to be in `real-time` updated ?

**Comment by jonsnowpt** [comment]
@migbash 

No need since this is pre-match information and do not change during the fixture.

**Comment by migbash** [comment]
@jonsnowpt 

Does it get updated before a fixture starts ? Or is it just a hardcoded, pre-match information data that never changes after being released to the public ?

**Comment by jonsnowpt** [comment]
@migbash even if it does we do not need real time. But yes it should be updated on the json

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash round the numbers, for example:

27.93% probability

should be:

28% probability

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
