### ISSUE TITLE
[Bug]: Competition page wrong font page weight

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The title font-weight is incorrect.

![Screenshot 2023-08-30 at 09 32 23](https://github.com/Betarena/scores/assets/37311649/27ff7fbc-8755-443d-a59c-7bfb36f2d479)
font weight

### 🤔 Expected Behavior

Font-weight is 600, not 700.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v814`.
