### ISSUE TITLE
[Bug]: Competitions incorrect breadcrumbs title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The breadcrumbs title is incorrect:

![Screenshot 2023-08-30 at 09 35 36](https://github.com/Betarena/scores/assets/37311649/8b98a257-ede8-4b01-b39e-6b3dd687d594)

### 🤔 Expected Behavior

Should be:

Team Hantharwady United will draw

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v814`.

> **Note**
> Live on `dev` from `v817`.
