### ISSUE TITLE
[Bug]: Competition countdown

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The countdown is going below 0.

![Screenshot 2023-08-30 at 09 41 12](https://github.com/Betarena/scores/assets/37311649/bb477b7c-440e-4fa9-ae8d-57b1bfc8bf3f)

### 🤔 Expected Behavior

The countdown should stop at 0 and change to playing after the fixture starts. If the game is late, it should keep 0 until a status change.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v820`.
