### ISSUE TITLE
[Bug]: Competitions social share

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The sharing options are not working.

![Screenshot 2023-08-30 at 09 44 23](https://github.com/Betarena/scores/assets/37311649/4d2f24cf-4c1b-46f5-a9ff-dd8083cc523e)

### 🤔 Expected Behavior

Able to share the competitions on the designated social networks.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition and try to share.

### Anything else?

- [🔗 | Social Media Link Generator Example](https://www.websiteplanet.com/webtools/sharelink/)

**Comment by migbash** [comment]
> Able to share the competitions on the designated social networks.

@jonsnowpt where are the `social` links for these social platforms ? Are they the same as the ones for the `footer` ?

**Comment by jonsnowpt** [comment]
@migbash this should be shared on the users social networks. Check the example on the original task

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash 

Should open the share in a new window. (_blank)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
