### ISSUE TITLE
[Bug]: Competitions tournament and items

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] The tournament icon is not. proportional; 
- [x] Font size is incorrect; it should be 19px, not 20px;
- [x] The flag should be rounded;
- [x] Change for the full country name;
- [x] Invalid full country name error.

![Screenshot 2023-08-30 at 09 48 35](https://github.com/Betarena/scores/assets/37311649/ce6a07ab-1636-4221-af60-9a91c0613df1)

### 🤔 Expected Behavior

- [x] The tournament icon is not. proportional; 
- [x] Font size is incorrect, it should be 19px, not 20px;
- [x] The flag should be rounded;
- [x] Change for the full country name;; it

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
>  The tournament icon is not. proportional;

@jonsnowpt What do you mean ? Are the `width` and `height` incorrect ?

**Comment by jonsnowpt** [comment]
@migbash in the example it seems the tournament icon are not proportional.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] The font size is incorrect for the tournament name;
- [ ] The flag size is incorrect;
- [ ] The logo of the tournament is not aligned;


![Image](https://github.com/Betarena/scores/assets/37311649/77027343-eb55-4237-895e-4e754966c489)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
