### ISSUE TITLE
[Bug]: Competitions incorrect preloader items position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The preloader items are in the incorrect order.

### 🤔 Expected Behavior

The preloader items should be in this order:

![Screenshot 2023-08-30 at 09 54 47](https://github.com/Betarena/scores/assets/37311649/d50cb10d-5dfd-43c1-975c-0a757fe831ac)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition on low-end mobile and take a look at the difference in the items order of the preloader.

**Comment by migbash** [comment]
> **Note**
> Implemented (fix), awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
