### ISSUE TITLE
[Bug]: Competitions incorrect spacing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The space between elements does not seem correct:

![Screenshot 2023-08-30 at 09 59 11](https://github.com/Betarena/scores/assets/37311649/206b4d36-3d35-4c6e-a3c7-79c9584fe082)

### 🤔 Expected Behavior

Correct spacing:

![Screenshot 2023-08-30 at 10 00 31](https://github.com/Betarena/scores/assets/37311649/3886d7cc-d0b4-43b9-a7c3-135859563624)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
@jonsnowpt What resolution is this on ?

**Comment by jonsnowpt** [comment]
1729 x 1329, for example, but it is on all Desktop resolutions.

**Comment by jonsnowpt** [comment]
@migbash done!
