### ISSUE TITLE
[Bug]: Wrong space

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Total prize: wrong space.

![Screenshot 2023-08-31 at 17 04 18](https://github.com/Betarena/scores/assets/37311649/907bbb03-8a60-4aa0-ad4a-2ae25daf52aa)

### 🤔 Expected Behavior

The space between elements should be lower.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition.

**Comment by migbash** [comment]
> The space between elements should be lower.

@jonsnowpt 

<img
src="https://github.com/Betarena/scores/assets/20924663/317ac9c2-4b11-46ef-bb61-8dcea9471cff"
width=250
/>

<img
src="https://github.com/Betarena/scores/assets/20924663/13dcf0b3-3ba8-424e-8ae5-3c5b7d5af712"
width=250
/>

Which is the correct expected spacing ? `41` or `46` ? It's not clear from the design.

**Comment by jonsnowpt** [comment]
@migbash 

41px to be similar to this:

![Screenshot 2023-09-05 at 21 58 40](https://github.com/Betarena/scores/assets/37311649/66977cd4-103a-48bc-9486-af9c771bc9bf)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
