### ISSUE TITLE
Betting sites change not loading the correct match

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#155]
If you check the attached image for the Portugal Betting sites it is loading bet365 which is not a supported betting site.

<img width="1457" alt="Screenshot 2022-01-20 at 18 09 13" src="https://user-images.githubusercontent.com/37311649/150396885-9a1e52da-0c90-479e-a7b0-e8a7bf5383c1.png">

**Comment by migbash** [comment]
Related to #147 #148
