### ISSUE TITLE
[Bug]: Competitions social share hover

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The hover at this time is not correct.

### 🤔 Expected Behavior

Correct hover:

![Screenshot 2023-08-31 at 17 28 04](https://github.com/Betarena/scores/assets/37311649/a274b853-9cf9-43ee-bc03-96f873270090)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition and hover over the social links.

**Comment by jonsnowpt** [comment]
@migbash 

The hover behavior is not correct:

https://github.com/Betarena/scores/assets/37311649/bea0e9f9-377e-4dcb-bf0c-324d77c9b86e

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v824`.

@jonsnowpt
