### ISSUE TITLE
[Bug]: Competitions back navigation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

If we navigate back on the browser, the data won't load correctly, "undefined" values are shown:

![Screenshot 2023-08-31 at 17 38 26](https://github.com/Betarena/scores/assets/37311649/b1da5129-fd6c-47cb-b6e1-bb24a80adae5)

### 🤔 Expected Behavior

No undefined values should be shown, and all data should be loaded correctly.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit the competition:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-qaraba-will-win/42

Select an option and move back on the browser.

**Comment by migbash** [comment]
**NOTES / REMARKS**

This appears to be working correctly at this time, perhaps related to another issue and its fix.

**Comment by jonsnowpt** [comment]
@migbash 

This happened in a competition that had no status, that was probably the cause.
