### ISSUE TITLE
[Bug]: Competitions dark theme

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Dark theme is not usable at this time:

![Screenshot 2023-08-31 at 17 42 48](https://github.com/Betarena/scores/assets/37311649/4c6de523-5da5-433f-8f19-f674a8ff288b)

### 🤔 Expected Behavior

Load the CSS correctly.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-qaraba-will-win/42

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
