### ISSUE TITLE
[Bug]: Invalid Competition Status

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Invalid `status` for when the win target status.

<img width="350" alt="image" src="https://github.com/Betarena/scores/assets/20924663/95ee058d-8fe6-4040-a761-09ce9c8e3847">

### 🤔 Expected Behavior

Should be `win` instead `lose`.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by jonsnowpt** [comment]
Resolved.
