### ISSUE TITLE
[Bug]: Competitions unregistered users no balance able to participate

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, unregistered users are able to participate in the competition, even without being logged and without balance.

### 🤔 Expected Behavior

Only registered users should be able to participate, and the balance should be checked to be allowed.

If a nonregistered user tries to compete, it should receive an alert with a message informing that he needs to be registered and 2 options: close or register.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition and participate.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v821`.
