### ISSUE TITLE
[Bug]: Competitions: Finished events allowing unregistered users

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Finished events keep showing the Join options for unregistered users:

![Screenshot 2023-08-31 at 21 16 43](https://github.com/Betarena/scores/assets/37311649/d96e6f80-13dc-4a69-83ae-e8b9a4330890)

### 🤔 Expected Behavior

The Join options should be disabled for all finished events.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a finished event like:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-qaraba-will-win/42

**Comment by migbash** [comment]
> The Join options should be disabled for all finished events.

@jonsnowpt There's an underlying error of the `WON` and `LOST` not being shown for when the `competition` is finished. Should the `WON` and `LOST` be shown for unauthenticated users also ? Or what is the expected design ?

**Comment by jonsnowpt** [comment]
@migbash yes it should show the won or canceled information
