### ISSUE TITLE
[Bug]: Competitions: Wrong link when changing lang

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

A 404 error appears when changing the language.

![Screenshot 2023-09-01 at 11 58 30](https://github.com/Betarena/scores/assets/37311649/516f201f-760d-4e8c-bf80-ce587a684f4a)

### 🤔 Expected Behavior

We should be able to change language and access the translated competition.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit and change the language:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-alianza-universidad-will-win/44

**Comment by jonsnowpt** [comment]
@migbash 

"RO" is not working:

https://betarena-scores-platform.herokuapp.com/ro/competitii/predictor/echipa-alianza-universidad-va-castiga/44

**Comment by migbash** [comment]
**🔸 UPDATE**

This occurs due to invalid `competitions` translation term diacritics clean: `ro_competiții` (needs to be simply `ro_competitii`) made on the `C# Backend` for `links_map` and the cache being affected by this.
