### ISSUE TITLE
[Bug]: Competitions missing link and number of "Open" competitions

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The "Predictor" option link is not working, and neither is the information about the number of competitions available.

![Screenshot 2023-09-01 at 12 21 16](https://github.com/Betarena/scores/assets/37311649/6c34ab1f-d662-467c-87d9-d36580e6a0e3)

### 🤔 Expected Behavior

Should link to the competitions category and show the number of "Open" competitions.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-alianza-universidad-will-win/44

**Comment by migbash** [comment]
> Should link to the competitions category

@jonsnowpt What `competitions` category ? We do not currently have a `/competitions/predictor` page route, as we opted away from it (already discussed). So where should it link to instead (the `predictor`) link ?

**Comment by jonsnowpt** [comment]
@migbash to the competitions lobby.

**Comment by jonsnowpt** [comment]
@migbash no need

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
