### ISSUE TITLE
[Bug]: Competitions breadcrumbs title languages

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The breadcrumbs in other lang is not correct:

![Screenshot 2023-09-01 at 12 27 10](https://github.com/Betarena/scores/assets/37311649/c456a083-baab-4dad-8504-eef1cb04d858)

### 🤔 Expected Behavior

The lang should be reflected in the breadcrumbs, for the sport and also for the title.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit a competition:

https://betarena-scores-platform.herokuapp.com/pt/competicoes/predictor/equipa-qaraba-vai-vencer/42

**Comment by migbash** [comment]
> **Note**
> Fixed as a `🧊 side-effect` of some other related issue.
> `⏸️ awaiting deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect:

![Image](https://github.com/Betarena/scores/assets/37311649/0b85bcf6-7ebf-4689-8f3c-ca1d2d9b518f)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
