### ISSUE TITLE
[Bug]: Competitions unable to participate

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, the Join button is not available on new competitions:

![Screenshot 2023-09-01 at 19 55 54](https://github.com/Betarena/scores/assets/37311649/5b719d0e-32ba-42b7-bc41-4c0e01cdeda9)

### 🤔 Expected Behavior

We should be able to participate in new competitions.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Create a new competition and try to join.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v823`.

@jonsnowpt
