### ISSUE TITLE
[Bug]: Competitions "No participants..."

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The "No participants..." message is incomplete, and the CSS is incorrect:

![Screenshot 2023-09-03 at 13 04 45](https://github.com/Betarena/scores/assets/37311649/129d5591-dddc-4631-a4ac-7bf0f238918d)

### 🤔 Expected Behavior

Correct message and CSS:

![Screenshot 2023-09-03 at 13 04 55](https://github.com/Betarena/scores/assets/37311649/4dd1461b-39a8-4d14-a322-719455fedb3e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-gil-vicente-will-win/45

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash 

Wrong size:



![Image](https://github.com/Betarena/scores/assets/37311649/3da72521-8919-4240-b069-ba7dce8a3151)

**Comment by jonsnowpt** [comment]
@migbash 

With the CSS refresh, its now ok.
