### ISSUE TITLE
[Bug]: Competitions Negative Pool prize

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Showing negative pool prize.

![Screenshot 2023-09-03 at 13 12 42](https://github.com/Betarena/scores/assets/37311649/57d4a638-ce93-42fd-bd0b-a79eb9f967b0)

### 🤔 Expected Behavior

No negative values are allowed.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit competition:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-wolverhampton-wanderers-will-win/46

**Comment by migbash** [comment]
**🔸 UPDATE**

Correct calculations being made on the `backend`. Appears to simply be a `frontend` platform issue in using the `betarena_comission` to show **total prize pool** amount that needs adjusting.
