### ISSUE TITLE
[Bug]: Competitions "lobby" finished competitions + canceled

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The canceled competitions are not visible in the "finished" competitions section. 

### 🤔 Expected Behavior

Canceled competitions should also be shown in the finished competition section.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit the competitions lobby and we can observe that the canceled ones are not available in the finished category.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
