### ISSUE TITLE
[Bug]: Competitions Link to Fixture + SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The fixture zone is missing the link to the fixture.

### 🤔 Expected Behavior

The fixture zone should include a link to the fixture that should be visible and crawlable for SEO purposes.

![Screenshot 2023-09-03 at 16 01 05](https://github.com/Betarena/scores/assets/37311649/f872ed74-73d3-4414-8760-2f99fe6874f7)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit any competition.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
