### ISSUE TITLE
[Bug]: Competitions link to tournament + SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The tournament link and name do not have the link to the tournament at this time.

![Screenshot 2023-09-03 at 16 03 10](https://github.com/Betarena/scores/assets/37311649/d4f46eb1-bbf8-4089-828b-76b3e862b892)

### 🤔 Expected Behavior

The tournament options should have a link to the tournament and also be visible and crawlable for SEO purposes.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit any competition.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
