### ISSUE TITLE
[Bug]: Competitions sport link + SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The sports link is not available at the time:

![Screenshot 2023-09-03 at 16 07 07](https://github.com/Betarena/scores/assets/37311649/14924b3b-7957-4127-bed1-2a749de76831)

### 🤔 Expected Behavior

The link for specific Livescore pages should be available, visible, and crawlable for SEO purposes.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit any competition.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
