### ISSUE TITLE
[Bug]: Competitions "0:0" result is not being shown

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The result at 0 is not shown:

![Screenshot 2023-09-04 at 07 00 56](https://github.com/Betarena/scores/assets/37311649/a25c2570-6134-4836-9321-3dbbd0dff137)

### 🤔 Expected Behavior

The "0:0" should be visible from the start.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-bragantino-will-win/47

**Comment by jonsnowpt** [comment]
@migbash 

The scores are not updating in real-time, and they should.

**Comment by migbash** [comment]
@jonsnowpt 

For which `competition` is this ?

At the moment, upon visiting the **currently active** competition / fixture, I get the correct `scores` shown:

<img
src=https://github.com/Betarena/scores/assets/20924663/12128550-7fb7-468e-8edf-4828c6c61ab4
width=250
/>

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-hapoel-raanana-will-win/48

**Comment by jonsnowpt** [comment]
@migbash 

I needed to refresh the competition page to get the updated score. I will keep there to see if the score changes on a goal.

**Comment by jonsnowpt** [comment]
@migbash it seems to be the old Firebase issue that stops updating from time to time

**Comment by migbash** [comment]
> **Note**
> Added a simple default show of `0` for both teams when scores have yet not become available, but competition has started.
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.
