### ISSUE TITLE
[Bug]: Competitions users should not be able to enter the event starts

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time users are able to enter the event after is already happening:

![Screenshot 2023-09-04 at 12 10 12](https://github.com/Betarena/scores/assets/37311649/a9969861-b9c5-44c1-bf70-e3e34d665e96)

### 🤔 Expected Behavior

Users should not be able to enter competitions after the fixture start.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Create a new competition, wait for the fixture to start, and we can confirm that the option to participate is still available.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v827`.

**Comment by jonsnowpt** [comment]
@migbash 

We need to change the color of these join buttons to grey after the event starts:


![Image](https://github.com/Betarena/scores/assets/37311649/3950811b-5d0a-4a35-a3f9-34217fd98768)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
