### ISSUE TITLE
[Bug]: Competitions participants order

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The participants are ordered by the oldest to the newest:

![Screenshot 2023-09-04 at 17 01 49](https://github.com/Betarena/scores/assets/37311649/c249629e-bde5-42fb-bc92-4fdc0bfbc004)

### 🤔 Expected Behavior

On top should be the newest participants, excluding the own user.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit any competition.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-num->.

**Comment by migbash** [comment]
> **Note**
> Took into effect as of `@betarena/scores-lib ➤ v.1.6.10` (via patch).

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
