### ISSUE TITLE
[Bug]: Competitions previous competition without user information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The user information is not present anymore:

http://betarena-scores-platform.herokuapp.com/competitions/predictor/team-bragantino-will-win/47

### 🤔 Expected Behavior

The user information should always be available.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

http://betarena-scores-platform.herokuapp.com/competitions/predictor/team-bragantino-will-win/47

**Comment by migbash** [comment]
> **Note**
> Nothing inherently wrong with the current logic / implementation and the `firebase public data` retrieval. Simply, the use of the `https://` is required, for a secure network connection. Therefore, upon visiting the link: https://betarena-scores-platform.herokuapp.com/ro/competitii/predictor/echipa-bragantino-va-castiga/47 , all works as expected. This is happening due to the string `CORS` added to the `firebase-services (functions)` endpoint for access only via `https://`.

> This issue can be closed @jonsnowpt.
