### ISSUE TITLE
[Bug]: Competitions Live Score information disappears

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The fixture scores stopped appearing.

![Screenshot 2023-09-04 at 19 15 29](https://github.com/Betarena/scores/assets/37311649/d84c912d-a3d2-4df8-82a6-94feeb181630)

### 🤔 Expected Behavior

The score information should always be available; need to use historic_fixtures.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

http://betarena-scores-platform.herokuapp.com/competitions/predictor/team-bragantino-will-win/47

**Comment by migbash** [comment]
> **Note**
> Related to the similar `data orphan` issue as that encountered in the `livescores-v2`. Endpoint creation for target `competition main (widget)` call data is required.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v837`.

**Comment by jonsnowpt** [comment]
@migbash 

Still not showing:

![image](https://github.com/Betarena/scores/assets/37311649/28bae9ce-4945-4734-93f8-bd0adbf13384)

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v838`.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ [#243](https://github.com/Betarena/scores-lib/issues/243).

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v841`.
