### ISSUE TITLE
[Bug]: Competitions own user always on top

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The user is not kept on top.

![Screenshot 2023-09-05 at 22 46 57](https://github.com/Betarena/scores/assets/37311649/30f325ac-5de5-419f-aa4b-b270fa5cd9aa)

### 🤔 Expected Behavior

The own user should always be on top.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Join a competition after other users.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
