### ISSUE TITLE
[Bug]: Competitions able to join more than once in the competition

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The users are able to join more than once in the competition.

https://github.com/Betarena/scores/assets/37311649/8ea5901e-4c5b-47a9-982e-16769c073316

### 🤔 Expected Behavior

Users should only be able to enter the competitions once.

The buttons should not be available on loading, and there must be a check if the user already exists on the DB to avoid duplicates.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Reload the competition.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
