### ISSUE TITLE
[Bug]: Add H1 and H2

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, there is no H1 or H2 present.

### 🤔 Expected Behavior

Add H1 and H2 for SEO purposes:

![Screenshot 2023-09-06 at 09 34 52](https://github.com/Betarena/scores/assets/37311649/2e8fb18d-3337-49ef-a825-f30aa955a91e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash Still missing.

**Comment by migbash** [comment]
> Add H1 and H2 for SEO purposes:

@jonsnowpt To clarify, the texts are supposed to be:
- `h1` -> `Team Gil Vincente will`
- `h2` -> `Liga Portugal` 

?

**Comment by jonsnowpt** [comment]
@migbash 

h1 -> Team Gil Vincente
h2 -> Liga Portugal

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing the "Team" expression before the actual team name.



![Image](https://github.com/Betarena/scores/assets/37311649/37b7bd0c-1f58-4eeb-830b-c29e5137837c)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
