### ISSUE TITLE
[Bug]: Competitions responsive issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The responsive adjustments are getting issues with elements overlapping each other.

https://github.com/Betarena/scores/assets/37311649/38a7494c-ea08-48e0-8fbe-c9df434da62a

### 🤔 Expected Behavior

Move to the tablet version before the elements overlap.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
