### ISSUE TITLE
[Bug]: Competitions the team box information should be fixed

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The box with the team and score information is getting larger depending on the team names.

![Screenshot 2023-09-06 at 09 46 52](https://github.com/Betarena/scores/assets/37311649/bb076677-cf18-4ed6-8c68-9dd8a4300691)

### 🤔 Expected Behavior

The box should have a fixed size, and the team names should have a "..." when the names are too big for the available size.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash 

The team name should be restricted to 1 line and to the space limit with (...)

![Image](https://github.com/Betarena/scores/assets/37311649/74fccc72-40a3-4de7-9ae0-f54dc4e63172)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
