### ISSUE TITLE
[Bug]: Competitions avatar position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The avatar position is not correct:

![Screenshot 2023-09-06 at 09 50 17](https://github.com/Betarena/scores/assets/37311649/3e678ef2-0844-4c3a-9e24-256b2e90d45b)

### 🤔 Expected Behavior

The avatars should closer to each other:

![Screenshot 2023-09-06 at 09 50 10](https://github.com/Betarena/scores/assets/37311649/0aa41bf7-739f-45b7-87b0-0e7e610f5131)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
