### ISSUE TITLE
[Bug]: Competitions reduce font-weight

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The font-weight on screen seems much thicker than on the design:

![Screenshot 2023-09-06 at 09 53 13](https://github.com/Betarena/scores/assets/37311649/4f679434-2149-4028-9402-21f68a8c78a3)

### 🤔 Expected Behavior

Change all fonts that have a font weight of 600 to 500 so that are more accurate with the design.

![Screenshot 2023-09-06 at 09 54 31](https://github.com/Betarena/scores/assets/37311649/ad12b56b-040e-4634-9f78-0e1a87c986e7)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> At the time of the issue creation, the for target text was of `font-weight: 600`, reduced to `500`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
