### ISSUE TITLE
[Bug]: Competitions name and vote color and position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The name and vote color are not correct:

![Screenshot 2023-09-06 at 10 00 38](https://github.com/Betarena/scores/assets/37311649/e40829fa-c962-4e48-bc51-d9cae1b952b9)

### 🤔 Expected Behavior

The color should be:

![Screenshot 2023-09-06 at 09 59 29](https://github.com/Betarena/scores/assets/37311649/92801c8c-a52a-460a-9c7a-299c29e419f1)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
