### ISSUE TITLE
[Bug]: Competitions lobby missing the mouse swipe

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The mouse swipes to move the competitions from left to right and vice versa are not working.

### 🤔 Expected Behavior

Example:

https://github.com/Betarena/scores/assets/37311649/ee09bbc2-2f27-480f-bb33-0fd654a1bced

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note***
> This should be working as expected already, via swipes on `lobby` page.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash 

Not working,

**Comment by migbash** [comment]
> Not working,

@jonsnowpt Need further clarification over a call.

**Comment by jonsnowpt** [comment]
@migbash 

Example of the dot carrousel:

https://swiperjs.com/demos/040-pagination-dynamic/core

**Comment by migbash** [comment]
> Example of the dot carrousel:

> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v835`.

**Comment by jonsnowpt** [comment]
@migbash 

This is still not correct:

- [ ] The arrows should only appear if there are more than 4 competitions;
- [ ] Should not slide automatically;
- [ ] The "Open", "Active" and "Finished" subtitles should only be available if there are competitions on that state;


Uploading Screenshare - 2023-09-13 2_10_34 PM.mp4…

**Comment by migbash** [comment]
> Should not slide automatically;

@jonsnowpt What do you mean by this ? Shouldn't it slide when using, in this case, the magic mouse sliding motion ? If not, what is the expected effect ? Also, does it work (the magic mouse) ?

**Comment by jonsnowpt** [comment]
@migbash it works uncontrollable, starts to slide and never stops. We can have a call tomorrow to show the behavior.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v836`.

**Comment by jonsnowpt** [comment]
@migbash 

The mouse slider still has strange behavior.

It also responds when the mouse is swiped up and down, and it should only respond to left and right.

Also, it should not allow us to go over the last competition:

![Screenshot 2023-09-13 at 22 00 54](https://github.com/Betarena/scores/assets/37311649/9ff3744c-fa57-4435-ba54-57e8d11af25a)

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v837`.

**Comment by jonsnowpt** [comment]
@migbash 

It seems the same issue is occurring.

https://github.com/Betarena/scores/assets/37311649/ecdf8ad0-f949-45d4-82b0-354642e38723

**Comment by migbash** [comment]
> It seems the same issue is occurring.

@jonsnowpt This is because small detection of the `X-axis` (horizontal direction) swipe is most likely detected when scrolling, hence the swipe.

Should I adjust for super small `X-axis` changes ?

**Comment by jonsnowpt** [comment]
@migbash yes please

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v838`.
