### ISSUE TITLE
[Bug]: Competitions lobby countdown missing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The countdown is missing:

![Screenshot 2023-09-06 at 10 18 53](https://github.com/Betarena/scores/assets/37311649/82c8b56b-92bf-4642-98d0-79f0bf967e38)

### 🤔 Expected Behavior

When competitions are less than 24 hours, the countdown should be active:

![Screenshot 2023-09-06 at 10 19 49](https://github.com/Betarena/scores/assets/37311649/ed5ce202-bd19-444f-9e72-660426c15ea0)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
