### ISSUE TITLE
[Bug]: Competitions lobby probability wrong font size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Probability wrong font size:

![Screenshot 2023-09-06 at 11 47 00](https://github.com/Betarena/scores/assets/37311649/11d7bc44-89c4-4335-815a-1a21e9c869ea)

### 🤔 Expected Behavior

Should be 12px.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
