### ISSUE TITLE
[Bug]: Competitions lobby incorrect "Win" expression

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In this case, should be "Win" not "Lose".

![Screenshot 2023-09-06 at 12 51 38](https://github.com/Betarena/scores/assets/37311649/c9546459-dfc8-490b-9b6c-25410d2a838e)

### 🤔 Expected Behavior

"Win" instead of "Lose"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-avispa-fukuoka-will-win/51

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
