### ISSUE TITLE
[Bug]: Competitions lobby incorrect positioning and visibility

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Incorrect position and visibility of the lateral scroll icons.

![Screenshot 2023-09-06 at 12 54 10](https://github.com/Betarena/scores/assets/37311649/9cfb3177-98d4-4ce1-a62f-b8b119a65b2d)

### 🤔 Expected Behavior

Add the correct positioning:

![Screenshot 2023-09-06 at 12 55 41](https://github.com/Betarena/scores/assets/37311649/fc566cb2-c4b6-414a-8fd6-bff8625e652e)

Also, the scroll options should only be visible when the mouse pointer hovers the section, for example:

https://github.com/Betarena/scores/assets/37311649/c11a4087-267d-4667-a26c-b08094302457

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
