### ISSUE TITLE
[Bug]: Competitions wrong link

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The prediction is that the team will lose, and the link shows the win option:

![Screenshot 2023-09-06 at 15 26 45](https://github.com/Betarena/scores/assets/37311649/aa53cb36-9bf8-4a1c-929b-d3c1bc996ac9)

### 🤔 Expected Behavior

The link should have been:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-equatorial-guinea-will-lose/52

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Requires `C# Backend` logic update.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#228](https://github.com/Betarena/backend_betarena/issues/228).

**Comment by jonsnowpt** [comment]
Assigned in a new issue.
