### ISSUE TITLE
[Bug]: Competitions Team flags proportional  

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The team flags are not proportional:

![Screenshot 2023-09-06 at 15 32 54](https://github.com/Betarena/scores/assets/37311649/10a85318-95ab-41a0-aa6b-e4766bf2ec4e)

### 🤔 Expected Behavior

The team flags should be proportional, original image:

https://cdn.sportmonks.com/images/soccer/teams/2/18786.png

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
