### ISSUE TITLE
[Bug]: Competitions tournament name 1 line

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The tournament title has more than one line:

![Screenshot 2023-09-06 at 15 38 01](https://github.com/Betarena/scores/assets/37311649/f6d23fea-0fd2-491e-9843-5777a2ba9e99)

### 🤔 Expected Behavior

There should be one line with "..." if the title exceeds the defined space.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-equatorial-guinea-will-win/52

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
