### ISSUE TITLE
[Bug]: Competitions decimals

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Values without the decimal:

![Screenshot 2023-09-06 at 16 01 30](https://github.com/Betarena/scores/assets/37311649/11f3b98f-0dc1-424d-8f7d-9bc9675ff4be)

### 🤔 Expected Behavior

Add the decimals, for example:

10.4 should be 10.40

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-equatorial-guinea-will-win/52

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
