### ISSUE TITLE
[Bug]: Competitions decimals

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Maximum 2 decimals:

![Screenshot 2023-09-06 at 18 51 59](https://github.com/Betarena/scores/assets/37311649/3a74635b-40bb-46a1-80d5-28bb637b53fc)

### 🤔 Expected Behavior

In this example, it should be:

1.59

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Duplicate / related of #1601.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash 

I suppose this should have stayed at 1.59, not 1.60.

**Comment by migbash** [comment]
> I suppose this should have stayed at 1.59, not 1.60.

@jonsnowpt **1.5999999996** rounded to `2 decimals` is `1.60` , because of the `6` on the end.

**Comment by jonsnowpt** [comment]
@migbash 

Discussion on slack:

https://betarena.slack.com/archives/D02B1UHEECS/p1694162391431069

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.

**Comment by jonsnowpt** [comment]
@migbash 

When its "63.00" we do not need to show the ".00".

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.
