### ISSUE TITLE
[Bug]: Invalid design for mobile alerts on competition target page.

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Alert on mobile devices is not correctly shown:

![IMG_E76C54B55A0F-1](https://github.com/Betarena/scores/assets/37311649/677abe24-c984-4905-bb4f-1dc1622e29a2)

### 🤔 Expected Behavior

The alerts should have a slide effect from the bottom, like an App:

![Screenshot 2023-09-06 at 18 54 35](https://github.com/Betarena/scores/assets/37311649/4da88ecf-1dcb-4246-ac3a-69456e092936)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash 

Users aren't able to see the confirmation options.

Also, we are missing the slide from the bottom animation instead of fade-in.

![Image](https://github.com/Betarena/scores/assets/37311649/d75bef2b-8eea-4889-8571-ceea7f95659b)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v829`.

**Comment by jonsnowpt** [comment]
@migbash 

Still not working.
