### ISSUE TITLE
[Bug]: Competitions team logo on title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The flag/logo is not proportional:

![Screenshot 2023-09-06 at 18 57 39](https://github.com/Betarena/scores/assets/37311649/912f79ea-8ebf-43d2-8c91-b6f1f24d9bcc)

### 🤔 Expected Behavior

The flag/icon should have a proportional size.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.
