### ISSUE TITLE
[Bug]: Invalid design for finished (lobby) competitions card

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1606]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 🐞 Describe the bug

The `design` does not currently match that of the implementation. Once a competition is `active` and/or `finished`, it's `bottom` row containing `participants` and `join` button should be hidden from view.

### 🤔 Expected Behavior

**🟥 Current**

<img
src="https://github.com/Betarena/scores/assets/20924663/b0d240ba-f12d-4bb0-816e-b097fc5168f6"
width=450
/>

**🟩 Expected**

<img
src="https://github.com/Betarena/scores/assets/20924663/838bc877-d0df-49fa-9d56-0ac548101af6"
width=450
/>

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [x] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [x] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [x] 📱 Mobile
- [x] 💻 Tablet
- [x] 🖥️ Laptop/Desktop

### Steps To Reproduce

- Navigate to the `competitions` lobby page (main), and you will see the issue of incorrect design.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v828`.

**Comment by jonsnowpt** [comment]
@migbash, we must add the link for the competition  in the following area and make it available to SEO:


![Image](https://github.com/Betarena/scores/assets/37311649/22355a5a-316d-4aa1-a3fa-0292d00ca894)


This will allow users to visit previous competitions.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
