### ISSUE TITLE
[Bug]: Competitions incorrect "probability"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The probability of Finland losing it is incorrect; it shows the probability of Finland winning.

![Screenshot 2023-09-07 at 12 46 56](https://github.com/Betarena/scores/assets/37311649/46f13df6-f94f-4ee7-b6ba-cdecc02735a6)

### 🤔 Expected Behavior

When the prediction is the team to lose, the correct probability is the opposite of won; for example, if the visitor team's prediction is to lose, the correct probability is the "1" market.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
