### ISSUE TITLE
[Bug]: Competitions align participants

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Participants and column titles are not aligned.

![Screenshot 2023-09-07 at 12 51 17](https://github.com/Betarena/scores/assets/37311649/da28a394-8f07-4c77-8766-4bbe045528ba)

### 🤔 Expected Behavior

Correctly aligned has shown in the design.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> This has been addressed as part of the issue :: #1614 .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
