### ISSUE TITLE
[Bug]: Competitions wrong colors

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The "No" icon and title has the wrong color:

![Screenshot 2023-09-07 at 12 54 07](https://github.com/Betarena/scores/assets/37311649/d30d04bf-b465-4953-a0b9-7c6db021335b)

### 🤔 Expected Behavior

Follow the design color:

![Screenshot 2023-09-07 at 12 55 20](https://github.com/Betarena/scores/assets/37311649/f88912f0-488a-4f5c-b005-2232a0596403)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
