### ISSUE TITLE
[Bug]: Competitions font-weight 600

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Still using 600:

![Screenshot 2023-09-07 at 12 57 24](https://github.com/Betarena/scores/assets/37311649/5237d01c-ccf8-414e-aea4-0c0989a26758)
![Screenshot 2023-09-07 at 12 58 40](https://github.com/Betarena/scores/assets/37311649/3e4927b5-2ca4-4d41-8533-485d922ec6ca)
![Screenshot 2023-09-07 at 12 58 11](https://github.com/Betarena/scores/assets/37311649/c9b4b39d-bd26-4875-9cb0-1c7dc6bfc32d)
![Screenshot 2023-09-07 at 12 57 44](https://github.com/Betarena/scores/assets/37311649/79c5ca22-73ed-476f-8f04-4814f0ade05c)

### 🤔 Expected Behavior

Change to 500.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Still using 600:

@jonsnowpt Please check with the `design` and confirm if they should be changed to `500`, as they say `600`.

<img
 src="https://github.com/Betarena/scores/assets/20924663/020ff3fc-85c4-43b4-97cc-bfb009f83719"
 width="550"
/>

<img
 src="https://github.com/Betarena/scores/assets/20924663/2b3c9f03-bbd4-4c18-bd6f-3c8879365e00"
 width="550"
/>

<img
 src="https://github.com/Betarena/scores/assets/20924663/8dd59d7e-64cb-4b6c-87ee-4581cf729ba9"
 width="550"
/>

<img
 src="https://github.com/Betarena/scores/assets/20924663/cd189791-512d-47c9-ab0e-1057865c216e"
 width="550"
/>

<img
 src="https://github.com/Betarena/scores/assets/20924663/a716a597-6676-4641-b1ad-06d3a54492fb"
 width="550"
/>

**Comment by jonsnowpt** [comment]
@migbash 

Change it. In the design, it is 600, but visually it's different than what we see in production. We need to adjust to 500.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
