### ISSUE TITLE
[Bug]: Competitions EN wrong translation "Share"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In EN the Share expression is in Portuguese:

![Screenshot 2023-09-07 at 13 11 47](https://github.com/Betarena/scores/assets/37311649/29099a41-b6bd-4287-82b3-6050f843ac57)

### 🤔 Expected Behavior

It should be in EN.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
