### ISSUE TITLE
[Bug]: Competitions languages expressions missing.

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

There are several translations missing:

![Screenshot 2023-09-07 at 13 14 22](https://github.com/Betarena/scores/assets/37311649/1083aaba-edd7-4340-95ad-3afc1ed3c4b2)

### 🤔 Expected Behavior

Review for all languages.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> (Already || Partially) addressed as part of issue ➤ #1602 .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing the sport.


![Image](https://github.com/Betarena/scores/assets/37311649/634eba82-92e4-4776-a849-ce9be3c759e4)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.

**Comment by migbash** [comment]
> **Note**
> Also adjusted for `lobby` page in `highlight (widget)` for `team` translation.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.
