### ISSUE TITLE
[Bug]: Competitions elementos aligned

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The following elements are not aligned:

![Screenshot 2023-09-07 at 13 18 55](https://github.com/Betarena/scores/assets/37311649/c9ddc0c4-4b97-4356-b82f-292748924758)

### 🤔 Expected Behavior

All elements should be correctly aligned.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
