### ISSUE TITLE
[Bug]: Competitions participants space between

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The space between the icons and information is too close and should be wider.

![Screenshot 2023-09-07 at 13 20 38](https://github.com/Betarena/scores/assets/37311649/8aa3a0c0-e09a-42fd-8ea7-283f752a7f72)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
