### ISSUE TITLE
[Bug]: Header not able to close dropdown

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The users are not able to close the language dropdown by just clicking outside:

https://github.com/Betarena/scores/assets/37311649/e33af6fe-a376-43f9-8cf5-5c6c83ee4d8f

### 🤔 Expected Behavior

Users should be able to close any dropdown by clicking outside.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
