### ISSUE TITLE
[Bug]: Mobile menu screen filling

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The mobile menu on the DEV environment is not filling the screen has supposed:

![Uploading File (56).jpg…]()

### 🤔 Expected Behavior

Fill the screen and work like it is now working on prod.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt No guidance as to what `menu` the issue is being referred to:

<img
 src="https://github.com/Betarena/scores/assets/20924663/f8a99bb8-2c8b-4c81-b93c-b01c77daeafb"
 width="450"
/>

Please update issue with a correct image.

**Comment by jonsnowpt** [comment]
@migbash 

Now, it is filling up the screen, but I'm unable to see the languages dropdown. options;

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.

**Comment by jonsnowpt** [comment]
@migbash 

I'm not able to close the dropdown when clicking outside the dropdown.

**Comment by jonsnowpt** [comment]
@migbash 

> @jonsnowpt on 📱 MOBILE side nav-bar ?

Correct.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
> **🤔 CAUSE**
> It appears that this wasn't a feature on `prod`, to __close language dropdown when clicking outside__. Has now been added for both `📱 MOBILE` and `💻 TABLET`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
