### ISSUE TITLE
[Bug]: Competitions fixtures page

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When opening the fixture page through the PWA, it behaves as if it is opening a new page or platform.

https://github.com/Betarena/scores/assets/37311649/b0d72d75-688a-4c78-b8f3-c2d549287e0b

### 🤔 Expected Behavior

It should behave as if it was browsing inside the same app like it happens in all scores platform.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
**🔸 UPDATE**

Also applies to `league/tournament` redirect.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
