### ISSUE TITLE
[Bug]: Competitions dark theme color palette

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The color palette for the dark theme seems different from the design:

![Screenshot 2023-09-07 at 14 46 18](https://github.com/Betarena/scores/assets/37311649/a5d24474-5f29-4f6f-a843-f4ca042874b5)

### 🤔 Expected Behavior

Figma file:

![Screenshot 2023-09-07 at 14 51 11](https://github.com/Betarena/scores/assets/37311649/3915e166-b049-4c62-85fa-161971ce92e1)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
