### ISSUE TITLE
[Bug]: Competitions dark theme wrong colors

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Wrong colors:

![Screenshot 2023-09-07 at 14 54 23](https://github.com/Betarena/scores/assets/37311649/f5623e49-ac02-42b0-b98a-2a4ab2cb3c2a)

### 🤔 Expected Behavior

![Screenshot 2023-09-07 at 14 56 40](https://github.com/Betarena/scores/assets/37311649/c15ebdc0-0794-4f23-8fb9-ba98bd6da15e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ #1621 .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
