### ISSUE TITLE
[Bug]: Competitions MOBILE top information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The spaces and positioning are not correct:

![Screenshot 2023-09-07 at 15 10 21](https://github.com/Betarena/scores/assets/37311649/d98c2c91-e4fa-4532-90af-a6fb4cd2e068)

### 🤔 Expected Behavior

![Screenshot 2023-09-07 at 15 10 21](https://github.com/Betarena/scores/assets/37311649/613efd4d-63a6-4892-a7f8-27100c5f6c5b)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Partially addressed as part of issue ➤ #1624 .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
