### ISSUE TITLE
[Bug]: Competitions Mobile spaces and alignments

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] The top information (tournament and country) space and alignments;
- [x] The event is active does not have any shadow;
- [x] Decrease the size of the conversion value defined in the design;

![Screenshot 2023-09-07 at 15 20 13](https://github.com/Betarena/scores/assets/37311649/9c6bb5d8-97bf-430f-bae7-ab0aa933d674)

### 🤔 Expected Behavior

![Screenshot 2023-09-07 at 15 25 40](https://github.com/Betarena/scores/assets/37311649/0644a8a6-a5bc-499e-9f9f-743eb7646bf3)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
