### ISSUE TITLE
[Bug]: Competitions conversion values size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The conversion values are the same size as the BTA value:

![Screenshot 2023-09-07 at 15 38 26](https://github.com/Betarena/scores/assets/37311649/2fce6457-e95b-4cad-a180-a7443c5075fe)

### 🤔 Expected Behavior

The conversion values should be smaller.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> The conversion values are the same size as the BTA value:

@jonsnowpt where are the conversion values for `BTA` to `Fiat` ?

**Comment by jonsnowpt** [comment]
@migbash 

The value is OK. The issue is in the design; if you check the Figma file, the size of the font for the conversion is smaller than the BTA.

**Comment by migbash** [comment]
> **Note**
> Partially addressed as part of issue ➤ #1642 .
> Further addressed in this issue for `participant list` section of `competition (target) page`.
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.
