### ISSUE TITLE
[Bug]: Competitions MOBILE participants position and alignment

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The alignment and positioning are incorrect, and there is no round corner.

![Screenshot 2023-09-07 at 15 45 43](https://github.com/Betarena/scores/assets/37311649/833b35e9-c15c-44cd-bf9a-507992eaab4e)

### 🤔 Expected Behavior

![Screenshot 2023-09-07 at 15 49 25](https://github.com/Betarena/scores/assets/37311649/36ef8f30-eb0b-402c-bbf3-9267fcc6961e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
