### ISSUE TITLE
[Bug]: Competitions MOBILE bottom fade out

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The bottom fades out it's not correct and there are is just 1 rounded corner in the bottom.

![Screenshot 2023-09-07 at 15 54 41](https://github.com/Betarena/scores/assets/37311649/839c18fb-075c-4e23-9035-4bc373ca9d19)

### 🤔 Expected Behavior

There should be 2 rounded corners, and the effect should probably be smaller and have a fade out without being a solid gradient.

![Screenshot 2023-09-07 at 15 56 12](https://github.com/Betarena/scores/assets/37311649/6235c2ad-5deb-4802-828b-4d9ee1b623ca)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> There should be 2 rounded corners, and the effect should probably be smaller and have a fade out without being a solid gradient.

@jonsnowpt This contradicts the issue #1626 , where it mentions `... and there is no round corner`. Please confirm.

**Comment by migbash** [comment]
> **Note**
> Partially Implemented, awaiting `🚀 deployment`.
> 📌 Regarding the `fade` issue.

**Comment by jonsnowpt** [comment]
@migbash no rounded corners on the first box and 2 in the second box. Take a look at the design.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
> 📌 Regarding both the `fade` and `rounded-corners` issue.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
