### ISSUE TITLE
[Bug]: Competitions MOBILE alerts dark theme

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The mobile alerts in the dark theme are white:

![Screenshot 2023-09-07 at 15 58 47](https://github.com/Betarena/scores/assets/37311649/90c6966f-57ee-4aa0-96ea-6846c46ac882)

### 🤔 Expected Behavior

The alerts in the mobile version dark theme should be dark.

![Screenshot 2023-09-07 at 16 00 03](https://github.com/Betarena/scores/assets/37311649/8e5f98aa-c361-437c-863f-cd228af111f4)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
