### ISSUE TITLE
[Bug]: Competitions dark theme event finished

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The event finished CSS is incorrect:

![Screenshot 2023-09-07 at 16 58 22](https://github.com/Betarena/scores/assets/37311649/6e301c5b-03a4-411f-8a70-f42f358d5d44)

### 🤔 Expected Behavior

Correct CSS.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ #1621 .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
