### ISSUE TITLE
[Bug]: Competitions prize distribution problem

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

This user competed in this competition:

(tuninhos)

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-finland-will-win/53

He won, but his balance got like this:

![Screenshot 2023-09-07 at 17 17 03](https://github.com/Betarena/scores/assets/37311649/7bc2d12b-78ec-45d5-b8f9-74494bd26ed9)

### 🤔 Expected Behavior

The prizes should work, and the balances should not be erased for any reason.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by jonsnowpt** [comment]
It seems the user never received the bonus but was able to participate, and that's an issue.

**Comment by jonsnowpt** [comment]
The system does not verify the user balance for users without a balance.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
