### ISSUE TITLE
[Bug]: Competitions "draw" incorrect link

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The link is incorrect:

![Screenshot 2023-09-08 at 09 28 42](https://github.com/Betarena/scores/assets/37311649/39c70d33-5076-4404-8e34-d32e0dde6f0b)

### 🤔 Expected Behavior

The link should include the "draw" not the "win".

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Duplicate task already exists ➤ #1598 .

**Comment by migbash** [comment]
Closing as per `parent` issue closure.
