### ISSUE TITLE
[Bug]: Competitions page space in title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The space between the team title is too big:

![Screenshot 2023-09-08 at 09 57 58](https://github.com/Betarena/scores/assets/37311649/445284e7-f3af-4e52-9844-a59af54c6950)

### 🤔 Expected Behavior

Correct space:

![Screenshot 2023-09-08 at 09 59 04](https://github.com/Betarena/scores/assets/37311649/f2784be8-b022-4b11-9584-924992cabf61)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
