### ISSUE TITLE
[Bug]: Competitions Lobby "null" values

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

"null" values in the country:

![Screenshot 2023-09-08 at 10 32 53](https://github.com/Betarena/scores/assets/37311649/a7500cda-02e3-47cb-9abd-633095de74aa)

### 🤔 Expected Behavior

There shouldn't be any "null" values.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.
