### ISSUE TITLE
[Bug]: Competitions lobby probability

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Probability is not working:

![Screenshot 2023-09-08 at 10 35 01](https://github.com/Betarena/scores/assets/37311649/f5e22f39-1bab-4ee2-89e3-51bc99665a71)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
