### ISSUE TITLE
[Bug]: Competitions lobby wrong section title format

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The section title size is incorrect:

![Screenshot 2023-09-08 at 10 39 47](https://github.com/Betarena/scores/assets/37311649/3cc3d454-0458-4630-b0d2-21ef8669a1d3)

### 🤔 Expected Behavior

Bigger font size for the section title.

![Screenshot 2023-09-08 at 10 41 17](https://github.com/Betarena/scores/assets/37311649/4918d668-9fd8-433c-b709-92378931b5c2)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
