### ISSUE TITLE
[Bug]: Competitions lobby cards tournament information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The alignment is not correct; neither is the rounded flag and the space between the tournament name and country.

![Screenshot 2023-09-08 at 10 42 22](https://github.com/Betarena/scores/assets/37311649/f69f14c0-4450-4394-b4d1-e2bb4fab1c1a)

### 🤔 Expected Behavior

Expected alignment and design:

![Screenshot 2023-09-08 at 10 44 40](https://github.com/Betarena/scores/assets/37311649/62f8ca6b-0dae-4db5-a77b-b2832b103d9e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
