### ISSUE TITLE
Leagues List - Search Field CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#164]
The search field does not follow the correct measurements of the design on Figma:

- Wrong Height;
- Wrong Font size;
- Wrong border color;

![Screenshot 2022-01-29 at 10 06 23](https://user-images.githubusercontent.com/37311649/151656905-8f24ceb2-dbb8-4f0f-9bd2-0c32db9fa434.png)

<img width="465" alt="Screenshot 2022-01-29 at 10 06 16" src="https://user-images.githubusercontent.com/37311649/151656909-ccf2de73-e984-407c-8806-90eb7ee5c6c8.png">

The same on the Dark version:

![Screenshot 2022-01-29 at 10 57 13](https://user-images.githubusercontent.com/37311649/151658398-a61a4903-6bab-4544-b6f0-6367f2ef45fc.png)

<img width="361" alt="Screenshot 2022-01-29 at 10 57 07" src="https://user-images.githubusercontent.com/37311649/151658400-d2322f6f-1d21-4508-9bbf-ea479be29b4d.png">

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
