### ISSUE TITLE
[Bug]: Competitions lobby tournament 1 line

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The tournament name has more than 1 line:

![Screenshot 2023-09-08 at 10 47 03](https://github.com/Betarena/scores/assets/37311649/540f345e-5e5f-4c1f-9547-a56cee91e4bc)

### 🤔 Expected Behavior

The tournament name should only have 1 line, if the space is not enough (...) should be added.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
**🔸 UPDATE**

> Also added similar styling to competition `team-names`.

![Image](https://github.com/Betarena/scores/assets/20924663/8f93e7c3-a24c-4d8a-92ae-3eab51b7f9a4)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
