### ISSUE TITLE
[Bug]: Competitions lobby fixture information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The gradient is not correct, and the space between the scores and the team names is too high:

![Screenshot 2023-09-08 at 10 49 36](https://github.com/Betarena/scores/assets/37311649/2073e4e6-c28d-4ba2-aa03-777a0dbe2624)

### 🤔 Expected Behavior

More gray in the gradient and less space between the team names and the scores:

![Screenshot 2023-09-08 at 10 51 44](https://github.com/Betarena/scores/assets/37311649/6b8b755b-d784-4e12-87ec-c47c2d0c3769)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v831`.
