### ISSUE TITLE
[Bug]: Competitions lobby dark theme review

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The dark theme of the lobby is not correct:

![Screenshot 2023-09-08 at 10 56 11](https://github.com/Betarena/scores/assets/37311649/cf51b955-bc10-4a38-a54e-e14469cbafa9)

### 🤔 Expected Behavior

The correct dark theme version:

![Screenshot 2023-09-08 at 10 57 09](https://github.com/Betarena/scores/assets/37311649/768b24eb-5561-445e-9e30-96bf0bd8cb8b)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

The "Draw" color is wrong on both the Lobby and Competition page.

Also, the font weight should be changed to "500" instead of "700".

![Screenshot 2023-09-12 at 09 33 25](https://github.com/Betarena/scores/assets/37311649/f0ba235f-1034-449d-a9c3-17546a8b1458)
![Screenshot 2023-09-12 at 09 33 07](https://github.com/Betarena/scores/assets/37311649/1a430659-e00e-4cea-bab4-8d21196859a5)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.
