### ISSUE TITLE
[Bug]: Competitions missing avatar image

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The avatar image is missing:

![Screenshot 2023-09-11 at 16 18 29](https://github.com/Betarena/scores/assets/37311649/805d4704-eeed-4ddd-8593-7fe1b0f85fda)

### 🤔 Expected Behavior

The default image should load correctly.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.
