### ISSUE TITLE
[Bug]: Competitions lobby avatar information too slow

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The avatar information takes too much time to load.

https://github.com/Betarena/scores/assets/37311649/faea6a53-2b75-4be0-85db-ae10dd4b765b

### 🤔 Expected Behavior

The load should be immediate. There is no reason for Firebase / Firestore data to take that amount of time.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v832`.
