### ISSUE TITLE
[Bug]: Competitions MOBILE balance "NaN"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

On mobile In the competitions section, the balance is showing a "NaN"

![File (57)](https://github.com/Betarena/scores/assets/37311649/79c0f4a5-65d3-4543-bb0a-7b514dc7c7ac)

### 🤔 Expected Behavior

Show the correct balance or if no balance is available, show a "0".

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> This happens when declaring a new `set` value for `main_balance` with an `undefined` value, such as: `undefined + 1`.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
