### ISSUE TITLE
[Bug]: Competitions MOBILE menu

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When selecting the options on the side menu on mobile devices, we are redirected to a new page; it should remain on "_self".

### 🤔 Expected Behavior

Remain inside the PWA.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.

**Comment by jonsnowpt** [comment]
@migbash 

The "Sports Content" portal is getting 500 internal error, this one is "_blank" that's probably the culprit.:

![IMG_A25225041D31-1](https://github.com/Betarena/scores/assets/37311649/1488f6ad-4a3e-4865-a3c8-fc07a98c851d)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
> **🤔 Cause**
> Links provided for `navigation` links at question had the `https://scores.betarena.com/[...]` and/or `https://www.betarena.com/[..]` and a mix up occurred when stripping down / cleaning the `url`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
