### ISSUE TITLE
Leagues List - CSS Flags

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#165]
Use CSS to apply the round effect to the flags the same way we have on the design:

https://www.w3schools.com/howto/howto_css_rounded_images.asp

![Screenshot 2022-01-29 at 10 18 12](https://user-images.githubusercontent.com/37311649/151657197-fd333c22-cdbb-46c3-8064-94196eaa16e9.png)

**Comment by migbash** [comment]
Updated - reflected in the `pull-request`
