### ISSUE TITLE
[Bug]: Competitions MOBILE "Participants" wrong size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The placeholder message size is incorrect on mobile and does not respect the <br>.

![File (58)](https://github.com/Betarena/scores/assets/37311649/9ec7ae92-0eed-4414-9206-1fc7f93b39a6)

### 🤔 Expected Behavior

Should respect the font size:

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> The placeholder message size [..]

@jonsnowpt There is no design given for the 📱 mobile `font-size` of the text for `No Participants ...`, what is it mean to be ?

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.
