### ISSUE TITLE
[Bug]: Competitions "Competition Finished"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

It showing the date and with the incorrect CSS:

![Screenshot 2023-09-12 at 09 26 31](https://github.com/Betarena/scores/assets/37311649/1e266ebc-fd25-4d94-8fd2-5915055e2970)
shows

### 🤔 Expected Behavior

It should show "Competition Finished" and the CSS needs adjustment.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-iceland-will-draw/68

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
