### ISSUE TITLE
[Bug]: Competitions LOBBY preloader incorrect color

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The preloader colors are not correct:

![Screenshot 2023-09-12 at 09 41 40](https://github.com/Betarena/scores/assets/37311649/52de111f-6794-483c-8b0f-f39e9fa8b7e0)

### 🤔 Expected Behavior

Correct colors:

![Screenshot 2023-09-12 at 09 44 30](https://github.com/Betarena/scores/assets/37311649/65bbfcee-146e-4602-8b63-94a88154b6d8)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.
