### ISSUE TITLE
[Bug]: Competitions LOBBY smaller space

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Reduce the following space to allow the timer into the space:

![Screenshot 2023-09-12 at 09 48 59](https://github.com/Betarena/scores/assets/37311649/9d417323-03cf-4715-a16f-5fb465e5fd96)

### 🤔 Expected Behavior

Goal:

![Screenshot 2023-09-12 at 09 50 23](https://github.com/Betarena/scores/assets/37311649/d2ce4790-acaf-4512-8890-3452e569de20)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v833`.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
