### ISSUE TITLE
[Bug]: Competitions LOBBY missing translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the correct translations:

![Screenshot 2023-09-12 at 09 52 40](https://github.com/Betarena/scores/assets/37311649/7e85f0bc-e4a3-4f1e-8ce2-58135f3139ec)

### 🤔 Expected Behavior

Available at:

competitions > (table) translation_page_home

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
