### ISSUE TITLE
[Bug]: Competitions MOBILE data alignment

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The data is not aligned:

![File (60)](https://github.com/Betarena/scores/assets/37311649/840ee8db-8ce2-4ecb-9435-3bcb3dc83950)

### 🤔 Expected Behavior

The second block should be aligned with the middle of the "vs".

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v830`.
