### ISSUE TITLE
[Bug]: Competitions LOBBY avatar space and border

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The avatar space for the "participants" expression is incorrect, and the border is incorrect in the dark theme.

![File (59)](https://github.com/Betarena/scores/assets/37311649/59753e88-1cd8-4e98-832e-680fefc7d4a9)

### 🤔 Expected Behavior

Correct positioning:

![Screenshot 2023-09-12 at 12 13 32](https://github.com/Betarena/scores/assets/37311649/944c7426-cf93-45c0-a8bf-2584cfcaba84)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v834`.
