### ISSUE TITLE
[Bug]: Competitions page "Deposit" is not forwarding the user

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Not working the Deposit option:

![Screenshot 2023-09-12 at 20 17 15](https://github.com/Betarena/scores/assets/37311649/ef5c796d-2441-4c17-81dd-7c8d7335b33e)

### 🤔 Expected Behavior

Should forward the user to the deposit options.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v835`.
