### ISSUE TITLE
[Bug]: Competitions page date

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The date does not seem to be using the correct style and space:

![Screenshot 2023-09-13 at 14 16 29](https://github.com/Betarena/scores/assets/37311649/a653d076-159f-417c-a69d-c0020f6c9f1e)

### 🤔 Expected Behavior

It should be similar to:

![Screenshot 2023-09-13 at 14 18 18](https://github.com/Betarena/scores/assets/37311649/9859c9f3-0795-4450-9fa3-2f9795368d2b)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-santos-will-win/75

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v837`.
