### ISSUE TITLE
Leagues List - CSS default images to specific countries - In Progress

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#166]
For a specific number of countries use this specific images:

Africa = https://www.betarena.com/wp-content/uploads/2022/01/africa.svg
Asia =  https://www.betarena.com/wp-content/uploads/2022/01/asia.svg
North & Central America = https://www.betarena.com/wp-content/uploads/2022/01/north-central-america.svg
South America = https://www.betarena.com/wp-content/uploads/2022/01/south-america.svg
World = https://www.betarena.com/wp-content/uploads/2022/01/world.svg

Use CSS for the correct colors.

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
