### ISSUE TITLE
[Bug]: Competition generation wrong prediction term

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Competition ID 76, the term is incorrect.

![Screenshot 2023-09-13 at 19 25 11](https://github.com/Betarena/scores/assets/37311649/bacb26f8-89a3-4915-932f-0724c32bf5b8)

### 🤔 Expected Behavior

It should be "WIN"

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

The category data was set, and normal generation was done.

**Comment by migbash** [comment]
@jonsnowpt `fixture_id: 18791262` is not a fixture in which `FC Bayern Munchen` is playing, 2 entirely different teams are playing. Please consult `Sportmonks` for more details.

**Comment by jonsnowpt** [comment]
@migbash 

It was an error when setting up the competition.
