### ISSUE TITLE
[FEATURE]: Add the Helpdesk to the competitions lobby + page + profile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1664]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We are adding a support Helpdesk to the platform; this helpdesk should only be available on the following pages:

- [x] Profile (All options)
- [x] Competitions Lobby
- [x] Competitions Page

![Screenshot 2023-09-14 at 13 53 37](https://github.com/Betarena/scores/assets/37311649/3749dde9-20e4-4d04-b8c3-d357bbaf763c)

![Screenshot 2023-09-14 at 13 53 52](https://github.com/Betarena/scores/assets/37311649/a0c5e045-f619-4131-a550-d0e26e850347)

![Uploading Screenshot 2023-09-14 at 13.54.12.png…]()

**Comment by migbash** [comment]
We are adding a support Helpdesk to the platform; this helpdesk should only be available on the following pages:

@jonsnowpt What is the code or documentation for adding the `helpdesk` to the platform ? And also the design the `helpdesk` ?

**Comment by jonsnowpt** [comment]
@migbash 

`<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="cb59b31a-b48f-42d5-a24b-e4cf5bac0222";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>`

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v837`.

**Comment by migbash** [comment]
> **Note**
> It appears the `helpdesk` does not show on initial page load or when navigating a page other than `competitions (all)` and/or `profile`. However, when navigating away from these pages, the `helpdesk` remains.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v838`.
