### ISSUE TITLE
[FEATURE]: Add a link option for the register form

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1665]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

To improve the number of registrations in the platform, we should have a way to add a variable to any link that will open the registration form by default:

Example: 

https://scores.betarena.com/competitions?form=register

![Screenshot 2023-09-14 at 12 02 00](https://github.com/Betarena/scores/assets/37311649/e8dfb47b-43d3-4e41-ab0e-4b2d29ed197b)

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v837`.

**Comment by jonsnowpt** [comment]
@migbash how does it work?

**Comment by migbash** [comment]
> @migbash how does it work?

@jonsnowpt Add the `[..]?authForm=true` to the end of any valid Betarena | Scores link.
