### ISSUE TITLE
[Bug]: Competitions "LOBBY" arrows not showing when +4

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When we have more than 4 but less than 8, the arrows for competition navigation won't show, and the users are unable to see them.

![Screenshot 2023-09-14 at 21 04 44](https://github.com/Betarena/scores/assets/37311649/15dbca07-a1b2-4e88-a8d6-820f4ce83e7a)

### 🤔 Expected Behavior

Arrows to be shown when more than 4.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v842`.
