### ISSUE TITLE
[Bug]: Competitions Logic minimum participants

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In this case, the competition should have been canceled since the minimum participants was not met.

https://scores.betarena.com/competitions/predictor/team-gremio-will-win/77

![Screenshot 2023-09-15 at 09 11 28](https://github.com/Betarena/scores/assets/37311649/c6fb5056-05e5-4321-9e3e-d4f257543bc0)

### 🤔 Expected Behavior

The competition should be canceled.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Partially addressed as part of issue ➤ [#240](https://github.com/Betarena/backend_betarena/issues/240).
> Implemented, awaiting `🚀 deployment`.
