### ISSUE TITLE
Leagues List - CSS space in between competitions 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#167]
The space between the competitions is smaller than in the design on Figma:

<img width="341" alt="Screenshot 2022-01-29 at 10 35 57" src="https://user-images.githubusercontent.com/37311649/151657760-d326df31-ac41-44d8-bd99-27e478111622.png">

![Screenshot 2022-01-29 at 10 35 51](https://user-images.githubusercontent.com/37311649/151657761-bf608d32-a0c7-468b-9fe2-a705e955dde5.png)

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
