### ISSUE TITLE
[FEATURE]: Crisp chat user registration / login integration

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1670]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

Since we must contact users to welcome them to the platform and inform them about essential features, we must integrate Crisp chat to gather the most relevant user data.

DATA TO BE ADDED TO CRIP USERS:

- [ ] Name (username)
- [ ] Email (email)
- [ ] UID (uid)
- [ ] Profile Photo (profile_photo)
- [ ] Lang (lang)
- [ ] competitions (number of competitions)

The data is added on registration and updated in every login.

### ➕ Further context and resources (cumulative)

We need to add the number of competition participations into the Firestore user profile:

```
[
  "lang",
  "profile_photo",
  "register_date",
  "competitions",
  "registration_type",
  0,
  "username"
]
```

This data can be gathered from the Hasura db:

`competitions/data`

**How to add users and integrate custom data:**

https://help.crisp.chat/en/article/how-can-i-automatically-set-custom-data-1xh7pqk/

https://docs.crisp.chat/references/rest-api/v1/#add-a-people-event

**[22/09/2023]**

Upon testing, it was noticed that the initial data for endpoint `.../website/:website_id/people/events/:people_id` does not update the correct segment of `custom data` as expected. Instead, the use of the `.../v1/website/{website_id}/people/data/{people_id}` and/or `.../v1/website/:website_id/people/data/:people_id` endpoints.

> **Important**
> Before being able to `update` data for a target `user` on CRIPS, it must be first created, it if does not exist, and relate it to a target `Betarena Firebase (Firestore) UID`. Otherwise, error of `"reason": "people_not_found",` will be returned.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#6](https://github.com/Betarena/firebase-services/issues/6) .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Testing on `DEV` was a success, with `_my_` account having the data on `Firestore` and `CRISP` updated correctly, as an increment was visible from `competitions_number: 10` to `11` and so did `CRISP Associated Profile` data.

**Comment by migbash** [comment]
> **Important**
> Currently, due to the nature of the data from `competitions` using nested `JSON` data for `participants`, all data for all `competitions` are retrieved, analysed, and updated for each participant present in a competition. This is because it's quicker and simpler to search by simply retrieving all `competitions` data, rather than query by `JSON` as a nested format. 

> Because of this, upon **each user login**, each competition participant will have their `competition_number` updated on `Firestore`, but not on `CRISP`. As the `CRISP` is limited to the supplied `uid's`. So if a user logs in, it will only update their `CRISP` Profile data.

**Comment by jonsnowpt** [comment]
@migbash Update on last active
