### ISSUE TITLE
[FEATURE]: Profile Competitions History

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1671]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

#### 📝 DESCRIPTION

We will add a competition history section to the user profiles listing all user competition participations based on the user UID.

![Screenshot 2023-09-20 at 08 59 03](https://github.com/Betarena/scores/assets/37311649/d9ec5ea8-56ee-4f9a-8e3a-92d709e2a1ff)

---

#### 📱 TARGET PLATFORMS

This option will be available on all platform versions.

---

#### 🎬 LINK

https://scores.betarena.com/u/tcompetitions/

---

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

In this section, users can access all competitions history.

This will allow users to understand their performance in the competitions and also easily access them.

The way data is filtered for each user is by using the UID.

There is a default screen when no transactions are available.

---

### Versions:

All theme variations are supported.

---

#### 💠 DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| competitions/data | id + sport_id + type_id + created_at + target_team_prediction_term + entry_fee + (total_prize - betarena_commission) + (prize_group_win_individual - betarena_commission) + target_team_prediction_term + winner_group + (prize_group_win_individual - betarena_commission) + status

---

#### 🎏 TRANSLATIONS

**Translations endpoint**

Within the specific Schema:

| table | columns |
| ----- | --------- |
| competitions | lang + data |

---

#### ⚡️ CACHE

Unavailable.

---

#### 🔎 SEO

Unavailable.

---

### Placeholder when there is no content:

It will have a placeholder, defined on the design, and a preloader when selecting show more.

---

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena-%2F-Desktop?type=design&node-id=7802%3A281534&mode=design&t=ogF90g0Udv4o0yWd-1

### ➕ Further context and resources (cummulative)

[29/09/2023]

 `(column) Balance` is not to be implemented as of yet, due to data point additional logic hurdles.

**Comment by migbash** [comment]
@jonsnowpt `already discussed, adding for reminder` missing translations for `_this_` widget.

---

@jonsnowpt For the `Contest Title`, is the name meant to be `Match Predictor` ? Or the actual `name` of the competition, such as: `Porto will win` is expected ? Also, what's meaning of `Pro` and `Classic` tags ?

**Comment by jonsnowpt** [comment]
@migbash 

> @jonsnowpt For the Contest Title, is the name meant to be Match Predictor ? Or the actual name of the competition, such as: Porto will win is expected ? Also, what's meaning of Pro and Classic tags ?

Contest Title / Style is:

```
Contest Title = Name of the competition
Type = Predictor (Category Type)
```


Ignore the mention of PRO and Classic; it was just used to illustrate.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
