### ISSUE TITLE
CSS - ALL WIDGETS wrong font color

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#168]
Noticed that the font color being used on all widgets for the white theme is: #121212; It's incorrect, the correct color is: #292929, which needs to be changed.

<img width="171" alt="Screenshot 2022-01-29 at 10 42 11" src="https://user-images.githubusercontent.com/37311649/151658009-16631475-a090-492a-a1ad-fb3be576abaf.png">

![Screenshot 2022-01-29 at 10 44 54](https://user-images.githubusercontent.com/37311649/151658014-78aa538e-8eb1-4df4-a44e-4db0c016c6f1.png)

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
