### ISSUE TITLE
[Bug]: Competitions Lobby and Page Swedish wrong translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

This expression is incorrect and does not correspond to the one available in the translations for Swedish:

![Screenshot 2023-09-20 at 17 29 02](https://github.com/Betarena/scores/assets/37311649/4d8fa873-864a-4517-90e1-e27e316738c8)

### 🤔 Expected Behavior

Correct translation from the correct endpoint.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Updated data, incoming from `(table) scores_general_transaltions`.

![Image](https://github.com/Betarena/scores/assets/20924663/c1410783-4ce5-4284-b49e-cb34024f2fe6)
