### ISSUE TITLE
[Bug]: Missing team logo

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The logo is missing:

![Screenshot 2023-09-20 at 19 35 04](https://github.com/Betarena/scores/assets/37311649/7ee4b0cb-15f4-43f1-8d55-7a52218fc827)

### 🤔 Expected Behavior

It should have all team logos.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/football/saudi-arabia/division-1

**Comment by migbash** [comment]
> **Note**
> This particular team does not appear in `Betarena (Hasura)` data, team in question: `id: 260801`.
> However, it is present in both the `V2` and `v3` of Sportmonks data.
> Check needs to be made on why / how it should've been updated.
> - [ ] Update of `teams` and `_teams_v2` needs to be done.

**Comment by migbash** [comment]
![Screenshot 2023-09-21 at 15 10 08](https://github.com/Betarena/scores/assets/37311649/d2927af4-4846-4cf4-b842-30b4e70e44fe)

**Comment by migbash** [comment]
**🔸 Update**

Both missing teams of `id's :: 263864, 260801` have been updated on `_teams (v1)` table on `Hasura` and standings have been updated.

- ![Image](https://github.com/Betarena/scores/assets/20924663/89d333a4-a63c-467f-a2ed-9560f17ecd5b)

- ![Image](https://github.com/Betarena/scores/assets/20924663/75e1cc7a-d322-427c-856e-fcf7412269fe)
