### ISSUE TITLE
[Bug]: Tournaments missing team logo AFC Cup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2023-09-21 at 15 10 08](https://github.com/Betarena/scores/assets/37311649/d2927af4-4846-4cf4-b842-30b4e70e44fe)

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/br/futebol/asia/afc-cup

**Comment by migbash** [comment]
> **Note**
> Duplicate task already exists ➤ #1681 . 
> Appended `this` issue on `original` issue.
