### ISSUE TITLE
Champions league - 2 red cards but only 1 existed

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1685]
https://scores.betarena.com/br/futebol/europe/champions-league

Only 1 red card was shown during the match:

![Image](https://github.com/Betarena/scores/assets/37311649/b6c8c357-c056-4753-a5ba-9c4c1306f3e2)

https://scores.betarena.com/br/futebol/benfica-salzburg-18996923

**Comment by migbash** [comment]
> **Note**
> `league_id: 2`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
