### ISSUE TITLE
Tournaments fixtures do not stop to be Live

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1687]
https://scores.betarena.com/br/futebol/israel/liga-leumit

![Image](https://github.com/Betarena/scores/assets/37311649/78edd2b9-9e3d-4959-99c7-3a1ba1c7ed42)

**Comment by migbash** [comment]
> **Note**
> **[BUG]** Created offspring task ➤ [#247](https://github.com/Betarena/scores-lib/issues/247).
