### ISSUE TITLE
[Bug]: Tournaments Taça de Portugal no Info

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

https://scores.betarena.com/football/portugal/taca-de-portugal

No information is available.

### 🤔 Expected Behavior

Fixtures, players, and tournament details should be available.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/football/portugal/taca-de-portugal

**Comment by jonsnowpt** [comment]
@migbash why there was no data?

**Comment by migbash** [comment]
@jonsnowpt What are you referring to ? The `League Info` ? Or the `Standings` ?

**Comment by jonsnowpt** [comment]
@migbash 

This:

> Data for the scores_football_seasons_details > (season_id) 21866 has been missing for majority of the columns, with the exception

**Comment by migbash** [comment]
@jonsnowpt 

> Believed to be related to the first initial testing period of the upgrade for the new `League > currentSeason` check, which probably updated the new season, without filling in the rest of the data columns, and then was not picked up as `NEW` later on, so remained un-updated. Checked for any similar cases of `seasons`, and couldn't fine similar cases, so just an expection.
