### ISSUE TITLE
[FEATURE]: Competitions lobby selection all card

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1689]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We are changing the approach on how to select the competition, and from now on, all the card is a clickable area that will open the competition.

![Screenshot 2023-09-25 at 17 11 43](https://github.com/Betarena/scores/assets/37311649/90a4893a-0979-4581-805d-2d9da96c9a42)

### ➕ Further context and resources (cummulative)

Add an animation (small lift of the card) like we can see in Opensea:

https://opensea.io/category/gaming

https://gempad.app/presales?page=1&filterBy=all&sortBy=no&networks=1%2C56%2C204%2C42161%2C8453%2C109%2C10201%2C137%2C179%2C75%2C4000%2C1116%2C88%2C369%2C2000%2C25%2C3797%2C40%2C4099%2C82%2C52%2C180

**Comment by migbash** [comment]
> **Note**
> Implemented Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Participants avatar and names are not showing;
- [ ] Remove the up effect on mobile;

**Comment by migbash** [comment]
> **Note**
> Implemented Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v851`.
