### ISSUE TITLE
Scores user guide competitions lobby

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1695]
#### 📝 DESCRIPTION

We will be adding a system to help out users using the platform. It can be a tooltip, popups, and other approaches that can exhibit instructions for the user on how to use the features in the platform. 

---

#### 📸 POPUP IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/f92deb81-e5dd-4ae0-8545-c3e79093ed6a)

![Image](https://github.com/Betarena/scores/assets/37311649/3e2b9c0e-f295-4501-bb88-55afcfaf92ef)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

The popup is shown after loading. 

---

### Popup verification to display

Verify if available on `userguide_list`

`scores_userguide_list/section_id`

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

The popup or element is only visible if the status is "published". It should be hidden if the status is "draft".

We have the different sections mapped, and this information should be added for each page, this way it will be possible to automatically add the different user guide elements to the different platform sections.

===

ANIMATIONS:

In the case of the mobile version, its a slider animation from the bottom, the same way we already have for the participating submissions in the competitions.

Tablets are the same as mobile.

Desktop a slider animation from the right side.

When closing, the opposite animation occurs.

=== SHOW POPUP

The options that do not show again are disabled by default, if the user chooses this option the popup should not be shown anymore except when the user specifically selects the option to see the help again.

=== Option in the Lobby

We need to add the option to trigger the popup in the lobby:

![Image](https://github.com/Betarena/scores/assets/37311649/8f070e9a-ec69-4ef2-82b0-38945611da5b)

=== VIDEO

The video is an embed YouTube video.

Link for each language:

`BR` and `PT` :: https://www.youtube.com/watch?v=R0pVwlnoLVs

`EN` :: https://www.youtube.com/watch?v=lrmAAadPVQI

---

### Versions:

All theme versions are supported.

---

#### 💠 ELEMENT DATA

➤ **Hasura**

Schema:

userguide

| table | columns |
| ----- | --------- |
| userguide_list | content |
| userguide_types_list |  |

---

#### 🎏 TRANSLATIONS

| userguide_list | content |
| competitions | translation_page_home |

---

#### ⚡️ CACHE

The cache data is already defined. When the cache is available, use it; if not, use the Hasura endpoint.

---

#### 🔎 SEO

No SEO is available in these cases.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=4hA74SSxfFWYz9ir-1

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
