### ISSUE TITLE
[FEATURE]: Add an event for new users CRISP chat

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1696]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

To be able to send campaigns, we need to add an event to users, in this case, for new contacts/registrations.

### Instructions:
Create a new profile with the API.
Push an event using this route:

https://docs.crisp.chat/references/rest-api/v1/#add-a-people-event

Name the event "user-registration"

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#8](https://github.com/Betarena/firebase-services/issues/8).
> Implemented, awaiting `🚀 deployment`.
