### ISSUE TITLE
[Bug]: Fixtures preload errors

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The following fixtures are missing with `preload fetch errors.`

https://betarena.slack.com/archives/D02B1UHEECS/p1696056588326439)
https://scores.betarena.com/pt/futebol/fc-union-berlin-sporting-braga-18997052
https://scores.betarena.com/pt/futebol/salzburg-real-sociedad-18997062
https://scores.betarena.com/pt/futebol/manchester-united-galatasaray-18997025
https://scores.betarena.com/pt/futebol/fc-copenhagen-fc-bayern-mnchen-18997027
https://scores.betarena.com/pt/futebol/lens-arsenal-18997042
https://scores.betarena.com/pt/futebol/psv-sevilla-18997043
https://scores.betarena.com/pt/futebol/napoli-real-madrid-18997053
https://scores.betarena.com/pt/futebol/inter-benfica-18997063
https://scores.betarena.com/football/roma-frosinone-18867374
https://scores.betarena.com/football/udinese-genoa-18867378
https://scores.betarena.com/football/atalanta-juventus-18867369
https://scores.betarena.com/football/fiorentina-cagliari-18867371
https://scores.betarena.com/football/godoy-cruz-instituto-18722672
https://scores.betarena.com/football/atromitos-asteras-tripolis-18901714
https://scores.betarena.com/football/ofi-aek-athens-18901716
https://scores.betarena.com/football/kayserispor-stanbul-baakehir-18903601
https://scores.betarena.com/football/real-espaa-olimpia-18901281
https://scores.betarena.com/football/goa-minerva-punjab-19004975
https://scores.betarena.com/football/castle-independiente-huachog-19017267
https://scores.betarena.com/football/tirana-lai-18960621
https://scores.betarena.com/football/kuksi-erzeni-shijak-18960623
https://scores.betarena.com/football/dinamo-tirana-vllaznia-shkodr-18960620
https://scores.betarena.com/football/chteauroux-red-star-18893218
https://scores.betarena.com/football/stjarnan-vkingur-reykjavk-18992343
https://scores.betarena.com/football/national-bank-of-egypt-zamalek-19010313
https://scores.betarena.com/football/amgk-al-quwa-al-jawiya-18988131
https://scores.betarena.com/football/al-sharjah-al-faysali-18988118
https://scores.betarena.com/football/nasaf-al-sadd-18988119
https://scores.betarena.com/football/sepahan-al-ittihad-18988130
https://scores.betarena.com/football/al-nassr-istiqlol-dushanbe-18988154
https://scores.betarena.com/football/al-duhail-persepolis-18988155
https://scores.betarena.com/football/bashundhara-kings-odisha-fc-18988262
https://scores.betarena.com/football/atk-mohun-bagan-maziya-18988263
https://scores.betarena.com/football/foutoua-al-ahed-18988213
https://scores.betarena.com/football/al-arabi-sc-al-nejmeh-18988251
https://scores.betarena.com/football/alnahda-jabal-al-mukaber-18988216
https://scores.betarena.com/football/paysandu-amazonas-18798779
https://scores.betarena.com/football/ec-so-jos-operrio-pr-18797612
https://scores.betarena.com/football/asec-mimosas-al-ahli-benghazi-18938540
https://scores.betarena.com/football/nouadhibou-ral-bamako-18938544
https://scores.betarena.com/football/al-hilal-omdurman-1-de-agosto-18938546
https://scores.betarena.com/football/saint-eloi-lupopo-sekhukhune-united-18942083
https://scores.betarena.com/football/diables-noirs-man-utd-zambia-academy-18942085
https://scores.betarena.com/football/future-fc-singida-big-stars-18942075
https://scores.betarena.com/football/club-africain-bahardar-18942077
https://scores.betarena.com/football/acadmica-do-lobito-al-merreikh-juba-18942097
https://scores.betarena.com/football/rivers-united-etoile-filante-18942103
https://scores.betarena.com/football/aris-kifisia-18901713
https://scores.betarena.com/football/panathinaikos-paok-18901717
https://scores.betarena.com/football/pas-giannina-olympiakos-piraeus-18901718
https://scores.betarena.com/football/volos-nfc-panserraikos-18901715

### 🤔 Expected Behavior

All fixtures must load correctly.

This is a recurrent issue; how can we prevent it from happening in the future?

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> This is a `API-limits` based error, where by the amount of `fixtures` (a.k.a Sportmonks Requests) were being throttled, for precaution, where precaution is no longer necessary. Adjustments to the logic of data aggregation need to be made to make sure on each endpoint trigger, data is gathered correclty, instead of the previous `re-trigger` of data based on `CRON`.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#247](https://github.com/Betarena/backend_betarena/issues/247).
> Implemented, awaiting `🚀 deployment`.
