### ISSUE TITLE
[Bug]: Competition History CSS wrong table width

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The table width size is incorrect:

![Screenshot 2023-10-01 at 14 47 56](https://github.com/Betarena/scores/assets/37311649/719ae972-e64b-4bde-810a-90b1ef827ddc)

### 🤔 Expected Behavior

It should be full width and cover all the space.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
