### ISSUE TITLE
[Bug]: Competitions History correct translations status

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The following translations are not correct:

![Screenshot 2023-10-01 at 15 03 34](https://github.com/Betarena/scores/assets/37311649/f62a0212-cc7c-49bb-9e7c-28ae7bbdca81)

### 🤔 Expected Behavior

Use the endpoint `betarena_general_data/translations/competitions`

Example:

```
"status": {
    "canceled": "Anulat:",
    "pending": "În așteptare:",
    "complete": "Finalizat"
}
```

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v854`.
