### ISSUE TITLE
[Bug]: Competition history missing the competition type

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the competition type:

![Screenshot 2023-10-01 at 15 07 26](https://github.com/Betarena/scores/assets/37311649/3be0e4bd-59c1-4de4-83d4-03aee16562a0)

### 🤔 Expected Behavior

Should include the type, for example:

"Predictor"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v854`.

**Comment by jonsnowpt** [comment]
@migbash 

Still missing:

![Image](https://github.com/Betarena/scores/assets/37311649/a2782b12-e4c0-40a5-aec9-7e284fdcfb40)

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#1713](https://github.com/Betarena/scores/issues/1713) .
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
