### ISSUE TITLE
[Bug]: Competition History real prize and potential win

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The total prize, potential win and prize are not including the associated fees.

### 🤔 Expected Behavior

- [x] Total prize: Include the Betarena commission.
- [x] Potential win: Individual prize, including the entry fee;
- [x] Prize: Individual prize + the entry fee.
- [x] In the case of loss, it should be the entry fee, not the total prize.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v854`.

**Comment by jonsnowpt** [comment]
@migbash 

Does not seem correct the potential prize:

![Image](https://github.com/Betarena/scores/assets/37311649/b61c351f-0dcd-4248-93f6-c2f1d8a7671a)



![Image](https://github.com/Betarena/scores/assets/37311649/6b4fc74a-b910-4c14-917c-e4ce44014946)






The correct value should be:

6.75

**Comment by migbash** [comment]
> Does not seem correct the potential prize:

@jonsnowpt It's meant to be `6.75` on where ? The `competition history` widget, or the `competition target page` ?

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
