### ISSUE TITLE
[Bug]: Competitions history links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The link for each tournament is missing in the title:

![Screenshot 2023-10-01 at 15 37 52](https://github.com/Betarena/scores/assets/37311649/ad2af345-34bd-43b9-a8e2-60c1bfd79caf)

### 🤔 Expected Behavior

Add the competition link in every title.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v854`.
