### ISSUE TITLE
[Bug]: Competitions History "Show More"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Show more is showing every competition.

### 🤔 Expected Behavior

Show more, should load 10 competitions at a time to avoid overloading the system.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing competitions and the show less option.

**Comment by migbash** [comment]
> Missing competitions [..]

@jonsnowpt what do you mean ?

---

> [..] and the show less option.

@jonsnowpt What's the design for the `show less option` ? Only `show more` on figma ? Should they be both available, as the `show more` goes in steps ? Please clarify.

**Comment by jonsnowpt** [comment]
@migbash 

>@jonsnowpt what do you mean ? Please provide a screenshot and or recording.

I have been on more competitions that the ones showing.

----

> @jonsnowpt What's the design for the show less option ? Only show more on Figma ? Should they be both available, as the show more goes in steps ? Please clarify.

Ignore the show less but the show more should go in steps.

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena.slack.com/files/U04MANUB3/F05UHKXK8KH/screenshot_2023-10-03_at_15.35.19.png
