### ISSUE TITLE
[Bug]: Competitions History "draft" should not be visible

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Draft competitions are being shown in the profile competitions history:

![Screenshot 2023-10-01 at 15 46 38](https://github.com/Betarena/scores/assets/37311649/f014f39b-c228-4eb6-a081-0b943e97b0b4)
![Screenshot 2023-10-01 at 15 46 23](https://github.com/Betarena/scores/assets/37311649/65cad29d-9f53-461d-9fcb-805a44226df7)

### 🤔 Expected Behavior

Draft competitions should not be visible in the "Competitions History"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ [#254](https://github.com/Betarena/scores-lib/issues/254).
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v854`.
