### ISSUE TITLE
[Bug]: Competition page cant change lang

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Not able to change LANG without the login:

https://scores.betarena.com/competitions/predictor/team-chelsea-will-win/134

### 🤔 Expected Behavior

Able to change the language.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
