### ISSUE TITLE
[Bug]: Competitions History

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Wrong color:

![Screenshot 2023-10-03 at 08 52 44](https://github.com/Betarena/scores/assets/37311649/6556adcc-2ae5-41a9-8fe2-fc12df573755)

### 🤔 Expected Behavior

Correct color:

#8C8C8C

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
