### ISSUE TITLE
[Bug]: Competitions History Dark Theme wrong colors

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing color variation inside the table and wrong text color:

![Screenshot 2023-10-03 at 08 56 43](https://github.com/Betarena/scores/assets/37311649/a32de9e9-2421-4f83-bbbb-b29170ff7d5a)

### 🤔 Expected Behavior

Correct colors:

<img width="1062" alt="Screenshot 2023-10-03 at 08 58 44" src="https://github.com/Betarena/scores/assets/37311649/f9e3ad2f-0eb6-4677-b254-4e6fc42ad94a">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Bottom `additional text` has been solved in #1708 .

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
