### ISSUE TITLE
[Bug]: Competitions History Dark Theme wrong hover color

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Incorrect hover color:

![Screenshot 2023-10-03 at 08 59 29](https://github.com/Betarena/scores/assets/37311649/d8cccb2e-1c6d-4fbb-bb38-6cb557d130f8)

### 🤔 Expected Behavior

Correct color:

<img width="983" alt="Screenshot 2023-10-03 at 09 00 21" src="https://github.com/Betarena/scores/assets/37311649/b97c4d8e-335b-4c87-9903-29ee37562a0d">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
