### ISSUE TITLE
[Bug]: Competitions history missing the sport translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the sport translation:

![Screenshot 2023-10-03 at 09 08 09](https://github.com/Betarena/scores/assets/37311649/e44519f9-ef33-4df4-adbe-bd4c004a62dd)

### 🤔 Expected Behavior

Add the sport-correct translation.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
