### ISSUE TITLE
[Bug]: Competitions History Mobile Missing Status Pending + "..."

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The title is too long, and the table name should not be 2 lines, also missing pending status:

![Screenshot 2023-10-03 at 09 12 49](https://github.com/Betarena/scores/assets/37311649/a5a17429-7eae-4e90-ba68-86668ed03b99)

### 🤔 Expected Behavior

"Contest Title" should be one line.

Add the "Pending" Status.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
