### ISSUE TITLE
[Bug]: Competitions History wrong title and not visible 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The status shows the prize and the rest of the elements are not visible.

![Screenshot 2023-10-03 at 09 15 45](https://github.com/Betarena/scores/assets/37311649/a4c6b40e-272c-41b7-bd2e-ced466a2d2af)

### 🤔 Expected Behavior

The title should show the correct values, and all elements should be visible.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> The status shows the prize and the rest of the elements are not visible.

@jonsnowpt That is because the `title` is too long, and causes a `double line`:

![Image](https://github.com/Betarena/scores/assets/20924663/d4578fbe-0813-4c39-be03-221932d42a89)

Should I have the `title` on `mobile` also hide the long text via an `ellipsis` (...) ?

**Comment by jonsnowpt** [comment]
@migbash 

Hide the title "Contest title" and use  (...)  if needed.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v855`.
