### ISSUE TITLE
[Bug]: Competitions History Tablet no need to limit the title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

On the competition detailed information the title is limited:

![Screenshot 2023-10-03 at 18 31 16](https://github.com/Betarena/scores/assets/37311649/78b3330a-6c82-4ab8-89a9-3ce831b9dfde)

### 🤔 Expected Behavior

Since we have the space available, we don't need to limit the number of characters in the title.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [X] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v856`.
