### ISSUE TITLE
[Bug]: Competitions History console error

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2023-10-03 at 18 35 47](https://github.com/Betarena/scores/assets/37311649/bc139897-a76b-4b0c-9f61-f0086dbc9333)

### 🤔 Expected Behavior

No errors in the console.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Not a frontend issue, it's a `response` formatting error on `firebase/services | functions` repo (app).

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Already addressed as part of issue ➤ #<-github-issue-number->.
> Implemented, awaiting `🚀 deployment`.
