### ISSUE TITLE
[Bug]: Competitions history inconsistent values Mobile / Desktop

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

<img width="1033" alt="Screenshot 2023-10-03 at 20 50 16" src="https://github.com/Betarena/scores/assets/37311649/761f8b31-f27d-4f02-846b-7a11ec9a20a4">

![IMG_6B4CC08D3663-1](https://github.com/Betarena/scores/assets/37311649/918affd2-6765-4b3e-80f4-ab0ac015d08d)

### 🤔 Expected Behavior

Same values.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect:

![IMG_53A9EF5C71BB-1](https://github.com/Betarena/scores/assets/37311649/8097ceae-d381-4508-a36d-18c3c91d6ced)

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v858`.
