### ISSUE TITLE
Fixture Page - Competition Widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1719]
#### 📝 DESCRIPTION

This widget will allow the users to participate in a competition associated with the fixture.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/e611d85b-7807-4925-9b87-207ca476b076)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Widget verification to display

Verify if available on `widgets_list`

`scores_widgets_list`

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

The widget is only present if there is a competition for the specific fixture. Also, there can be more than 1 competition for each match; in this case, the competition that will be displayed is the one with the most participants. if there are no participants in any of the competitions, the older ID is shown.

The widget logic is the same as we have on the competition page; this is just a way to make it faster and easier for users to participate in the competitions.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| competitions | data |
| competitions | translation_page_competition |

---

#### 🎏 TRANSLATIONS

| table |
| ----- | 
| competitions | translation_page_competition |
| scores_widgets_list |
---

#### ⚡️ CACHE

The cache data is already defined. When the cache is available, use it; if not, use the Hasura endpoint.

---

#### ⚡️ COMPRESSION

Use compression to the endpoint.

---

#### 🔎 SEO

Widget title

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=9rGjyMIDs4POWBkp-1

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
