### ISSUE TITLE
[Bug]: Comeptitions History Mobile pending color

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The pending color is not correct:

![File (61)](https://github.com/Betarena/scores/assets/37311649/9bc6f803-c20b-404e-884e-ff873cb1d9ab)

### 🤔 Expected Behavior

Correct color:

![pending](https://github.com/Betarena/scores/assets/37311649/2cc4a748-99d7-4ef7-8baf-d2f7c18802c5)

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
