### ISSUE TITLE
Crisp not adding new users

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1728]
https://betarena.slack.com/archives/D02B1UHEECS/p1696434562362069

**Comment by migbash** [comment]
> **Note**
> This was caused by the wrong `secrets` being deployed on the last deployment for `firebase/functions`. The newly redeployed secrets have been set and have been tested. Waiting for target `_this_` user `UID` in question to return to the platform to have their `CRISP UID` updated.

**Comment by migbash** [comment]
@jonsnowpt This has been dealt with ? Fix was made by the end of last week. Please confirm.

**Comment by jonsnowpt** [comment]
@migbash 

Fixed!
