### ISSUE TITLE
[Bug]: Competitions Lobby "How to play" missing hover and pointer

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We are missing the mouse pointer and hover:

![Screenshot 2023-10-09 at 14 08 11](https://github.com/Betarena/scores/assets/37311649/40dbac3b-08ba-4172-b5e4-e3c85658e11e)

### 🤔 Expected Behavior

The hover is the usual change to the orange.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
