### ISSUE TITLE
[Bug]: Competitions Lobby "How to play" animation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The slider should not have a fade in effect, also it seems that does not correctly when arriving from another page, check the examples:

https://github.com/Betarena/scores/assets/37311649/90353cfe-8597-4cf8-8994-d1372c9c445b

### 🤔 Expected Behavior

It should be a slider animation that fires up when the page loads.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v865`.

**Comment by jonsnowpt** [comment]
@migbash 

Not ok yet.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.

**Comment by jonsnowpt** [comment]
@migbash 

When the slider is animating out the header is over the popup and should be bellow.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v873`.
