### ISSUE TITLE
[Bug]: Competitions lobby "How to play" corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Wrong font-weight;
- [x] The YouTube video is not loading;
- [x] The margin at the footer is incorrect;
- [x] After selecting the checkbox and if the user comes back, the checkbox should be checked, and the user should have the option to remove the option to reverse the current option;

![Screenshot 2023-10-09 at 14 16 56](https://github.com/Betarena/scores/assets/37311649/c7cfc844-59ce-412f-8cfb-00e168952764)
![Screenshot 2023-10-09 at 14 15 57](https://github.com/Betarena/scores/assets/37311649/a6697810-42d8-45a1-95ec-565f22fb819f)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.

**Comment by migbash** [comment]
> The font weight of the title is still incorrect;

> **Note**
> Done via the `betarena_prod/userguide/data > (column) contents` data handle.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.
