### ISSUE TITLE
[Bug]: Competitions lobby "How to play" internal scroll position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The scroll bar position is incorrect:

![Screenshot 2023-10-09 at 14 16 56](https://github.com/Betarena/scores/assets/37311649/b7aa54a6-ddc6-48e0-846e-338f5876b8e9)

### 🤔 Expected Behavior

Should be more to the right side:

<img width="1476" alt="Screenshot 2023-10-09 at 14 21 55" src="https://github.com/Betarena/scores/assets/37311649/7962b648-f3e3-4887-98eb-96276831044a">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.

**Comment by jonsnowpt** [comment]
@migbash 

Disable the scroll in the background when the popup is open.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.
