### ISSUE TITLE
[Bug]: Competitions Lobby "How to play" mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] The slider animation for the mobile version is from the bottom to top;
- [x] The title and introduction are not centered;
- [x] The font size is not correct;
- [x] The popup should not cover fully but partially;
- [x] The "X" size is not correct;
- [x] The title is not positioned correctly;
- [x] The YouTube format is not correct;
- [x] The bullet points text position is not correct;
- [x] There is a white bar at the bottom that should not exist;

### 🤔 Expected Behavior

Correct view and positioning:

<img width="419" alt="Screenshot 2023-10-09 at 14 37 43" src="https://github.com/Betarena/scores/assets/37311649/48947584-b193-424d-bee2-44117840f5e4">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] The slider animation when closing the popup should be the same;
- [ ]  The "X" position is not correct;
- [ ]  The Do not show anymore position and font size are incorrect;
- [ ]  There is a white bar at the bottom that should not exist;

**Comment by migbash** [comment]
> The slider animation when closing the popup should be the same;

> **Note**
> Addressed in #1730.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.

**Comment by jonsnowpt** [comment]
@migbash 

Something is wrong with the line height, it's not assuming the correct value:



https://github.com/Betarena/scores/assets/37311649/3957d2f6-ccb4-4bb9-be4a-ff1b390f2725

**Comment by migbash** [comment]
> Something is wrong with the line height, it's not assuming the correct value:

@jonsnowpt don't understand, I asm using `125%` and `128%` for `line-height` as per design, is are they not the correct values ?

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v873`.
