### ISSUE TITLE
[Bug]: Competitions Lobby "How to play" status

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The popup does not respect the "draft" status.

![Screenshot 2023-10-09 at 20 28 58](https://github.com/Betarena/scores/assets/37311649/11405e5a-43f5-4fa0-b60c-845d7221c463)

### 🤔 Expected Behavior

The popup should only be visible if the status is published.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v865`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v866`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.
