### ISSUE TITLE
[Bug]: Competitions lobby "How to play" lang

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The lang is not being respected, only after a refresh.

### 🤔 Expected Behavior

When changing language, the popup should respond to the new set language without needing a refresh.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v866`.

**Comment by migbash** [comment]
> Still not working.

@jonsnowpt Please check again

**Comment by jonsnowpt** [comment]
@migbash 

Still not working.

**Comment by migbash** [comment]
@jonsnowpt Please check on `betarena_prod/userguide/data > (column) content`. The data for all `translations` are in `English` for every language.

**Comment by jonsnowpt** [comment]
@migbash 

Still not working for me

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.
