### ISSUE TITLE
[Bug]: Fixture tournament is opening in a new window

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In the DEV environment, the tournament link inside the fixture is opening has an external website.

https://github.com/Betarena/scores/assets/37311649/89873b25-4e4d-459b-abcf-98a63a605478

### 🤔 Expected Behavior

It should open like the other links internally, and understand why it happens in this version.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by jonsnowpt** [comment]
@migbash also happening in the h2h links.

**Comment by jonsnowpt** [comment]
@migbash also happening in the featured match widget

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v865`.
