### ISSUE TITLE
[Bug]: Competitions History $ should be BTA

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Fees, prizes, and potential wins are shown in $.

![Screenshot 2023-10-10 at 11 55 42](https://github.com/Betarena/scores/assets/37311649/335a76c1-da59-4150-832c-e7aa3f8af4f6)

### 🤔 Expected Behavior

It should be BTA.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
