### ISSUE TITLE
[Bug]: Header arrow not in position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The arrow should is not centered:

![Screenshot 2023-10-10 at 17 44 31](https://github.com/Betarena/scores/assets/37311649/d160b9f1-0704-4080-b4db-e8b086d95828)

### 🤔 Expected Behavior

The arrow should be centered.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v868`.
