### ISSUE TITLE
[Bug]: Competitions Lobby "How to Play" Tablet

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The popup size is incorrect:

![Screenshot 2023-10-11 at 08 55 41](https://github.com/Betarena/scores/assets/37311649/673452ab-6371-4ed8-a447-d7aa24a399c7)

### 🤔 Expected Behavior

Should be wider.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [X] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v872`.

**Comment by migbash** [comment]
> The issue persists:

@jonsnowpt What is the `device-width` / `pixels` of this ?

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v873`.
