### ISSUE TITLE
Leagues List - Expressions added

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#175]
I have added the following expressions that were missing for translation:

Show full list
No Results Found

===

`{"leagues_by_country":"Leagues by country",
"top_leagues":"Top leagues",
"search_form":"Search countries or leagues",
"widget_title":"Leagues",
"competitions_results":"Competitions",
"countries_results":"Countries",
"full_list":"Show full list",
"no_results":"No Results Found"
}`

This can now be added to all languages, translations already available.

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
