### ISSUE TITLE
[Bug]: Competitions lobby load performance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The competitions are taking too long to load.

### 🤔 Expected Behavior

The competitions should load immediately, maximum of 3s.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Anything else?

Check if Redis is being correctly used and introduce pagination to avoid loading all competitions, loading only the ones that are visible.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
