### ISSUE TITLE
[Bug]: Fixture undefined

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Undefined values:

![Screenshot 2023-10-12 at 11 15 32](https://github.com/Betarena/scores/assets/37311649/abe29d27-cffb-4fbd-9636-6b92d53ee731)

### 🤔 Expected Behavior

No undefined values.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/football/cuiab-cruzeiro-18791298

### Console Logs (if any)

![Screenshot 2023-10-12 at 11 17 40](https://github.com/Betarena/scores/assets/37311649/6eb21f47-86cb-49db-aad0-cff163a3a709)

### Anything else?

Lots of undefined values in the console.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v878`.
