### ISSUE TITLE
[Bug]: Fixture competition widget showing with no competition 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The competition widget shows where there is no competition:

![Screenshot 2023-10-17 at 15 57 44](https://github.com/Betarena/scores/assets/37311649/1c25736c-c561-480f-862b-efac11e9816b)

### 🤔 Expected Behavior

The widget only shows in fixtures with a competition active.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/pt/futebol/finland-kazakhstan-18713008

**Comment by migbash** [comment]
Related to #1778 

> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
