### ISSUE TITLE
[Bug]: Fixture competition hide the voting widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Voting widget being shown:

![Screenshot 2023-10-17 at 15 59 38](https://github.com/Betarena/scores/assets/37311649/94e46b8f-2cb5-4161-aa40-979163d7210e)

### 🤔 Expected Behavior

When the competition widget is active, the voting widget should be hidden.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/pt/futebol/finland-kazakhstan-18713008

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
