### ISSUE TITLE
[Bug]: Fixture competition widget dark overlay

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The dark overlay is not covering the header:

![Screenshot 2023-10-17 at 16 02 33](https://github.com/Betarena/scores/assets/37311649/8dfa2d5f-bbec-4ac2-a5e4-9c523f6866d2)

### 🤔 Expected Behavior

The overlay should cover all screen.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/amrica-mineiro-botafogo-18791308

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
