### ISSUE TITLE
[Bug]: Fixture competition widget corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Title alignment
- [x] Space for the probability, entry fee and Total prize;
- [x] Join No Dark wrong color
- [x] Participants avatar without the circle;
- [x] White version colors are wrong and the boxes do not have shadows;

![Screenshot 2023-10-17 at 16 06 22](https://github.com/Betarena/scores/assets/37311649/57f29f54-7445-4ea0-b9d5-f99f8a9a69d2)

![Screenshot 2023-10-17 at 16 09 29](https://github.com/Betarena/scores/assets/37311649/002cb0d9-5450-4dc5-80d6-3f98074c7d97)

![Screenshot 2023-10-17 at 16 11 48](https://github.com/Betarena/scores/assets/37311649/0b7b2b0a-59b5-425a-a239-7e21e3413a42)

### 🤔 Expected Behavior

Follow the Figma instructions.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/amrica-mineiro-botafogo-18791308

**Comment by migbash** [comment]
> **Note**
> Corrected), awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.

**Comment by jonsnowpt** [comment]
@migbash 

The Join Yes and No disabled CSS is still incorrect on the dark theme:



![Image](https://github.com/Betarena/scores/assets/37311649/f968260b-5129-4ba0-ab5f-86d5d933607a)



Should be like this:



![Image](https://github.com/Betarena/scores/assets/37311649/cc8482a1-d361-4e26-ad98-3e6ffccf4d9b)

**Comment by migbash** [comment]
> **Note**
> Corrected addressed as part of issue ➤ [#1785](https://github.com/Betarena/scores/issues/1785) .
> Awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing the 50% passthrough that is present on Figma.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v884`.
