### ISSUE TITLE
[Bug]: Fixtures competition widget font-weight

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Font-weight too heavy:

![Screenshot 2023-10-17 at 16 13 15](https://github.com/Betarena/scores/assets/37311649/8fdc51ff-346c-4ea9-a4fb-b5ecfed78bcd)

### 🤔 Expected Behavior

Change to 500.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/amrica-mineiro-botafogo-18791308

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
