### ISSUE TITLE
[Bug]: Fixtures competition widget status CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The status CSS is not correct:

![Screenshot 2023-10-17 at 16 15 48](https://github.com/Betarena/scores/assets/37311649/a447a85d-82e1-458a-940a-7d8adfbfe60c)

### 🤔 Expected Behavior

![Screenshot 2023-10-17 at 16 16 09](https://github.com/Betarena/scores/assets/37311649/6ef239fc-9f02-442c-b97d-1875f90f0568)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/river-plate-boston-river-18942277

**Comment by migbash** [comment]
> **Note**
> Already Corrected addressed as part of issue ➤ #1765 .
> Awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.

**Comment by jonsnowpt** [comment]
@migbash 

Here are still incorrect:

![Image](https://github.com/Betarena/scores/assets/37311649/103ca1dc-7cda-40d9-8c02-a616a5728cab)

**Comment by migbash** [comment]
> **Note**
> Corrected addressed as part of issue ➤ [#1785](https://github.com/Betarena/scores/issues/1785) .
> Awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v883`.

**Comment by jonsnowpt** [comment]
@migbash 

Use the same colors you find here:


https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-morocco-will-win/175

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v884`.
