### ISSUE TITLE
[Bug]: Fixtures competition widget allowing unregistered users to participate

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Users without login are able to participate.

### 🤔 Expected Behavior

Without login the users should not be able to participate and the request to register should be shown.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/england-italy-18712364

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
