### ISSUE TITLE
[Bug]: Fixture competition widget link to competitions

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing link to the Predictor competitions:

![Screenshot 2023-10-17 at 16 18 58](https://github.com/Betarena/scores/assets/37311649/6dedcbdc-8f65-44ff-b25b-48ba7f5accbb)

### 🤔 Expected Behavior

Add the link to the competition lobby and add that link to the SEO.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
