### ISSUE TITLE
[Bug]: Fixture competition widget link to competition

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the link to the competition:

![Screenshot 2023-10-17 at 16 22 30](https://github.com/Betarena/scores/assets/37311649/e7a53df3-90c7-44f3-b38a-b9cd6fa688c5)

### 🤔 Expected Behavior

Add a link to the competition and add it to the SEO.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/england-italy-18712364

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
