### ISSUE TITLE
[Bug]: Fixture competition widget expression "Competition Finished"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The expression at this time is "Event is Finished"

### 🤔 Expected Behavior

Should be:

"Competition Finished"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/ajax-az-18853969

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
