### ISSUE TITLE
[Bug]: Fixture competitions widget wrong top color dark

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Incorrect color:

![Screenshot 2023-10-17 at 17 36 13](https://github.com/Betarena/scores/assets/37311649/ae8c7c6d-cba7-418e-9883-9da8f7e90729)

### 🤔 Expected Behavior

Correct color:

![Screenshot 2023-10-17 at 17 36 33](https://github.com/Betarena/scores/assets/37311649/d403dbc6-45fd-4ea9-a882-b53c50ca52db)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Already Corrected addressed as part of issue ➤ [#1765](https://github.com/Betarena/scores/issues/1765).
> Awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `vXYZ`.
