### ISSUE TITLE
[Bug]: Fixture competitions widget not updating in real time

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The widget is not updating:

<img width="934" alt="Screenshot 2023-10-17 at 17 56 54" src="https://github.com/Betarena/scores/assets/37311649/040a2945-1807-4cfd-87f5-fdf48c1d9bef">

<img width="1392" alt="Screenshot 2023-10-17 at 17 56 48" src="https://github.com/Betarena/scores/assets/37311649/9ff9e4a6-f498-42b2-b522-a5c63e970802">

### 🤔 Expected Behavior

Probably not using the Hasura subscriptions to real-time data.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://betarena-scores-platform.herokuapp.com/football/uruguay-brazil-18946409

**Comment by migbash** [comment]
**🔍 CAUSE**
All working correctly (as in the `Event Listener`), just the participants for `NO` voters where not being reflected in `real-time` due to just restrictions to those in `yes`.

> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.
