### ISSUE TITLE
[Bug]: Always showing the same ODDS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The platform is now showing the same odds for all fixtures:

https://github.com/Betarena/scores/assets/37311649/3d7248f5-ce4e-404f-aaff-e0fcf83f45cb

### 🤔 Expected Behavior

Should load different odds.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit different fixtures.

### Anything else?

This issue started to happen after the last release.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**🔍 CAUSE**
The data point for `sessionStore.live_odds_fixture_target = [..]` is shared amongst `Featured Match (Home Page)` widget and in this case the `Scoreboard (Fixture Page)` widget, causing for the `Scoreboard` widget data to use that of the `Featured Match` when navigating on the Scores Platform under the same `session`.

**🟩 SOLUTION**
Data is now refreshed, and properly adjusted to `null-ify` for this specific case, even when navigating between pages (like in the case of this issue). 

> **Note**
> In addition, because the `Scoreboard (Fixture Page)` widget was not dynamically loaded, but rather directly imported, the svelte reactivity would trigger immediately upon page load, causing the `front-run` of the previously set `Featured Match (Homepage)` data for `1X2` odds. This has been adjusted as an additional condition check, to `null-ify` the data point.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.

**Comment by migbash** [comment]
> **Note**
> Took into effect as of `v.X.Y.Z` (via patch hot-fix).

**Comment by jonsnowpt** [comment]
@migbash 

We still have issues here.

The odds now are not repeated, but we still get the undefined error that should not occur:

https://scores.betarena.com/football/san-marcos-juventud-la-joya-19024641


![Image](https://github.com/Betarena/scores/assets/37311649/dfd94765-12f5-4cd0-bc1b-bfe37c5f6dc0)

**Comment by migbash** [comment]
> **Note**
> Still seen to be happening :: [slack](https://betarena.slack.com/archives/D02B1UHEECS/p1697751551392679)

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.

**Comment by migbash** [comment]
> **Note**
> The issue of the `odds` mirroring (a.k.a using that of the Featured Match) has been registered again [slack-conversation](https://betarena.slack.com/archives/D02B1UHEECS/p1697886139140939)

It appears that the `firebase-real-time listener` is somehow still using the `listener` which was set on the `homepage`. So, it seems the connection needs to be **obliterated** to prevent the odds from the `featured match` to act upon the data. Although, `fixtureId` checks are made to prevent the use of the `_1x2` odds, but nonetheless, a re-check is required.

**Comment by jonsnowpt** [comment]
@migbash 

Still having issues:

https://betarena.slack.com/archives/D02B1UHEECS/p1698144324706619
