### ISSUE TITLE
[Bug]: League search "undefined" country.

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Getting undefined country.

<img width="389" alt="Screenshot 2023-10-18 at 11 26 59" src="https://github.com/Betarena/scores/assets/37311649/8f26416a-0afc-48a9-92ef-b4c68d1ec04a">

### 🤔 Expected Behavior

The countries should be added, removing the undefined values.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v880`.

**Comment by migbash** [comment]
> **Note**
> Took into effect as of `v.X.Y.Z` (via patch hot-fix).
