### ISSUE TITLE
[Bug]: Type errors 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We continue to have various type errors that may be the culprit for the performance issues:

https://betarena.sentry.io/issues/4549970261/?environment=production&project=6275655&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

Cannot read properties of null (reading ‘includes’)
SCORES-PLATFORM-1CG | Today at 11:28 AM | Added by Sentry

https://betarena.sentry.io/issues/4557985078/?environment=production&project=6275655&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

Cannot read properties of null (reading ‘data’)
SCORES-PLATFORM-1ES | Today at 11:33 AM | Added by Sentry

https://betarena.sentry.io/issues/4549989847/?environment=production&project=6275655&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2

TypeError
Cannot set properties of undefined (setting ‘events’)
SCORES-PLATFORM-1CQ | Today at 11:21 AM | Added by Sentry

https://betarena.sentry.io/issues/3786711658/?environment=production&project=6275655&query=is%3Aunresolved&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=5

### 🤔 Expected Behavior

No errors identified and fast performance.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.
