### ISSUE TITLE
[Bug]: Fixtures competition widget Disabled CTA with wrong colors

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Wrong colors:

![Screenshot 2023-10-19 at 12 16 48](https://github.com/Betarena/scores/assets/37311649/b5b3597f-645b-4b40-b8bc-08e52fa47f36)

### 🤔 Expected Behavior

Correct colors:

![Screenshot 2023-10-19 at 12 17 02](https://github.com/Betarena/scores/assets/37311649/fe4adc94-91e8-458f-93ce-cf053d757fcc)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
**🔍 CAUSE**
Missed the step of creating a `all-single-chunk.css` file for the newly added `styles` and `app.css` to the html `<head>`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v883`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing the 50% passthrough.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v884`.
