### ISSUE TITLE
[Bug]: Fixtures competition widget inverted selection

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Selecting NO is showing the YES message in the popup:

![Screenshot 2023-10-19 at 12 22 21](https://github.com/Betarena/scores/assets/37311649/cb870b36-be30-4236-98d9-9be4c2853f59)

### 🤔 Expected Behavior

Should show the correct option.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v883`.
