### ISSUE TITLE
[Bug]: Fixtures competition widget repeated word

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

"Join" is repeated.

![Screenshot 2023-10-19 at 12 23 58](https://github.com/Betarena/scores/assets/37311649/fd62e0b7-e814-4277-bbeb-ea022c0fc2f9)

### 🤔 Expected Behavior

Only once.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v883`.
