### ISSUE TITLE
[Bug]: Fixture competition widget avatar spacing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The avatar spacing of the participants is not correct:

<img width="877" alt="Screenshot 2023-10-19 at 12 33 15" src="https://github.com/Betarena/scores/assets/37311649/822577d8-53fb-4902-b284-f81137f562de">

### 🤔 Expected Behavior

Should be like this:

![Screenshot 2023-10-19 at 12 33 29](https://github.com/Betarena/scores/assets/37311649/c56f5fff-ac3d-4422-a7e2-8ba8db677e91)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v883`.
