### ISSUE TITLE
[Bug]: Missing Fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We continue to have thousands of missing fixtures.

https://scores.betarena.com/football/milan-juventus-18867393
https://scores.betarena.com/football/lamia-pas-giannina-18901726
https://scores.betarena.com/football/sassuolo-lazio-18867396
https://scores.betarena.com/football/panaitolikos-volos-nfc-18901723
https://scores.betarena.com/football/sknderbeu-kor-vllaznia-shkodr-18960631
https://scores.betarena.com/football/santa-clara-vianense-19016515
https://scores.betarena.com/football/paredes-moreirense-19016502
https://scores.betarena.com/football/atltico-cp-vizela-19016498
https://scores.betarena.com/football/nacional-mirandela-19016517
https://scores.betarena.com/football/vila-mea-estrela-amadora-19016494
https://scores.betarena.com/football/rabo-peixe-casa-pia-19016507
https://scores.betarena.com/football/atltico-malveira-ad-marco-09-19016518
https://scores.betarena.com/football/leixes-vitria-fc-19016523
https://scores.betarena.com/football/felgueiras-1932-arouca-19016495
https://scores.betarena.com/football/academico-viseu-unio-de-leiria-19016513
https://scores.betarena.com/football/cd-olivais-e-moscavide-sporting-cp-19016496
https://scores.betarena.com/football/upnfm-vida-18901299
https://scores.betarena.com/football/defensor-sporting-cerro-largo-18942298
https://scores.betarena.com/football/henan-songshan-longmen-cangzhou-18813056
https://scores.betarena.com/football/unin-tarapoto-independiente-huachog-19024654
https://scores.betarena.com/football/defensor-porvenir-star-ancash-19024650
https://scores.betarena.com/football/fbc-club-aurora-maristas-19024653
https://scores.betarena.com/football/deportiva-agropecuaria-escuela-municipal-19024642
https://scores.betarena.com/football/deportiva-tahuishco-ucv-moquegua-19024644
https://scores.betarena.com/football/ecosem-pasco-vraem-19024646
https://scores.betarena.com/football/unin-santo-domingo-defensor-cubillas-19024647
https://scores.betarena.com/football/sport-cceres-juventud-palmeiras-19024648
https://scores.betarena.com/football/atletico-juventud-inclan-real-atltico-nueva-19024649
https://scores.betarena.com/football/miguel-grau-sociedad-de-tiro-28-19024652
https://scores.betarena.com/football/renovacin-pacifico-diablos-rojos-juliaca-19024656
https://scores.betarena.com/football/udinese-lecce-18867398
https://scores.betarena.com/football/fiorentina-empoli-18867391
https://betarena-scores-platform.herokuapp.com/football/uruguay-brazil-18946409
https://scores.betarena.com/football/galatasaray-fc-bayern-mnchen-18997030
https://scores.betarena.com/football/inter-salzburg-18997064
https://scores.betarena.com/football/manchester-united-fc-copenhagen-18997031
https://scores.betarena.com/football/lens-psv-18997044
https://scores.betarena.com/football/sevilla-arsenal-18997045
https://scores.betarena.com/football/sporting-braga-real-madrid-18997054
https://scores.betarena.com/football/fc-union-berlin-napoli-18997055
https://scores.betarena.com/football/benfica-real-sociedad-18997065

**🔸 UPDATE**

- https://betarena-scores-platform.herokuapp.com/football/amgk-sepahan-18988132

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **🔍 CAUSE**
Related [#251](https://github.com/Betarena/backend_betarena/issues/251).

**Comment by migbash** [comment]
> **Note**
> Issue has been fixed with [#251](https://github.com/Betarena/backend_betarena/issues/251) and tested on future `2-Weeks` fixtures for `frontend` visibility.

**Comment by jonsnowpt** [comment]
@migbash 

Supposedly this was sorted out with the tournament data update that also verified the `historic_fixtures`.

https://github.com/Betarena/scores/issues/1516

If this is working we probably do not need the corn jobs.

**Comment by jonsnowpt** [comment]
Another fixture missing:

https://scores.betarena.com/football/villarreal-maccabi-haifa-18997000

**Comment by migbash** [comment]
> Another fixture missing:

@jonsnowpt the fixture is missing from the `Sportmonks v2`...

Check on :: https://soccer.sportmonks.com/api/v2.0/fixtures/between/2023-10-24/2023-11-07?per_page=200&page=4, and look for the target `fixture id :: 18997000` starting at `19:00:00`. It's not there in the list.

Looks like `_this_` fixture has been moved ?

https://soccer.sportmonks.com/api/v2.0/fixtures/18997000.

**Comment by jonsnowpt** [comment]
@migbash 

Task to review to the 96 hours:

https://github.com/Betarena/scores/issues/1516
