### ISSUE TITLE
[Bug]: Odds missing in the probabilities

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

"2" odds missing in this market in the probabilities widget: all fixtures

<img width="511" alt="Screenshot 2023-10-19 at 21 08 50" src="https://github.com/Betarena/scores/assets/37311649/ba38cc41-4945-4678-8cef-90e3cf0b65fa">

### 🤔 Expected Behavior

Odds showing.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.
