### ISSUE TITLE
[Bug]: Fixtures competitions widget missing translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2023-10-20 at 19 53 55](https://github.com/Betarena/scores/assets/37311649/275fc9a9-57d0-4da8-bee7-f197cf98480f)

### 🤔 Expected Behavior

Translation available.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.
