### ISSUE TITLE
[Bug]: Fixtures competitions widget mobile corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Align the pool prize left and push them a little bit to the left to allow space for bigger numbers;
- [x] Avatar sizes are incorrect;

![Screenshot 2023-10-20 at 20 10 48](https://github.com/Betarena/scores/assets/37311649/4945fcf4-2a80-47c0-b840-332385b28cdd)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.
