### ISSUE TITLE
[Bug]: Fixtures competitions widget tablet corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Pool prize position is incorrect;

![Screenshot 2023-10-20 at 20 16 03](https://github.com/Betarena/scores/assets/37311649/07987b28-abd2-4035-93b7-9a2329b17f5b)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [X] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v887`.
