### ISSUE TITLE
[FEATURE]: Remove Crips integration add Intercom integration

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1802]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

Crisp did not work as expected, and the campaigns were not correctly sent to users. For that reason, we are moving to Intercom.

### 📝 Feature Request Description

Remove all Crisp code integrations, including the Firestore and events logic.

### ➕ Further context and resources (cummulative)

Add Intercom integration with the same user information. (Instructions sent to email)

Data to be added:

competition_number
email
lang
name
uid

Replace the code snippet of Crisp chat with the Intercom alternative.

https://www.intercom.com/help/en/articles/268-what-is-user_id-and-why-would-i-want-to-use-it

**Comment by migbash** [comment]
> **Note**
> Use the: https://developers.intercom.com/installing-intercom/web/installation/

> **Note**
> Implemented, awaiting `🚀 deployment`.
