### ISSUE TITLE
[Bug]: Infinite Scrolling in "Open Competitions" Section

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In the Open Competitions section, if a user continues clicking the slider button when there are no more open competitions available, the list keeps scrolling, revealing an endless sequence of black content.

### 🤔 Expected Behavior

When there are no more open competitions, clicking the slider button should not allow the list to keep scrolling. It should either show an appropriate message (e.g., "No more open competitions") or disable the button.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

- https://scores.betarena.com/competitions

### Anything else?

![image](https://github.com/Betarena/scores/assets/114171785/69c4da5e-00ba-4b9a-9853-64a9873d6c0d)

**Comment by jonsnowpt** [comment]
Resolved.
