### ISSUE TITLE
[Bug]: Betting partners cache endpoint not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The cache endpoint is not working:

![Screenshot 2023-10-25 at 17 53 59](https://github.com/Betarena/scores/assets/37311649/fb2c59b8-ab47-4105-97f6-7a14e897ff5e)

### 🤔 Expected Behavior

Update the endpoint.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Updated and documentation created on `Obsidian` in `Betarena Scores > ⚡️ API Services`.
