### ISSUE TITLE
[Bug]: Competitions not loading correctly on fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

https://github.com/Betarena/scores/assets/37311649/947db0b2-f913-4530-9694-8f5c54e55c5c

### 🤔 Expected Behavior

The competitions should load correctly in the fixtures that have competitions available.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/football/paris-saint-germain-milan-18997084

**Comment by migbash** [comment]
**🔍 CAUSE**
Incorrect `condition` handling when target `live competition map` does not contain target `fixture/competition` data.

> **Note**
> Corrected, awaiting `🚀 deployment`.
