### ISSUE TITLE
[Bug]: International flag load performance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

After we changed the European flag, the international flag takes a lot of time to load correctly:

https://github.com/Betarena/scores/assets/37311649/ea5ec7dd-9e98-4892-a5f0-bf23f996b52a

### 🤔 Expected Behavior

All flags should load instantly.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
