### ISSUE TITLE
[Bug]: Competitions lobby new competitions

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The competitions continue not to appear after we create them.

### 🤔 Expected Behavior

Competitions should immediately be available after we create them.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
**🔍 CAUSE**
Use of unnecessary `@cached (ttl: 300)` to be added to the `graphql` queries of competitions. 

> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Checklist**
- [ ] upgrade `scores` to `scores-lib@X.Y.X`
- [ ] upgrade `cache` to `scores-lib@X.Y.X`
