### ISSUE TITLE
[Bug]: About and footer nor respecting the language change

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When we change the language, the footer does not update, nor does the About message on the homepage. We need to force a refresh to changes to take effect.

<img width="1422" alt="Screenshot 2023-10-27 at 10 17 57" src="https://github.com/Betarena/scores/assets/37311649/29efed96-400d-40dc-ac88-23d02147c790">
<img width="733" alt="Screenshot 2023-10-27 at 10 17 44" src="https://github.com/Betarena/scores/assets/37311649/63ee2dfb-9f01-4473-95c8-56c6b2c4b45a">

### 🤔 Expected Behavior

The footer and about message should change when changing language.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
