### ISSUE TITLE
[Bug]: Fixture page betting site not loading

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The betting site information is not loading; it may be related to the service worker error:

https://github.com/Betarena/scores/assets/37311649/03284084-abfc-4c2b-9db9-735891e18d12

### 🤔 Expected Behavior

Every information on the fixtures page should load correctly.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> `/football/arouca-moreirense-18870387` as target `fixture` with error.

@jonsnowpt Cannot reproduce, is it still happening to you on the target fixture ?

**Comment by jonsnowpt** [comment]
@migbash it happens to all finished fixtures, for example:

https://scores.betarena.com/football/hhc-heracles-almelo-19015739

**Comment by migbash** [comment]
@jonsnowpt Hmm, all working on my end (Firefox), in both cases:

- [video-1](https://github.com/Betarena/scores/assets/20924663/2d487c37-3baf-4f09-9404-2d5888c208e5)
- [video-2](https://github.com/Betarena/scores/assets/20924663/9067f31e-d966-4721-8675-c60dd021be1c)

**Comment by jonsnowpt** [comment]
@migbash no, since it is also happening on iPhone:

![image](https://github.com/Betarena/scores/assets/37311649/57fe16f6-ebee-4540-914f-7ba144b36056)

**Comment by migbash** [comment]
> **Note**
> Can replicate in the case of `/football/corinthians-athletico-pr-18791342` target `url`.

<img
src=https://github.com/Betarena/scores/assets/20924663/df0e6b77-091a-4275-8425-6eb5541b868b
width=250
/>

**Comment by jonsnowpt** [comment]
@migbash What happens is that after a refresh, the betting site logos are loaded, but every time that we access the page for the first time, the logos are "undefined".


https://github.com/Betarena/scores/assets/37311649/2f44fe2e-1c19-402d-b2ef-a21bda0121f8

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
