### ISSUE TITLE
[Bug]:  Missing fixture

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

https://scores.betarena.com/pt/futebol/estoril-porto-19008399

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Same issue as discussed before, the data is incorrect as supplied by `Sportmonks | v2`, and/or has been `POSTPONED` for `_this_` fixture `id: 19008399`.

```json
[..]
"time": 
{
  "status": "NS",
  "starting_at": 
  {
      "date_time": "2023-12-06 18:00:00",
      "date": "2023-12-06",
      "time": "18:00:00",
      "timestamp": 1701885600,
      "timezone": "UTC"
  },
[..]
```

**Comment by jonsnowpt** [comment]
@migbash 

Do you have a suggestion to avoid this? A sweep to get the postponed status and update the dates accordingly?

**Comment by migbash** [comment]
> Do you have a suggestion to avoid this? A sweep to get the postponed status and update the dates accordingly?

@jonsnowpt I need to check as to why this is not auto-updating, as we did have setup a change in `status` and/or `fixture date` to cause a update of a target fixture on the `Hasura` DB. Will get back with an update.

**Comment by jonsnowpt** [comment]
deprecated
