### ISSUE TITLE
[FEATURE]: Smart Contract Betarena Launchpad

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1822]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

![Image](https://user-images.githubusercontent.com/37311649/225444207-5dff2041-c7eb-42f9-bc86-0990c28a51c3.png)

### 📝 Description:

We need to develop a smart contract to handle various functionalities in the Betarena investor section. The contract should allow investors to send USDC or USDT to Polygon Betarena addresses and log necessary data.

---

### ℹ️  Environment Setup:

- [x] Node.js, npm, Truffle/Hardhat project initialization.
- [x] OpenZeppelin contracts and libraries.
- [x] OpenZeppelin Defender for security.

This is the recommended environment. OpenZeppelin must be used in this case.

---

### Smart Contract Development

- [x] Use Solidity and OpenZeppelin templates.
- [x] **frontend** Functions for handling USDC and USDT.

---

### User Authentication

- [x] **frontend** WalletConnect for frontend wallet connections.
- [x] **frontend** Validate the user's UID from Betarena.

The UID is available in the Firebase AUTH and Firestore.

---

### Chain Switch

- [x] **frontend** Prompt user to switch to Polygon via WalletConnect.

Since we are using Polygon for BTA it makes sense that the users invest directly in the correct chain.

---

### Currency Selection

- [x] **frontend** Function for selecting between USDC and USDT.

---

### Transaction and Data Logging

- [x] **frontend/endpoint** Log data upon transaction confirmation.
- [x] **frontend/endpoint** Use GraphQL to send data to PostgreSQL via Hasura.

The data will be sent to the `transaction_history` table.

---

### Data to Log:

- [x] User UID [uid]
- [x] Date of transfer [date]
- [x] Amount of Currency used (quantity)
- [x] Asset used [asset]
- [x] Number of BTA tokens received [amount]
- [x] Token price [bta_price]
- [x] deposit_wallet_address*

The wallet_address structure:

```
{
    "wallet_address": {
      "type": "0",
      "address": "0"
    }
}
```

---

### Testing:

- [x] Unit tests using OpenZeppelin test helpers.
- [x]  Test on a testnet.

---

### Deployment:

- [ ] `⏸️ pending` Use OpenZeppelin Defender for secure deployment to Polygon.
Awaiting Defender API Keys and Access.

---

### Frontend Integration:

- [x] Integrate WalletConnect on the frontend.

---

### Monitoring and Maintenance:

- [ ] Use OpenZeppelin Defender's monitoring tools.

---

### ✅ Acceptance Criteria:

- [ ] All functionalities are implemented and tested.
- [ ] Smart contract is securely deployed.
- [ ] Necessary data is correctly logged and sent to the database.

**Comment by migbash** [comment]
> **Note**
> @jonsnowpt For the smart contract, are the deposits made by users with USDC / USDT should be:
> - stored on the `contract` and be only withdrawal only by **superuser** ?
> - _or_ automatically forwarded/sent the **deposit** amount to a target `address` right upon successful deposit ?

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena.slack.com/archives/D02B1UHEECS/p1699651467336559

**Comment by jonsnowpt** [comment]
@migbash 

> stored on the contract and be only withdrawal only by superuser ?
or automatically forwarded/sent the deposit amount to a target address right upon successful deposit ?


Sent to the investor presale wallet:

0x53c3d0F4ee3DDf4e9D000f0F84F1fC8E797Dfe86

**Comment by migbash** [comment]
> **Note**
> Partially Implemented, awaiting `🚀 deployment`.
> **Regarding Smart Contract**

**Comment by migbash** [comment]
> [!NOTE]
> Fully Implemented, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

You need to change the recipient address and move on to add the Smart Contract into the `testnet` using the new Defender version.

**Comment by migbash** [comment]
@jonsnowpt Require additional access to the `Defender V2`:

![Image](https://github.com/Betarena/scores/assets/20924663/6bb73d00-0adc-4291-89ce-a5ed3910c40a)
