### ISSUE TITLE
[Bug]: Crisp code present

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We still have Crisp code in the platform since it is identifying users' activity in the platform:

![Screenshot 2023-11-08 at 09 43 49](https://github.com/Betarena/scores/assets/37311649/91eadedd-d2d9-49d1-9c6f-e73b1e5a8671)

### 🤔 Expected Behavior

Crisp code should be totally removed and stop recording users' activity.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Update of the `firebase-functions` is required to remove last parts of the `CRISP` being acted in the background.
