### ISSUE TITLE
[FEATURE]: Review readme for the Scores project to allow DEV environment

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1830]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We must add the platform to manager accesses and secrets for the `DEV` environments.

**Comment by migbash** [comment]
> [!NOTE]
> `⏸️ pending` Ready and awaiting.

**Comment by jonsnowpt** [comment]
Resolved.
