### ISSUE TITLE
Investor Section: Widget Round

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1832]
#### 📝 DESCRIPTION

This widget includes the round information, which can be in 4 different stages.

1: INVITE ONLY
2: TO BE ANNOUNCED
3: Countdown with defined date
4. Open with countdown to finish

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/c0265cc5-c8cd-4cfe-8508-c1177618cf2d)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Loader.

---

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

The `current_value` of the investment should be the sum of all private presale investments available in the following table:

`betarena_general_data  /   public    /   transaction_history`

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| betarena_prod / investors / widgets | round / data
| betarena_prod / investors / widgets | round / values

---

#### 🎏 TRANSLATIONS

Inside the main table.

---

#### ⚡️ CACHE

No REDIS cache.

---

#### 🔎 SEO

No SEO.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5029%3A36364&mode=design&t=9ndywvmodF5KFedp-1

**Comment by migbash** [comment]
> [..] The `current_value` of the investment should be the sum of all private presale investments available in the following table: 
> `betarena_general_data  /   public    /   transaction_history`

@jonsnowpt How to differentiate between the different kinds of `deposits` we have on the `(table) transaction_history` ? Should I count the transactions with the `(column) description :: BTA Deposit Request` ?

**Comment by jonsnowpt** [comment]
@migbash 

description

The description will be visible in the Investment Details table in the Investor Section, and will inform the type of investment, Private or Public Presale.

```
Private Presale
Public Presale
```

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
