### ISSUE TITLE
[FEATURE]: Investors logic

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1833]
### 📝 Feature Request Description

We need to add a new table to add the investor's details that will include all information about the investments and will update accordingly when investors claim their tokens.

### IMPORTANT:

The tiers and vesting period calculations only happen prior to the defined Public Presale end date.

### Investor table information:

Table: `investors`
Path:  `betarena_general_data / investors`

Table Structure:

```
id
uid
data
```

UID (User UID)
TGE Tokens 
```
The number of TGE tokens is calculated based on the total tokens available in the investor wallet and tier.

Formula:
TGE Amount = Total Tokens in Investment Wallet × TGE Percentage for Tier

Where:

TGE Amount is the number of tokens the user will receive at the TGE.

Total Tokens in Investment Wallet is the total number of BTA tokens the user has in their investment wallet.
TGE Percentage for Tier is the percentage of tokens that are available to the user at the TGE, based on their investment tier.

Example:
Suppose a user is in the "Gold" tier, which has a TGE percentage of 25%, and they have 10,000 BTA tokens in their investment wallet. The calculation would be:

TGE Amount = 10,000 × 25% =2,500 BTA tokens

So, this user would receive 2,500 BTA tokens at the TGE.

```
Investor Wallet Addresses

This data is populated from the `transactions_history` table, field `wallet_address`

Vesting Periods:

```
To calculate the token amounts for each vesting period based on the total number of tokens in an investor's wallet, you'll need to know the total vesting period and the frequency of vesting (e.g., monthly, quarterly). Here's a general formula you can use:

Formula:
```

![Screenshot 2023-11-15 at 17 04 25](https://github.com/Betarena/scores/assets/37311649/a99581f4-f0c6-4cf5-8bf0-56f4e13da011)

```
Where:

Total Tokens in Investment Wallet is the total number of tokens the investor holds.
TGE Tokens is the number of tokens received at the Token Generation Event (TGE).
Number of Vesting Periods is the total number of periods over which the tokens will be vested. 

Example:

Suppose an investor in the "Gold" tier has 10,000 BTA tokens in total, with 25% (2,500 tokens) received at TGE and a vesting period of 18 months. The calculation for the number of tokens they would receive in each subsequent vesting period would be:

```
![Screenshot 2023-11-15 at 17 05 02](https://github.com/Betarena/scores/assets/37311649/02814026-f8f0-46ec-92ca-d3c90e6ce54c)

```
So, this investor would receive approximately 416.67 BTA tokens per month over 18 months after the TGE.

Adjust the formula based on your specific vesting schedule and frequency.
```

Vesting Period

`This information varies depending on the investor tier and can go up to 18.`

Vesting Available date

`Here, after the calculations, the date is always the first of every month, and the initial release date will be set on the round widget on the future public presale.`

Vesting Tokens

`The number of tokens available for each vesting period. Based on the already mentioned formula.`

Vesting Status

The vesting status change depending on:

```
no status (Setup a daily cron that will verify the vesting date, if the vesting date is met the status changes)
Available (If when the cron runs the date is met, the status should be changed from "no_status" to "available")
Pending (If the user claims the tokens the status should change from "Available" to "Pending")
Distributed (When the tokens are reclaimed and moved from the investor wallet to the main wallet)
```

Vesting wallet reclaim

`The investor when requesting the tokens from the vesting period the wallet information should change from "null" to "Main Wallet".`

Vesting Distribution Date

`When the funds are approved to be moved from the investor wallet to the main wallet, the date of that distribution should be added to the vesting period table.`

Vesting Claim Date

`The date of the claim is set after the investor confirms the claim option.`

Vesting Claimed Status

`The button status is changed after the investor confirms the claim option.`

Bonus Summary:

Bonus Referrals

`The total amount of tokens added to the investor wallet through referrals.`

Bonus Referred

`The total amount of tokens added to the investor wallet from being referred.`

Number of Referrals

`The total number of referrals `

Total Earned Bonus

`The total amount of bonus received from both being a referred and referral `

Referral History:

Referral UID

`The UID of each referral`

Referral Bonus Percentage

`Percentage earned for each referral`

Referral Bonus Tokens

`Total number of tokens earned by each referral`

Date

`Date of the referral investment`

Structure:

```
{
  "uid": "",
  "tge_tokens": "",
  "investor_wallets": {
    "1": "0x68Ec3Ebd8DfFf3d2988Fb20364A8E1523824505c",
    "2": "0x68Ec3Ebd23233d2988Fb20364A8E1523824505c"
  },
  "vesting_periods": {
    "1": {
      "id": 1,
      "available_date": "01/01/24",
      "tokens": "2500",
      "status": "3",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": "30/01/24",
      "claim_status": "3"
    },
    "2": {
      "id": 2,
      "available_date": "01/01/25",
      "tokens": "2500",
      "status": "1",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": null,
      "claim_status": "1"
    },
    "bonus_summary": {
      "referral_bonus": "0",
      "referred_bonus": "0",
      "referrals_number": "0",
      "total_bonus": "0"
    },
     "referral_history": {
    "1": {
      "id": 1,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
    },
    "2": {
      "id": 2,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
  }
}}}
```

**Comment by migbash** [comment]
> [!Note]
> Implemented, awaiting `🚀 deployment`.
