### ISSUE TITLE
Investor Section: Widget Invest Box

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1834]
#### 📝 DESCRIPTION

This widget will allow investors to proceed with their investments in the presale stage, both private and public.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/689b0a4c-9d83-485b-ab5c-a292fceae05c)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Loader.

---

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

The Fiat option will send users to the following Stripe payment option:

`https://buy.stripe.com/7sIeWc72V8Hw33WbIM`

We need to collect the following information:

User UID [uid]

===

**TERMS and DISCLAIMER**

The terms and disclaimer options should open a popup with the same design we already have in the competitions.

![Image](https://github.com/Betarena/scores/assets/37311649/21a4154f-135a-46ae-89f4-b901d5f945a1)

===

**REAL-TIME CURRENCY CONVERSION**

We need to have a real-time currency converter between the USDC / USD + USDT/USD. also, the number of BTA tokens is considering the USD value.

Platform to conversion: https://coinmarketcap.com/api/documentation/v1/

===

**CHAIN CHANGE**

After connecting the wallet, the user will be forced to change their chain to guarantee that the amount transferred is sent from the correct wallet balance.

===

**DEPOSIT AMOUNT**

The available amount to deposit will check the investor's wallet for available funds. The minimum deposit is 2500 USD.

===

**TIER**

The investor tier checks:

`number of tokens currently in the investor wallet + deposit amount`

Depending on the total value, the tier changes, and the discount is applied, changing the total number of tokens the investor will receive.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| betarena_prod / investors / widgets | investor_box / data
| betarena_prod / investors / widgets | investor_box / values

---

#### 🎏 TRANSLATIONS

Inside the main table.

---

#### ⚡️ CACHE

No REDIS cache.

---

#### 🔎 SEO

No SEO.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5029%3A36364&mode=design&t=vAbJoQ18y4cZs1Xi-1

**Comment by migbash** [comment]
Related [#1834](https://github.com/Betarena/scores/issues/1834)

**Comment by migbash** [comment]
> [!NOTE]
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!WARNING]
> Please note, the current `BetarenaBank` cryptocurrency `deposits` are redirected to my (Miguel's) MetaMask account `0xA7B90A598ba81977dA54DA40AAAD3e30d702346f`.

**Comment by migbash** [comment]
> [!TIP]
> Missing designg have been added to `Figma`. Need implementation.
