### ISSUE TITLE
Profile: Investor Section Option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1835]
#### 📝 DESCRIPTION

We will add an investor section to the user profiles that will allow the users to participate in the Betarena ICO.

![Image](https://github.com/Betarena/scores/assets/37311649/b9e77ca5-bbbc-4540-94f9-369279656230)

---

#### 📱 TARGET PLATFORMS

This option will be available on all platform versions.

---

#### 🎬 LINK

https://scores.betarena.com/u/investor/pt

---

#### ℹ️ OTHER CONDITIONS (& RELEVANT INFO)

In this section, users will be able to access both the private and public presale and all data referring to their investments.

The way data is filtered for each user is by using the UID.

---

### Versions:

All theme variations are supported.

---

#### 💠 DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| betarena_prod | profile_translations |

---

#### 🎏 TRANSLATIONS

➤ **Hasura**

| table | columns |
| ----- | --------- |
| betarena_prod | profile_translations |

---

#### ⚡️ CACHE

Unavailable.

---

#### 🔎 SEO

Unavailable.

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5029%3A36364&mode=design&t=Yk0nHcqvF5tPtwrf-1

**Comment by migbash** [comment]
Related [#1834](https://github.com/Betarena/scores/issues/1834)

**Comment by migbash** [comment]
> [!NOTE]
> Implemented, awaiting `🚀 deployment`.
