### ISSUE TITLE
[FEATURE]: Referral ID logic for new and existing users

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1836]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

To implement the referral ID logic in your system using Firestore, you'll need to update your user registration process and add referral ID functionality to your existing user data. Here's how you can proceed:

### Step 1: Generating Unique Referral IDs

- [x] **For New Registrations:** When a new user registers, generate a unique referral ID. This can be a combination of alphanumeric characters that is easy to share but unique enough to avoid duplicates.
- [x] **For Existing Users:** Run a one-time script to generate and assign unique referral IDs to all existing users in Firestore.

### Step 2: Updating Firestore Schema

**User Collection Schema:**

- [x] Add a new field, referralID, to store the unique referral ID for each user.
- [x] Add a field like referredBy, which stores the referral ID of the user who referred them, if applicable.
- [x] Add a field (array) that includes all referred_users;

Example:

![Screenshot 2023-11-20 at 08 33 35](https://github.com/Betarena/scores/assets/37311649/2b46cb2d-49b0-4963-9008-25140f47c3fe)

### Step 3: Handling Incoming Referral Links

- [x] When a new user registers through a referral link, parse the referralId parameter from the URL.
- [x] Automatically fill in the referring user's ID in the registration process, linking the new account to the referrer.

### Step 4: Backend Logic for Referral Tracking

- [x] Validate Referral IDs: On the backend, validate incoming referral IDs to ensure they correspond to an existing user.
- [x] Associate Referrals: When a new user signs up using a referral link, associate this action with the referrer in your database.

### Cookies and logic for the Referrals

To implement a referral system where the referral ID in a link associates the referral for 30 days using cookies, you'll need to coordinate between your SvelteKit frontend and C# backend. Here's a step-by-step approach:

**Frontend (SvelteKit)**

Parsing Referral Link:

When a user visits your site with a referral link (e.g., https://yourapp.com?referralId=USER_REFERRAL_ID), parse the referralId from the URL query parameter.

Setting Cookies:

If a referralId is present, set a cookie on the user's browser with this ID. Use JavaScript to create a cookie that expires in 30 days.

Example code snippet to set a cookie:

`document.cookie = `referralId=${referralId}; max-age=${30 * 24 * 60 * 60}; path=/;`;`

**Cookie Reading on Registration:**

- [x] On the registration page, check for the presence of the referralId cookie.
- [x] If the cookie exists, automatically associate the referral ID with the new user's registration data sent to the backend.

**Backend (C#)**

**Receiving Registration Data:**

- [x] When receiving the registration data from the frontend, check if it includes a referral ID.

Referral Association Logic:

- [x] If a referral ID is present, create a record in Firestore linking the new user to the referrer.
- [x] Implement logic to handle the referral tracking, such as validating the referral ID against your database to ensure it corresponds to an existing user.

Handling the 30-Day Association:

- [x] Store the date when the referral association was made.
- [x] Implement logic to consider the referral valid if a registration occurs within 30 days from this date.

**Security and Data Integrity**

- [x] Ensure the security of the information being passed, especially when dealing with cookies and personal data.

### FIRESTORE TIPS:

Adding Referred IDs:

When a new user is referred, add their ID to the referring user's Referred IDs array.
Use Firestore's array union operation to ensure the ID is added uniquely and prevents duplicates.

```
const userRef = firestore.collection('users').doc(referrerUserId);
userRef.update({
  referredIds: firebase.firestore.FieldValue.arrayUnion(newReferredUserId)
});
```

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> ![NOTE]
> Updated **all** users on `Firestore` with a new assigned `referralId` property.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v970`.
