### ISSUE TITLE
Investor Claim trigger: Logic

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1838]
### 📝 Feature Request Description

When the user claims the TGE tokens or a specific vesting period that is now available for withdrawal, a transaction is added to the transaction_history table to be verified to run the trigger.

### IMPORTANT

When the user selects and confirms the claim option, the number of tokens claimed is immediately removed from the investor wallet, and the information about the claim is updated. If the claim is not fulfilled, the transaction detail is updated, and tokens are reverted to the investor wallet.

### Transaction History data:

Table: `transaction_history`
Path:  `betarena_general_data / transaction_history`

Table Structure:

```
id
date
asset
quantity
amount
description
type
status
Gateway
first_name
last_name
payment_email
iban
bic_swift
wallet_address_erc20
uid
payment_processor_fee
platform_fee
tier
bta_priceit
deposit_wallet_address
withdraw_wallet_address
```

### Claim logic:

When the funds are available to be withdrawn, the user will be able to reclaim them to be transferred to the main wallet.

- [ ] CTA is available
- [ ] Investor select over the CTA
- [ ] A confirmation message is displayed (content and translations in `investors / general_translations`)
- [ ] User cancels the investor section is displayed and nothing changes
- [ ] The investor confirms, the claim button changes from "Claim" to "Claimed", the status from "Available" to "Pending";
- [ ] The withdraw transaction is added to the `transaction_history` table;

---

### TRIGGER

When the trigger runs, the following events must occur:

STATUS PENDING

- [x] Update the number of tokens available in the main wallet;
- [x] Update the data in the `investors` table;

```
  "vesting_periods": {
    "1": {
      "id": 1,
      "available_date": "01/01/24",
      "tokens": "2500",
      "status": "3",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": "30/01/24",
      "claim_status": "3"
    },
```

STATUS CANCELED

- [x] Add back the tokens requested to be withdrawn to the investor wallet;
- [x] Change back the status of the vesting period from "Pending" to "Availble";

Structure:

```
{
  "uid": "",
  "tge_tokens": "",
  "investor_wallets": {
    "1": "0x68Ec3Ebd8DfFf3d2988Fb20364A8E1523824505c",
    "2": "0x68Ec3Ebd23233d2988Fb20364A8E1523824505c"
  },
  "vesting_periods": {
    "1": {
      "id": 1,
      "available_date": "01/01/24",
      "tokens": "2500",
      "status": "3",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": "30/01/24",
      "claim_status": "3"
    },
    "2": {
      "id": 2,
      "available_date": "01/01/25",
      "tokens": "2500",
      "status": "1",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": null,
      "claim_status": "1"
    },
    "bonus_summary": {
      "referral_bonus": "0",
      "referred_bonus": "0",
      "referrals_number": "0",
      "total_bonus": "0"
    },
     "referral_history": {
    "1": {
      "id": 1,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
    },
    "2": {
      "id": 2,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
  }
}}}
```

**Comment by migbash** [comment]
> [!Note]
> Implemented, awaiting `🚀 deployment`.
