### ISSUE TITLE
[Bug]: Invest Box USD Conversion

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The conversion is not working:

![Screenshot 2023-11-27 at 08 13 08](https://github.com/Betarena/scores/assets/37311649/3717be77-b931-423a-8690-450925420261)

### 🤔 Expected Behavior

USDC should be converted to USD in real-time. Also, the number of tokens (BTA) will depend on the conversion of USDC to USD.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Caused by `CORS` issues imposed by **CoinMarketCap**
> https://stackoverflow.com/questions/55670206/i-cant-get-data-from-a-public-api-access-control-allow-origin-missing

> [!NOTE]
> Solved by creating a custom **Server Endpoint** to fetch **CoinMarketCap** data (via custom middleware).

**Comment by jonsnowpt** [comment]
@migbash 

Update every 30s once the user select the invest box.

The BTA value is indexed to the USD, so yes.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Should be:

0.99 USD

![Screenshot 2023-11-30 at 07 32 44](https://github.com/Betarena/scores/assets/37311649/f2f5adda-8eee-4833-9349-c9da3ccf598e)

**Comment by migbash** [comment]
@jonsnowpt Should the BTA amount calculation use the `(rounded) 0.99 USD` value ? Or the full `0.9974533...` is provided ?

**Comment by jonsnowpt** [comment]
@migbash 

The `BTA` calculation is currently incorrect because the discount is not being applied.

By default 1 BTA = 1 USD

But the price varies depending on the `current tier discount`

Formula:

`BTA = 1 USD - Tier Discount`

![Screenshot 2023-11-30 at 12 24 10](https://github.com/Betarena/scores/assets/37311649/b654e7cd-9763-4cf0-b503-6759f62f3ea6)

This is incorrect, it's not applying the discount.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v951`.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

We should invert it:

1 BTA = 0.80 USDC 

Also, respect this format.

![Image](https://github.com/Betarena/scores/assets/37311649/5fef82b6-adf1-4718-bca1-39a56bbacb26)


Also, the total BTA does not seem to be correct:


![Image](https://github.com/Betarena/scores/assets/37311649/4c9dfca1-bbf6-4f5c-92bb-a24b370874a0)



![Image](https://github.com/Betarena/scores/assets/37311649/2f669ea1-e7d5-4118-8b48-978185847038)

**Comment by migbash** [comment]
> Also, respect this format.

@jonsnowpt Are you're referring to the numbers being `2 decimal places` ?

> Also, the total BTA does not seem to be correct:

@jonsnowpt The calculation was agreed upon to be that of using `USD` for `BTA Amount`, therefore `BTA (amount) = (25000 / 0.999) / 0.7 = 35750.04`, where `0.999 is USD` and not `USDC`.

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v953`.
