### ISSUE TITLE
[Bug]: Switch Networks Verification Missing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The invest box is not forcing the correct chain ~~and there is no information of the balance and chain connected.~~

### 🤔 Expected Behavior

When the user connects verify the chain and advise to the correct one. ~~Also, add the chain and balance information in the Invest Box:~~

![Screenshot 2023-11-27 at 13 34 21](https://github.com/Betarena/scores/assets/37311649/23e1dc7d-19e0-4d3c-b114-37639d9cdf8f)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Also, add the chain and balance information [..]

@jonsnowpt Where to add the `chain information` on the `Invest Box` UI ?

**Comment by jonsnowpt** [comment]
@migbash 

I asked the design team; I will let you know once it is ready.

**Comment by migbash** [comment]
> [!NOTE]
> Created offspring task ➤ [#1849](https://github.com/Betarena/scores/issues/1849).

**Comment by migbash** [comment]
> [!NOTE]
> Marked as working ? **Default chain** and *only** connecting wallet set to be that of `Polygon` and no other option available though `WalletConnect`.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v951`.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v952`.
