### ISSUE TITLE
[FEATURE]: Create environment for Development for the new repo

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1844]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

Create a new `dev` environment on Docker with Github actions using the new Hetzner cloud server:

- [x] Use the repo apidatanarratives;
- [ ] Configure Docker;
- [ ] Add Git Actions;
- [ ] First commit to c# dev;
- [ ] Make a first deployment to server (for testing)

**Comment by migbash** [comment]
> [!Note]
> Created offspring task ➤ [#1](https://github.com/Betarena/apidatanarratives/issues/1).

**Comment by jonsnowpt** [comment]
@migbash 

Directly to `main`, we will not add a development branch for now.

**Comment by migbash** [comment]
> [!NOTE]
> Completed as part of the closed **child task** :: [#1](https://github.com/Betarena/apidatanarratives/issues/1).
