### ISSUE TITLE
[Bug]: Invest Box checkbox hovers

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

~~The checkbox should not have border and the color is not correct,~~ also missing the mouse hover with the correct pointer.

![Screenshot 2023-11-28 at 15 51 47](https://github.com/Betarena/scores/assets/37311649/d577a73c-7b7a-4bc0-bb1f-fbc319522261)

### 🤔 Expected Behavior

- [x] Mouse pointer for selection;
- [ ] ~~Change the checkbox for darker color without border;~~

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> - [ ] Change the checkbox for darker color without border;

@jonsnowpt Unknown `checkbox` design UI when in a `non-selected` state (missing from Figma). Example needed, concerning the `border-color` and wether it should be `hollow` or `filled` (if so, what color).

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v949`.
