### ISSUE TITLE
[Bug]: Invest box showing null and default 2000

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The invest box in the deposit option is showing "null" and a "2000" default value.

![Screenshot 2023-11-30 at 07 34 31](https://github.com/Betarena/scores/assets/37311649/a4654de2-7616-4319-a3ee-30cc9604ea98)

### 🤔 Expected Behavior

It should be "0" for both cases.It should

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v951`.
