### ISSUE TITLE
[Bug]: Preloader white and the logo with lettering / broken image

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When on a dark theme, the preloader uses the white version, and the placeholder of the logo is shown with lettering.
https://github.com/Betarena/scores/assets/37311649/c9308254-2a7b-46bd-a4b4-72de11c15e7d

### 🤔 Expected Behavior

The preloader on the dark theme should be dark, and the logo should be a default image placeholder.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

We can add back the splashscreen

**Comment by migbash** [comment]
> [!Note]
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
