### ISSUE TITLE
[Bug]: Private session 500 error

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When accessing the DEV platform on the private window, we get a 500 internal server error:

![Screenshot 2023-12-11 at 10 12 25](https://github.com/Betarena/scores/assets/37311649/34533e8c-d93f-43bc-acf6-8bb13241782d)

### 🤔 Expected Behavior

Should be able to access.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
