### ISSUE TITLE
[Bug]: Investor section: Wrong title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Incorrect title:

![Screenshot 2023-12-11 at 10 18 19](https://github.com/Betarena/scores/assets/37311649/3fd2ba70-0413-49a9-8c13-c1396a998a00)

### 🤔 Expected Behavior

It should be "Public Presale." it's available on the DB.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
