### ISSUE TITLE
[Bug]: Investor section: Round widget corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Missing the subtitle under Round 1;
- [x] Wrong colors on different titles;
- [x] Add "-" when no data is available;
- [x] Data to be announced wrong color;

### 🤔 Expected Behavior

Correct CSS

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [ ] Missing the subtitle under Round 1;

@jonsnowpt current available widget states:

#### InviteOnly 

?

#### To Be Accounced

![Image](https://github.com/Betarena/scores/assets/20924663/16ffc74c-e712-4c94-9acd-8c309b66dd10)

#### Future Defined Date

![Image](https://github.com/Betarena/scores/assets/20924663/76ad4c48-aac2-4c10-9716-7fe6762b18ef)

#### Countdown With Defined Date

![Image](https://github.com/Betarena/scores/assets/20924663/da1945f0-37c9-4f9d-b639-f6da65ff1cc1)

#### Countdown To Finish

![Image](https://github.com/Betarena/scores/assets/20924663/8ad1e1f5-6569-4dfd-9e0e-31313611253d)

#### In Progress

![Image](https://github.com/Betarena/scores/assets/20924663/9c6e05d5-8b44-4416-b4d5-e28d8d2fab54)

#### Ended

![Image](https://github.com/Betarena/scores/assets/20924663/cfd6788a-4366-423b-8117-806ac439c47f)

Should the `Presale starts|ends in` subtitle be present in **all** states given above ? Or when should it not be seen ?

**Comment by jonsnowpt** [comment]
@migbash 

There aren't so many states. Should be:

Invited investors only;
Starts In
Ends In
Ended

> Should the Presale starts|ends in subtitle be present in all states given above ? Or when should it not be seen ?

No, only in the start and end states.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.

**Comment by jonsnowpt** [comment]
@migbash 

Following what was mentioned, this version is incorrect:

![Image](https://github.com/Betarena/scores/assets/37311649/8a5568de-26d8-4b9a-9c09-d08e09dbaff3)

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
@jonsnowpt How to deal with the states `2` and `4` ? As they have not been defined from the start as possible states, but the user needs to know whe the round is going to start in the near `future` and when it is going to end.

| Widget State | Description |
| - | - |
| X. InviteOnly | Unknonw condition |
| 1. ToBeAnnounced | No target dates defined for both start **or finish |
| 2. ShowStartDate | Defined `start date` for a invest round **is shown** |
| 3. CountdownWithDefinedDate | Defined `start date` is going to start within 24 hours, **show countdown** |
| 4. ShowEndDate | Defined `end date` for a invest round **is shown** |
| 5. CountdownToFinish | Defined `end date` is going to start within 24 hours, , **show countdown** |
| 6. Ended | Display an `end` message |

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Change to the correct state.

![Image](https://github.com/Betarena/scores/assets/37311649/d792f81f-0aa1-49ec-a4a6-2399d1652e40)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
