### ISSUE TITLE
[Bug]: investor Section Box

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] CSS on the terms ticker;
- [x] Change from "$" to "USD";
- [x] Add a decimal "0.8" to "0.80";

![Image](https://github.com/Betarena/scores/assets/37311649/d953e008-cbd0-4d9a-bcb5-99ffc84919ca)

### 🤔 Expected Behavior

Corrections applied.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
