### ISSUE TITLE
[Bug]: Investor section limit the decimals on balance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Limit the number of decimals on balance to 2.

![Screenshot 2023-12-11 at 10 49 40](https://github.com/Betarena/scores/assets/37311649/37d5ab14-2b3f-4c86-909c-417184d4cd96)

### 🤔 Expected Behavior

Like this:

![Screenshot 2023-12-11 at 10 51 18](https://github.com/Betarena/scores/assets/37311649/6c5daef6-0104-42fa-8a11-88c7b5568fc0)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
