### ISSUE TITLE
[Bug]: Investor section - Confirmation popups incorrect CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The popups do not have the correct CSS:

![Screenshot 2023-12-11 at 10 57 01](https://github.com/Betarena/scores/assets/37311649/4f198a3b-9134-4500-9c65-369b05264e65)
![Screenshot 2023-12-11 at 10 57 37](https://github.com/Betarena/scores/assets/37311649/98ecad49-816f-4d9d-a778-4b2a24f021c3)

### 🤔 Expected Behavior

Correct CSS:

![Screenshot 2023-12-11 at 10 59 17](https://github.com/Betarena/scores/assets/37311649/22c90957-cc5d-47c4-8353-09bf05dcda34)
![Screenshot 2023-12-11 at 10 59 23](https://github.com/Betarena/scores/assets/37311649/b61cd50a-e94e-4307-8395-ef0af91f3d57)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.

**Comment by jonsnowpt** [comment]
@migbash 

The second popup of the transaction confirmed is not being shown.

**Comment by migbash** [comment]
> [!NOTE]
> Related to [#1877](https://github.com/Betarena/scores/issues/1877)

**Comment by migbash** [comment]
@jonsnowpt We potentially need an `error` popup for the transaction.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v958`.

**Comment by jonsnowpt** [comment]
@migbash 

> @jonsnowpt We potentially need an error popup for the transaction flow, when something goes wrong. Don't have one right now.

Requested

**Comment by jonsnowpt** [comment]
@migbash 

Design available.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
