### ISSUE TITLE
[Bug]: Investor Section Round raised amount

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The raised amount will be manually added using the `current_value` in the round widget option.

![Screenshot 2023-12-11 at 11 02 31](https://github.com/Betarena/scores/assets/37311649/70d14d5f-2cfb-48c7-9941-32bc5dd96197)

### 🤔 Expected Behavior

Manually added.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> The raised amount will be manually added using the current_value in the round widget option.

@jonsnowpt So the current logic for the `automatic` fetching of the `betarena_general_data > (schema) public > (table) transaction_history > (column) description` should be disabled in favour of the (mentioned) `(data point) current_value` ?

**Comment by jonsnowpt** [comment]
@migbash 

The logic is going to be applied on other widgets but not in the total value of the round widget.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
