### ISSUE TITLE
[Bug]: Investor section does not work on mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Not able to execute a transaction on mobile.

### 🤔 Expected Behavior

Users should be able to buy tokens through mobile devices.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Not able to get the investment go through, check the video examples:

https://betarena.slack.com/archives/D02B1UHEECS/p1703435009468509

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.
