### ISSUE TITLE
[Bug]: Investor section: Missing CTA "glow"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing CTA glow:

![Screenshot 2023-12-12 at 14 55 32](https://github.com/Betarena/scores/assets/37311649/4aa1d814-a42e-41a2-8e74-8d567e58861c)

### 🤔 Expected Behavior

Follow Figma CSS 

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.
