### ISSUE TITLE
[Bug]: Investor Section CSS corrections Light Theme

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Wrong progress bar color;
- [x] Change the font_weight of this section from 500 to 400 (the Figma font weight is 500, but when implemented, the 400 reflects the correct design)
- [x] The green bar on the progress bar should have a glow, as seen on the design for both theme versions;
- [x] Correct subtitle colors to correspond to the correct ones;

![Screenshot 2023-12-12 at 14 59 00](https://github.com/Betarena/scores/assets/37311649/deb2cf3e-49fb-4691-b184-ca4a2f6c203f)

### 🤔 Expected Behavior

Pixel perfect.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v956`.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
> Caused by invalid use of the missing `@betarena/scores-lib` version.

**Comment by migbash** [comment]
> **Note**
> Live on `dev` from `v957`.

**Comment by jonsnowpt** [comment]
@migbash 

Still getting font-weight 500 and 600. Please change it to 400.

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Wrong colors:

![Image](https://github.com/Betarena/scores/assets/37311649/12bedaf5-48e8-49b1-abb0-d500784ed5b9)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Here is `USD`

![Image](https://github.com/Betarena/scores/assets/37311649/a7a3f190-7f78-4ad2-a0ca-b3620d09633a)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
