### ISSUE TITLE
[Bug]: Investor section checkbox alignment

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The checkbox is not aligned:

![Screenshot 2023-12-16 at 12 26 26](https://github.com/Betarena/scores/assets/37311649/289a1027-e3bd-4472-9411-58a79eb749cc)

### 🤔 Expected Behavior

Correct version:

![Screenshot 2023-12-16 at 12 27 55](https://github.com/Betarena/scores/assets/37311649/187be9b8-14e2-4fcb-b234-3c8fb5e86aea)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
