### ISSUE TITLE
[Bug]: Investor section Header on top

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The header is on top of the dark overlay:

![Screenshot 2023-12-16 at 12 32 45](https://github.com/Betarena/scores/assets/37311649/c1b25e92-776a-4e4f-9234-7cc3f782aaca)

### 🤔 Expected Behavior

The Header should be bellow the dark overlay.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

> [!NOTE]
> Live on `dev` from `v958`.

**Comment by jonsnowpt** [comment]
@migbash 

The issue persists:

![Image](https://github.com/Betarena/scores/assets/37311649/0073e121-bdcf-4299-b279-8e146665d442)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
