### ISSUE TITLE
[Bug]: Investor section Transfer not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The last 25 USDC transfer did not go through:

![Screenshot 2023-12-16 at 12 38 18](https://github.com/Betarena/scores/assets/37311649/5953e1ce-6a83-4d0e-bfde-ede83381c4c7)

### 🤔 Expected Behavior

After making a 25 USDC investment, it should be available at the recipient's address.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Caused by the unexpected update of the `pakcage-lock.json` when doing a `rm -rf node_modules pakcage-lock.json` which caused the wrong patched version to be installed of (?) `walletconnect`, causing (apprently) some removed features from `walletconnect` package, leading to issues in transfers, whcih were working fine before.
> Fixed by reverting to the latest stable `package-lock.json`.
