### ISSUE TITLE
Investor section FAQ task

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1878]
Add the FAQ on the investor section.

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Add space before the Title;
- [ ] Limit the content width inside the faq answers;
- [ ] Add a <p> on the Need more information;
- [ ] Add the link to the presale "https://about.betarena.com/presale"
- [ ] Add an easing effect on the dropdown;



![Image](https://github.com/Betarena/scores/assets/37311649/3f38d6f6-c47a-428e-af94-8938e6013e9d)

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v971`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Align the presale CTA at the bottom;
- [ ] Open in a new window "_blank";

![Image](https://github.com/Betarena/scores/assets/37311649/6f90d353-5950-45f8-ae8a-83cd32b15958)

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v974`.
