### ISSUE TITLE
[Bug]: Investor Section Mobile CSS corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. Launchpad title incorrect size;
- [x] 2. Invest box title incorrect size;
- [x] 3. "Current Tier..." incorrect positioning;
- [x] 4. FAQ incorrect CSS for mobile;

1.

![Screenshot 2023-12-24 at 14 44 17](https://github.com/Betarena/scores/assets/37311649/d2a6983c-f035-452f-9da7-09588b079b37)

2.

![Screenshot 2023-12-24 at 14 46 47](https://github.com/Betarena/scores/assets/37311649/f5b0e8eb-00e1-4ff9-a7a3-04f9f8242cf5)

3.

![Screenshot 2023-12-24 at 14 47 48](https://github.com/Betarena/scores/assets/37311649/3bb0c195-67fb-4d36-a5a6-2a95b5e1e088)

4.

![Screenshot 2023-12-24 at 14 49 05](https://github.com/Betarena/scores/assets/37311649/3cddafab-0536-4594-9316-5d66d636f9bd)

### 🤔 Expected Behavior

Follow the Figma pixel-perfect approach.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v971`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] FAQ title incorrect size;
- [ ] Link to presale incorrect CSS;
- [ ] The content width inside the FAQ should be bigger;

![Image](https://github.com/Betarena/scores/assets/37311649/8194ce93-0f92-4b80-be52-95c185cc8075)
![Image](https://github.com/Betarena/scores/assets/37311649/4ad8a0ae-4d22-4f19-9028-240d2bc3c3ea)

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v974`.

**Comment by jonsnowpt** [comment]
@migbash 

Overflow on mobile is breaking the design:

![Image](https://github.com/Betarena/scores/assets/37311649/05f5a716-2365-4b75-aeb0-aa7cf555e1ed)

Also, the FAQ title does not have the correct space in the description, and the block is not aligned correctly:

![Image](https://github.com/Betarena/scores/assets/37311649/1a903b55-e4e6-47ae-aa21-ab777276630f)

The expressions inside the deposit box are incorrect:

**Comment by migbash** [comment]
@jonsnowpt No translations available for `Balance`.

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
> No translations available for Balance. Needs to be added.

@migbash added into the invest_box translations.

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Center the tabs info;
- [ ] 2. Verify the width of the FAQ section;
- [ ] 3. Missing translation;

1.

![Image](https://github.com/Betarena/scores/assets/37311649/2691e39b-157f-413e-b62c-91bda62ea00e)


2.

![Image](https://github.com/Betarena/scores/assets/37311649/9fe32efa-1b11-4e5a-bc33-2b50a1796729)


3.

![Image](https://github.com/Betarena/scores/assets/37311649/f61c2579-b06e-48b2-95fa-f453a1753871)

**Comment by jonsnowpt** [comment]
@migbash 

We do not need more translations. The following responds to all necessities:

```
        "max_title": "Unlimited",
        "round_title": "Round 1",
        "date_message": "Presale invite only stage",
        "progress_title": "Progress",
        "round_description": "Starts in",
        "current_value_title": "Raised:"
```
