### ISSUE TITLE
[Bug]: Investor section - Invest box only numeric values

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The investor box allows letters and symbols:

![IMG_F829837F6FDF-1](https://github.com/Betarena/scores/assets/37311649/1fb2f5b3-2d7e-438f-b9dc-3851a1d089a0)

### 🤔 Expected Behavior

Should only allow numeric values.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> 

@jonsnowpt A known `Firefox` and `Safari` issue due to their outdated `HTML5` parsing. Does not happen in `Chrome`. The input values will show an error upon `submit` action. We can close the issue.

https://stackoverflow.com/questions/17976393/html5-input-type-number-not-working-in-firefox

**Comment by jonsnowpt** [comment]
Closing the issue
