### ISSUE TITLE
[Bug]: Investor section terms modal font size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The font size of the content inside the terms is incorrect:

![Screenshot 2023-12-25 at 17 51 35](https://github.com/Betarena/scores/assets/37311649/07082906-513c-40c7-b5df-0e156898051c)

### 🤔 Expected Behavior

It should be this size:

![Screenshot 2023-12-25 at 17 51 52](https://github.com/Betarena/scores/assets/37311649/4454d0db-8b56-4398-b1fa-c99b18710280)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v971`.

**Comment by jonsnowpt** [comment]
@migbash 

The "X" close option does not follow the same approach we have in the competitions, where its color and size is a little bit different and is always present.


![Image](https://github.com/Betarena/scores/assets/37311649/6843e35e-e89d-4147-a2ca-4f0fc3e9661f)
![Image](https://github.com/Betarena/scores/assets/37311649/b5d0160d-89b9-440b-9caf-ed5a44e57a86)

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v974`.

**Comment by jonsnowpt** [comment]
@migbash 

The "X" is not fixed in the top in the desktop version, please review.

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.
