### ISSUE TITLE
Investor section setup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1884]
- [x] Correct wallet connect ID;
- [x] Defender integration;

**Comment by migbash** [comment]
Related [#1822](https://github.com/Betarena/scores/issues/1822)

**Comment by jonsnowpt** [comment]
@migbash 

Access updated.

**Comment by migbash** [comment]
> [!NOTE]
> - [x] Defender integration;

Completed, and setup to be used with `hardhat` for the respective contract deployment.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Review and correct relevant issues reported by Defender;
- [ ] Confirm the Wallet Connect API key change;

**Comment by migbash** [comment]
> Confirm the Wallet Connect API key change;

@jonsnowpt It is confirmed, change in the `WalletConnect Project Id` has been setup and deployed on `heroku-dev@latest` version ? Is there an issue ?
