### ISSUE TITLE
[Bug]: Investor section missing translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2023-12-26 at 11 12 30](https://github.com/Betarena/scores/assets/37311649/72d98b94-da08-4f2f-8ed7-f431181b38d3)

### 🤔 Expected Behavior

All expressions should be available on the respective languages.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
@jonsnowpt Missing **translations**.

**from `(schema) investors > (table) widgets > widget_name:: round`**

- `Presale ends in` 
- `Date To Be Announced`
- `Invite Only`
- `Ended`

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v974`.

**Comment by jonsnowpt** [comment]
@migbash 

Still missing:

![Image](https://github.com/Betarena/scores/assets/37311649/a994e03c-4388-4cc5-a9ef-64043419bc18)

**Comment by migbash** [comment]
> [!NOTE]
> https://github.com/Betarena/scores/issues/1885#issuecomment-1870117390
> Corrected, awaiting `🚀 deployment`.
