### ISSUE TITLE
Investor Section - Widget Video Presentation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1886]
#### 📝 DESCRIPTION

This widget will contain the YouTube presale video presentation.

![Image](https://github.com/Betarena/scores/assets/37311649/ef41c177-721f-4dd2-be32-498607afdf1e)

**IMPORTANT: The investor box moves on the scroll in the desktop version.**

---

#### 📸 WIDGET IMAGE

YouTube Thumbnail.

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

Video link: 

`https://www.youtube.com/watch?v=AGIXX306u-Y`

`<iframe width="560" height="315" src="https://www.youtube.com/embed/AGIXX306u-Y?si=E0siOfU9wRJk0oql&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=sq0qKNgUD2PFryoX-1

**Comment by migbash** [comment]
> [!NOTE]
> Preliminary (Stable) Implementation Complete, awaiting `🚀 deployment`.
> Live on `dev` from `v978`.
