### ISSUE TITLE
[Bug]: Investor Section Light Theme popup alert CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The CSS for the Light theme is not correct:

![Screenshot 2023-12-27 at 09 32 53](https://github.com/Betarena/scores/assets/37311649/69d683f4-681d-4771-9b9b-7233ee771d5f)

### 🤔 Expected Behavior

CSS should be working correctly for all themes.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

The header at the end of the transaction overlaps the layout:

![Image](https://github.com/Betarena/scores/assets/37311649/89b65fb1-679c-45f6-ab52-c3649080ed0a)

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.
