### ISSUE TITLE
Investor Section - Tier Pricing Widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1889]
#### 📝 DESCRIPTION

This widget will contain information about the tiered pricing and also inform in which tier the investor is at the current time.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/230e00b2-b569-404c-bd8a-171dde025051)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

| table | columns |
| ----- | --------- |
| investors | widgets + tiers + data |

**Investor token information:**

`transaction_history`
`investors`

The total BTA tokens the investor owns will be:

The sum of all transactions with user UID with the "Private Sale" description with the completed status + Total Bonus from referred and referral. 

In the case of this particular widget, the value will never be subtracted for claimed tokens since it is just historical information and not the true value of the investor wallet.

![Image](https://github.com/Betarena/scores/assets/37311649/6caf4af2-a349-4ef7-b50a-c141a4b52d43)

---

### Resources

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=sq0qKNgUD2PFryoX-1

**Comment by migbash** [comment]
@jonsnowpt What is the design/UI for the **ivestment reaching a tier** (the circle) ?

![Image](https://github.com/Betarena/scores/assets/20924663/b3bbb449-db03-4425-90c9-509e01071a0a)

**Comment by jonsnowpt** [comment]
@migbash 

You can use the same we have here:

https://about.betarena.com/presale

![Screenshot 2024-01-12 at 20 35 18](https://github.com/Betarena/scores/assets/37311649/0a5d31c8-a00e-4d39-9ae5-218d3cdd8f92)

**Comment by migbash** [comment]
@jonsnowpt Is the `Your Staked Amount` box meant to _slide_ (get closer to next tier) with increased investment ? Or should it remain in `between` distance of 2 tiers ?

Asking because, where on the `progress line` should the `Your Staked Amount` box be placed when a user has reached `> $100,000` (platinum), which does not have a `maximum` ?

**Comment by jonsnowpt** [comment]
@migbash 

It stays in the correspondent Tier until it reaches the next one.

**Comment by migbash** [comment]
> [!NOTE]
> Preliminary (Stable) Implementation Complete, awaiting `🚀 deployment`.
> Live on `dev` from `v978`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1, Titles do not respect the original format available on the DB;
- [ ] 2. The widget title position is incorrect;
- [ ] 3. Without investment, the tier mark should not exist;
- [ ] 4. The spaces between investment tiers are not correct;
- [ ] 5. The tier grey icon colors are incorrect;
- [ ] 6. The animation is not working;
- [ ] 7. The height space is incorrect from the end to the tiers icons;
- [ ] 8. The values do not seem to respect the data from the database;

![Image](https://github.com/Betarena/scores/assets/37311649/1967b782-30b9-471b-9fb9-ee6036638245)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [TIP]
> Used direct figma side-by-side comparison for UI error detection.

**Comment by jonsnowpt** [comment]
@migbash 

The animation is not working correctly.

**Comment by migbash** [comment]
> @jonsnowpt Working correctly for me, can you send a sample/video of it not working ?

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> Animation starts later than it is supposed;

@jonsnowpt When should the animation start ? As soon as, the _this_ widget is visible (is in view) ? Or have a buffer, as it is setup right now, which triggers upon close scroll (window-top) proximity.

**Comment by jonsnowpt** [comment]
@migbash 

> When should the animation start ? As soon as, the this widget is visible (is in view) ? Or have a buffer, as it is setup right now, which triggers upon close scroll (window-top) proximity.

When the widget is visible.

**Comment by migbash** [comment]
The heights are incorrect.

![Screenshot 2024-01-26 at 08 41 45](https://github.com/Betarena/scores/assets/37311649/07145762-f470-438d-816c-0c166ea8419f)

**Comment by migbash** [comment]
> When the widget is visible.

@jonsnowpt When its visible like this ?

<img
src=https://github.com/Betarena/scores/assets/20924663/14f0b59c-57d9-491e-bb58-290c6a4c6702
width=350
/>

**Comment by jonsnowpt** [comment]
@migbash 

Yes.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
**Offspring** #1924

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v986`.
