### ISSUE TITLE
Investor Section - Investor wallet widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1890]
#### 📝 DESCRIPTION

On this widget, the investor will be able to verify the total tokens available in their wallet and check the curve of their portfolio over time.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/2abd8387-7b28-4cae-90f6-d4a571d65d51)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

`betarena_general_data`

| table | columns |
| ----- | --------- |
| transactions_history | amount + description + type |
| investors | data |

Total BTA = Transaction history, both deposit and withdraw, using the user UID + Investors data that reflects the total bonus amount.

Graph Curve information = Transaction history, both deposit and withdraw, using the user UID + Investors data that reflects the total bonus amount

---

#### 🎏 TRANSLATIONS

`betarena_pod/investors`

| table | columns |
| ----- | --------- |
| investor_wallet | data |

`betarena_pod/public`

| table | columns |
| ----- | --------- |
| scores_general_translations | months |

---

### Resources

For creating graphs and charts in Svelte, some of the best libraries include:

Svelte-Chartjs: Leverages Chart.js, a widely-used JavaScript charting library, offering a wide range of chart types and customization options.

Svelte-ApexCharts: Integrates ApexCharts, known for its rich features and dynamic, interactive charts.

Svelte-Frappe-Charts: Utilizes Frappe Charts, which offers simple, SVG-based charts with a focus on simplicity and ease of use.

Svelte-Visx: Based on Visx from Airbnb, it's a collection of reusable low-level visualization components.

D3-Svelte: A Svelte-specific wrapper for D3.js, which is a powerful tool for creating complex and customizable data visualizations.

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=3646%3A26969&mode=design&t=vPPvOYeUmBXLRhJ4-1

**Comment by migbash** [comment]
> [!NOTE]
> Implemented, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Check if it is possible that the fill color is a gradient like in the Figma example;
- [ ] Review the border/graph line. It should be thicker;
- [ ] The total token values do not correspond to the graph, and sometimes 100000 is shown. Other times it won't;

**Comment by migbash** [comment]
> [..] both deposit and withdraw [..]

@jonsnowpt Do you mean transactions of `type: investment` and `type: vesting` ? Not the actual `deposit` and `withdrawal`, right ? As they are different things.
Take a look at `betarena_general_data > _enum > transaction_type` for the respective `type` information if need be.

> [..] reflects the total bonus amount.

@jonsnowpt 
- Should the `bonus` data also be reflected on the chart as to when a said **bonus** was obtained ? 
- or, should it just be added to the **total investor wallet** amount displayed, without reflected on the `chart` ?

**Comment by jonsnowpt** [comment]
> Should the bonus data also be reflected on the chart as to when a said bonus was obtained ?
or, should it just be added to the total investor wallet amount displayed, without reflected on the chart ?

@migbash 

We can add also the `bonus`.

Remember that the `withdrawals` and `refunds` should also be visible in the graph.

**Comment by migbash** [comment]
> ![Note]
> Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v982`.
