### ISSUE TITLE
[Bug]: Investor section FAQ Tablet

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Change the width of the FAQ content:

![Screenshot 2023-12-28 at 15 52 00](https://github.com/Betarena/scores/assets/37311649/0527eaa7-c28a-4a77-ae0e-3da2fbceef69)

### 🤔 Expected Behavior

Follow the FIGMA example.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [X] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.
