### ISSUE TITLE
Investor Section - TGE tokens widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1893]
#### 📝 DESCRIPTION

On this widget, the investor will be able to verify the total tokens available on the launch date TGE, it will also allow the investor to claim their tokens.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/721f967b-16f1-45c6-83a8-a6c8c5f73a06)
![Image](https://github.com/Betarena/scores/assets/37311649/bdf67c88-148e-4255-925b-c07664a9ce27)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

`betarena_general_data`

| table | columns |
| ----- | --------- |
| betarena_general_data / investors | data |
| betarena_prod / widget_name / round | data | 

From the investor's table, we get the TGE amount.

From the round widget, we get the date for calculating the TGE release date.

![Image](https://github.com/Betarena/scores/assets/37311649/33883d10-280d-40d0-82c3-3b6037205cec)

---

#### 🎏 TRANSLATIONS

`betarena_prod/investors`

| table | columns |
| ----- | --------- |
| tiers | data |

---

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5095%3A63370&mode=design&t=ALEsqT7swSI4IaNZ-1

**Comment by migbash** [comment]
@jonsnowpt **TGE** date is the **end of the Public Sale** (the last sale condutcted), right ?

**Comment by jonsnowpt** [comment]
@migbash exactly, and its the date that will allow to calculate all vesting periods.

**Comment by migbash** [comment]
> [!NOTE]
> Preliminary (Stable) Implementation Complete, awaiting `🚀 deployment`.
> Live on `dev` from `v978`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Incorrect font size;
- [ ] 2. Missing paragraph;
- [ ] 3. Incorrect color/grey should be #CCCCCC;


![Image](https://github.com/Betarena/scores/assets/37311649/2c21b6b1-cc76-4ed7-a6d7-a4d2016fe289)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!TIP]
> Used direct figma side-by-side comparison for UI error detection.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v979`.
