### ISSUE TITLE
Investor Section - Investment Details

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1894]
#### 📝 DESCRIPTION

On this widget, the investor can verify all transactions that he has made to acquire BTA tokens.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/fd0fe38f-52f8-4eb0-9dff-360beee5af5d)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

`betarena_general_data`

| table | columns |
| ----- | --------- |
| betarena_general_data / transaction_history | date + quantity  + bta_price + tier... |

`betarena_general_data   _keypair   investor_tier  `

| table | columns |
| ----- | --------- |
| betarena_general_data / _keypair | tier + data |

**DATA:**

```
Date = date
Type = type
Tier = tier
Discount = betarena_general_data / _keypair | tier + data
Investment = quantity + asset
Tokens = amount
Price = bta_price
```

---

#### 🎏 TRANSLATIONS

`betarena_prod/investors`

| table | columns |
| ----- | --------- |
| investment_details | data |

---

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5095%3A63370&mode=design&t=ALEsqT7swSI4IaNZ-1

**Comment by migbash** [comment]
@jonsnowpt In the design there's a **horizontal scrollbar**, are there other `columns` that are not shown in the desing/UI that need to shown ?

![Image](https://github.com/Betarena/scores/assets/20924663/902641c2-8fb4-4883-a0b7-cf11aa72ffbb)

**Comment by jonsnowpt** [comment]
@migbash 

Not for now, but its a safeguard for the case that we want to show more data in the table without having the need to edit the code.

**Comment by migbash** [comment]
> [!NOTE]
> Preliminary (Stable) Implementation Complete, awaiting `🚀 deployment`.
> Live on `dev` from `v978`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Wrong gray on the columns text;
- [ ] When no values are available, use the design provided;



![Image](https://github.com/Betarena/scores/assets/37311649/f8698032-5f5c-4c72-a0d9-8fe052b6c47b)
![Image](https://github.com/Betarena/scores/assets/37311649/8d56015a-9a24-466d-bb32-cf2e3fcb56d2)
![Image](https://github.com/Betarena/scores/assets/37311649/a87fbd06-3cf8-4208-b009-cb151d2c2886)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!TIP]
> Used direct figma side-by-side comparison for UI error detection.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v979`.

**Comment by jonsnowpt** [comment]
@migbash 

Use the correct message available on `translations_new`; besides that, follow the default design.

```
    "general": {
    "no_information": "Ingen information tillgänglig för tillfället."
          },
```

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> Missing the default message and correct CSS when there is no data.

@jonsnowpt It's exaclty the same as that of the `Vesting-History` and `Referral-History` style and layout, perhaps you don't see it because you have data in the respective `table`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Remove the table bar when there is no information;
- [ ] Add the `no information` message;

**Comment by migbash** [comment]
> Remove the table bar when there is no information;

@jonsnowpt What do you mean by this ? Currently, where there is `no data`, the `table header (column names)` are not shown.

**Comment by jonsnowpt** [comment]
@migbash 

https://betarena.slack.com/archives/D02B1UHEECS/p1706297320355099

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v986`.
