### ISSUE TITLE
Investor Section - Vesting Periods

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1898]
#### 📝 DESCRIPTION

The investor can verify all vesting period details on this widget and reclaim the available tokens.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/5525f763-d632-4098-b62c-119be27a4e1a)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

`betarena_general_data`

| table | columns |
| ----- | --------- |
| investor | data / vesting_periods |

**DATA:**

```
"vesting_periods": {
    "1": {
      "id": 1,
      "available_date": "01/01/24",
      "tokens": "2500",
      "status": "3",
      "wallet": "Main Wallet",
      "distribution_date": "02/01/25",
      "claim_date": "30/01/24",
      "claim_status": "3"
    },
```

---

#### 🎏 TRANSLATIONS

`betarena_prod/investors`

| table | columns |
| ----- | --------- |
| vesting | data |

---

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5095%3A63370&mode=design&t=YC4DVmBXeqxIx2oH-1

**Comment by migbash** [comment]
> [!NOTE]
> Preliminary (Stable) Implementation Complete, awaiting `🚀 deployment`.
> Live on `dev` from `v978`.

**Comment by jonsnowpt** [comment]
@migbash 

Use the default message and CSS when no information is available:



![Image](https://github.com/Betarena/scores/assets/37311649/28c2092a-fa81-47e2-91a9-8827662f954f)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
> Includes `No Widget Data` child component `Modal` corrections.

> [!TIP]
> Used direct figma side-by-side comparison for UI error detection.

**Comment by jonsnowpt** [comment]
@migbash 

Incorrect default message and CSS:

```
    "general": {
    "no_information": "Ingen information tillgänglig för tillfället."
          },
```

![Image](https://github.com/Betarena/scores/assets/37311649/b6ff2c4b-a3fe-4be5-a7c0-a583c48e3e1f)
![Image](https://github.com/Betarena/scores/assets/37311649/cd94c8e3-11ae-4dca-adb3-f87c6340dd42)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
