### ISSUE TITLE
[Bug]: Investor Section - Translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Translations are not being loaded:

![Screenshot 2024-01-10 at 12 10 13](https://github.com/Betarena/scores/assets/37311649/106d8424-9b4b-4036-86fb-aacc0cf59bc2)

### 🤔 Expected Behavior

Translations should work correctly on the different widgets.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Issue has been extended to allow for currently missing **Investor** Section widget translation added to complete respective section.

**Comment by jonsnowpt** [comment]
@migbash 

Added!

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v980`.

**Comment by jonsnowpt** [comment]
- [ ] 1. Incorrect expression;

1.

![Image](https://github.com/Betarena/scores/assets/37311649/f289fb8d-2a62-4be0-95f1-f9523b17d397)

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Added translation to the investment details title widget: `    "widget_title": "Investment Details",`

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Here should be the date:

![Image](https://github.com/Betarena/scores/assets/37311649/818b40a3-7283-4dab-9719-a5d01d01bd19)

**Comment by migbash** [comment]
> Here should be the date:

The date only appears when you set it on the respective table for the target `data row`. In this case being the: `(db) betarena_general_data  > (schema) _keypair > (table) investor_presale > (column) data > (json-property) start_date`. All woking as expected.
