### ISSUE TITLE
Investor Section - Referrals

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1900]
#### 📝 DESCRIPTION

This section allows the investors to check all their data related to the referral process, instructions on how to proceed, and an easy share option.

---

#### 📸 WIDGET IMAGE

![Image](https://github.com/Betarena/scores/assets/37311649/1a3a2f71-0e8c-4ac7-bac9-674d6c78922e)

![Image](https://github.com/Betarena/scores/assets/37311649/b6385803-81c1-428b-b5d7-e91e88062a0e)

---

#### 📱 TARGET PLATFORMS

All versions are supported.

---

#### 🎬 INITIAL STATE

Preloader.

---

### Versions:

All theme versions are supported.

---

#### 💠 WIDGET DATA

➤ **Hasura**

`betarena_general_data`

| table | columns |
| ----- | --------- |
| investor | data / referral_history |

**DATA:**

```
  "referral_history": {
    "1": {
      "id": 1,
      "type": 1,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
    },
    "2": {
      "id": 2,
      "type": 2,
      "bonus_percentage": null,
      "bonus_bta": null,
      "date": null
  }
```

➤ **Firebase Storage**

Referral ID: `referralID`

Referral Link: `https://scores.betarena.com/referralID`

(Only available after a tier of investment is met)

---

#### 🎏 TRANSLATIONS

`betarena_prod/investors`

| table | columns |
| ----- | --------- |
| referral | data |

---

#### 💠 WIDGET INFORMATION

The user, when selecting the "Invite Investors" will access a popup that allows to share on social media. The content and images shared are available in the translations of the widget. `| referral | data |`.

The CTA is only available if the investor is withing one of the investment tiers.

Once the user gets into one of the tiers, the `"active"` info is enabled, as is the access to the CTA.

The downloaded image has QR code that allows access to the score website.

---

Figma Design:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=5110%3A23198&mode=design&t=kSW9m7Y87ER8fV7G-1

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
> Includes `No Widget Data` child component `Modal` corrections for **Referral History**.

> [!TIP]
> Used direct figma side-by-side comparison for UI error detection.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v979`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Incorrect title position:

![Image](https://github.com/Betarena/scores/assets/37311649/9d02babe-57fe-4a89-8379-d9ca3fa87023)

**Comment by migbash** [comment]
> [!NOTE]
> [?] Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v982`.
