### ISSUE TITLE
[Bug]: Investor Section - Video controls and more videos

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The video is not showing the player control that allows to select to move forward or backward, and more videos are being shown:

![Screenshot 2024-01-14 at 15 47 28](https://github.com/Betarena/scores/assets/37311649/ba4e81c9-84de-4ab7-a4fd-6a086dd3f388)
![Screenshot 2024-01-14 at 15 46 57](https://github.com/Betarena/scores/assets/37311649/870ef5f1-a413-4d34-b6d4-1e6e9bfd9f3e)

Also, if possible, make the video player edges round the same way we have on the design:

![Image](https://github.com/Betarena/scores/assets/37311649/7ed3bb52-1206-4f36-9682-51752ca539f7)

### 🤔 Expected Behavior

Add the video controller that allows users to select a specific point to load the video and move forward and backward. Also, if possible, remove the option to check more videos or at least load the videos associated with the Betarena channel.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Take a look if the `https://www.youtube.com/embed/AGIXX306u-Y?rel=1` is acceptable for you, as the available option to show further `relevant` channel videos.

https://developers.google.com/youtube/player_parameters#rel

**Comment by jonsnowpt** [comment]
@migbash 

We can use the following:

`https://www.youtube.com/embed/AGIXX306u-Y?rel=0`

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v980`.
