### ISSUE TITLE
[Bug]: Investor Section - Widget width 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The Widgets width are incorrect.

![Screenshot 2024-01-14 at 15 51 34](https://github.com/Betarena/scores/assets/37311649/b4d2be6a-3381-49a0-a299-a47a3b6a8540)

### 🤔 Expected Behavior

Correct sizes:

![Screenshot 2024-01-14 at 15 53 07](https://github.com/Betarena/scores/assets/37311649/41cd7ff9-0c9c-4d07-9e3e-f999b851f416)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v980`.
