### ISSUE TITLE
[Bug]: Investor Section - Incorrect conversion

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Conversion not working.

![Screenshot 2024-01-14 at 15 57 20](https://github.com/Betarena/scores/assets/37311649/34e004d1-1e9f-499e-bcf8-519d26ce9003)

### 🤔 Expected Behavior

The conversion should be working and live.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Potentially related to the `API` not working correctly from `CoinMarketCap` and/or issues with `overuse` of the API.

**Comment by migbash** [comment]
@jonsnowpt All is working and was working correctly:

![Image](https://github.com/Betarena/scores/assets/20924663/d4dcc1d8-8fab-4741-b0f3-857d77881d4b)

**Comment by jonsnowpt** [comment]
@migbash 

The conversion should be made for each value the user enters, for example:

20 USDT = 19.88 USD

and so on.
