### ISSUE TITLE
[Bug]: Investor Section - Missing presale details

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing all presale details:

![Screenshot 2024-01-14 at 15 58 59](https://github.com/Betarena/scores/assets/37311649/a2ed1b0d-eb4f-4ee3-a4a0-b5a435ee137b)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> The modification of the `data` for the inclusion of different presales objects has broken the logic, hence no data is shwon, as previous data was just a sinlge `object {...}` and now there's a `{ "a": { .. }, "b": { .. }` structure.

**Comment by migbash** [comment]
> [!NOTE]
> Logic has been adjusted and offset to a new table:

- `(db) betarena_general_data > (schema) _keypair > (table) investor_presale`

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v980`.
