### ISSUE TITLE
[Bug]: Investor Section - Section title "Investment Information"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Incorrect height, missing paragraph, and different color / bold.

![Screenshot 2024-01-15 at 08 55 36](https://github.com/Betarena/scores/assets/37311649/bc4ac0eb-df98-4959-8e76-59dfd109f854)

### 🤔 Expected Behavior

Respect Figma design.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v980`.

**Comment by jonsnowpt** [comment]
@migbash 

Still missing the paragraph.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
