### ISSUE TITLE
Investor Section Tier Information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Mssing "." decimals (values). 
- [x] Remove "at"

![Screenshot 2024-01-19 at 11 01 43](https://github.com/Betarena/scores/assets/37311649/10167b58-59aa-4f42-8bb3-f2ab0c0209cd)

### 🤔 Expected Behavior

Have "," between the total investment values and remove the "at" expression.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Should be "." not ",".

**Comment by migbash** [comment]
> [!NOTE]
> [?] Corrected, awaiting `🚀 deployment`.
> Live on `dev` from `v982`.
