### ISSUE TITLE
[Bug]: Investor Section: Invest Box missing Min and Max deposit information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing Min and Max deposit information

![Screenshot 2024-01-26 at 08 36 34](https://github.com/Betarena/scores/assets/37311649/949ab995-c905-4283-b57f-0833dfee29d0)

### 🤔 Expected Behavior

Should have the Min. and Max. Information. Available on the DB table.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v986`.
