### ISSUE TITLE
[Bug]: Investor Section: Investor Wallet scale and scrolling

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The scale should start at 100. Also, the graph should be gradable so that we can move between months since there is at least a 24-month vesting, and investors can keep their BTA even longer in the platform. 

![Image](https://github.com/Betarena/scores/assets/37311649/38aafc11-d627-4993-8931-183a27d92e0d)

### 🤔 Expected Behavior

Verify the possibility that the chart can move forward and backward to give investors access to the full history.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Also, the graph should be gradable so that we can move between months since there is at least a 24-month vesting [..]

@jonsnowpt So should the chart show up-to `24-months` of past data ? Or should there be no limit ?

**Comment by jonsnowpt** [comment]
@migbash  From Feb 2024 forward.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v986`.
