### ISSUE TITLE
[Bug]: Investor Section: Referral Bonus Summary

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

By default, the data is hidden with the no information standard message. Also, the number of referrals is not BTA.

![Screenshot 2024-01-26 at 08 53 31](https://github.com/Betarena/scores/assets/37311649/973062ba-00de-4ba5-9801-a9f332523d88)

### 🤔 Expected Behavior

- [x] Standard Message;
- [x] Remove BTA for the number of referrals;

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v986`.
