### ISSUE TITLE
[Bug]: Investor Section: TGE widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The release date is not present on the "claim" variation.

### 🤔 Expected Behavior

We should keep the information about the release date, check FIGMA example:

![Screenshot 2024-01-29 at 14 57 16](https://github.com/Betarena/scores/assets/37311649/4cd29eb9-178b-4fe9-b6c6-8a0def41285c)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Was only aware of the other `2` designs that are prominent in the design file:

[1] ![Image](https://github.com/Betarena/scores/assets/20924663/5542b080-524e-47e4-adee-93fd0132f04b)

[2] ![Image](https://github.com/Betarena/scores/assets/20924663/d8931d19-bce5-4743-95ae-3d64369cb050)

So, **[2]** is invalid design ?

Also, I change the `design` to use the `(button) claim` + `(countdown) release date` (as per issue), probably would need a design for displaying an error message for the user, that the `claim` is not yet available.

**Comment by jonsnowpt** [comment]
@migbash 

Correct designs:

1. Not available to claim with a defined date for TGE:

![Screenshot 2024-01-30 at 08 52 49](https://github.com/Betarena/scores/assets/37311649/81ccd6b6-6c4d-48b7-94de-b5a2b2e832be)

2. Ready to be claimed with the information of the date it was made available:

![Screenshot 2024-01-30 at 08 54 00](https://github.com/Betarena/scores/assets/37311649/d263ec60-a0aa-43cb-8c5a-f4297cf41be1)

3. Already claimed:

![Screenshot 2024-01-30 at 08 56 04](https://github.com/Betarena/scores/assets/37311649/7e62944d-7faa-4427-8fb3-6fcd96e28426)


The design had some inconsistencies and led you in the wrong way.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!NOTE]
> Live on `dev` from `v990`.

**Comment by jonsnowpt** [comment]
@migbash 

In this case, the `claim` CTA does not exist:


![Uploading Screenshot 2024-01-30 at 18.12.49.png…]()

**Comment by migbash** [comment]
> In this case, the claim CTA does not exist:

@jonsnowpt Cannot see the snapshot: 

![Image](https://github.com/Betarena/scores/assets/20924663/28bb54d7-ccb3-4461-b0e3-c07d41c91cad)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v995`.
