### ISSUE TITLE
[Bug]: Investor Section: Vesting Periods status icons

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The status icons are not present at the time.

![Screenshot 2024-01-29 at 15 41 05](https://github.com/Betarena/scores/assets/37311649/14d5909d-d982-473b-961d-dc81d46851f9)

### 🤔 Expected Behavior

- [x] Add the correct icon for every status;

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!NOTE]
> Live on `dev` from `v990`.
