### ISSUE TITLE
[Bug]: Investor Section Light Theme incorrect Background size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The background-size is incorrect, probably because of the invest box behavior.

![Screenshot 2024-01-29 at 15 45 08](https://github.com/Betarena/scores/assets/37311649/5fffbc5a-7d3d-4815-8f35-8a4c0de36adb)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!NOTE]
> Live on `dev` from `v990`.
