### ISSUE TITLE
[Bug]: Investor Section Light Theme CSS corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. Invest Box Missing the color glow;
- [x] 2. Tier Pricing: 2. Missing the bottom message and incorrect position;
- [x] 3. Investment information title: Incorrect color
- [x] 4. Refer tiers missing the CTA glow;
- [x] 5. FAQ responses only the first has the correct color;
- [x] 6. link presale CTA missing the glow;

1.

![Screenshot 2024-01-29 at 16 14 08](https://github.com/Betarena/scores/assets/37311649/29035a90-6163-4211-90ab-3f6a303a5701)

2.

![Screenshot 2024-01-29 at 16 17 06](https://github.com/Betarena/scores/assets/37311649/ec51f6bb-8a9e-4e09-bc18-632f4e4af08a)

3.

![Screenshot 2024-01-29 at 16 18 39](https://github.com/Betarena/scores/assets/37311649/17db4116-3c56-4809-9e5a-d5119f9a2aeb)

4.

![Screenshot 2024-01-29 at 16 21 38](https://github.com/Betarena/scores/assets/37311649/25614c14-631f-4cbf-baf2-b5390947d0d0)

5.

![Screenshot 2024-01-29 at 16 22 47](https://github.com/Betarena/scores/assets/37311649/7b5ac0c0-1cf8-4159-bc17-291ccd3e2b1a)

6.

![Screenshot 2024-01-29 at 16 23 39](https://github.com/Betarena/scores/assets/37311649/bb9cafb1-42f6-43b4-a40a-85c41218eea2)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

> [!NOTE]
> Live on `dev` from `v990`.
