### ISSUE TITLE
[FEATURE-I-W]: Claim Pop-Up

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1936]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 📝 Description

Addition of **(Modal) PopUp** for Widgets that make use of a respective **claim** action for movement of users wallet internal **investor funds**, within their account (primarily to **main wallet** displacement).

Using the existing `competitions` section modal.

To be applied to the widget(s):
- TGE
- Vesting Period

### Feature target platform availability

- [x] 📱 Mobile
- [x] 💻 Tablet
- [x] 🖥️ Laptop/Desktop

### 📸 Feature Request Image

![Image](https://github.com/Betarena/scores/assets/20924663/b627e21e-09f9-4111-869c-8b04f8b18755)

### 💠 Feature required data

- `(db) betarena_prod > (schema) investors > (table) translation_new`

![Image](https://github.com/Betarena/scores/assets/20924663/c4fe1d32-1b54-4b10-94d0-ffb39a8cf96d)

**Comment by migbash** [comment]
> @jonsnowpt Should they also not allow for `background` scroll when the `pop-up's` are active ?

**Comment by jonsnowpt** [comment]
@migbash 

by default, when a pop-up is visible, the background scroll should be disabled, also in this case.

**Comment by migbash** [comment]
> [!NOTE]
> Implemented, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v995`.

**Comment by jonsnowpt** [comment]
@migbash 

Missing the amount information on the popup.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v996`.
