### ISSUE TITLE
[Bug]: Investor Section: Invest  Box Wallet Connect Initial position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When connecting the wallet the invest box gets back to the default position.

### 🤔 Expected Behavior

The invest box should keep its position.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Caused by `WalletConnect` overrides.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v995`.
