### ISSUE TITLE
[Bug]: Investor Section: Refer investors invite popup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Both the download image and copy link aren't working.

![Screenshot 2024-01-31 at 09 05 19](https://github.com/Betarena/scores/assets/37311649/a99a68ef-fba4-4a15-ac5d-69993b3db2b7)

### 🤔 Expected Behavior

Users should be able to download the image and copy the link after they have the first investment.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [..] download the image and copy the link [..]

@jonsnowpt Donwload the `image` in the `pop-up` ? And copy the link for their `referral-code` ?

> [..] after they have the first investment.

@jonsnowpt It should be only available for the (1) download and/or (2) link copy after they have made an intiail first investment.

**Comment by jonsnowpt** [comment]
@migbash 

No, this is the image:

https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Finvestors%2Fshare_referral_betarena_qrcode.png?alt=media&token=510238e7-cb5a-48b4-9fc3-762be3a1bddc

Yes, those options should only be visible after the threshold is met.

**Comment by migbash** [comment]
> [..] and copy the link [..]

@jonsnowpt for the `image` with the `QR` code ? Or link with their `referral code` ?

**Comment by jonsnowpt** [comment]
@migbash 

The link is with their `referral code`

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v995`.

**Comment by jonsnowpt** [comment]
@migbash 

We have to let go of the download image option since we had to generate the QR code for each user and add it to the image if we just supply a generic one, the `referral` code is not added.

**Comment by migbash** [comment]
> [!Note]
> Live on `dev` from `v995`.

**Comment by jonsnowpt** [comment]
@migbash 

None of the social networks work.

**Comment by migbash** [comment]
> None of the social networks work.

@jonsnowpt Should be `sharable` link with the users `referral-code` ? Or just redirect to the `Betarena Social Pages` respectively ?

**Comment by jonsnowpt** [comment]
@migbash 

sharable link with the users referral-code

**Comment by migbash** [comment]
- Facebook :|: https://developers.facebook.com/docs/sharing/reference/send-dialog
- Twitter (X)
- WhatsApp
- Telegram
- Reddit

**Comment by jonsnowpt** [comment]
@migbash 

1. Social link incorrect;
2. Whats app message is not getting the link at all;

1.

https://twitter.com/intent/tweet?text=Join%20the%20Betarena%20Presale%20and%20Be%20Part%20of%20the%20Future%20of%20Sports%20Content.%20Join%20Now%20for%20Exclusive%20Rewards!&url=scores.betarena.com?referralId=https://betarena-scores-platform.herokuapp.com?referralId=REF400802

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Whatsapp link is missing.
