### ISSUE TITLE
[Bug]: Investor Section Mobile CSS corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. Lower height;
- [x] 2. Wrong height;
- [x] 3. Incorrect progress percentage position;
- [x] 4. Video incorrect format and incorrect order;
- [x] 5. Incorrect invest box title position: Crypto and Fiat options seem to have different sizes, and incorrect height after CTA;
- [x] 6. Incorrect title size, paragraph and bold color;
- [x] 7. Investors wallet add "." in the total amount, remove the chart left legend and move it to the left;
- [x] 8. TGE widget needs revision;
- [x] 9. Investor wallet missing the `copy`;
- [x] 10. Arrows incorrect colors and missing the status CSS;
- [x] 11. Refer investors Correct CSS of the tiers and arrow color;
- [x] 12. Referral history, arrow color;
- [x] 13. FAQ incorrect content position;
- [x] 14. Border do not exist anywhere in the platform;

1.

![Screenshot 2024-01-31 at 09 11 02](https://github.com/Betarena/scores/assets/37311649/9071fb3d-3385-4729-9364-342316be596f)

2.

![Screenshot 2024-01-31 at 09 15 26](https://github.com/Betarena/scores/assets/37311649/60d0658e-02a8-4b87-95d3-8d622e86b28e)

3.

![Screenshot 2024-01-31 at 09 16 27](https://github.com/Betarena/scores/assets/37311649/f965044b-c3d3-46aa-b80c-b85f034a2c8f)

4.

![Screenshot 2024-01-31 at 09 18 15](https://github.com/Betarena/scores/assets/37311649/27cf0bba-2031-4669-9c74-6f08a9d0b2ef)

5.

![Screenshot 2024-01-31 at 09 19 55](https://github.com/Betarena/scores/assets/37311649/3d973e9a-f0ce-48f8-8f97-ad502aa6095f)

6.

![Screenshot 2024-01-31 at 09 29 22](https://github.com/Betarena/scores/assets/37311649/95b72e38-2a3a-49b8-9c73-3f918c5f8cf9)

7.

![Screenshot 2024-01-31 at 09 30 45](https://github.com/Betarena/scores/assets/37311649/acf7a07b-8a58-4df2-b8ab-db7b3313769e)

8.

![Screenshot 2024-01-31 at 09 34 33](https://github.com/Betarena/scores/assets/37311649/1c3c2678-8cf5-4fb9-9041-54cef4cb5374)

9.

![Screenshot 2024-01-31 at 09 36 34](https://github.com/Betarena/scores/assets/37311649/653a2abc-ed87-4be4-87dc-61f31b2f8ce4)

10.

![Screenshot 2024-01-31 at 09 38 37](https://github.com/Betarena/scores/assets/37311649/c4839fd3-ef5b-412b-ba61-7af45ae3b6eb)

11.

![Screenshot 2024-01-31 at 09 40 49](https://github.com/Betarena/scores/assets/37311649/c488df1a-4423-41db-96f5-8da3257a1382)

12.

![Screenshot 2024-01-31 at 09 44 10](https://github.com/Betarena/scores/assets/37311649/9d740130-2eb5-4f0e-b7f3-7ab82757e24d)

13.

![Screenshot 2024-01-31 at 09 45 08](https://github.com/Betarena/scores/assets/37311649/b6058c39-030e-42f0-bc3a-eb2cdc193baa)

14.

![Screenshot 2024-01-31 at 09 47 22](https://github.com/Betarena/scores/assets/37311649/2f91457d-4489-45d4-b916-d82353d299c6)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` from `v997`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 3. Still incorrect;
- [ ] 11. Alignment still incorrect;
- [ ] 15. Missing the bolds;
- [ ] 16. Should start in Feb, not March;

11.

![Screenshot 2024-02-04 at 18 36 08](https://github.com/Betarena/scores/assets/37311649/e5a120cd-b696-426d-a642-350e6888fe0c)


15.

![Screenshot 2024-02-04 at 18 29 41](https://github.com/Betarena/scores/assets/37311649/e25ba34e-412c-48d1-83fc-b87f804574fc)

16.

![Screenshot 2024-02-04 at 18 31 50](https://github.com/Betarena/scores/assets/37311649/a35863f3-ed0a-4cca-b05f-4d2bf2a881dd)

**Comment by migbash** [comment]
> [!NOTE]
> 15. Missing the bolds;
> A `Firefox` issue.

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

3. Alignment still incorrect;

3.

<img width="544" alt="Screenshot 2024-02-07 at 17 41 08" src="https://github.com/Betarena/scores/assets/37311649/abbcb9fc-2813-46a4-b8a9-afe5e6b327d9">
<img width="534" alt="Screenshot 2024-02-07 at 17 40 58" src="https://github.com/Betarena/scores/assets/37311649/7a000d89-7246-496c-8137-a4c81d064058">

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.
