### ISSUE TITLE
[Bug]: DEV Speed and missing data / Broken

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The latest node implementation broke the DEV performance and data.

- [x] Fixtures loading very slowly;
- [x] News and Media stopped loading;
- [x] Tournaments information missing;

Link examples:

https://betarena-scores-platform.herokuapp.com/football/chaves-farense-18870483

https://betarena-scores-platform.herokuapp.com/football/portugal/liga-portugal

All the platforms are sluggish.

Other issues are probably impossible to verify one by one.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!Note]
> Corrected, awaiting `🚀 deployment`.
