### ISSUE TITLE
[Bug]: Investor Section: FAQ Desktop CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The CSS for the questions title is incorrect:

![Screenshot 2024-02-04 at 18 48 04](https://github.com/Betarena/scores/assets/37311649/bc8b79c8-eaee-4ae7-bbc1-cd2afe4fa8d2)

### 🤔 Expected Behavior

Check Figma.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [Note]
> Corrected, awaiting `🚀 deployment`.
