### ISSUE TITLE
[Bug]: Investor Section - Padding issue on mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Padding on the right side:

https://github.com/Betarena/scores/assets/37311649/f3653e01-7c4f-4dce-9f40-ad6d8face6f7

### 🤔 Expected Behavior

No padding "overflow"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Can't seem to replicate it, what resolution (dimensions) is this on ?

**Comment by jonsnowpt** [comment]
@migbash 

Still happening

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
