### ISSUE TITLE
[Bug]: Authors: Corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. Laptop title change font-weight from 600 to 500;
- [x] 2. Missing the translation option on the header;
- [x] 3. Change the Betarena Logo, Sign-In, and Theme option to have the same size and positioning the same way we have on the rest of the platform;
- [x] 4. Missing the placeholder on loading;
- [x] 5. Avatar animation is not working correctly, example bellow;
- [x] 6. Sign-in does not work;
- [x] 7. The default theme is not correct;
- [x] 8. Change the font-weight of the tags from 500 to 400 on laptop;
- [x] 9. Tags are getting repeated;
- [x] 10. Tags on laptop should be divided by line not the swipe approach;
- [x] 11. Wrong size on description, missing separation and incorrect colors;
- [x] 12. Change content font-weight from 400 to 300 on laptop;
- [x] 13. Add spaces on paragraphs;

5. 

https://github.com/Betarena/scores/assets/37311649/eb8f258c-5121-455f-bf99-23d6454fcd80

11.

<img width="470" alt="Screenshot 2024-02-07 at 08 13 29" src="https://github.com/Betarena/scores/assets/37311649/2b1946e1-6535-4089-84e6-46e6d08286fa">

13. 

<img width="755" alt="Screenshot 2024-02-07 at 08 20 55" src="https://github.com/Betarena/scores/assets/37311649/9cbfb9a7-7801-4818-af66-14f33d11ec70">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Laptop title size is 38;
- [ ] 2. Laptop text size change from 20 to 18;
- [ ] 3. Logout should keep the user on the same page not redirect to the homepage;
- [ ] 4. Tags on laptop should be divided by line not the swipe approach;
- [ ] 5. Language selection not working;
- [ ] 6. AI icon incorrect size;
- [ ] 7. HTML content not rendered


7.

![Image](https://github.com/Betarena/scores/assets/37311649/a190d478-cf2f-4d7c-b30f-b9bb94f9e11f)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1036`

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Link that does not exist anymore is not correctly removed (https://betarena-scores-platform.herokuapp.com/a/betarena-tenis-br/palpite-vaishnavi-adkar-sahaja-yamalapalli-vs-dalila-jakupovic-sabrina-santamaria-2023-2024-dicas-de-apostas-para-o-wta-125-mumbai-women-double-8yomojf34kyzq0j1707239141)
- [ ] 2. Reviewed the issues reported before and removed the checkmarks;
- [ ] 3. Hover not working in the dropdown;
- [ ] 4. Not able to close the dropdowns when clicking outside the dropdowns area, both for languages and profile;
- [ ] 5. The horizontal scroll should not exist;
- [ ] 6. The tags movement/effect should be easing, check YouTube example;
- [ ] 7. Months translations are not working;
- [ ] 8. Reading time and date published are not working;
- [ ] 9. Authors position incorrect, AI icon size still incorrect, space between the the reading time from the author still incorrect;
- [ ] 10. Mobile default theme incorrect, missing options, and logo not proportional;


3.

![Image](https://github.com/Betarena/scores/assets/37311649/c2728f88-e1cf-4005-8895-d2fa654b0f03)

5.

![Image](https://github.com/Betarena/scores/assets/37311649/63a6d33d-f706-4103-ae56-f132dfc3fedd)

8.

![Image](https://github.com/Betarena/scores/assets/37311649/1448638f-df6e-4646-8cdc-0661e7bdaf83)

9.

![Image](https://github.com/Betarena/scores/assets/37311649/3903a1ea-cdab-4f9b-8b93-c20fd08a0558)

**Comment by migbash** [comment]
> 5. The horizontal scroll should not exist;

@jonsnowpt The `scroll bar` you mean ? Or the _ability_ to scroll horizontally should be disabled, and only allowed with `buttons` ?

**Comment by jonsnowpt** [comment]
@migbash 

Scrollbar.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. Missing the  about content on Laptop;
- [ ] 2. Missing the H1 title in the HTML;
- [ ] 3. For some reason the section options on the header stoped to respect the language option;
- [ ] 4. The hover effect should be the same we have on the translations;
- [ ] 5. Tags are being repeated;
- [ ] 6. Subscribe option on the footer is not working on all platform;
- [ ] 7. Mobile default theme continue to be incorrect;
- [ ] 8. Mobile: Signing in and then signing out gives a undefined error and from that point cant access the author content anymore with an internal server error;
- [ ] 9. Remove the language option on mobile;
- [ ] 10. Mobile: The back option and avatar should always be visible with two different behaviours, if using the PWA should send the user back to the previous screen, if not using the PWA it should redirect the user to the Homepage;


1.

![Image](https://github.com/Betarena/scores/assets/37311649/a923352f-b1b6-4f06-a28d-ed0bec823bdc)

2.

![Image](https://github.com/Betarena/scores/assets/37311649/0a16dd4e-7569-492b-9556-40861dadf354)

3.

![Image](https://github.com/Betarena/scores/assets/37311649/ad1573ac-b7f1-4e57-8552-c0bc934c3bee)

4.

![Image](https://github.com/Betarena/scores/assets/37311649/6d80ea48-8999-4109-a272-01bf855f6c45)

8.

![Image](https://github.com/Betarena/scores/assets/37311649/4d272994-7ceb-4f5b-a7de-c193a0701cee)

10.

![Image](https://github.com/Betarena/scores/assets/37311649/638b3b2d-a20d-46de-a707-09fb69da66ef)

**Comment by migbash** [comment]
>  2. Missing the H1 title in the HTML;

@jonsnowpt The `title` is set to `<h1>`, do you mean it's missing from the `SEO` ?

**Comment by jonsnowpt** [comment]
@migbash 

Yes, missing from the SEO.

> What is the mobile default theme you are referring to ?

Dark theme.

**Comment by jonsnowpt** [comment]
- [ ] 1. Horizontal width is very different from Figma on the laptop version;
- [ ] 2. Football information with icon and number of matches disappeared from the header on laptop and mobile;
- [ ] 3. Not able to do anything after signout and the signing option disappear to show the default avatar;
- [ ] 4. The options should be visible on scroll has shown on the design, continue to be fixed on the top;
- [ ] 5. Mobile: The top is inverted;
- [ ] 6. Mobile: Wallet address not visible on mobile;
- [ ] 7. Mobile: Incorrect margins
- [ ] 8. Mobile: Avatar section is incorrect;
- [ ] 9. Tablet: Keep the language selection;


1.

![Image](https://github.com/Betarena/scores/assets/37311649/efb43621-2063-4b73-b870-2a1cc98d9f06)

2.

![Image](https://github.com/Betarena/scores/assets/37311649/a79ba7d0-01ad-47ab-8669-ca45cc0bee84)

3.

https://github.com/Betarena/scores/assets/37311649/3bf271ed-81d2-4280-b9fb-8c9cadbed9a2

5.

![Image](https://github.com/Betarena/scores/assets/37311649/05fc16c6-b203-4e5a-bbc7-d347be853a68)

7.

![Image](https://github.com/Betarena/scores/assets/37311649/1f277fd8-a380-4dd0-8f53-bbaae9889ed0)

8.

![Image](https://github.com/Betarena/scores/assets/37311649/40438b7e-7ba4-4bd0-bbf2-78f6f71267b5)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 15. The Avatar position and maybe the size are not correct on mobile;
- [ ] 16. Incorrect height space is smaller;
- [ ] 17. In the PWA version, we don't need the blur; check the example video, WEB the top can be fixed.
- [ ] 18. Preloaders have incorrect sizes and positioning;


15. 

![Image](https://github.com/Betarena/scores/assets/37311649/1d1b0cb7-597e-42c4-aae1-1d30b124cc9b)

16. 

![Image](https://github.com/Betarena/scores/assets/37311649/91d36194-ac57-458c-b924-16fe984d35ae)

17. 

https://github.com/Betarena/scores/assets/37311649/cd987233-58f1-4382-a449-34020a0e205b

18. 

![Image](https://github.com/Betarena/scores/assets/37311649/89d22b84-2851-432b-8ac7-d1f09b6ac155)

**Comment by jonsnowpt** [comment]
@Izobov 

On the desktop and tablet version the placeholder has too manny title lines, please check:


![Image](https://github.com/Betarena/scores/assets/37311649/cc916eb4-c28d-4bc4-aeee-a3f9018cc0c7)
