### ISSUE TITLE
[Bug]: Investor Section : Invest box only numbers

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, letters and other characters are being allowed on the investor box:

![Screenshot 2024-02-09 at 17 07 51](https://github.com/Betarena/scores/assets/37311649/23092605-5558-4ec0-bda3-1b330306ae30)

### 🤔 Expected Behavior

Only numbers are allowed.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
Already addressed issue in the past :|: https://github.com/Betarena/scores/issues/1882

**Comment by jonsnowpt** [comment]
@migbash 

Cant we just show the keypad on mobile:


![image](https://github.com/Betarena/scores/assets/37311649/375dcc79-d86f-44ac-b512-d4fe9aff27c4)

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1009`
