### ISSUE TITLE
[Bug]: Investor Section :  Mobile version not loading

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Not able to access the investor section on mobile:

![Screenshot 2024-02-10 at 11 31 18](https://github.com/Betarena/scores/assets/37311649/83eef0b1-5514-494f-9ffb-497944edc123)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Not able to access the investor section on mobile:

![Image](https://github.com/Betarena/scores/assets/20924663/bb7d660f-20f9-426f-a8d2-2c31fe72cc5a)

@jonsnowpt Is the `snapshot` related to the `mobile` issue ? The snapshot shown is due to the incorrect translation in respective `database`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version v1008
