### ISSUE TITLE
[Bug]: Investor Section : Fiat / Crypto option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Fiat button/option chosen even when moving on with crypto:

![Screenshot 2024-02-10 at 12 03 12](https://github.com/Betarena/scores/assets/37311649/f0205ee0-3a00-48f2-9497-0494a39b3ea5)

### 🤔 Expected Behavior

The hover should be kept on the crypto option even after selecting Fiat.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1009`
