### ISSUE TITLE
[Bug]: Investor Section : Invest box Min. Amount

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, there is no message or block for minimum amounts.

![Screenshot 2024-02-10 at 12 05 38](https://github.com/Betarena/scores/assets/37311649/4d2b6815-8a4a-40be-9319-b935cc2cb316)

### 🤔 Expected Behavior

The investor should get a message that he needs to invest a minimum amount if one of the conditions are not met:

- [x] Already have a minimum investment made;
- [x] If no investment has been made before the new investment must be at least the minimum amount in this case 2500.

Added the translations and variable to the translations:

`minimum_amount_request`

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`

**Comment by jonsnowpt** [comment]
@migbash 

Not working at this time, Im able to proceed even without meeting the minimum criteria.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

No message is being displayed, and I'm able to invest below the minimum.

https://betarena.slack.com/files/U04MANUB3/F06JMRC3B1B/screenshare_-_2024-02-14_9_09_16_am.webm

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`

**Comment by jonsnowpt** [comment]
@migbash 

The minimum amount is incorrect: 

![Screenshot 2024-02-16 at 18 25 21](https://github.com/Betarena/scores/assets/37311649/110d99cc-2883-4528-8000-6b46af89c579)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
