### ISSUE TITLE
[Bug]: Investor Section : Header incorrect z_index

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Header incorrect z_index:

![Screenshot 2024-02-10 at 12 20 14](https://github.com/Betarena/scores/assets/37311649/ee9ebffa-4594-4065-986f-aa2915635641)

### 🤔 Expected Behavior

Should be bellow the overlay (this has already been corrected a few times)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected through [#1957](https://github.com/Betarena/scores/issues/1957)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1009`
