### ISSUE TITLE
[Bug]: Investor Section :  Not able to close popup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Not able to select "OK" and close the "popup"

![Screenshot 2024-02-10 at 12 22 06](https://github.com/Betarena/scores/assets/37311649/110a2186-6ce4-41e8-a832-87d350f3906a)

### 🤔 Expected Behavior

Should be able to close the "popup"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1009`
