### ISSUE TITLE
[Bug]: Investor trigger / event had not effect on the investor data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

No data has been populated on the investor table after running the trigger:

![Screenshot 2024-02-10 at 13 05 27](https://github.com/Betarena/scores/assets/37311649/9f73f072-8c8f-452b-a417-f8011872240c)

It has added the tokens directly to the `main_wallet`

![Screenshot 2024-02-10 at 13 06 51](https://github.com/Betarena/scores/assets/37311649/1eaae39e-f837-4a87-b147-d561ff59814a)

### 🤔 Expected Behavior

Should have populated all data into the investor table.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Issue was due to the use of the hard-coded values being used for the `Buy BTA` action.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version v1008
