### ISSUE TITLE
[Bug]: Investor Section : Invest box terms on Fiat

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

At this time, the investor is able to access the Fiat investment without checking the terms and disclaimers option.

![Screenshot 2024-02-10 at 19 07 04](https://github.com/Betarena/scores/assets/37311649/7a2465b1-5da2-464e-9b40-b03d87967837)

### 🤔 Expected Behavior

The investor must check the option to be able to move forward.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
