### ISSUE TITLE
[Bug]: Investor Section : Transfer in progress

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The transfer in progress is not being shown.

### 🤔 Expected Behavior

The popup should be shown during the process.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Has been addressed as part of the issue [1955](https://github.com/Betarena/scores/issues/1955)

**Comment by migbash** [comment]
> [!NOTE]
> Has been addressed as part of the issue [1955](https://github.com/Betarena/scores/issues/1955)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
