### ISSUE TITLE
[Bug]: Investor Section : Transaction information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. Quantity is the total sum used, in this case 2500 USDC;
- [x] 1. Amount is the sum of BTA tokens received, in this case 3125;
- [x] 1. Description should be the presale title, in this case, "Private Presale";
- [x] 2 .No erc20 wallet was used;
- [x] 3. Incorrect BTA price;
- [x] 4. Missing tier information;

1.

![Screenshot 2024-02-10 at 19 20 37](https://github.com/Betarena/scores/assets/37311649/2cff8265-35f0-4b71-a290-a2be8c1b3d9c)

2. 

![Screenshot 2024-02-10 at 19 22 51](https://github.com/Betarena/scores/assets/37311649/8e42dfec-b6cc-49b4-a3d2-eb0aea4cdc41)

3.

![Screenshot 2024-02-10 at 19 23 46](https://github.com/Betarena/scores/assets/37311649/71647d2c-2ab0-4366-903d-9c7e88bb6c34)

4.

![Screenshot 2024-02-10 at 19 24 10](https://github.com/Betarena/scores/assets/37311649/fa832d05-4b25-47db-891e-118743f04b80)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
