### ISSUE TITLE
[Bug]: Investor Section : Incorrect investment details

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] 1. The graph seems to be showing 2023 at first and not 2024;
- [x] 2. The total `TGE` amount is incorrect;
- [x] 3. Missing the tier icon and info, the investment was 2500 USDC, are the conversion being considered?, BTA price is incorrect;
- [x] 4. Period should start at "1", I Cant understand the first date, less decimals, the status do not seem correct and missing icons, distribution and claiming data is not correct, and the claim CTA should not be visible at this time.
- [x] 5. Missing the referral link;
- [x] 6. Unknown referred bonus;

1.

![Screenshot 2024-02-10 at 19 28 00](https://github.com/Betarena/scores/assets/37311649/0bf69495-6054-4024-b34e-57d41539fa12)

2.

![Screenshot 2024-02-10 at 19 29 44](https://github.com/Betarena/scores/assets/37311649/bdd4d8f1-8ef0-4cec-93e3-19554585469a)

3.

![Screenshot 2024-02-10 at 19 30 03](https://github.com/Betarena/scores/assets/37311649/2ddae13a-f3a5-445c-b95b-0008935000a7)

4.

![Screenshot 2024-02-10 at 19 38 50](https://github.com/Betarena/scores/assets/37311649/29576a3f-ef33-425c-82f6-96de33b8aa59)

5.

![Screenshot 2024-02-10 at 19 37 37](https://github.com/Betarena/scores/assets/37311649/f40f63fc-8c11-45cc-80be-9ab466e03f74)

6.

![Screenshot 2024-02-10 at 19 40 30](https://github.com/Betarena/scores/assets/37311649/53a2a6c7-5851-4222-be5a-c4cb8aa9188a)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> 2. The total TGE amount is incorrect;

Correction of `firebase/functions`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
