### ISSUE TITLE
[Bug]: Invalid Exchange Rate

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1963]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 🐞 Describe the bug

The exchange rate is invalid, in that it is not (or appears to not be) following the correct exchange rate when (for example `USDC (does not equal) = 1 USD`.

### 🤔 Expected Behavior

The `USDC = 1 USD = 1 BTA` should reflect in the change of the exhcange rate for the target cryptocurrency.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [x] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> All appears to be fine, other that the user and or data did not reflect the correct exchange amount due to `decimal places` being incorrectly configured.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`

**Comment by migbash** [comment]
@jonsnowpt Can this be closed ?

**Comment by jonsnowpt** [comment]
@migbash 

It's not working at this time.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1030`
