### ISSUE TITLE
[Bug]: Header and widgets duplicate appear. Blicking. 

### ISSUE THREAD

**Issue by ihardz** [Betarena/scores#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

https://github.com/Betarena/scores/assets/31627738/050a7dfe-ce32-402e-8194-034a4384455b

Screenshot:
![1707563451110](https://github.com/Betarena/scores/assets/31627738/1f92fd60-8f06-4279-b14c-792b4dccebd3)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

### Steps To Reproduce

1. Open the app on mobile 
2. click `Sign In` button and then click outside of the Login popup so that it should dissapear.

### Anything else?

1. Looks like it is reproduced when there are `Live `matches
2. Additional factor: possible setTimeout or setInterval impact

**Comment by jonsnowpt** [comment]
Resolved.
