### ISSUE TITLE
[Bug]: Investor Section : Mobile alert

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Alert of missing requirement not visible:

https://github.com/Betarena/scores/assets/37311649/9b74adfd-9ed1-4217-a90e-afd6b4c320b2

### 🤔 Expected Behavior

The user should be directed to the missing requirement and able to read all message.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by jonsnowpt** [comment]
@migbash 

Now the alert on the desktop is out of place, and the screen tilts:

https://github.com/Betarena/scores/assets/37311649/2026822f-b464-48e2-b466-b8ae4cbb585e

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
