### ISSUE TITLE
[Bug]: Investor Section : Round countdown

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Showing 4 squares with information:

![IMG_23FE187F0A68-1](https://github.com/Betarena/scores/assets/37311649/4b5eeb49-03c9-460c-8dc3-8f4814e16f51)

### 🤔 Expected Behavior

We should limit to only 3. So in this case the information viewed would be:

01d : 08h : 38m

Just that.

The hours, minutes, and seconds are only when we are less than 24 hours.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`

**Comment by jonsnowpt** [comment]
@migbash 

Still missing the days:

![Screenshot 2024-02-13 at 14 32 06](https://github.com/Betarena/scores/assets/37311649/85f03505-1365-4200-a25c-98ac6279f7b3)

In this case, it should be:

2d 9h 27m

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
