### ISSUE TITLE
[Bug]: Investor section Currency search

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Showing the search at this time:

![Screenshot 2024-02-11 at 15 23 42](https://github.com/Betarena/scores/assets/37311649/0dcbd824-8aa0-431f-91bf-42128f0fedaf)

### 🤔 Expected Behavior

Since we have two currencies allowed, there is no need for the search; we may disable it.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
