### ISSUE TITLE
[Bug]: Investor Section : Cryptocurrency selection missing translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Cryptocurrency selection missing translation

![IMG_31D1FEC616FE-1](https://github.com/Betarena/scores/assets/37311649/d78b264c-25f7-4643-945a-274031371ae8)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing translation from `(db) betarena_prod > (schema) investors > (table) translation_new > (column) data`

**Comment by jonsnowpt** [comment]
@migbash 

Added:

`crypto_selection":"Select Crypto Currency`

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
