### ISSUE TITLE
[Bug]: Investor Section : Tiers translations missing "months"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Months translation is missing:

![Screenshot 2024-02-11 at 15 43 10](https://github.com/Betarena/scores/assets/37311649/b891088e-9b6b-48ec-b2bc-cab5abc0b552)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing translation from `(db) betarena_prod > (schema) investors > (table) translation_new > (column) data` of just the `term` for **months**.

**Comment by jonsnowpt** [comment]
@migbash 

Added:

`months":"months`

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
