### ISSUE TITLE
[Bug]: Investor Section : Tiers value spacing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Values with an unnecessary line break.

![IMG_274F1791EA3A-1](https://github.com/Betarena/scores/assets/37311649/43a53f27-b6e5-413e-8a75-bfc8ee830a37)

### 🤔 Expected Behavior

Should be in one line.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
