### ISSUE TITLE
[Bug]: Investor section : Investor wallet missing translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing widget title and months translations:

![Screenshot 2024-02-11 at 15 47 15](https://github.com/Betarena/scores/assets/37311649/8983f6bd-15c8-4b73-81fd-9452fe063e1a)
month

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing translation from `(db) betarena_prod > (schema) investors > (table) translation_new > (column) data`

**Comment by jonsnowpt** [comment]
@migbash 

Added:

    `"title_wallet":"Investor Wallet"`

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
