### ISSUE TITLE
[Bug]: Investor Section : TGE missing translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the date translation:

![Screenshot 2024-02-11 at 15 48 54](https://github.com/Betarena/scores/assets/37311649/89d80044-76f0-483e-b7de-206ec077ba66)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing translation from `(db) betarena_prod > (schema) investors > (table) translation_new > (column) data`

**Comment by jonsnowpt** [comment]
@migbash 

Added:

`"date_title_2": "Announced Soon",`

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
