### ISSUE TITLE
[Bug]: Investor Section : Investment details missing translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing translations:

![Screenshot 2024-02-11 at 15 50 33](https://github.com/Betarena/scores/assets/37311649/9444482b-bb9c-491c-8408-c23f2bdbc74f)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
