### ISSUE TITLE
[Bug]: Investor Section wallet information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the wallet information:

![Screenshot 2024-02-11 at 15 51 45](https://github.com/Betarena/scores/assets/37311649/f45ada8c-4258-4ab9-8b63-6724235b9f51)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
