### ISSUE TITLE
[Bug]: Investor Section : Vesting period translations missing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing translations:

- [x] Claim CTA;
- [x] Detailed information;

![Screenshot 2024-02-11 at 15 54 08](https://github.com/Betarena/scores/assets/37311649/569d26b6-67b1-4f17-a577-829354dcf334)
![Screenshot 2024-02-11 at 15 53 26](https://github.com/Betarena/scores/assets/37311649/72f160f3-c233-4bf8-b661-464a97caaad8)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1010`
