### ISSUE TITLE
[Bug]: Investor Section : Referral information missing translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing translations on referred and referral:

![IMG_DD477DE25C6F-1](https://github.com/Betarena/scores/assets/37311649/0c66bfd6-145d-4482-b115-3f1e1d2bbad6)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing translation from `(db) betarena_prod > (schema) investors > (table) translation_new > (column) data`.

Require for inidividual translation terms of `You recieve` and `Referred`.

**Comment by jonsnowpt** [comment]
@migbash 

Added:

```
      "receive":"Receive",
      "referred":"Referred"
```

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Not able to check more levels, the dropdown does not work:

![IMG_F7DE1DD8467F-1](https://github.com/Betarena/scores/assets/37311649/37507d51-810e-4d2e-8f4e-c00cf8e7e9b9)

**Comment by migbash** [comment]
> [!NOTE]
> Believed to be a glitch and/or caused by some potentially causing issues, that have now been fixed, will need to be tested upon **next** re-deployment.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`

**Comment by jonsnowpt** [comment]
@migbash 

Missing translation:

![Screenshot 2024-02-14 at 09 15 52](https://github.com/Betarena/scores/assets/37311649/d196a94f-efda-4aac-8432-b89e484421bb)

**Comment by migbash** [comment]
@jonsnowpt Need new translations for `or more` term.

**Comment by jonsnowpt** [comment]
@migbash 

Change it to:

`(+$100.000)`

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

Same here:

![Screenshot 2024-02-15 at 07 47 36](https://github.com/Betarena/scores/assets/37311649/8259edaa-fb5d-4ebf-84a9-7242f132274b)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
