### ISSUE TITLE
[Bug]: Transaction history on presale investments missing the icon

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing the investment icon:

![Screenshot 2024-02-11 at 15 59 34](https://github.com/Betarena/scores/assets/37311649/d27e2c85-95c4-402c-9c3e-6d7a348f4534)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
