### ISSUE TITLE
[FEATURE]: Investor Section : Add "Sale Ended" information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1980]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

Missing the sale-ended information (state)

![Screenshot 2024-02-13 at 09 12 54](https://github.com/Betarena/scores/assets/37311649/db8469d9-2762-40f2-af92-037566f9a2cb)

### 📝 Feature Request Description

- [x] Add the sale ended information with translations, already available on the endpoint:  `"end_message":"Sale ended"`
- [x] Disable the invest box CTA and add the message `"end_message":"Sale ended"` where we have "Buy BTA"
- [x] Remove the following elements from the invest box: "Connect your Wallet" + "Credit Card" + "Deposit" + Receive;

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
