### ISSUE TITLE
[FEATURE]: Investor Section : Invest box default value

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1981]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

The default value should be 2600 to guarantee that the minimum USD is met by default.

### 📝 Feature Request Description

The default value should be 2600 to guarantee that the minimum USD is met by default.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
