### ISSUE TITLE
[Bug]: Investor Section : Invest box "null"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Showing "null" instead of "0"

![Screenshot 2024-02-13 at 09 32 59](https://github.com/Betarena/scores/assets/37311649/566e0c14-762a-4d85-a15c-ce899351fcd1)

### 🤔 Expected Behavior

Value should be "0"

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
