### ISSUE TITLE
[Bug]: Investor section : invest box wrong calculations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

1 USDC is not 11 BTA

![Screenshot 2024-02-13 at 09 34 42](https://github.com/Betarena/scores/assets/37311649/c7f84fe8-5115-43cf-9c3c-f6d5461c0842)

### 🤔 Expected Behavior

Correct the value.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Is still happening ? Cannot replicate.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
