### ISSUE TITLE
[FEATURE]: Investor Section : Popup transfer succeeded refresh page

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1984]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

At this time, after the investor invests and selects OK to confirm that the transfer was complete, the data is not immediately available on the investment details. (pending investment), we should refresh the page or make the data available immediately.

### 📝 Feature Request Description

Refresh the page or add the data without refresh if possible to allow the investor to understand that the investment is correctly pending at this time.

**Comment by migbash** [comment]
> [!NOTE]
> Added page refresh after user clicks on `OK` upon investment completion.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by jonsnowpt** [comment]
@migbash 

The transfer complete message is incorrect.

![Screenshot 2024-02-15 at 07 54 54](https://github.com/Betarena/scores/assets/37311649/eb030faa-06ec-4edd-9e53-c4763d08b1b4)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
