### ISSUE TITLE
[Bug]: Investor Section : Chart information only after completed

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The chart shows investments yet to be approved.

### 🤔 Expected Behavior

It should only show already approved investments.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Adding another `chart` related issue from #1987 

- [ ] Chart should have that amount flatline;

This is related to the discussion had on `slack` :|: https://betarena.slack.com/archives/D02B1UHEECS/p1707757994699839 for chart/portfolio UI.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by jonsnowpt** [comment]
@migbash 

Cant see any changes:

![Screenshot 2024-02-15 at 07 59 08](https://github.com/Betarena/scores/assets/37311649/a5e05ac5-c5c7-433a-8f36-b50fa6f4a4c0)

**Comment by migbash** [comment]
> Cant see any changes:

@jonsnowpt Firefox ?

**Comment by jonsnowpt** [comment]
@migbash 

Yes!

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
