### ISSUE TITLE
[Bug]: Investor Section : Investment Details Add Description and correct data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Add the status;
- [x] Add the description;
- [x] Invert token and amount invested;

![Screenshot 2024-02-13 at 10 02 57](https://github.com/Betarena/scores/assets/37311649/8c6eeb3b-02d5-4987-a0b5-c9ca4a58c07c)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> - [ ] Add the description;

@jonsnowpt You mean to add the `description` column, like in the `Transaction History` table ?

**Comment by jonsnowpt** [comment]
@migbash 

yes!

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
