### ISSUE TITLE
[Bug]: Investor Section : Wrong investment data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Wrong total on the investor wallet;
- [x] Wrong TGE calculation;
- [ ] ~~Chart should have that amount flatline;~~

![Screenshot 2024-02-13 at 10 06 22](https://github.com/Betarena/scores/assets/37311649/819fb4f0-6f76-4038-abb3-07bc822f22aa)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> - [ ] Chart should have that amount flatline;
> Moved to #1985 for grouping of issues.

**Comment by migbash** [comment]
> [!NOTE]
> - [ ] Chart should have that amount flatline;
> Moved to #1985 for grouping of issues.

> [!NOTE]
> Addressed via `firebase/functions`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. The chart is not showing the data;
- [ ] 2. TGE data is incorrect;

1. 

![Screenshot 2024-02-14 at 09 25 02](https://github.com/Betarena/scores/assets/37311649/bdacc108-a6a7-4629-88ed-ba141730b5c2)

2.

![Screenshot 2024-02-14 at 09 25 58](https://github.com/Betarena/scores/assets/37311649/1106a873-9da7-4be3-a482-5ae4d57187c8)

**Comment by migbash** [comment]
> [!NOTE]
> Adjusted via `firebase/functions (backend)` for the correct use of the `initial_tge_percentage` data property to calculate `TGE`.

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect:

![Screenshot 2024-02-14 at 15 13 11](https://github.com/Betarena/scores/assets/37311649/04154745-d56b-4959-82ed-8595a4f1530c)

**Comment by migbash** [comment]
@jonsnowpt Not yet deployed to firebase functions.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by migbash** [comment]
> The second transfer is completely ignored:

In regards to the `tier` you mean ? (related #1996) 

As the `balances` seem to have been updated.

Or are you referring to somehting else ?

**Comment by jonsnowpt** [comment]
@migbash 

Yes.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
