### ISSUE TITLE
[Bug]: Investor Section : Tiers widget title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We are not able to check the title in full but we still have space to add it:

![Screenshot 2024-02-13 at 14 46 08](https://github.com/Betarena/scores/assets/37311649/3f30a34f-f96a-4f2e-82cb-81186e89bd83)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
