### ISSUE TITLE
[Bug]: Investor Section : Investment Details add decimal

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Add the decimal the same way we have on the desktop version:

![IMG_F54DB0D06BF0-1](https://github.com/Betarena/scores/assets/37311649/fb9410b6-1d22-4cb4-b02f-ff1a3c9f6484)

### 🤔 Expected Behavior

Users are able to view exactly the cost of each BTA.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`
