### ISSUE TITLE
[FEATURE]: Investor Section : Share option with "X"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1990]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 🤔 Is feature request related to a problem? Please describe the problem.

Change the Twitter logo to "X".

![Screenshot 2024-02-13 at 15 11 06](https://github.com/Betarena/scores/assets/37311649/a1dd0a99-cadb-4182-b768-5983d7f4f751)

### 📝 Feature Request Description

![Screenshot 2024-02-13 at 15 11 06](https://github.com/Betarena/scores/assets/37311649/c6406932-0cfe-4f3b-878b-d6ef17c14524)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1012`

**Comment by jonsnowpt** [comment]
@migbash 

On mobile, move the "copy" to the left side because at this time is under the chat icon:

![IMG_E31B7F0FE5E9-1](https://github.com/Betarena/scores/assets/37311649/89178247-000d-4524-b9aa-16de6a6039ba)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`
