### ISSUE TITLE
[Bug]: Tge/Vesting Claim Logic Faulty

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1991]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### 🐞 Describe the bug

https://betarena.slack.com/archives/D02B1UHEECS/p1707836349900409

### 🤔 Expected Behavior

Both `Vesting` and `TGE` claim logic should be working, including respective data update on the database to refelect said claims.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`

**Comment by jonsnowpt** [comment]
@migbash 

Issues:

- [ ] 1. Missing the date:
- [ ] 2. Just 2 decimals;
- [ ] 3. Get an error when claiming the TGE.
- [ ] 4. Wrong CSS for the CTA;

1.

![Image](https://github.com/Betarena/scores/assets/37311649/37c4d304-8912-44e1-975a-da38a7d069f2)


2.

![Image](https://github.com/Betarena/scores/assets/37311649/057e3f4c-8956-4d76-bbf9-df47abb9c299)


3.

![Image](https://github.com/Betarena/scores/assets/37311649/2c6a39ad-7a7c-4847-9d88-608694568390)


4.

![Image](https://github.com/Betarena/scores/assets/37311649/8d40acf8-9722-4778-a06a-a425e00d6d8f)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`
