### ISSUE TITLE
[Bug]: Investor Section : Popup translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing translations:

![Screenshot 2024-02-14 at 08 59 11](https://github.com/Betarena/scores/assets/37311649/3115bb78-d378-4c9e-9cb1-00d80e9201d0)
![Screenshot 2024-02-14 at 08 59 17](https://github.com/Betarena/scores/assets/37311649/88852874-2b2e-4d86-885a-0861f36a0923)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Missing respective translations.

**Comment by jonsnowpt** [comment]
@migbash 

Added:

```
  "popup_transfer": {
    "message_1": "Transfer is processing wait for confirmation...",
    "message_2": "Transfer Incomplete",
    "message_3": "Transfer Complete"
  },
```

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by jonsnowpt** [comment]
@migbash 

The complete message is showing the incomplete version.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
