### ISSUE TITLE
[Bug]: Investor Section : Countdown character space

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

There is space between the characters:

![Screenshot 2024-02-14 at 09 03 01](https://github.com/Betarena/scores/assets/37311649/6f6bbf73-dd3b-419c-bc03-aaaee4a4d6dd)

![Screenshot 2024-02-14 at 09 02 51](https://github.com/Betarena/scores/assets/37311649/25049cea-04f5-4377-b31f-7c56da5acdc6)

### 🤔 Expected Behavior

Remove the space between the characters, should be:

1d 14h 55m

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`
