### ISSUE TITLE
[Bug]: Investor Section : Investor walled default view

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Remove the chart data and add the default message:

![Screenshot 2024-02-14 at 09 06 04](https://github.com/Betarena/scores/assets/37311649/2b480392-27cb-4118-9876-77c53c53b6d2)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`
