### ISSUE TITLE
[Bug]: Investor Section : Investment detail information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

On mobile, the space is not enough to show the private presale information:

![IMG_6EFB93E893CF-1](https://github.com/Betarena/scores/assets/37311649/3ba9b1c9-c981-481a-80ea-765097774041)

### 🤔 Expected Behavior

Probably, the best approach is to add this information into a specific column.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1016`

**Comment by jonsnowpt** [comment]
@migbash 

Overflow of the messages and a blue highlight.

![IMG_5953](https://github.com/Betarena/scores/assets/37311649/0abea108-2f09-41a1-96a5-16b323333d9b)

**Comment by migbash** [comment]
> [..] blue highlight.

@jonsnowpt missing translation.

**Comment by jonsnowpt** [comment]
@migbash 

Can push the level down.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`

**Comment by jonsnowpt** [comment]
@migbash 

Wrong color, lettering:

![IMG_6AE90E0569CD-1](https://github.com/Betarena/scores/assets/37311649/8a9b3e5c-6997-4623-bb7f-bcb1ae95ec46)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
