### ISSUE TITLE
[Bug]: Investor Section : Second transfer no tier information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Tier information is missing on the second transfer:

![Screenshot 2024-02-15 at 07 57 00](https://github.com/Betarena/scores/assets/37311649/9e5deb98-e7f4-48a6-a85c-4f65d045480d)

![Screenshot 2024-02-15 at 07 56 49](https://github.com/Betarena/scores/assets/37311649/982e5e26-77d5-4a2f-94e9-8dff09d33483)

### 🤔 Expected Behavior

Should check the investor tier and act accordingly.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
Tier information is missing on the second transfer:

@jonsnowpt Should it have been `tier: NaN` ?

**Comment by jonsnowpt** [comment]
@migbash 

In these cases, it should be the investor's current tier.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`
