### ISSUE TITLE
[Bug]: Investor Section : Referred bonus

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Check if I'm being referred;
- [x] If I'm being referred, the amount is incorrect;

![Screenshot 2024-02-15 at 08 03 34](https://github.com/Betarena/scores/assets/37311649/0fba519f-02cb-4eec-a0a8-ab08d3b3b9f7)

### 🤔 Expected Behavior

The correct amount would be:

83.66 BTA

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Fixed (but not deployed) via the `firebase/functions`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1017`

**Comment by jonsnowpt** [comment]
@migbash 

A number of referrals should be available; in my case, 4.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`

**Comment by jonsnowpt** [comment]
@migbash 

Still not being shown:

![Screenshot 2024-02-18 at 16 01 41](https://github.com/Betarena/scores/assets/37311649/c7143f29-2f44-4cdc-b9b7-1e0d120a9c82)

**Comment by migbash** [comment]
> [!NOTE]
> Calculated from `firebase/functions`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
