### ISSUE TITLE
[Bug]: Investor Sectio : Investment logic issues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [ ] After the second investment does not recognize the first;

https://betarena.slack.com/archives/D02B1UHEECS/p1708080062322719

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt This was already solved yesterday ?
