### ISSUE TITLE
[Bug]: Investor Section : Blue highlight remove for the "OK"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Remove the highlight and verify if the OK is in capital letters.

![Screenshot 2024-02-16 at 18 26 45](https://github.com/Betarena/scores/assets/37311649/cf6d0305-d431-442b-9799-44964638cf42)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
