### ISSUE TITLE
[Bug]: Investor Section : Wallet + TGE decimals

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Two decimals on those values:

![Screenshot 2024-02-16 at 19 08 42](https://github.com/Betarena/scores/assets/37311649/52770bf7-4415-4183-a7fe-fc40f0905f52)

![Screenshot 2024-02-16 at 19 07 59](https://github.com/Betarena/scores/assets/37311649/ebff3789-902e-46f0-a1bd-43f2a454303c)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`

**Comment by jonsnowpt** [comment]
@migbash 

Also two decimals here:

![Screenshot 2024-02-18 at 15 55 52](https://github.com/Betarena/scores/assets/37311649/70763bc8-2b2c-4d2e-8e4d-c333056becc9)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
