### ISSUE TITLE
[Bug]: Investor Section : Transaction failing 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Sometimes the transactions are not successful need to be addressed:

https://betarena.slack.com/archives/D02B1UHEECS/p1708172185599649

### 🤔 Expected Behavior

The transaction is always successful.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`

**Comment by jonsnowpt** [comment]
@migbash 

Still happening:

https://betarena.slack.com/files/U04MANUB3/F06KAQA0V7F/screenshare_-_2024-02-18_3_59_44_pm.webm

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1021`
