### ISSUE TITLE
[Bug]: Referred users not visible on the referral

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The referred user is not being added to the referral:

![Screenshot 2024-02-19 at 07 50 59](https://github.com/Betarena/scores/assets/37311649/848fb573-b2c7-464b-972c-b6b8521e43b0)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`
