### ISSUE TITLE
[Bug]: Investor Section : Bonus from being referred not added to the investor wallet + TGE + chart

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Bonus from being referred not added to the investor wallet + TGE + chart

![Screenshot 2024-02-19 at 07 59 42](https://github.com/Betarena/scores/assets/37311649/8cbad575-f839-4a02-8676-273fd9fa4ca2)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Should `referral_total` be added to the `tier` calcualtion ?

**Comment by jonsnowpt** [comment]
Clarified on slack

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`

**Comment by jonsnowpt** [comment]
@migbash 

Still getting the same values:

<img width="1063" alt="Screenshot 2024-02-19 at 18 13 56" src="https://github.com/Betarena/scores/assets/37311649/2e7bd0dc-e279-4cd9-8034-b6f17863330b">

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`
