### ISSUE TITLE
[Bug]: Investor Section : Incorrect referral percentage

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2024-02-19 at 18 41 19](https://github.com/Betarena/scores/assets/37311649/f1d5a746-bc63-400f-bed7-5d9afd118e4a)

Is not 5% of:

<img width="485" alt="Screenshot 2024-02-19 at 18 41 38" src="https://github.com/Betarena/scores/assets/37311649/f2b084ec-9492-45fe-868a-d631f4e6bd90">

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`

**Comment by jonsnowpt** [comment]
Both data are incorrect.

5% of 3246.75 its 162.33

Also the value in this case should be exactly the same.

![Screenshot 2024-02-20 at 15 31 14](https://github.com/Betarena/scores/assets/37311649/eb7a3f5f-e1d5-4c6c-9b78-7202f300b67b)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1029`

**Comment by jonsnowpt** [comment]
@migbash 

We discussed this on the call; the percentage must be by transaction.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1030`
