### ISSUE TITLE
[Bug]: Investor Section : MIssing the reference information

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2024-02-19 at 18 42 36](https://github.com/Betarena/scores/assets/37311649/46bb2749-831d-49db-8f90-265eadd0fc21)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1025`
