### ISSUE TITLE
[Bug]: Investor Section : Investment details "Status" translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

![Screenshot 2024-02-20 at 11 10 16](https://github.com/Betarena/scores/assets/37311649/650a9a69-eb41-41ca-9053-1223ac5a7caa)

`    "status":"Status",   `

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.
