### ISSUE TITLE
[Bug]: Investor Section : Referral not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Referral not working:

https://betarena.slack.com/archives/D02B1UHEECS/p1708428357601039

![Screenshot 2024-02-20 at 11 25 12](https://github.com/Betarena/scores/assets/37311649/e8270092-b021-46c3-a72e-7ab28829f701)

### 🤔 Expected Behavior

The following data is missing:

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1027`

**Comment by jonsnowpt** [comment]
@migbash 

Resolved
