### ISSUE TITLE
[Bug]: Investor Section : Investment Details "Description" translation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

` "description":"Description",`

![Screenshot 2024-02-20 at 12 11 21](https://github.com/Betarena/scores/assets/37311649/4af4a290-98be-4fdc-a354-21aef6453322)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1027`
