### ISSUE TITLE
[Bug]: Investor Section : Investment information color title

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Incorrect color:

![Screenshot 2024-02-20 at 12 37 01](https://github.com/Betarena/scores/assets/37311649/7d55a1ba-bcbe-428e-a582-d6d5e412ea6d)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1027`
