### ISSUE TITLE
[Bug]: Investor Section : Incorrect tier discount

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In this case, it should be GOLD:

![Screenshot 2024-02-20 at 16 09 09](https://github.com/Betarena/scores/assets/37311649/3683dfff-04d9-407a-9a4d-59f049f2e3c7)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
@jonsnowpt Don't forget the `Exchange Conversion`!

![Image](https://github.com/Betarena/scores/assets/20924663/61df4bf2-cc98-4167-b6fc-ca9707a0246f)
