### ISSUE TITLE
[Bug]: Investor Section : TGE CSS Token icon position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

When the number of tokens is high, the token icon is incorrectly positioned:

![Screenshot 2024-02-20 at 17 22 56](https://github.com/Betarena/scores/assets/37311649/92f3f3f7-1f59-41dc-8f1f-3f23eac6afe4)

If necessary, we can always use the two lines approach on Desktop.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1030`
