### ISSUE TITLE
[Bug]: investor Section : TGE CSS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

"BTA" + icon are not aligned with the value:

![Screenshot 2024-02-21 at 16 31 01](https://github.com/Betarena/scores/assets/37311649/1aa60f00-6b33-42f9-8e84-3643c76fd536)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1030`
