### ISSUE TITLE
[Bug]: Investor Section : Invest Box Loading

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The Invest box should not be visible on loading when the presale is over:

https://github.com/Betarena/scores/assets/37311649/8ae47e52-226a-4a21-9449-0d1aef741eeb

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1030`
