### ISSUE TITLE
[Bug]: Investor Section : Responsiveness 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The behavior is not correct:

https://github.com/Betarena/scores/assets/37311649/5bcb51d6-74fe-418c-b084-5bcbdc2064e4

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`
