### ISSUE TITLE
[Bug]: Transaction history TGE claim "decimals"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Change only to show 2 decimals.

![Screenshot 2024-02-24 at 11 02 22](https://github.com/Betarena/scores/assets/37311649/643cbc49-4035-4243-9acf-a2583a061516)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`
