### ISSUE TITLE
[Bug]: Investor Section : Chart not reflecting the current value

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The chart is getting a different value from the investor wallet after the claim of TGE and one vesting period:

![Screenshot 2024-02-24 at 11 06 28](https://github.com/Betarena/scores/assets/37311649/3b8078b0-85e6-4193-942a-9148019e1350)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`

**Comment by jonsnowpt** [comment]
@migbash 

For the investments, the chart should only include the completed.

**Comment by jonsnowpt** [comment]
Resolved.
