### ISSUE TITLE
[Bug]: Investor Section : TGE claim option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Even after the TGE has been reclaimed, the option to reclaim it is still visible, and what should be visible in the "Reclaimed" information:

![Screenshot 2024-02-24 at 11 30 02](https://github.com/Betarena/scores/assets/37311649/4d8368ba-013a-4184-a23a-061d9d2b6a4d)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`

**Comment by jonsnowpt** [comment]
@migbash 

Now it is showing that it has already been claimed when it was not:

![Image](https://github.com/Betarena/scores/assets/37311649/ec5886d0-61bb-4614-bb5a-b15c1637846a)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`
