### ISSUE TITLE
[Bug]: Investor Section : Invest box default token USDT

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Invest box default token USDT

![Screenshot 2024-02-24 at 11 47 08](https://github.com/Betarena/scores/assets/37311649/2f2dda72-5b97-40da-bbec-5002f87847b6)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`
