### ISSUE TITLE
[Bug]: Investor Section : Investment incomplete periodically

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We continue to get transfer incomplete sometimes on first investment:

https://betarena.slack.com/archives/D02B1UHEECS/p1708775890499729

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`
