### ISSUE TITLE
[Bug]: Investor Section : Incorrect Platinum amount discount

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Simulating an investment of 75000 USD after a previous investment of 2600 and 17000 shows a platinum discount that requires at least a +100.000 investment. It is not correct.

![Screenshot 2024-02-26 at 08 27 28](https://github.com/Betarena/scores/assets/37311649/9707da25-64bd-4cd7-9d1c-e235efd86d7c)
![Screenshot 2024-02-26 at 08 27 01](https://github.com/Betarena/scores/assets/37311649/7cbb4b0e-cfe7-429c-9f95-b47a1fcf8576)
![Screenshot 2024-02-26 at 08 26 46](https://github.com/Betarena/scores/assets/37311649/58653f1e-3a4d-4945-9b78-2f067de48f7e)

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1034`

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect:

![Image](https://github.com/Betarena/scores/assets/37311649/bfcd65cb-f916-428c-9aa9-79ccf595fb65)

**Comment by migbash** [comment]
> [!NOTE]
> Corrected, awaiting `🚀 deployment`.

**Comment by migbash** [comment]
> [!NOTE]
> Live on `dev` with version `v1036`
