### ISSUE TITLE
Onboard tasks 1

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2060]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

Description:

Various tasks to prepare for the onboarding of new developers.

- [x] Video tutorial exemplifying how to set the project codespaces and initial logic

Add the videos to our YouTube channel and share them on Tettra.

**Comment by migbash** [comment]
**🟧 STATUS UPDATE**

Video completed and shared.
