### ISSUE TITLE
[Bug]: Football link error

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Getting an error when clicking on the "Fooball" link:

![Screenshot 2024-03-24 at 14 38 18](https://github.com/Betarena/scores/assets/37311649/3752ff4f-b9cc-4229-869e-16ddff1b6df0)

### 🤔 Expected Behavior

It should redirect to the football scores list.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by Izobov** [comment]
@jonsnowpt  What page it should open? Is it just "scores" page?

**Comment by jonsnowpt** [comment]
@Izobov yes.
