### ISSUE TITLE
[FEATURE]: Implement Frontend for Tags Section

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2079]
### 📝 Feature Request Description

We are introducing a new feature on our website - a dedicated section for tags that will display all articles associated with each tag. The objective is to enhance user engagement by providing a streamlined way to access articles by tags. This section will leverage data from our Redis cache for speed, with a fallback to load directly from Hasura if the cache is unavailable.

### Requirements

**Tag Page Content:**

`Display the Tag name and Tag Description.`

**List articles under each tag with the following details:**

```
Title
Author Avatar
Author Name
Published Date
Tags
Featured Image
Permalink
SEO Details
```

### Follow Option:

**Logged-in Users**: If a user is logged in, provide the option to follow the tag. This action adds the tag to the `following` field under `tags` in the user's profile in the **Firestore Database**.

Example:

```
{
  "username": "new_user",
  "profile_photo": "default_profile_photo_url",
  "register_date": "2024-04-02T15:47:00Z",
  "registration_type": "google",
  "lang": "en",
  "following": {
    "tags": [
      "olympics"
    ]
  }
}
```

Guest Users: Guests are prompted to register or log in.

`?authForm=true`

### Language and Sorting:

Articles are sorted by the most recent.

The data is loaded according to the default language specified in the user’s profile FIRESTORE DATABASE. Users can change the language using a dropdown option to either a specific language or load articles in all languages, prioritizing the default language.

### Followers Count and Total Articles:

Display the number of users following the tag (this data is added to the `followers` table on Hasura) and the total number of associated articles. This data changes in real-time as users follow/unfollow tags using Hasura real-time:

https://hasura.io/learn/graphql/intro-graphql/graphql-subscriptions/

### SEO Details:

Load SEO details for each tag from the seo_details field in the Hasura tags table.

### Themes:
Ensure the section supports both Light and Dark themes.

### Data Endpoints
**Hasura Production Endpoint** (betarena_prod authors tags):
**Fields: name**, description, seo_details
**Redis Cache**: Use as the primary data source for faster content loading.
Fallback to Hasura: In case data is not available in Redis.

### Back option behaviours:

**Step 1: Detect PWA or Browser Environment**

First, you need to determine if the user is visiting from a PWA or a web browser. You can check if the site was launched from the home screen (PWA) or directly in the browser.

```
function isLaunchedFromPWA() {
    return window.matchMedia('(display-mode: standalone)').matches ||
        window.navigator.standalone ||
        document.referrer.includes('android-app://');
}
```

**Step 2: Implement the Back Button Logic**

Create a back button component that checks the environment. If the user is on a PWA, the button will take them to the last visited screen. If they're in a browser, it will redirect them to the homepage.

<img width="480" alt="Screenshot 2024-04-08 at 11 40 02" src="https://github.com/Betarena/scores/assets/37311649/a05194ff-11b5-4a6a-8e02-a5bdbb576a12">

```
<script>
  import { onMount } from 'svelte';

  function goBack() {
    if (isLaunchedFromPWA()) {
      // PWA: Go back to the last visited screen
      window.history.back();
    } else {
      // Browser: Redirect to the homepage
      window.location.href = '/';
    }
  }
</script>

<button on:click={goBack}>Back</button>
```

**Step 3: Handle Edge Cases**
For the PWA scenario where the user might not have a history within your site (e.g., they opened the PWA directly to a specific page), ensure that window.history.back() does something sensible. You might need to check if going back is possible or provide a default fallback URL.

```
function goBackWithFallback() {
  if (isLaunchedFromPWA()) {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      // Fallback for PWA if no history is available
      window.location.href = '/defaultPwaPage'; // Your default page for PWA
    }
  } else {
    window.location.href = '/';
  }
}
```

**Step 4: Test Thoroughly**

In Browser Testing: Ensure that the back button redirects to the homepage when accessed through a web browser.
In PWA Testing: Confirm that the back button navigates to the last visited screen when accessed through the PWA. Test edge cases where the user might not have a navigation history.

### 🔎 HTML SEO

The following content should be available on HTML to SEO purposes:

`Tag name and Tag Description.`

**Articles content:**

```
Title
Published Date
Tags names
Tags Links
Permalink (to the article)
```

**Implementation Notes**

We're using SvelteKit as the frontend framework.
Ensure compatibility with both Redis and Hasura for data fetching.
Implement error handling for the fallback mechanism from Redis to Hasura.

### Acceptance criteria:

- [ ] SvelteKit components for the tags section.
- [ ] Integration logic with Redis, Hasura, and Firestore.
- [ ] Light and Dark theme support.
- [ ] Implement the language filter and sorting logic based on user preferences and profile settings.
- [ ] Different PWA behaviour;
- [ ] Add HTML SEO content;
- [ ] The following feature should update the Firestore Database appropriately for logged-in users.
- [ ] Documentation of the feature's functionality and codebase changes.
- [ ] A pull request with all changes was submitted to the designated repository branch.

Timeline
Deadline for completion:

Please ensure all code is thoroughly tested and reviewed before submission. This feature is pivotal in enhancing our content discoverability and user engagement.

### FIGMA:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=7184%3A48570&mode=design&t=5YEegxK8uyzwzdo4-1

**Comment by jonsnowpt** [comment]
@Izobov 

We have pushed directly to the DEV environment, but it is not working:

For example:

`https://betarena-scores-platform.herokuapp.com/a/tag/atp`

**Comment by jonsnowpt** [comment]
@Izobov 

Corrections:

- [ ] 1. User authentication is not working;
- [ ] 2. View more option should disappear when there are no more results;
- [ ] 3. Missing the top line under the header
- [ ] 4. It should show ten results per page;
- [ ] 5. Incorrect Desktop tags approach;
- [ ] 6. Incorrect space between the author's name and published date;
- [ ] 7. Language not working;
- [ ] 8. Authors not working;
- [ ] 9. The published date is not working;
- [ ] 10. The image should also be linkable;
- [ ] 11. Smooth the hovers;



![Image](https://github.com/Betarena/scores/assets/37311649/2b0cdd8b-3b1d-49bd-a451-444cf403e282)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] The one is still not working, and it's not getting my user authorization state.
- [ ] 5 add an easing effect;
- [ ] 12. Unable to change the platform language;

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 7 and 12 still not working
- [ ] 13. When we change platform lang it messes up with the tags;
- [ ] 14. No SEO details present;
- [ ] 15. Image elements do not have explicit width and height
- [ ] 16. Poor speed performance, check if there are improvements to be made;
- [ ] 17. No HTML data is being loaded: https://totheweb.com/learning_center/tools-search-engine-simulator/
- [ ] 18. CSS DESKTOP: Distance from the top is different and the tag description finishes before the language dropdown;
- [ ] 19. The responsiveness is not working and breaks the platform that stops working;


13.

![Image](https://github.com/Betarena/scores/assets/37311649/7cd4f3ac-83b7-42a1-9137-c35cb29d53eb)

15

![Image](https://github.com/Betarena/scores/assets/37311649/8d67649a-0b4b-49d6-89a3-5dcadef71228)

16.

![Image](https://github.com/Betarena/scores/assets/37311649/e84316f7-11b7-4d01-a324-afbee913fe86)

18.

![Image](https://github.com/Betarena/scores/assets/37311649/6bc07b6c-420d-4bd7-8fe0-cccd6453c3ab)

19.

https://github.com/Betarena/scores/assets/37311649/1375cf19-76f2-437e-8ce9-ba85ce62074a

**Comment by Izobov** [comment]
@jonsnowpt  
17. Theres screenshoot from https://betarena-scores-platform.herokuapp.com/a/tag/atp.
So html data exist


![Image](https://github.com/Betarena/scores/assets/54995954/7ff35b36-d01d-4197-891a-5e91c085d81a)

**Comment by Izobov** [comment]
23. Works for me 

![Image](https://github.com/Betarena/scores/assets/54995954/264ecc84-a63a-48b6-863d-c675cf9e7aed)

**Comment by jonsnowpt** [comment]
> [@jonsnowpt](https://github.com/jonsnowpt) 17. Theres screenshoot from https://betarena-scores-platform.herokuapp.com/a/tag/atp. So html data exist
> 
> ![Image](https://private-user-images.githubusercontent.com/54995954/326170177-7ff35b36-d01d-4197-891a-5e91c085d81a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzU2NTAsIm5iZiI6MTcxNDM3NTM1MCwicGF0aCI6Ii81NDk5NTk1NC8zMjYxNzAxNzctN2ZmMzViMzYtZDAxZC00MTk3LTg5MWEtNWU5MWMwODVkODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA3MjIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzQ1ZDQ2MDE5NzJmZTU5YTM0YzNhN2E3ZjAyMzQyYzY0MWZlNzNiNzM5MzI1MWQzOTlmZDg0MjA4ZGEwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhhgkdjqTrAX-XvAEUok3cRvfWtttQZreTU1c5TCKCc)

@Izobov 

Its not working you need to add the H1, H2 and all the required HTML data requested on the task.

**Comment by jonsnowpt** [comment]
- [ ] 14 Seo details still not working, you need to replace the {} with the correct data;
- [ ] 7 Still pending
- [ ] 12 Still pending
- [ ] 17 Is still not done
- [ ] 20 Still missing = ease animation when showing the description content +  article title with wrong height + wrong tag approach + wrong post date size and color
- [ ] 24 CSS MOBILE Wrong top
- [ ] 25 CSS MOBILE Wrong Arrow position
- [ ] 26 CSS MOBILE Back button behavior like the video
- [ ] 27 In this case there is not footer with infinite scrolling, no view more neither number of articles;
- [ ] 28 CSS TABLET: Wrong author name size + Article title height + font size and color published date;



14.

![Image](https://github.com/Betarena/scores/assets/37311649/beda36a9-11ef-4090-a166-90c21803cee1)

24.

![Image](https://github.com/Betarena/scores/assets/37311649/89ab6872-cca6-4800-9850-80e08d308e6e)

25.

![Image](https://github.com/Betarena/scores/assets/37311649/7e10024b-c036-4baa-846f-b6b79405310f)

26

https://github.com/Betarena/scores/assets/37311649/92c4c06b-0c90-4b0c-82ca-465dc6a34c51

28

![Image](https://github.com/Betarena/scores/assets/37311649/eb7e6f51-619a-4821-b40a-62c815a5a8b6)

**Comment by Izobov** [comment]
@jonsnowpt  @migbash 31 sorting by relevant date should be done on the backend side. Same reason, on fronted we recieve only 10 articles (that means that on front we can sort only 10 articles)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 20 Ease animation is to be applied when the space is opening and closing, not only the fade in of the content;
- [ ] 34. Followers update is not working, shows always 0;
- [ ] 35. Missing English language option;
- [ ] 12. Unable to change platform language still have issues;
- [ ] 36. Missing the border on the light theme;
- [ ] 37. The user Avatar should be present on Desktop and Tablet variations;
- [ ] 38. When changing the language of the articles its also changing the platform expressions, its incorrect, should be just a content filter;

**Comment by jonsnowpt** [comment]
@Izobov 

For review:

- [ ] 40 Canonical link issue;

40.

![Image](https://github.com/Betarena/scores/assets/37311649/2d1c466a-e55d-446b-8e4d-7151fbcdf539)
