### ISSUE TITLE
[Bug]: Excess usage Hasura

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

We are consuming too much data without a specific reason. There are thousands of identified requests that probably shouldn't be happening.

![Screenshot 2024-04-18 at 19 39 23](https://github.com/Betarena/scores/assets/37311649/c05bcbe6-44f0-4deb-8e74-29229fa19934)

![Screenshot 2024-04-18 at 19 43 32](https://github.com/Betarena/scores/assets/37311649/4154ac50-aff7-4a41-b2e6-730ccdb023df)

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [ ] 🖥️ Laptop/Desktop

**Comment by jonsnowpt** [comment]
We will be sorting this out with a different approach on cache.

**Comment by migbash** [comment]
Moving to `Icebox`.
