### ISSUE TITLE
[Bug]: Unable to load more content

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Unable to load more content on tags.

https://scores.betarena.com/a/tag/atp

![Screenshot 2024-05-05 at 09 25 12](https://github.com/Betarena/scores/assets/37311649/30578c30-8517-427b-9128-0c563af2a092)

### 🤔 Expected Behavior

Should be able to view more results.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by Izobov** [comment]
@migbash @jonsnowpt
The script error tells us that we have 2 articles with the same ID. I can solve this problem in the frontend by removing the already shown element.

But the problem may be deeper. This is probably due to the Redis cache (not sure)

**Comment by jonsnowpt** [comment]
Resolved on the frontend.

**Comment by migbash** [comment]
via Hubstaff
User: Miguel Bacharov

Project: scores - https://app.hubstaff.com/projects/2983891
Date Range: 05/06/24 - 05/06/24
Work session total: 1:28:48
Billable: Yes

Grand total: 1:28:48
