### ISSUE TITLE
[FEATURE]: Change the Tips and News & Views

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2139]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

Since the content is now published inside the Scores platform, we need to change how it is added to the Livescore and News & Views tabs.

![Screenshot 2024-05-21 at 16 36 07](https://github.com/Betarena/scores/assets/37311649/5be063f1-f754-44ce-8064-7ffc1ce1d177)

![Screenshot 2024-05-21 at 16 36 27](https://github.com/Betarena/scores/assets/37311649/1a1c485e-af8e-4732-9387-a69decfd61b1)

Now, the logic will be added to the` articles_update` table.

Every time an article runs in the ` articles_update`, it will be checked for the game ID inside the URL and also check for the lang and tag:

![Screenshot 2024-05-21 at 18 05 51](https://github.com/Betarena/scores/assets/37311649/a7243aec-115a-4a4e-8494-c7a067dc32c3)

For EN must have the tag: 1648
For ES must have the tag: 1676
For SE must have the tag: 1093
For FR must have the tag: 1680
For BR must have the tag: 1668
For PT must have the tag: 1673
For RO must have the tag: 1650
For IT must have the tag:  1681

Then, it will add the link to the fixtures table:

`betarena_prod   public   historic_fixtures  tip_link_wp`

Respecting the json format:

`{"br":"https://apostas.betarena.com/palpite-atalanta-x-bayer-04-leverkusen-2023-2024-dicas-de-apostas-para-a-liga-europa-no-dia-22-de-maio-de-2024/","en":"https://www.betarena.com/atalanta-vs-bayer-04-leverkusen-betting-tip-2023-2024-picks-and-predictions-for-the-europa-league-match-on-may-22nd-2024/","es":"https://www.betarena.com/pronostico-atalanta-vs-bayer-04-leverkusen-2023-2024-apuestas-para-el-22-mayo-2024-en-la-liga-europa/","it":"https://www.betarena.com/europa-league-atalanta-bayer-04-leverkusen-pronostici-probabili-formazioni-e-consigli-per-le-scommesse-sul-match-del-22-maggio-2024/","pt":"https://apostas.betarena.com/prognostico-atalanta-vs-bayer-04-leverkusen-2023-2024-apostas-para-a-liga-europa-no-dia-22-de-maio-de-2024/"}`

**Comment by jonsnowpt** [comment]
@migbash 

For the news and views we can use the authors data already available on Hasura and Cached in Redis.

`betarena_prod   authors   articles`

Column:

seo_details

Using the Title and Description.

**Comment by migbash** [comment]
**🟧 UPDATE**

- [ ] Data Manager (C#) (delta) logic implemntation
- [ ] Prepare for shutdown/deprecate of existing logic using Betarena-Wordpress-API for `tips` + `external_content` generation.
