### ISSUE TITLE
[FEATURE]: Header CSS change

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2149]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We are changing the Header CSS for the mobile version of the platform:

For the mobile WEB:

https://www.figma.com/design/thLKCrDNpVADLdkau4WxCy/BTA-Design-Scores-Mobile?m=dev&node-id=0-1

For the mobile PWA:

https://www.figma.com/design/thLKCrDNpVADLdkau4WxCy/BTA-Design-Scores-Mobile?m=dev&node-id=88-103203

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 1. DESKTOP: The desktop version missing the custom option;
- [ ] 2. DESKTOP: Incorrect balance information should be around 397;
- [ ] 3. DESKTOP: The light theme is missing the dark background;
- [ ] 4. DESKTOP: Wrong information on the competitions section;
- [ ] 5. MOBILE PWA: On the profile section the header is incorrect should be the same that we have inside the fixture for example (it was wrong on the design);
- [ ] 6. MOBILE PWA: The icons have incorrect CSS and sizes and the back button does not work;
- [ ] 7. MOBILE PWA: Incorrect header inside the tournaments;
- [ ] 8. MOBILE PWA: Breadcrumb "Football" link not working;
- [ ] 9. MOBILE PWA: Inside the competition, we use the same header we have inside the fixture;
- [ ] 10. MOBILE WEB: Inside the competition we use the same header we have inside the fixture;
- [ ] 11. MOBILE PWA and MOBILE WEB: The header was ok for tags and now it's not, check FIGMA
- [ ] 12. MOBILE PWA and MOBILE WEB: The header was ok for articles and now its not, check FIGMA


1.

![Image](https://github.com/Betarena/scores/assets/37311649/41173382-3791-46e3-b384-957d6272600d)


2.

![Image](https://github.com/Betarena/scores/assets/37311649/e7b02c05-c397-42d1-9d52-cc9f7bf8f8b9)

3.

![Image](https://github.com/Betarena/scores/assets/37311649/3952e470-4559-43f7-9ef7-34011e2f970f)
![Image](https://github.com/Betarena/scores/assets/37311649/4fee27cd-2710-473d-81c1-e7f92083bca9)

4.

![Image](https://github.com/Betarena/scores/assets/37311649/8a8a1025-7cf2-49ed-98e5-92dacfad4aa0)
![Image](https://github.com/Betarena/scores/assets/37311649/1a918d72-9dab-46c6-aa16-7c08834e6f0d)

5. 

![Image](https://github.com/Betarena/scores/assets/37311649/7901895c-9db9-437b-9b7e-e0059db1f9d8)

6. 

![Image](https://github.com/Betarena/scores/assets/37311649/36e11d64-f1cf-4d67-9e96-6d012efe9f0f)


7. 

![Image](https://github.com/Betarena/scores/assets/37311649/95ab5068-9e51-4d8a-814d-7c6ed84a0ce0)

9. 

![Image](https://github.com/Betarena/scores/assets/37311649/13e8c581-4b1e-4cc0-b01f-54e3cf059c21)

11. 

![Image](https://github.com/Betarena/scores/assets/37311649/0b161b68-2213-47ae-9fab-a568b0f15dfc)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ]  13. DESKTOP: The dar background on the light theme is smaller, review Figma;
- [ ] 5. Still incomplete
- [ ] 6. Still have CSS issues;

6. 

![Image](https://github.com/Betarena/scores/assets/37311649/88e39f0e-0147-47ce-9322-24d67b792cf6)

**Comment by Izobov** [comment]
@jonsnowpt  6 point
Are you sure that you run correct port?

It looks normal to me

![Image](https://github.com/Betarena/scores/assets/54995954/c7730eed-f5e9-4fb6-9343-71d741efe366)

**Comment by jonsnowpt** [comment]
@Izobov 

Still happening using my iPhone:

![Screenshot 2024-06-13 at 09 29 19](https://github.com/Betarena/scores/assets/37311649/3569ee91-7192-4aad-bc0f-5cc4909575e7)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 13. Dark background is stil incorrect;
- [ ] 14. The top menu is incorrect inside the article and tags
- [ ] 15. Something wrong with the Dropdown CSS;
- [ ] 8. MOBILE PWA: Breadcrumb "Football" link not working;


13. 

![Image](https://github.com/Betarena/scores/assets/37311649/f6cb15ee-d909-4b9f-8f6f-95d7cd67c889)


It seems you are adding white not grey and it is till too bellow.

![Image](https://github.com/Betarena/scores/assets/37311649/44b44bc8-f75a-4d9c-8d3b-beed21e60c68)

14. 

Inside the article should not have the border neither the top options in the menu.
Inside the tags it has the border but not the top options in the menu;

![Image](https://github.com/Betarena/scores/assets/37311649/c04ae4ab-6b2d-42a7-9077-d46fd733c330)

15. 

![Image](https://github.com/Betarena/scores/assets/37311649/f0eb6213-2d9c-479e-bcd3-55557ce6cdc4)

**Comment by jonsnowpt** [comment]
- [ ] 16. Incorrect header on tablet inner pages; (asked for changes from the design its on HOLD)
- [ ] 17. Subheader is on top of dark lightbox;
- [ ] 18. Remove the breadcrumbs on the PWA versions;



16. 

The inner pages on tablet should behave the same way we have on mobile.

![Image](https://github.com/Betarena/scores/assets/37311649/e8d0ff61-7485-414b-bb81-19d56f63f2b9)

17. 

![Image](https://github.com/Betarena/scores/assets/37311649/3af38ddd-271e-45b0-a901-35a735726af1)

**Comment by jonsnowpt** [comment]
@Izobov 

As discussed the tablet approach was still not correct.

**Comment by jonsnowpt** [comment]
Tested but it will confirmed on prod.
