### ISSUE TITLE
[Bug]: Wrong info EURO Championship

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

- [x] Wrong default date;
- [ ] Missing standings and details;

### 🤔 Expected Behavior

It should open on the 2024 date and show the correct groups.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge
- [X] Brave
- [X] Opera

### What device/platform can the problem be seen?

- [X] 📱 Mobile
- [X] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
**🟧 UPDATE**

> - [x] Wrong default date;
↳ Corrected and on `heroku-dev`.

>  - [ ] Missing standings and details;

Needs `manual` data regeneration.
