### ISSUE TITLE
Live Score - Flag for european competitions

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#226]
At this time the following European competitions have the wrong flags:

Champions League #2
UEFA Europa League #5

<img width="513" alt="Screenshot 2022-02-17 at 10 41 34" src="https://user-images.githubusercontent.com/37311649/154459344-0d9805ec-dd55-42c4-a0cb-d9a022cf92cd.png">

The correct flag:

https://betarena.com/images/flags/EU.svg

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
