### ISSUE TITLE
SSL Renew Lets Encrypt

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2267]
- [x] Let's Encrypt certificate expiration notice for domain "sitemap.betarena.com"
- [x] Let's Encrypt certificate expiration notice for domain "apinarratives.betarena.com"
- [x] Let's Encrypt certificate expiration notice for domain "ads.betarena.com"

**Comment by migbash** [comment]
**📝 NOTE**

Looks like the `crons` have not been correctly working, needs a revisit.

**Comment by jonsnowpt** [comment]
Resolved.
