### ISSUE TITLE
Featured Match - European Competitions Flag

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#227]
At this time the following European competitions have the wrong flags:

Champions League #2
UEFA Europa League #5

![Image](https://github.com/Betarena/scores/assets/37311649/f33e23de-8a64-4901-a177-35d87513ef96)

The correct flag:

https://betarena.com/images/flags/EU.svg

**Comment by migbash** [comment]
> **Note**
> Implemented, awaiting `🚀 deployment`.
