### ISSUE TITLE
Add Partner About Page

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2286]
We need a new partner on the About page.

![Image](https://github.com/user-attachments/assets/515ded10-08d9-4573-87b3-8315c624400f)

![Image](https://github.com/user-attachments/assets/87d8c201-78c5-402a-8dc5-42a2587452f9)

An expert in A.I., business intelligence, and blockchain for telecommunications and gambling. Founder of FidelisBet and other successful ventures, currently consults with companies to optimize operations and harness disruptive technologies. Also an active crypto investor.

**Comment by Izobov** [comment]
@jonsnowpt  you can add him to data and he will appear automatically. No need code adjustments. Same as for IBC Group
