### ISSUE TITLE
Indexation problems

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#272]
For some reason we got 37 indexed pages, most of them do not contain any content.

`https://scores.betarena.com/ptesptes
04/03/2022
https://scores.betarena.com/br
03/03/2022
https://scores.betarena.com/pt
03/03/2022
https://scores.betarena.com/es
03/03/2022
https://scores.betarena.com/britpt
03/03/2022
https://scores.betarena.com/ptbrit
03/03/2022
https://scores.betarena.com/ptbrbr
03/03/2022
https://scores.betarena.com/ptites
03/03/2022
https://scores.betarena.com/ptitbr
03/03/2022
https://scores.betarena.com/ptptpt
03/03/2022
https://scores.betarena.com/ptptptpt
03/03/2022
https://scores.betarena.com/ptitit
03/03/2022
https://scores.betarena.com/brbres
03/03/2022
https://scores.betarena.com/brptit
03/03/2022
https://scores.betarena.com/ptesit
03/03/2022
https://scores.betarena.com/
03/03/2022
https://scores.betarena.com/brespt
03/03/2022
https://scores.betarena.com/britbr
03/03/2022
https://scores.betarena.com/ptbres
03/03/2022
https://scores.betarena.com/britbrit
03/03/2022
https://scores.betarena.com/ptptit
03/03/2022
https://scores.betarena.com/bresbres
03/03/2022
https://scores.betarena.com/ptbrpt
03/03/2022
https://scores.betarena.com/ptesbr
03/03/2022
https://scores.betarena.com/brptpt
03/03/2022
https://scores.betarena.com/pteses
03/03/2022
https://scores.betarena.com/ptespt
03/03/2022
https://scores.betarena.com/brptbrpt
02/03/2022
https://scores.betarena.com/ptes
02/03/2022
https://scores.betarena.com/brit
02/03/2022
https://scores.betarena.com/brpt
02/03/2022
https://scores.betarena.com/bres
02/03/2022
https://scores.betarena.com/brbr
02/03/2022
https://scores.betarena.com/ptpt
02/03/2022
https://scores.betarena.com/ptbr
02/03/2022
https://scores.betarena.com/ptit
02/03/2022
https://scores.betarena.com/it`

**Comment by migbash** [comment]
This needs to be fixed using an `404` error page for non-existing languages
