### ISSUE TITLE
hreflang support

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#280]
Since we have multiple pages with the same content for different languages we must add support to hreflang.

### What is hreflang:

https://ahrefs.com/blog/hreflang-tags/

### Example:

    <link data-n-head="ssr" rel="alternate" hreflang="de" href="https://oddspedia.com/de">
    <link data-n-head="ssr" rel="alternate" hreflang="pt" href="https://oddspedia.com/br">
    <link data-n-head="ssr" rel="alternate" hreflang="es" href="https://oddspedia.com/es">
    <link data-n-head="ssr" rel="alternate" hreflang="it" href="https://oddspedia.com/it">
    <link data-n-head="ssr" rel="alternate" hreflang="ru" href="https://oddspedia.com/ru">
    <link data-n-head="ssr" rel="alternate" hreflang="ja" href="https://oddspedia.com/ja">
    <link data-n-head="ssr" rel="alternate" hreflang="bg" href="https://oddspedia.com/bg">
    <link data-n-head="ssr" rel="alternate" hreflang="en-US" href="https://oddspedia.com/us">
    <link data-n-head="ssr" rel="alternate" hreflang="nl" href="https://oddspedia.com/nl">
    <link data-n-head="ssr" rel="alternate" hreflang="es-MX" href="https://oddspedia.com/mx">
    <link data-n-head="ssr" rel="alternate" hreflang="fr" href="https://oddspedia.com/fr">
    <link data-n-head="ssr" rel="alternate" hreflang="x-default" href="https://oddspedia.com/">

### Data Endpoints:

**Hasura endpoint Dev:**

scores_hreflang_dev

**Hasura endpoint Prod:**

scores_hreflang

**Comment by jonsnowpt** [comment]
@migbash 

This "null" does not seem correct.

<img width="947" alt="Screenshot 2022-04-27 at 08 11 52" src="https://user-images.githubusercontent.com/37311649/165462430-7cfdbcdc-ae0c-4d16-a630-34cba80f7fbe.png">

**Comment by migbash** [comment]
Updated and reflected in the next `pull-request`
