### ISSUE TITLE
Google Analytics not working correctly

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#281]
it seems that the Google Analytics integration is not working correctly, for Svelte we need to use a different approach.

### Possible solution:

https://github.com/beyonk-adventures/svelte-google-analytics

https://tute.io/google-analytics-svelte-sapper

**Comment by migbash** [comment]
Issue with the `https://github.com/beyonk-adventures/svelte-google-analytics` `npm - library`
