### ISSUE TITLE
Featured Match Place Holder Translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#286]
Add the translations for the featured_match widget using the Hasura endpoint.

<img width="568" alt="Screenshot 2022-03-24 at 10 46 53" src="https://user-images.githubusercontent.com/37311649/159900031-825f734f-4dc2-4ac4-a24d-afb82c0c1d35.png">

**Hasura endpoint:**

widget_featured_match_translations

**Column:**

place_holder

**Json example:**

{"no_matches":"No matches available","info":"Sorry, at this time there is no featured match available"}

PS: Update the widget on the content platform.

**Comment by migbash** [comment]
**NOTES**

- [x] cache
- [x] frontend
