### ISSUE TITLE
Best Goal scorers - Wrong player information on the SEO results

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#291]
In the international version, we have 15 players but in the SEO results, there are much more players. It should have the same number of players.

<img width="546" alt="Screenshot 2022-03-28 at 18 24 09" src="https://user-images.githubusercontent.com/37311649/160453336-3543d315-afd5-403d-81f7-3e71c414ea8e.png">

Simulation here:

https://totheweb.com/learning_center/tools-search-engine-simulator/

**Comment by migbash** [comment]
Keep as it is
