### ISSUE TITLE
Best Goal Scorers - H2 title not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#296]
It seems the widget title has not been specified as an H2 title:

The widget title should be identified as an H2 title.

**Comment by migbash** [comment]
Corrected

**Comment by jonsnowpt** [comment]
@migbash 

Still missing:

<img width="1005" alt="Screenshot 2022-03-30 at 07 48 26" src="https://user-images.githubusercontent.com/37311649/160768994-06c84dd5-e7b0-4391-8063-68a56d73cd3e.png">

**Comment by migbash** [comment]
Corrected
