### ISSUE TITLE
Add Google Analytics to the Scores Platform - Header

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#3]
We need to add the GA code to the Scores platform, this should be added on the Header to be available on all platform.

GA-Code:

UA-60160331-9

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-60160331-9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-60160331-9');
</script>
`

**Comment by migbash** [comment]
Completed
