### ISSUE TITLE
Performance issues - Unused JS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#307]
Since the last deployment the Lighthouse results decrease significantly, check the report to see if we can improve the performance.

<img width="1082" alt="Screenshot 2022-03-31 at 08 16 00" src="https://user-images.githubusercontent.com/37311649/160999120-d2de5ae3-273a-45ad-bf13-c54c15d8f5f7.png">

<img width="830" alt="Screenshot 2022-03-31 at 08 16 12" src="https://user-images.githubusercontent.com/37311649/160999161-38cc3549-56d9-4cfb-9f36-55554bb1504a.png">

<img width="2487" alt="Screenshot 2022-03-31 at 08 16 40" src="https://user-images.githubusercontent.com/37311649/160999332-ef39beb4-f1da-4d81-bc3b-6915d095fb6f.png">

<img width="874" alt="Screenshot 2022-03-31 at 08 21 20" src="https://user-images.githubusercontent.com/37311649/161000052-bb1dd737-724c-45b1-a4c9-5df020e63860.png">

Suggestions:

https://web.dev/unused-javascript/?utm_source=lighthouse&utm_medium=devtools

https://www.reddit.com/r/sveltejs/comments/tih8sx/pagespeed_lighthouse_reduce_unused_javascript/

**Comment by migbash** [comment]
Looking for solution and waiting for `sveltekit` tested response
