### ISSUE TITLE
ublock preventing the platform to operate normally 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#323]
We have received a few reports from users who aren't able to view the platform contents correctly when using unlock.

https://ublockorigin.com/

This is an AD Blocker, it should not block the website content.

<img width="1636" alt="Screenshot 2022-04-06 at 12 12 46" src="https://user-images.githubusercontent.com/37311649/162167621-4112bf33-50e4-4357-9b61-9156de7b50d0.png">

After exchanging some messages this could be as simple as the DIV names that are originating the issue.

**Comment by jonsnowpt** [comment]
From my understanding, the issue is when the country is not detected. Can we load a default version for when no country is detected?

**Comment by migbash** [comment]
**NOTES**

> Need further information:
- Browser used
- Ad-blocker used
- Screenshot of `dev-logs` on `browser` on occurrence.
- Location `(GeoJs)` of user

**Comment by jonsnowpt** [comment]
@migbash 

We will not be able to get that information at this time. I will close the issue and keep checking if it happens again so that we can pinpoint it.
