### ISSUE TITLE
Standings - Bad performance

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#335]
We are getting bad performance results on the new league table .js file, it has 734kb and almost half is not used, we had this issue in the past with the other widgets, please review and optimize.

<img width="2229" alt="Screenshot 2022-04-27 at 08 29 08" src="https://user-images.githubusercontent.com/37311649/165465289-8585895c-44b6-4529-8538-286246974270.png">

**Comment by migbash** [comment]
Linked to #314
