### ISSUE TITLE
Dropdown should close when clicking outside

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#36]
In this case, when clicking outside the dropdown area the open dropdown should close.

<img width="1435" alt="Screenshot 2021-11-30 at 08 03 03" src="https://user-images.githubusercontent.com/37311649/144008950-f6ed0705-f97f-4ac3-8430-194367e8cd58.png">

**Comment by migbash** [comment]
Added the ability for closing `dropdowns` from the click of outside
