### ISSUE TITLE
Footer CSS change and options added (Newsletter subscription is also not working)

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#371]
We have changed the footer design and added new options:

All translations and options are available on Hasura DB.

- [x] CSS correctly implemented for all versions;
- [x] Translations working;
- [x] SEO Cache data added (Links)
- [x] Working on all languages;

Figma:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=32%3A1635

![Image](https://github.com/Betarena/scores/assets/37311649/3ca1ef7b-4496-457c-b534-ce2c0c5f78a8)

EN:

Changes in the links and order, the subscribe newsletter option, and CSS.

- Removed the Betting tips link;
- Discord  = https://discord.com/invite/vx7p9bd
- Telegram = https://t.me/betarenaen
- Medium = https://medium.com/@betarena-project
- Twitter = https://twitter.com/betarenasocial
- LinkedIn = https://www.linkedin.com/company/betarena
- Github = https://github.com/betarena
- Change Log = https://headwayapp.co/betarena-changelog

Add the "Status" option: https://stats.uptimerobot.com/PpY1Wu07pJ

====

**Comment by migbash** [comment]
> **Note**
> Created offspring task ➤ #<-github-issue-number->.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] We are missing "x" and also the order is not correct it should be:

Discord
Telegram
x 
Medium
LinkedIn 
Github 
Change Log

- [ ] Missing the hovers over the text and button;
- [ ] Tablet version the CSS is not correct at the bottom;



![Image](https://github.com/Betarena/scores/assets/37311649/6e972ef5-9da4-4274-81c8-9ccc16964f10)


Correct version:



![Image](https://github.com/Betarena/scores/assets/37311649/b25ce149-afca-473a-b9d9-39b665916b81)

**Comment by migbash** [comment]
> **Note**
> Corrected, awaiting `🚀 deployment`.

**Comment by jonsnowpt** [comment]
@migbash 

The links should be "_blank"
