### ISSUE TITLE
Sports Names are repeating

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#38]
Since we add the EN label to the buttons it is showing, it shouldn't.

<img width="1392" alt="Screenshot 2021-11-30 at 08 10 09" src="https://user-images.githubusercontent.com/37311649/144009536-2f6ba70e-62f3-4ee1-9c33-fd4e6f8ec265.png">

**Comment by migbash** [comment]
Amended - updated to fit in with the DB incoming `data`
