### ISSUE TITLE
On mobile and tablet there is no space on the right side for the slider

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#40]
So that the user can understand that it should swipe to check other sports, the space on the right side does not exist. Check images,

<img width="424" alt="Screenshot 2021-11-30 at 08 16 29" src="https://user-images.githubusercontent.com/37311649/144010370-31d986da-3fe0-4405-94ec-cacc047c8ec0.png">

![Screenshot 2021-11-30 at 08 17 50](https://user-images.githubusercontent.com/37311649/144010401-85695733-9090-41cb-be28-fb51b53f3532.png)

**Comment by migbash** [comment]
This is no longer applicable ? 

New design:

![image](https://user-images.githubusercontent.com/20924663/144169371-2951b5f7-3285-470c-b907-3d257060fccf.png)

Implemented according to the design
