### ISSUE TITLE
Frontend Widget football_Fixtures_Odds

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#451]
### Versions supported:

This widget will be available on all versions, Desktop, Tablet, and Mobile.

<img width="952" alt="Screenshot 2022-07-04 at 08 48 56" src="https://user-images.githubusercontent.com/37311649/177107451-a69b26e6-7eb5-4af0-a39d-9fcc6f3b7727.png">

### Initial State:

The widget should have the placeholder available when the data is being loaded.

### Other relevant information:

The widget will use Hasura and Firebase for real-time evens when the fixtures are occurring.

### Versions:

The widget is available in the Light and Dark theme.

### Other remarks:

At this first phase of development, the odds will not be available.

The date and fixtures time information will vary depending on the visitor computer date and time. This means that some fixtures that will be in the 5th of the Month in Portugal may be fixtures from the 4th or 6th, depending from the timezone.

The winner team should have a different color from the team that is is loosing or lost.

We need to respect also the color codes for the date and time of the fixtures.

### Data Endpoints:

**Hasura endpoint Dev:**

```
historic_fixtures_dev
scores_widget_football_fixtures_odds_translations_dev
scores_general_translations_dev
scores_football_seasons_details_dev
sportsbook_details_dev
```

**Hasura endpoint Prod:**

```
historic_fixtures
scores_widget_football_fixtures_odds_translation
scores_general_translations
scores_football_seasons_details
sportsbook_details
```

**Firebase_endpoint**

`livescores_now`

### Data Available: 

```
Rounds and weeks = scores_football_seasons_details + round_data + scores_general_translations
Day and Month = historic_fixtures + "league_id" + "time" +  scores_general_translations (Filter fixtures between dates or rounds to get fixtures day information, varies depending on the computer date and time of the end user) 
Fixture Date = historic_fixtures + "time" (Varies depending on the computer date and time of the end user)
Fixture Live Time Information (Status LIVE) = livescore_now  + ""minute": 13,"
Team Names = historic_fixtures + "home_team_name" + "away_team_name"
Red Cards = historic_fixtures + "cards"
Tip = tip_link_wp + scores_general_translations
Fixture Link = fixture_link_wp
media_link = historic_fixtures + media_link + "video_link"
Betting Site Icon = sportsbook_details (GEO or forced header option)
Score = historic_fixtures + "ft_score"
```

### SEO Cache data:

Team names, fixtures links, tip links and media links.

### Google Analytics Events:

Add GA events to the betting site icon:

`logo event name = betting_site_logo_football_fixtures_odds_tournament`

### Placeholder when there is no content:

Add the default placeholder to appear when no content is loaded.

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=32%3A1635

**Comment by migbash** [comment]
@jonsnowpt Still working on the `widget` implementation on the frontend, almost done, with remaining tasks:

- [ ] `Real-time` functionality
- [ ] `2h_updated` backend -> frontend communication to update target fixtures
