### ISSUE TITLE
Dealing with Multi-Stage Seasons from Major Leagues

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#456]
For example, leagues like Argentina (Superliga) has its most recent season [2022, 20/21, 2020] as `non-Regular Seasons` with various nested group-stages for the seasons. Respective `seasons_ids` [17708, 17956, 19353]. 

By contrast, previous seasons are of `Regular Type` = `season_id`: 16361

**Comment by jonsnowpt** [comment]
We already have a new approach to this multi-stage competition.
