### ISSUE TITLE
Dealing with error of Win Probabilities Generation

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#457]
`Athletico PR` has:
`current_season_id`: 19152

`Palmeiras` has:
`current_season_id`: 19434

despite both belonging to the same `season_id` of major Serie A league from Brazil

**BREAKING**

Prevents the appropiate generation of the `Win Probability` for the inability of the `Athletico PR` and other similar teams identification of the `?include=upcoming` sportmonks parameter:

**❌ Athletico PR**
https://soccer.sportmonks.com/api/v2.0/teams/3432?include=upcoming,stats&seasons=19152
^ no `upcoming` data is generated, despite having upcoming fixtures from other endpoints...

**✔ Palmeiras**
https://soccer.sportmonks.com/api/v2.0/teams/3422?include=upcoming,stats&seasons=19434

**Comment by jonsnowpt** [comment]
@migbash 

Should be fixed, please confirm!

**Comment by migbash** [comment]
@jonsnowpt confirmed, awaiting `CRON` update to verify and see if any other team has the same issue
