### ISSUE TITLE
Score AHREFS

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#465]
We have several issues in the AHREFS score that should be reviewed:

<img width="1416" alt="Screenshot 2022-07-01 at 15 42 43" src="https://user-images.githubusercontent.com/37311649/176916473-d3e14634-f317-4204-874c-2be1f1d06fc4.png">

- [x] Review 500 Status code

There are several links that are not accessible and return 500 internal server errors. The issues are:

- URLs format errors:  https://scores.betarena.com/ro/fotbal/italia/serie-d:-girone-a  (these results should be flattened to https://scores.betarena.com/ro/fotbal/italia/serie-d-girone-a removing the ":" 

---

- [x] Also all countries should have a redirect to the main page at this time;
- [x] Also we must confirm that only "domestic" links are available on the crawl;

**Comment by migbash** [comment]
Related #468 

@jonsnowpt the caching was not made for the `PROD` , all seems to be working fine, please check previously wrong links.
