### ISSUE TITLE
Security updates

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#494]
<img width="988" alt="Screenshot 2022-08-04 at 09 45 44" src="https://user-images.githubusercontent.com/37311649/182804648-39b9702f-b9e6-47c6-8634-500639a5e52d.png">

**Comment by migbash** [comment]
[DISMISSED]

![Image](https://user-images.githubusercontent.com/20924663/184632576-1eec9947-2319-4000-aeb2-788d49cdfca2.png)
