### ISSUE TITLE
Language menu option

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#495]
At the top of the language selection option, the chosen language should not appear as an option in the dropdown. Also, the order should always be the same despite the selected language.

![Screenshot 2022-08-04 at 09 47 01](https://user-images.githubusercontent.com/37311649/182805165-b0339c07-48a7-4a01-8d57-42875f7d8468.png)

**Comment by migbash** [comment]
`Fixed` upon next `DEV` deployment

**Comment by jonsnowpt** [comment]
@migbash 

Missing the "SE" option.




![Image](https://user-images.githubusercontent.com/37311649/186196939-737f5126-4d7a-411c-93d0-9792f5ea23b5.png)

**Comment by migbash** [comment]
@jonsnowpt cache on `DEV` needs updating

**Comment by jonsnowpt** [comment]
@migbash ignore then, since we are moving most of the endpoints to the PROD DB

**Comment by jonsnowpt** [comment]
Testing comments.
