### ISSUE TITLE
Missing the new season

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#503]
In the same way, it happened in the Primeira Liga, it seems that new seasons seem to be loading in a lot of tournaments, for example:

https://betarena-scores-platform.herokuapp.com/football/albania/superliga

At this time, we already have information for the new season.

![Screenshot 2022-08-08 at 08 38 21](https://user-images.githubusercontent.com/37311649/183365535-2ce0930e-5175-49e7-a4cf-7e85353b54e2.png)

**Comment by migbash** [comment]
`Updated`
