### ISSUE TITLE
Data not available on the provider but showing on the standings stats

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#513]
![Screenshot 2022-08-09 at 22 02 25](https://user-images.githubusercontent.com/37311649/183760963-e0838ca2-e065-4365-adf7-7aab9ad76230.png)

![Screenshot 2022-08-09 at 22 03 42](https://user-images.githubusercontent.com/37311649/183761118-880d5c26-a4c1-4173-b8b7-7c8a6c450ad2.png)

https://betarena-scores-platform.herokuapp.com/br/futebol/brasil/serie-b

https://betarena-scores-platform.herokuapp.com/br/futebol/brasil/serie-c

**Comment by migbash** [comment]
Related `#457`
