### ISSUE TITLE
Missig team logos

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#526]
Missing team logos in the Armenian Premier League:

https://scores.betarena.com/football/armenia/premier-league

![Image](https://user-images.githubusercontent.com/37311649/184379856-a56c2012-66e9-4ae4-ac5e-56fef3a06d06.png)

**Comment by migbash** [comment]
@jonsnowpt Fixed

Looks like for some reason we had 19,000 teams of the 29,000 total available from Sportmonks. Eventually, as data updates, missing logos will be updated automatically.
