### ISSUE TITLE
Tournaments - La Liga Missing player information and has data for teams that didn't played yet

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#530]
The standings show data for teams without any fixtures. Also, there is no information about the best players.

https://scores.betarena.com/pt/futebol/espanha/la-liga

![Image](https://user-images.githubusercontent.com/37311649/184528334-75c65d5b-46b8-4362-a17e-e3f4ce37a3da.png)

**Comment by jonsnowpt** [comment]
@migbash still happening:



![Image](https://user-images.githubusercontent.com/37311649/184595218-09539260-b8e5-4f1f-9957-29ed70a0a11f.png)

**Comment by migbash** [comment]
@jonsnowpt Reason #543

**Comment by jonsnowpt** [comment]
@migbash 

Top players are disappearing from the platform without any reason:



![Image](https://user-images.githubusercontent.com/37311649/184934964-7ec4e244-cac2-4cee-9eaf-0818d34ef133.png)

**Comment by migbash** [comment]
Issue identified. `Fixed` upon next `DEV` deployment
