### ISSUE TITLE
Best Players not being updated

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#532]

**Comment by jonsnowpt** [comment]
The Best players are not being updated for any tournament at this stage.

https://scores.betarena.com/pt/futebol/portugal/primeira-liga



![Image](https://user-images.githubusercontent.com/37311649/184528481-874bc387-3916-4cc6-b480-91bb6b419bfc.png)

**Comment by migbash** [comment]
`Heroku memory allocation JavaScript Error` - too much is updated at once for:
- `Tournament | Standings`
- `Top Players`
