### ISSUE TITLE
Too much data being used 3 to 5GB daily

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#534]
We are using too much data now, an average of 3 to 5GB.

We need to pinpoint which endpoints are using so much data and determine how this can be decreased.

![Image](https://user-images.githubusercontent.com/37311649/184533511-074c645c-376a-4dc4-a265-d0dee646d375.png)

**Comment by migbash** [comment]
@jonsnowpt In order to reduce the `data` Hasura current consumption:
- `CRON` times can be increased to higher intervals for fewer `read/writes`
- A hybrid of `cache-update` and `further chunking` can be done to decrease `read/writes`

**Comment by jonsnowpt** [comment]
@migbash 

Wich crons?

**Comment by migbash** [comment]
@jonsnowpt

**Comment by jonsnowpt** [comment]
@migbash we are working on this at this time and will keep experimenting and refining to limit the usage without harming the application functionality.

**Comment by jonsnowpt** [comment]
This issue has been corrected and verified.
