### ISSUE TITLE
Hreflang and HTML lang mismatch

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#535]
https://scores.betarena.com/br 

![Image](https://user-images.githubusercontent.com/37311649/184533654-6a4bcede-91ed-490c-a503-f5ade26d3012.png)

**Comment by migbash** [comment]
@jonsnowpt Should it be `pt-BR` for both ?

**Comment by migbash** [comment]
`Fixed` upon next `DEV` deployment

**Comment by jonsnowpt** [comment]
Testing in prod
