### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#537]
We are getting application errors during the day, 122 in 24 hours.

![Image](https://user-images.githubusercontent.com/37311649/184541432-e5d33a6b-db36-4540-a726-1bbd23e37a19.png)

![Image](https://user-images.githubusercontent.com/37311649/184541371-1e2cd439-7dc3-44ea-bfc0-9dbae8b909c5.png)

**Comment by migbash** [comment]
Related to #542
