### ISSUE TITLE
Team statistics and season details updates happening at the wrong time

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#538]
The goal is to get the updates happening at 12pm (last-day matches). At this time, the update is happening sooner.

**Comment by migbash** [comment]
This was a test I was performing a manual update of the:

- `scores_team_statistics`
- `scores_football_seasons_details` + `sqaud`

Cause the update to happen sooner.

Still set to update on the usual 12:00 (01:00 GMT+1)

![Image](https://user-images.githubusercontent.com/20924663/184628721-7c71e673-ef32-46ad-8baf-aa57f160f857.png)

**Comment by jonsnowpt** [comment]
ok @migbash thanks!

**Comment by migbash** [comment]
Updated to `12pm` (13:00 GMT+1)

**Comment by migbash** [comment]
@jonsnowpt close issue ?
