### ISSUE TITLE
Standings wrong position when checking home and away

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#540]
When checking home and away standings, the positions do not appear correctly.

https://scores.betarena.com/pt/futebol/espanha/la-liga

![Image](https://user-images.githubusercontent.com/37311649/184626612-b5072eb1-cd4e-4098-8845-2c6d3e98e11b.png)

**Comment by migbash** [comment]
@jonsnowpt need the formula to calculate position when `start` of season has all teams with the same `points` of `0` from `Sportmonk`

**Comment by jonsnowpt** [comment]
@migbash, you can order it by points and alphabetically order!

**Comment by migbash** [comment]
`Fixed` upon next `DEV` deployment

**Comment by migbash** [comment]
@jonsnowpt ready for review

https://scores.betarena.com/es/futbol/inglaterra/premier-league

---

![Image](https://user-images.githubusercontent.com/20924663/186159327-40f00cd3-ba00-48eb-bf6a-d2d1c60ac70a.png)

![Image](https://user-images.githubusercontent.com/20924663/186159400-b51198c0-48a9-4ff0-8f6b-80b1965e8aea.png)
