### ISSUE TITLE
Problems changing language to SEI inside the tournaments

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#541]
Changing language to SE inside the tournaments page causes errors in the platform behavior.

https://scores.betarena.com/se/futebol/spanien/la-liga

**Comment by migbash** [comment]
@jonsnowpt `SE` translation inside `scores_widget_top_players_translations` missing: `show_more_less` field

**Comment by jonsnowpt** [comment]
@migbash  added.

**Comment by jonsnowpt** [comment]
@migbash even after making the requested change still having problems. Do you need to restart the cache somewhere?

**Comment by migbash** [comment]
@jonsnowpt updated cache for `translations` should be all working now

**Comment by jonsnowpt** [comment]
@migbash working, closing this issue.
