### ISSUE TITLE
Memory Overflow (Project Dependency Update)

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#542]
We appear to have a potential `memory leak` on the `PROD` Heroku, causing the app from time to time crash with the `Applciation Error` from #537.

Perhaps picked up by #494 [?]

![Image](https://user-images.githubusercontent.com/20924663/184627341-40e263c6-d401-4ba4-bbab-2fa44fded66d.png)

[Before & After latest deployment]

![Image](https://user-images.githubusercontent.com/20924663/184627657-947c7fcf-33f3-4048-8076-40ebe5272d4e.png)

Similar deployments on the `DEV` and `TESTING` identical versions on `Heroku` do not have the same issue.

**[FIX]**

- [ ] Update `Dependency Bot Security Suggestions`
- [x] Update `NPM` dependencies
- [x] Update `sveltekit` to `latest`
- [x] A/B test with `bull` workers files and packages removed from a `PROD` deployment
- [ ] tune `available memory` with `--max_old_space_size=2560`

**Comment by migbash** [comment]
Need to `debug` the issue on `PROD` deployment after completing the `backend` task

**Comment by jonsnowpt** [comment]
@migbash 

The issue persists:



![Image](https://user-images.githubusercontent.com/37311649/186615078-16fb22dd-4dcf-46c8-be56-c6ac35208365.png)

**Comment by jonsnowpt** [comment]
The issue has been identified, and since we are replacing the Livescore the issue will be closed.
