### ISSUE TITLE
Missing position Number

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#546]
Missing the position number here:

https://scores.betarena.com/football/armenia/premier-league

![Image](https://user-images.githubusercontent.com/37311649/184649333-ac83e428-52e0-4dd4-89a1-b09dfddc6203.png)

**Comment by migbash** [comment]
@jonsnowpt the `BKMA` has the `result`

**Comment by migbash** [comment]
@jonsnowpt Is this fixed ?

**Comment by jonsnowpt** [comment]
@migbash Done!

**Comment by jonsnowpt** [comment]
@migbash 

This has been changed but the issue persists:



![Image](https://user-images.githubusercontent.com/37311649/186189661-67e33f02-98b4-498c-b691-548cfc2da191.png)

**Comment by migbash** [comment]
@jonsnowpt needs the following addition to `color_codes_league_standings_positions`

`Relegation Play-off": "#FF3333"` - with a `lowercase` letter `o`

**Comment by jonsnowpt** [comment]
@migbash 

Done!
