### ISSUE TITLE
Top leagues not changing when selecting different languages

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#547]
The top leagues should change for each language selected, but it always shows the same:

https://scores.betarena.com/br

![Image](https://user-images.githubusercontent.com/37311649/184671417-a3860fe4-0879-4475-b528-7627a4abd269.png)

**Comment by migbash** [comment]
@jonsnowpt change based on `GEO`

**Comment by migbash** [comment]
@jonsnowpt This is working as expected, changing `GEO` changes the `Top 7 Leagues`

**Comment by jonsnowpt** [comment]
@migbash will be testing this on DEV when deployed.

**Comment by jonsnowpt** [comment]
This is going to be dealt in another issue.
