### ISSUE TITLE
Remove the type of tournament limit and change the selection based on supported leagues

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#549]
We will change the approach to published tournaments (and drafts) available to users.

Instead of the tournament type, what controls whether tournaments are published will now be the supported_leagues endpoint in Hasura.

### Steps:

**1. Remove the way that tournaments are being published**

We had a limit to only publish domestic tournaments, now we will publish all types.

Change this to publish all tournaments that are supported in `leagues_supported_filter`

**Hasura endpoint Dev:** 

leagues_supported_filter_dev

**Hasura endpoint Prod:** 

leagues_supported_filter

**Columns:**

`league_id`

https://cloud.hasura.io/project/1b086d12-8b64-462e-b7cc-f3f5e2c1702d/console/data/betarena_prod/schema/public/tables/leagues_supported_filter/browse

**Update frequency:**

In this case, we can use event triggers; if the DB is updated or changed will trigger this change.

**Comment by jonsnowpt** [comment]
@migbash 

Still not working.

https://betarena-scores-platform.herokuapp.com/football/india/hero-super-cup

**Comment by migbash** [comment]
@jonsnowpt `Fixed` 

![Image](https://user-images.githubusercontent.com/20924663/190091104-a567dba1-a63a-41c2-9588-aed081f8af92.png)

**Comment by migbash** [comment]
`Fixed` and updated to make use of the `leagues/tournaments` that **only** exist in the `supported_leagues_filters`
