### ISSUE TITLE
Missing data in the standings

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#552]
Noticed that some tournaments are missing data, like the Brazilian Serie A:

![Image](https://user-images.githubusercontent.com/37311649/185382720-898d05cf-7b98-4c06-95ee-c14fda692ae0.png)

**Comment by migbash** [comment]
@jonsnowpt what is the `URL` ?

**Comment by jonsnowpt** [comment]
@migbash 

https://scores.betarena.com/football/brazil/serie-b

**Comment by migbash** [comment]
@jonsnowpt wrong `current_season_id`

**Comment by jonsnowpt** [comment]
@migbash 

Reported to the provider, it was corrected a few hours later the issue happened again.

I will move this task out of the sprint but I will keep talking with the provider to sort it out.

**Comment by jonsnowpt** [comment]
Same issue has #505
