### ISSUE TITLE
Add odds from the Firebase to the Widget football_Fixtures_Odds inside the tournaments

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#553]
This is just an add-on to the existing football_fixtures_odds widget.

The goal is to have the odds available for all matches inside the widget.

There will be 2 types of odds, the pre-live and the live odds. The latest is not available on all markets, regions, and fixtures.

The odds will only be visible for not started fixtures or live ones; all games with the "FT" status will not have available odds. In this case, the placeholder will be visible.

![Image](https://user-images.githubusercontent.com/37311649/185453765-400d7c88-51b9-4c32-834f-f186e3f94539.png)

### Versions supported:

All versions are supported, Desktop, tablet, and mobile.

### Versions:

Dark and Light theme available.

### Other relevant information:

The betting site logos are the ones available in the Hasura endpoint:

**Hasura endpoint Dev:**

`sportsbook_details_dev`

**Hasura endpoint Prod:**

`sportsbook_details`

### Data Endpoints:

In this case, we use the Firebase Realtime DB, with a specific filter depending on whether the match is Live or Not-Started.

The odds are loaded using the country GEO, following the list in the endpoint:

**Hasura endpoint Dev:**

`sportsbook_details_dev`

**Hasura endpoint Prod:**

`sportsbook_details`

On pre-live fixtures (not yet started), we will be using the first 3 betting sites in the GEO region available in the endpoint, `sportsbook_details`, each odd being from one of those betting sites; if there are not enough betting sites in the region, the same one will supply all the odds.

On Live odds, the first betting site in the GEO region in the endpoint: `sportsbook_details` will supply all the odds.

**Firebase odds endpoint**

`https://betarena-rv-6b382.firebaseio.com/odds`

### Google Analytics Events:

`logo event name = tournaments_football_fixtures_odds`

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=32%3A1635

**Comment by migbash** [comment]
@jonsnowpt still working my way through the `odds` population for the widget
