### ISSUE TITLE
Change DEV Endpoints to use PROD

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#561]
Since we are going to start a new approach, the endpoints of the DEV platform become the same as those of PROD.

The exception is that new endpoints need to be first tested in the DEV database, and when confirmed to work properly, they are then moved to the PROD database and the endpoints updated accordingly.

**Comment by migbash** [comment]
Taking effect as of next `sprint` for `PROD` endpoints usage in `DEV` environment
