### ISSUE TITLE
Add Homepage Leagues List Links to the tournaments into the SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#565]
To increase the number of internal links present on the platform we should be adding the league's list links to each tournament:

![Image](https://user-images.githubusercontent.com/37311649/186658495-56dae823-2576-443a-9fe9-39f66e682210.png)

**Comment by migbash** [comment]
**NOTES**

- [x] cache `updated & deployed`
- [x] frontend
