### ISSUE TITLE
Postponed fixtures not working correctly

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#569]
The Benfica vs Paços Ferreira from round 3 was postponed to be played this week. If we scroll back to the correct round (3) the present one is (5) when the fixture is live it does not show any information in the correspondent round:

![Image](https://user-images.githubusercontent.com/37311649/187542036-1e8fa72a-a372-4e4f-9a01-afdc9429a081.jpeg)

Should be something like this:

![Image](https://user-images.githubusercontent.com/37311649/187542194-03f21fa6-940f-41e7-9ed7-15902b376f7c.png)

Also the fixtures is not showing in the correct week:

![Image](https://user-images.githubusercontent.com/37311649/187542450-79571c23-95bf-424c-8221-7dc10fd98487.jpeg)

As supposed:

![Image](https://user-images.githubusercontent.com/37311649/187542535-cdce828d-0646-42ab-a09a-4636002d9db9.png)

**Comment by migbash** [comment]
@jonsnowpt such instances will be updated `weekly` as per issue ? This will reflect the `fixture` update when cached

**Comment by jonsnowpt** [comment]
@migbash 

In this case, when a match has a postponed status it will trigger an update for all rounds in the season where the team competes.

(task to be included in another sprint)

**Comment by jonsnowpt** [comment]
When a "postponed" fixture is verified, we need to update all rounds for the season where it occurs.

**Comment by migbash** [comment]
**NOTES**

> Changes in fixture `status` / `time` / `team-name's` configured - with respective `cache` trigger

**Comment by jonsnowpt** [comment]
@migbash 

We continue to have issues here:

https://scores.betarena.com/football/turkey/super-lig

Round 24 do not have any fixtures.


![Image](https://user-images.githubusercontent.com/37311649/218790340-16da1935-664a-44c9-bb9d-ced683ac993d.png)

**Comment by migbash** [comment]
**NOTES**

> Unrelated to the `issue title` (not a `POSTP` issue)
