### ISSUE TITLE
Undefined on the date

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#570]
![Image](https://user-images.githubusercontent.com/37311649/187543575-0202a4f6-748c-4d9a-b020-5187b065cc12.jpeg)

**Comment by migbash** [comment]
@jonsnowpt incorrect `months_abbreviation` for `PT` translation in `scores_general_translations_dev`:

![Image](https://user-images.githubusercontent.com/20924663/187565859-c345f279-6e0f-45ce-8719-1d8418067978.png)

**Comment by jonsnowpt** [comment]
@migbash 

Corrected!
