### ISSUE TITLE
Missing lots of rounds

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#571]
The platform is missing lots of fixtures on future rounds.

https://betarena-scores-platform.herokuapp.com/br/futebol/italia/serie-a

![Image](https://user-images.githubusercontent.com/37311649/187545761-84f57590-7f2a-4c3f-b256-9163c665872d.png)

**Comment by migbash** [comment]
@jonsnowpt `historic_fixtures` endpoints need to be restarted to update the data after. Will increase `Hasura` data usage.

**Comment by jonsnowpt** [comment]
@migbash 

Yes, do it. I didnt add them because they just existed to the DEV and we need to the PROD DB now.

**Comment by migbash** [comment]
@jonsnowpt updated & fixed, rounds available until the end
