### ISSUE TITLE
Fixture links do not work

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#573]
None of the fixtures have links to the matches available.

![Image](https://user-images.githubusercontent.com/37311649/187624533-593f7793-a579-4f0b-b8f0-27db7e3a4780.png)

**Comment by jonsnowpt** [comment]
@migbash 

All that area should be clickable to navigate to the fixture-link, you can check how it works in the Live Score table we have at this time.

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
