### ISSUE TITLE
CSS Week and round color selection

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#574]
Present:

Wrong selection color and wrong default color (grey).

![Image](https://user-images.githubusercontent.com/37311649/187626514-cd9381b2-3ff4-4840-beea-93943035311a.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/187626570-6158141c-065c-4491-a2ef-e662cf2988af.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
