### ISSUE TITLE
CSS - Incorrect distance between the scores and the icons

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#577]
![Image](https://user-images.githubusercontent.com/37311649/187634943-2fe9cf37-458b-4685-9117-1a841d09781e.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/187634983-0e9b72be-6ac2-404b-a321-e102968664f1.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
