### ISSUE TITLE
CSS - Missing Hover navigation buttons

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#579]
![Image](https://user-images.githubusercontent.com/37311649/187636597-a3ea33d4-1385-4aff-9688-1d642b635027.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/187636699-8a16f898-ccbb-4136-bd3c-7a1fcd5abfa0.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
