### ISSUE TITLE
Missing tip links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#581]
Missing tip links in several fixtures:

![Image](https://user-images.githubusercontent.com/37311649/187638527-244d5133-406c-462e-b58b-58f8de84f28d.png)

![Image](https://user-images.githubusercontent.com/37311649/187638528-d9cb3f8b-2171-42eb-a381-d8a7d270f1d0.png)

**Comment by migbash** [comment]
`Fixed` and updated `data from past` month and available on `DEV`
