### ISSUE TITLE
CSS - Review dark theme colors and strokes / borders

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#583]
Present:

![Image](https://user-images.githubusercontent.com/37311649/187640041-fce31776-411f-4c7d-91c6-9322cb4064d9.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/187640013-163ced1c-7194-418d-85c3-c32b0f37032a.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
