### ISSUE TITLE
Updates stop working when leaving and getting back into the browser

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#585]
Unlike in our game table, when we check a live game the updates stop working if we exit and return to the browser (keeping the window open). 

This updates should resume if we come back without needing to refresh the browser.

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`

**Comment by jonsnowpt** [comment]
@migbash 

Still happening.

**Comment by jonsnowpt** [comment]
@migbash 

Ignore, now seems to be updating, will test further!
