### ISSUE TITLE
Wrong round

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#589]
The wrong round is loaded by default when in the last day of the round:

![Image](https://user-images.githubusercontent.com/37311649/187860885-10f360e9-f0e3-4ff8-9789-f0aa5a665efa.png)

https://betarena-scores-platform.herokuapp.com/football/england/premier-league

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
