### ISSUE TITLE
When searching by date lots of weeks do not have fixtures available

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#594]
![Image](https://user-images.githubusercontent.com/37311649/188262391-148f1d93-130c-43a2-8221-8fd63dcbb708.png)

**Comment by migbash** [comment]
@jonsnowpt should these weeks be hidden ? And only those with fixtures should be shown ? And what should be the `week <number>` in such cases of `skipped` empty weeks ?

**Comment by jonsnowpt** [comment]
@migbash 

The issue is that we have games on those dates:



![Image](https://user-images.githubusercontent.com/37311649/188282765-96b1706e-57db-4aba-9a2a-3526237fd201.png)

**Comment by jonsnowpt** [comment]
@migbash 

The week number should stay with the number order, even when existing weeks without fixtures:

14, 15, 16....



![Image](https://user-images.githubusercontent.com/37311649/188312647-b9769bc4-cd13-48b4-9bbe-8b5906f37270.png)
![Image](https://user-images.githubusercontent.com/37311649/188312646-94d1e8af-bd9f-4e21-9294-2af19659503f.png)
