### ISSUE TITLE
CSS - Play Icon wrong border color

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#595]
Present:

![Image](https://user-images.githubusercontent.com/37311649/188269284-85601181-20d2-4fab-80d7-615adbb6961b.png)

Figma:

![Image](https://user-images.githubusercontent.com/37311649/188269277-837881a7-f5a9-4bc3-a4cd-9c9ab5533779.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
