### ISSUE TITLE
CSS - Red cards wrong format

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#596]
In the dark version, the border is incorrect.

Present:

![Image](https://user-images.githubusercontent.com/37311649/188269358-268a2a33-a70e-491f-8421-16a1ed2f82eb.png)

Figma:

![Image](https://user-images.githubusercontent.com/37311649/188269362-ebe03ab2-62cc-4d3b-ac68-6e480a9c1bd5.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
