### ISSUE TITLE
Live (Firebase) the cards are inversed

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#598]
On live matches the cards are appearing in the inverse order:

Incorrect:

![Image](https://user-images.githubusercontent.com/37311649/188269970-5fae0f42-bd36-4e87-af18-6dc5b82c6156.jpg)

Correct:

![Image](https://user-images.githubusercontent.com/37311649/188269985-dc6ab546-cd0d-483b-9324-eda9a60b48dc.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
