### ISSUE TITLE
Populate seasons from 21/22 Historic Fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#605]
We will populate the data for the games widget (21/22). Populate the data of all seasons for those years.

This data will not use the cache to be visualized because it is sporadically accessed and does not justify using the upstash.

Using this logic, we should create the following method:

Only `current_seasons` from the `historic_fixtures` endpoint are added to the cache to Upstash. All others will not be added.

**Comment by migbash** [comment]
@jonsnowpt it's being populated

**Comment by jonsnowpt** [comment]
@migbash 

Do you confirm that Upstash is not being used here?

**Comment by migbash** [comment]
@jonsnowpt it's not, we are just populating the `21/22` fixtures data

**Comment by migbash** [comment]
@jonsnowpt This is now complete, we went from - to:

![Image](https://user-images.githubusercontent.com/20924663/192611865-2b921c34-702f-4ed5-bf2e-5fea45ac142a.png)

**Comment by jonsnowpt** [comment]
@migbash 

We need the matches to be visible in the frontend.
