### ISSUE TITLE
Data is not being updated

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#606]
Players' data is not being updated. Also, the names do not seem correct; use the same field used in the homepage widget:

![Image](https://user-images.githubusercontent.com/37311649/188572909-ecafe3ad-ba20-44f6-9d30-89b28902f575.png)

![Image](https://user-images.githubusercontent.com/37311649/188572910-3e2d7c93-0217-4f50-a7a7-a8578a136eff.png)

**Comment by migbash** [comment]
@jonsnowpt using the `common_name` as outlined by the task #425

![Image](https://user-images.githubusercontent.com/20924663/188603996-9b4441de-3d1d-4430-ba52-f59b6fba0ccc.png)

What field to use instead ?

**Comment by jonsnowpt** [comment]
@migbash 

What are we using in the homepage top players?

**Comment by migbash** [comment]
Related #543 (hasura query connection issue), need to chunk up the request

![Image](https://user-images.githubusercontent.com/20924663/188608388-3248ec34-f81f-4ec5-bc39-d33fe131a2aa.png)
