### ISSUE TITLE
Tournaments - Players Avatars issue

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#607]
There are a lot of players missing the correct Avatar inside the tournaments.

The issue is caused because of an incorrect link:

The link that is being loaded is:

https://cdn.sportmonks.com/images/soccer/leagues/16/186320.png

and it should be:

https://cdn.sportmonks.com/images/soccer/players/16/186320.png

![Image](https://user-images.githubusercontent.com/37311649/188611050-d2ed831d-065a-46c4-b3a0-335e7e67f327.png)

**Comment by migbash** [comment]
`Fixed` and available in the next `pull-request` deployment

![Image](https://user-images.githubusercontent.com/20924663/189978458-d1db7646-cb58-478a-b403-c45c3e212273.png)
