### ISSUE TITLE
All of this fixtures have betting tips

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#616]
![Image](https://user-images.githubusercontent.com/37311649/189518558-bf32d549-f907-4655-8ce6-b5ca6462f549.png)

**Comment by migbash** [comment]
`Fixed` and available in the next `pull-request` deployment

![Image](https://user-images.githubusercontent.com/20924663/189977905-79a168c7-47c3-4ef1-9d6f-7a5819c40bee.png)
