### ISSUE TITLE
Players incorrect data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#619]
https://scores.betarena.com/br/futebol/portugal/primeira-liga

The total number of goals is incorrect, and probably the rest of the data:

![Image](https://user-images.githubusercontent.com/37311649/189623360-5699fa00-c01b-491f-b0c9-87274b91db02.png)

![Image](https://user-images.githubusercontent.com/37311649/189623385-e50d6b17-e5d3-493b-bc77-86559f812446.png)

**Comment by migbash** [comment]
@jonsnowpt looks like a `Sportmonks` issue, but monitoring of `top_players` for daily 12pm updates is to be continued.

**Comment by jonsnowpt** [comment]
@migbash 

Already reported. Thanks!
