### ISSUE TITLE
Hasura lagging

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#620]
Hasura seems to be lagging with the `Cron Events` since the slow-down and identification of the inconsistencies in the data... last `ping` time at `22:25` when it was already `22:50` and counting, with heavy delay...

![Image](https://user-images.githubusercontent.com/20924663/189773316-e1b2b1be-0123-4d66-88c3-d61916186750.png)
(^) last pinged endpoint

However, using `Postman` all is working correctly...

**Comment by migbash** [comment]
Related #609 #616 #618 #607 
@jonsnowpt reason for no up to date data... something is throttling `Hasura Cron Events`

**Comment by jonsnowpt** [comment]
@migbash no, that I'm aware off; you can open a support request with Hasura if you need.

**Comment by jonsnowpt** [comment]
There is another task to proceed with the cron migration.
