### ISSUE TITLE
CSS - Missing lines

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#622]
FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/189986487-de0a9c75-47b8-4cdf-9538-41b61811e7b2.png)

Present:

![Image](https://user-images.githubusercontent.com/37311649/189986486-7289f9d3-14c5-44e6-9a2b-e5d208a9c29e.png)

**Comment by migbash** [comment]
`Fixed` and updated in the next `pull-request` deployment
