### ISSUE TITLE
Missing  preloader when loading the data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#624]
The preloader is missing in this widget:

![Image](https://user-images.githubusercontent.com/37311649/189989627-8202b365-df0d-4c80-b23f-a68d0bfb9fb7.png)

**Comment by migbash** [comment]
`Fixed` and available in the next `pull-request` deployment

**Comment by jonsnowpt** [comment]
Are you sure? I get this:

![Image](https://user-images.githubusercontent.com/37311649/190104993-fef13c27-d873-43e3-9cee-68e21e2f8424.png)

**Comment by migbash** [comment]
@jonsnowpt I will slow it down to show it

**Comment by migbash** [comment]
`Fixed` and available in the next `pull-request`
