### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#628]
The links in the sitemaps should only contain the supported leagues:

https://scores.betarena.com/sitemap.xml

**Comment by migbash** [comment]
@jonsnowpt can you give an example which are not meant / missing from there ?

**Comment by jonsnowpt** [comment]
@migbash 

For example:

https://scores.betarena.com/br/futebol/espanha/primera-nacional-femenina---group-7 

It seems that is sending everything.

**Comment by migbash** [comment]
`Fixed` and updated in the next `pull-request`
