### ISSUE TITLE
Timezone fixtures not working

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#631]
The timezone is not working.

If we visit the platform from Brazil, the following fixtures have the same hour as when we visit from Portugal (also incorrect, the fixtures are one hour ahead in Portugal. The fixture's time is incorrect, and the day is also incorrect for some fixtures.

https://scores.betarena.com/football/portugal/primeira-liga

![Image](https://user-images.githubusercontent.com/37311649/190139607-7197c7d7-373b-4196-bf0a-626bf225dab9.png)

**Comment by migbash** [comment]
`Fixed` and available in the next `DEV` pull-request `deployment`
