### ISSUE TITLE
Add tournament links into Featured Match Widget

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#632]
We will add the tournaments' links into the widgets where the leagues are mentioned. In this case, the Featured Match Widget.

### Versions supported:

It will be available on all versions desktop, tablet, and mobile.

### Other relevant information:

The URLs of the tournaments will vary depending on the language.

### Data Endpoints:

**Hasura endpoint Prod:**

`scores_tournaments`

Columns:

```
tournament_id
lang
urls
```

### SEO Cache data:

All tournament links should be added to the SEO Cache.

**Comment by migbash** [comment]
@jonsnowpt working without any issues, with the `widget league_name` having the appropiate `URLS` for the navigation to the correct `tournament page` - under the correct translation
