### ISSUE TITLE
Top Players Show more the fixtures disappear to the bottom

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#633]
![Image](https://user-images.githubusercontent.com/37311649/190145951-1b72a48f-ec34-4cfd-8d04-5413183d3e66.png)

**Comment by migbash** [comment]
@jonsnowpt what `browser` are using to get this error ? Can't seem to replicate it on `Safari 16` 

![Image](https://user-images.githubusercontent.com/20924663/190229711-1efefe21-a487-4165-acce-1ebe5517c285.png)

**Comment by jonsnowpt** [comment]
@migbash tested on Firefox

**Comment by migbash** [comment]
@jonsnowpt huh, can't see that error. Have you refreshed the page `hard refresh` the `DEV` ?

![Image](https://user-images.githubusercontent.com/20924663/190231032-7d7e2bdb-b3c1-4275-9480-9568bea9a865.png)

Can't replicate on any browser on `DEV` / `locally`

**Comment by jonsnowpt** [comment]
@migbash it does not happen on DEV, ignore!
