### ISSUE TITLE
Hasura metadata clean

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#636]
Need to update the `hasura metadata` to `clean` the **past** `processed events` and `invocation logs`.

https://hasura.io/docs/latest/migrations-metadata-seeds/manage-metadata/
https://hasura.io/docs/latest/scheduled-triggers/clean-up/

**Comment by migbash** [comment]
**NOTES**

> Awaiting `confirmation` from Hasura team on steps to clean metadata, as `guides` and `docs` not working as intended.

**Comment by jonsnowpt** [comment]
@migbash 

Going back to Icebox?
