### ISSUE TITLE
Deploy the `cache` application as standalone / worker

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#637]
Currently we have a separate `app` that is running for the update of the `cache` on `heroku` with a `1GB` RAM configuration, but it at often times goes overboard - but does not crash.

The app needs to be modified to solely be a server which accepts `jobs` / `requests-pings` to update the `cache`. 

Also, perhaps it needs to be outsourced to a separate server deployment with more than `8GB` of `RAM` to better manage the load of the `cache` at peak times.

---

Revisit `#2`

Currently, the `cache` is being run by a separate application on `Heroku` that handles the `cache` generation.

This is rather expensive, as a `1Gb` configuration is required to not `crash` the `app` to generate the cache`.

The application has been deployed separately due to the fear of overloading the main `website` hosted on `scores-platfrom-prod` and just have it be used for the `serving` of the `website` to the users - and not worry about background long intensive tasks.

---

Heroku ultimately is expensive, when alternative hosting platforms exist where the `cache` app can be deployed. We need to migrate and reconfigure this `cache` app `(scores-testing-app)` to only handle endpoints for long intensive tasks.

**Comment by jonsnowpt** [comment]
@migbash 

I need to know the specifications for this instance to prepare the new Cloud VM.

Requirements:

RAM
Disk Space
Image: Ubuntu, Debian, Fedora, Docker.

**Comment by migbash** [comment]
@jonsnowpt 

Any `Cloud VM` will do, but let's use:
- `Ubuntu 22` version, with `Docker`. 
- Although `Docker` can be installer later.
- 4 GB of RAM necessary, for now.
