### ISSUE TITLE
Flag Icon stopped working Featured Match

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#639]
![Image](https://user-images.githubusercontent.com/37311649/190591588-22ec3173-7909-4797-8fd9-a3627b5065a9.png)

**Comment by migbash** [comment]
@jonsnowpt testing the `missing` icons images and will check over today for more similar errors on `DEV`

**Comment by jonsnowpt** [comment]
CSS = Should be aligned

![Image](https://user-images.githubusercontent.com/37311649/191435610-325a95e5-d5a2-4b55-9957-d57c355f66ca.png)


Figma:



![Image](https://user-images.githubusercontent.com/37311649/191435922-2ac0c543-994b-454a-b501-c16dbc4e4c27.png)
