### ISSUE TITLE
Fixtures missing all status beside FT

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#646]
There are several states that matches can have besides FT, for example, Cancl AET, Posp. At this time, it seems that only FT is being considered. In the following matches they were postponed, but no information is visible:

![Image](https://user-images.githubusercontent.com/37311649/191001679-cdb66659-6bcc-495d-838a-043dd7523ba1.png)

**Comment by migbash** [comment]
@jonsnowpt `CACNL` translation is missing from `scores_livescore_football_translations`

**Comment by jonsnowpt** [comment]
@migbash working on that.

**Comment by jonsnowpt** [comment]
@migbash 

Added all translations.
