### ISSUE TITLE
Missing Media Links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#656]
![Image](https://user-images.githubusercontent.com/37311649/191062110-9dac0f44-84c0-4d55-8ac0-bca1b666b3a7.png)

![Image](https://user-images.githubusercontent.com/37311649/191062176-b63aa5b3-357a-4bde-9392-582d572b0a8e.png)

**Comment by jonsnowpt** [comment]
@migbash 

Still missing.

![Image](https://user-images.githubusercontent.com/37311649/191436324-98306417-aa67-4ccd-826f-f5e3256f6c35.png)

**Comment by migbash** [comment]
@jonsnowpt it is going to take a bit to go back and re-populate the `media-links` due to them being a 24h `CRON` job, checking with `matching team names` to insert the `media-links`.

I will need to re-populate and observe if such issue happens again with other fixtures

**Comment by jonsnowpt** [comment]
@migbash The important thing is that it does not happen in the future; there are no worries about missing in the previous fixtures.
