### ISSUE TITLE
Missing fixtures in the Tournament

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#682]
https://scores.betarena.com/br/futebol/republic-of-ireland/premier-division

![Image](https://user-images.githubusercontent.com/37311649/191997228-6b74fc56-f9ed-44c5-b1fa-2363e0240402.png)

![Image](https://user-images.githubusercontent.com/37311649/191997229-3d7b3eda-f139-4c62-afaa-02b60418bd25.png)

**Comment by migbash** [comment]
`Fixed` available in next `pull-request`
