### ISSUE TITLE
Odds showing on desktop and not showing on mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#684]
https://scores.betarena.com/pt/futebol/brasil/serie-a

![Image](https://user-images.githubusercontent.com/37311649/192163422-160d2a06-1b86-43e8-9563-2ee687824005.png)

![Image](https://user-images.githubusercontent.com/37311649/192163478-b703154c-b6a0-46f6-8f2a-762a3236e994.jpg)

**Comment by migbash** [comment]
@jonsnowpt perhaps you have different `Bookmakers` selected on the devices ?

**Comment by jonsnowpt** [comment]
@migbash 

I confirmed at the time, and it was the same. I will be testing further, if it happens again, I will report it.
