### ISSUE TITLE
Fixtures Football Frontend Page Generation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#685]
The Frontend will consume the data sent by the historic_fixtures endpoint by publishing the various available fixtures pages. The information from the endpoint will also indicate which widgets should be integrated.

### Versions supported:

The fixtures are available in all versions, Desktop, Tablet, and Mobile.

### Initial State:

The fixtures section will have the breadcrumbs available by default, and only the fixtures with the status "published" should be accessible.

Data used for frontend page creation (endpoint: historic_fixtures):

```
sport = (breadcrumbs & URL)
country =  (breadcrumbs) = "league": { "data": { "country_id": 6783} = scores_football_countries = scores_general_translations = countries 
league_name = (breadcrumbs)
status = (Definition if the fixture is visible or not)
widgets = (The widgets that will be loaded on this fixtures section) = scores_widgets_list
```

**SEO**

The endpoint to get the SEO data: `scores_seo_fixtures`; depending on the language, the following data should be loaded:

The {} present in the data should be replaced by the correspondent variables:

{home_team_name}  = `historic_fixtures / home_team_name`
{away_team_name}  = `historic_fixtures / away_team_name`
{sport} = `historic_fixtures / sport`
{id} = `historic_fixtures / id`
{fixtures_day} = `historic_fixtures / fixture_day`
{data.venue.data.name} = `historic_fixtures / "venue": {"data": { "name": "Stadiumi Liri Ballabani"}`
{data.venue.data.city} = `historic_fixtures / "venue": {"data": { "city": "Burreli"}`

```
main_data
opengraph
twitter_card
```

**Make use of the hreflang for all available languages.**

    <link rel="alternate" hrefLang="en" href="https://scores.betarena.com/football/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="it" href="https://scores.betarena.com/it/calcio/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="es" href="https://scores.betarena.com/es/futbol/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="pt" href="https://scores.betarena.com/pt/futebol/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang=""pt-BR" href="https://scores.betarena.com/br/futebol/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="ro" href="https://scores.betarena.com/ro/fotbal/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="se" href="https://scores.betarena.com/se/fotboll/aston-villa-southampton-50977>
    <link rel="alternate" hrefLang="x-default" href="https://scores.betarena.com/football/aston-villa-southampton-50977>
    <link rel="canonical" href="https://scores.betarena.com/football/aston-villa-southampton-50977>

**Load the correct SEO information:**

All expressions inside {} should be replaced by the correct variables depending on the language, endpoint:

`scores_endpoints_translations`

SEO ENDPOINT:  `scores_seo_fixtures`

**Variables:**

```
{sport} = `historic_fixtures / sport`+ scores_endpoints_translations/cities
{data.venue.data.city} = `historic_fixtures / "venue": {"data": { "city": "Burreli"}` + scores_endpoints_translations/cities
```

**Example Content:**

```
main_data

{"title":"{home_team_name} vs {away_team_name} live score, H2H and lineups - - Betarena","noindex":"false","keywords":"{home_team_name}-{away_team_name}-live score","nofollow":"false","canonical":"http://scores.betarena.com/{sport}/{home_team_name}-{away_team_name}-{id}","description":"{home_team_name} {away_team_name} live score (with video online live stream) on {fixtures_day} at {data.venue.data.name}, {data.venue.data.city}. Best highlights, statistics, odds and standings."}

opengraph

{"url":"http://scores.betarena.com/{sport}/{home_team_name}-{away_team_name}-{id}","type":"website","title":"{name} {home_team_name} vs {away_team_name} live score, H2H and lineups - Betarena","images":[{"alt":"Betarena Live Score","url":"https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg","width":850,"height":650}],"locale":"en_GB","description":"{home_team_name} {away_team_name} live score (with video online live stream) on {fixtures_day} at {data.venue.data.name}, {data.venue.data.city}. Best highlights, statistics, odds and standings."}

twitter_card

{"site":"@betarenasocial","image":"https://www.betarena.com/wp-content/uploads/2021/12/betarena_scores.jpeg","title":"{name} {home_team_name} vs {away_team_name} live score, H2H and lineups - Betarena","imageAlt":"Betarena Live Score","description":"{home_team_name} {away_team_name} live score (with video online live stream) on {fixtures_day} at {data.venue.data.name}, {data.venue.data.city}. Best highlights, statistics, odds and standings."}
```

### Versions:

This section is available in the Light and Dark theme.

### Other remarks:

This section must respect the `historic_fixtures/publish_status` (if the status is draft, the fixtures page should not appear) and the widges_list (only widgets available to this section should be visible)

### Data Endpoints:

**Hasura endpoint Prod:**

```
historic_fixtures
scores_seo_fixtures
scores_general_translations
```

### SEO Cache data:

Breadcrumbs links should be visible on the SEO Cache Data.

### Hreflang Support:

Add alternate lang pages for search engine optimization.

### Resources

Figma Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=32%3A1635

**Comment by migbash** [comment]
`Complete` reflected in next `DEV pull-request`
