### ISSUE TITLE
Fixtures Status Setup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#686]
The default fixtures `publish_status` is "draft". This means that by default, the fixtures page is not visible and not included in the sitmaps. Only fixtures from supported leagues `leagues_supported_filter` have the default `publish_status` to "published". 

For testing purposes and to allow us to prepare this section, only the following fixture will be published:

`ID: 18535246`

After we finish all widgets and this section is ready, we will add more fixtures for testing purposes, and once everything is running as expected, we will then set up the logic to publish all fixtures from supported leagues.

We can always manually overwrite the fixture's status.

When changing the `historic_fixtures` `publish_status` from "draft" to "publish" it will affect the sitemaps, adding the fixture to the sitemap, the same if the inverse occurs, in case the fixture changes to "draft" `publish_status` it should be removed from the sitemaps.

### Steps:

**1. Publish the following fixture ID**

`ID: 18535246`

**Hasura endpoint Prod:** 

`historic_fixtures`

**Columns:**

`league_id`

#### THIS SECOND STEP IS ONLY DONE AFTER ALL WIDGETS ARE AVAILABLE AND SEVERAL FIXTURES TESTED.

**2. Change the fixtures `publish_status` for all supported `leagues_supported_filter`**

Verify the supported leagues:

`leagues_supported_filter`

Run on the "historic_fixtures" endpoint to change the `publish_status` from "draft" to "published".

**Comment by migbash** [comment]
`Point 1` - complete, fixture visible and enabled in `next pull-request`

**Comment by jonsnowpt** [comment]
@migbash 

I have changed the fixtures "publish_status" from "published" to "draft" and I can still access the fixtures, this should not be the case.

**Comment by jonsnowpt** [comment]
@migbash 

Does not seem to be working, changed the status for the following fixture:

`{"br":"https://scores.betarena.com/br/futebol/gillingham-afc-wimbledon-16952170","en":"https://scores.betarena.com/football/gillingham-afc-wimbledon-16952170","es":"https://scores.betarena.com/es/futbol/gillingham-afc-wimbledon-16952170","it":"https://scores.betarena.com/it/calcio/gillingham-afc-wimbledon-16952170","pt":"https://scores.betarena.com/pt/futebol/gillingham-afc-wimbledon-16952170","ro":"https://scores.betarena.com/ro/fotbal/gillingham-afc-wimbledon-16952170","se":"https://scores.betarena.com/se/fotboll/gillingham-afc-wimbledon-16952170"}`

Invoked the request from Hasura but none of the links are available:

https://betarena-scores-platform.herokuapp.com/br/futebol/gillingham-afc-wimbledon-16952170
