### ISSUE TITLE
Fixtures URL Creation

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#687]
In the same way, the URLs are created in the tournaments, a similar approach is applied to the fixtures URLs.

### Steps:

**1. Add the URLs to the `historic_fixtures` endpoint `urls`**

Collect the following information to populate the `urls` column.

All spaces should be replaced by "-" and all Upper cases should be changed to Lower.

**Hasura endpoint Prod:** 

`historic_fixtures`

**Columns:**

sport = `historic_fixtures/sport` + `scores_endpoints_translation/sports_translation`
home_team_name =  `historic_fixtures/home_team_name`
away_team_name = `historic_fixtures/away_team_name`

**Mock Data:**

https://cloud.hasura.io/project/1b086d12-8b64-462e-b7cc-f3f5e2c1702d/console/data/betarena_prod/schema/public/tables/historic_fixtures/edit

`{"br":"https://scores.betarena.com/br/futebol/leicester-city-southampton-18535246","en":"https://scores.betarena.com/football/leicester-city-southampton-18535246","es":"https://scores.betarena.com/es/futbol/leicester-city-southampton-18535246","it":"https://scores.betarena.com/it/calcio/leicester-city-southampton-18535246","pt":"https://scores.betarena.com/pt/futebol/leicester-city-southampton-18535246","ro":"https://scores.betarena.com/ro/fotbal/leicester-city-southampton-18535246","se":"https://scores.betarena.com/se/fotboll/leicester-city-southampton-18535246"}`

**Update frequency:**

The URL creation should always happen in the same loop used to populate the `historic_fixtures`.

**Comment by migbash** [comment]
`Urls` created and populated on backend `[deployed]`
