### ISSUE TITLE
Mobile CSS - Header logo incorrect, footer logo incorrect position, hamburger menu incorrect position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#7]
The mobile CSS is not correct. Follow Figma guidelines.

**Comment by migbash** [comment]
Amended - reflected in the next `Pull-Request`

**Comment by jonsnowpt** [comment]
@migbash 

The burger menu position is still incorrect, check the Figma design.

<img width="578" alt="Screenshot 2021-11-22 at 08 59 27" src="https://user-images.githubusercontent.com/37311649/142832245-aa56c0b8-5693-4ee8-9816-3f7753096b4b.png">

**Comment by jonsnowpt** [comment]
@migbash the logo used on mobile is also incorrect.
