### ISSUE TITLE
Routine to Update league_info cache

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#702]
Every day a job runs to check the competitions that have finished their rounds. When tournaments that have completed their round are identified, new content is generated for the league_info widget.

The job runs every day at 02:00 AM (London time).

It is necessary to create a routine that performs this check and refreshes the cache, in this case, at 05:00 AM (London time).

### Steps:

**1. Query the Hasura DB to identify tournaments that finished their rounds**

**Hasura endpoint Prod:** 

`scores_football_season_details`

**Columns:**

```
is_current_season
round_data
league_id
```

**Query Example**

```
query DAILY_TOURNAMENTS {
                  scores_football_seasons_details(where: {is_current_season: {_eq: true}, round_data: {_cast: {String: {_iregex: "2022-09-28"}}}}) {
                        is_current_season
                        round_data
                        league_id
                    }
            }
```

**Update frequency:**

Prod = Dailly at 05:00 AM (London Time)

**Comment by migbash** [comment]
`About League` widget data update
