### ISSUE TITLE
SEO Description in Italian and Swedish

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#716]
In this case the fixture day is not working:

"Leicester City Southampton  risultati dal vivo (con video in diretta streaming) il {fixture_day} a King Power Stadium, Leicester. Migliori quote, highlights, statistiche e classifiche."

"Leicester City Southampton  iveresultat (och gratis videoströmning över internet - live stream) startar {fixture_day} på King Power Stadium, Leicester. Höjdpunkter, statistik, odds, ställning."

**Comment by migbash** [comment]
@jonsnowpt that's not correct, it should be `{fixtures_day}` like in the rest of the `seo` properties and not `{fixture_day}`. This needs to be changed on the `Hasura`

**Comment by jonsnowpt** [comment]
@migbash 

You are right, I corrected Hasura now.
