### ISSUE TITLE
Featured Match Review - Missing Border on odds

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#76]
<img width="716" alt="Screenshot 2021-12-15 at 10 58 58" src="https://user-images.githubusercontent.com/37311649/146174664-9a40775c-3905-4c74-9e42-4927b08e2c41.png">

![Screenshot 2021-12-15 at 10 59 51](https://user-images.githubusercontent.com/37311649/146174689-a60cd113-6428-4609-9c4b-49ea6210e543.png)

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
