### ISSUE TITLE
Fixture Scoreboard not loading

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#779]
At least on Firefox this happened:

https://betarena-scores-platform.herokuapp.com/football/manchester-united-aston-villa-16924760

![Image](https://user-images.githubusercontent.com/37311649/197709673-9ded0a33-51f0-48aa-bf2b-6fda8220db21.png)

**Comment by jonsnowpt** [comment]
@migbash 

Now the link is not working:

https://scores.betarena.com/br/futebol/manchester-united-aston-villa-16924760

**Comment by migbash** [comment]
@jonsnowpt please `re-trigger` the `manual event` as `SEO` is automatically refreshed every 24h
