### ISSUE TITLE
Featured Match Review - Space available for a few more stream icons

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#78]
Isn't their space available on the right to avoid the stream icons being with that right space?

<img width="687" alt="Screenshot 2021-12-15 at 11 06 28" src="https://user-images.githubusercontent.com/37311649/146175913-862eda0f-2cea-4976-9162-39dbb435fae5.png">

**Comment by migbash** [comment]
Updated - changed the `figma` proportions to fit with the CSS
