### ISSUE TITLE
Fixtures Lineups - Field position

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#783]
It seems the position should be different here, please confirm if the provider do not define this.

![Image](https://user-images.githubusercontent.com/37311649/197719532-2c0f6c76-7d4c-4f52-b727-4b319e53d213.png)

![Image](https://user-images.githubusercontent.com/37311649/197719531-3722b7f1-c74d-43b6-a531-01e7fd6f8ec7.png)

**Comment by migbash** [comment]
@jonsnowpt Not defined properly

**Comment by jonsnowpt** [comment]
@migbash 

Did you follow the instructions here:

https://docs.sportmonks.com/football/how-to-guides/match-and-team-pages/how-to-build-a-match-page-with-line-ups-formations

**Comment by jonsnowpt** [comment]
@migbash 

The issue is that you pull the players back when there is one less line, but the goal is to keep them at the same distance in the back and at the end. Check here the example:



![Image](https://user-images.githubusercontent.com/37311649/197964031-621e529c-0bbb-418e-92e0-df95e45705db.png)
