### ISSUE TITLE
Featured Match Review - Background position is incorrect

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#79]
![Screenshot 2021-12-15 at 11 13 12](https://user-images.githubusercontent.com/37311649/146176626-4261ef52-fb22-4ed6-96c8-bbac971abed2.png)

<img width="2427" alt="Screenshot 2021-12-15 at 11 12 44" src="https://user-images.githubusercontent.com/37311649/146176632-192799c6-8851-4172-9a1a-fa399cfa43b4.png">

**Comment by migbash** [comment]
Updated - reflected in next `pull-request`
