### ISSUE TITLE
Fixtures - Time to load when changing browser size

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#792]
Is it possible to get the data loaded quickly when changing the size of the browser? Supposedly the data is already loaded; just changing the size of the components.

https://user-images.githubusercontent.com/37311649/197961985-1cf5135a-267e-4b7a-ba56-c686b9ecc336.mp4

**Comment by jonsnowpt** [comment]
@migbash 

This is happening again.

**Comment by migbash** [comment]
@jonsnowpt not possible at the current time due to `complex` widget ordering and cross-platform layout switching.

**Comment by jonsnowpt** [comment]
@migbash 

Are plans to be supported by other browsers?

**Comment by migbash** [comment]
@jonsnowpt not any time soon: https://caniuse.com/?search=masonry

But I am looking for an alternative
