### ISSUE TITLE
Featured Match translations string

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#80]
Now we have available expressions in the different languages for the widget title.

DB:

widget_title

<img width="1630" alt="Screenshot 2021-12-16 at 08 36 38" src="https://user-images.githubusercontent.com/37311649/146336816-d4e02ef1-4465-4f82-aa88-198e2cba7ac8.png">

**Comment by migbash** [comment]
Updated - reflected in the next `pull-request`
