### ISSUE TITLE
Fixture Lineups missing avatars

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#800]
![Image](https://user-images.githubusercontent.com/37311649/198085668-72e50eb8-4122-438b-80bc-451c187cfa54.png)

**Comment by migbash** [comment]
@jonsnowpt seems like a `Sportmonks` issue:

`Brugge`

![Image](https://user-images.githubusercontent.com/20924663/198095071-2003f929-34e6-4890-9159-1726e887a7a1.png)

`Porto`

![Image](https://user-images.githubusercontent.com/20924663/198095173-51678475-c383-45b3-928b-1981bbe0aa3a.png)

---

- https://cdn.sportmonks.com/images//soccer/coaches/24/523928.png
- https://cdn.sportmonks.com/images//soccer/coaches/25/121.png

![Image](https://user-images.githubusercontent.com/20924663/198095287-53438dfc-a4d2-4da1-af95-8cd8e7d33306.png)

**Comment by migbash** [comment]
@jonsnowpt about the missing `player-avatar` for `Slyia` looks like we do not have that player on our `DB` as its a newly added player, with `ID: 37630141`
