### ISSUE TITLE
Update past seasons tournaments data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#843]
The task to continue to update data from past seasons:

11/12
10/11
09/10
08/09
06/07
05/06

**Comment by migbash** [comment]
**NOTES**

> ⚙️ In process

**Comment by jonsnowpt** [comment]
@migbash 

Missing standings for 21/22 + 18/19 + 17/18 + 16/17 + 15/16 + 14/15 + 13/14 + 08/09 + 07/08 + 06/07

https://betarena-scores-platform.herokuapp.com/football/portugal/liga-portugal

Also, rating do not load on first load; we have to use the dropdown to get the data to appear.

**Comment by migbash** [comment]
**NOTES**

> Missing standings, missing seasons due to either, incorrect `format` or due to `league-name` change or `multipart` missing...

![Image](https://user-images.githubusercontent.com/20924663/218990780-cec9d658-91b7-48ef-9de1-53287e3741cb.png)

> ⚙️ processing backend `standings-history` DB

**Comment by jonsnowpt** [comment]
@migbash 

Still missing the data and issues with the player's ratings.

**Comment by migbash** [comment]
**NOTES**

- [x] `erroneous` past `Liga Portugal` standings updated (Hasura)
- [ ] (cont.) cache update
- [x] fixtures from 05/06 - 12/13 updated
