### ISSUE TITLE
Featured Match no Round info

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#854]
Even though this is a cup match, should have the round name as well ("1st Round Replays" in this case, refering to the stage_id)

![image](https://user-images.githubusercontent.com/114171785/201972412-99cc55a8-868d-44ad-8d56-8c3e0e5c5205.png)

**Comment by jonsnowpt** [comment]
When there is no information about the round, it should be replaced by the stage.

**Comment by jonsnowpt** [comment]
@migbash 

I will test later since we need a match outside the ones that have rounds.
