### ISSUE TITLE
Scoreboard incorrect image link

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#879]
https://scores.betarena.com/football/villefranche-versailles-18592218

![Image](https://user-images.githubusercontent.com/37311649/203961762-9c93ff22-0dd4-4c17-8e4b-26f919d92a5b.png)

https://cdn.sportmonks.com/images/images/soccer/teams/30/9662.png

should be:

https://cdn.sportmonks.com/images/soccer/teams/30/9662.png

**Comment by migbash** [comment]
**UPDATE**

Incorrect `provided` url, correct fixture with issues

> https://scores.betarena.com/football/rukinzo-tigre-noir-18572855
