### ISSUE TITLE
Fixtures voting not working on future fixtures

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#881]
https://scores.betarena.com/football/boca-juniors-estudiantes-18722725

![Image](https://user-images.githubusercontent.com/37311649/203977563-df8676ce-59c6-413f-8ad4-b12740ced2ab.png)

**Comment by migbash** [comment]
@jonsnowpt no `odds` nor no `probabilities` data for the such future `fixtures`... Is the value of **1** in calculations acceptable ? Or not show the `bet-site` section in such cases?

![Image](https://user-images.githubusercontent.com/20924663/207889280-dc29930b-f934-4be5-8618-8c464798350f.png)

**Comment by jonsnowpt** [comment]
@migbash, by default, adds 1.50, which usually is the minimum odds that bettors use when going in with a market.
