### ISSUE TITLE
Fixtures Lineups - Firebase data the Lineups wont completely appear

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#883]
![Image](https://user-images.githubusercontent.com/37311649/203990232-1624acf8-8ee6-4ce8-8417-29e1f8721e05.png)

**Comment by migbash** [comment]
**NOTES**

`Lineups` should be injected into the `data` when `fixture` goes **LIVE** (basically generate them inside the widget) as with the `cache` - to avoid the user having to `reload` the page to see changes / new data.
