### ISSUE TITLE
Fixtures Mobile - World CUP Logo issue

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#884]
The WC Logo is out of place.

![Image](https://user-images.githubusercontent.com/37311649/204025829-6a675c77-e483-4190-a703-a309bd3f839e.jpeg)

**Comment by migbash** [comment]
@jonsnowpt what browser was this `issue` detected ? Cannot replicate on any browser

**Comment by jonsnowpt** [comment]
@migbash iOS / Safari

**Comment by migbash** [comment]
**NOTE**

Cannot replicate on `iOS 16.2` nor `iOS 16` on emulators and `devices` views on `Safari`
