### ISSUE TITLE
Fixtures Group Stage Standings CSS Problems

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#885]
![Image](https://user-images.githubusercontent.com/37311649/204026550-ca9fb896-d76f-49f2-8b17-9744115ae5fe.jpeg)
![Image](https://user-images.githubusercontent.com/37311649/204026551-929656c1-8b7e-4a0f-8782-6ae1ca9792c5.jpeg)

**Comment by migbash** [comment]
@jonsnowpt is there a reason `light` and `dark` mode have different spacing for the `MOBILE` view of `Table 1` on standings ?

`LIGHT MODE`

![Image](https://user-images.githubusercontent.com/20924663/208473241-8a0998ab-9d90-4f96-8c2c-0de1959fc8aa.png)

`DARK MODE`

![Image](https://user-images.githubusercontent.com/20924663/208473327-7200d0b6-c245-4ed4-abd2-5458d371c3d8.png)

Or it's meant to be like that ?

---

**NOTE**

Not the same difference in `Group Stage` based standings.

**Comment by jonsnowpt** [comment]
@migbash its an error, should be the same size.
