### ISSUE TITLE
Top Players + League Info format

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#886]
The page for the Superleague of Argentina is different than the rest, with overlapping widgets

![image](https://user-images.githubusercontent.com/114171785/204029079-76c2899b-293d-45c9-a031-b02679bb1502.png)

**Comment by jonsnowpt** [comment]
The issue is that the Group Phase standings are being added when they shouldn't. This should be regular standings.

**Comment by jonsnowpt** [comment]
(The design team is creating an alternative for this view)

**Comment by jonsnowpt** [comment]
To address this issue we have added a new design alternative with phases to distribute the phases and leave the main information correctly visible.

![Image](https://user-images.githubusercontent.com/37311649/220984306-70c0599e-b0c0-4095-a058-1f1984363b77.png)

**Comment by jonsnowpt** [comment]
@migbash 

Im not able to close the dropdown outside the dropdown option.

The phase that is showing is the current one?
