### ISSUE TITLE
Several CUPs missing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#894]
The following tournaments seem missing:

https://scores.betarena.com/football/bulgaria/bulgarian-cup

https://scores.betarena.com/football/argentina/copa-argentina

https://scores.betarena.com/football/argentina/super-cup

https://scores.betarena.com/football/argentina/copa-de-la-superliga

**Comment by migbash** [comment]
- `no standing data` in `DB` for `.../football/bulgaria/bulgarian-cup` - `[no provided Sportmonks Data]`




- `no standing data` in `DB` for `.../football/argentina/copa-argentina` - `[no provided Sportmonks Data]`

- `no standings data` in `DB` for `.../football/argentina/super-cup` - `[no provided Sportmonks Data]`

**Comment by jonsnowpt** [comment]
@migbash 

Those are cups and do not have standings like the usual leagues.

The internal server error should not occur.
