### ISSUE TITLE
Fixture content tab

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#904]
- [x] Repeated content
- [x] Characters issue

![Image](https://user-images.githubusercontent.com/37311649/204812396-55398235-6959-4ee5-86bd-49f8e0c27ef2.png)

**Comment by migbash** [comment]
@jonsnowpt duplicate contents for the `posts` : `apostas_betarena`
- .../v2/posts/1068400
- .../v2/posts/1068768

Same for the other posts on the `fixture` (can check on `external_content` on Hasura) for this `gameid`
