### ISSUE TITLE
Wrong World Cup Group information

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#910]
1 - Senegal no info
2 - The +1.5 and +2.5 percentages make no sense in this case. There were only 3 matches played, and Equador had 1 with +2.5 goals, so should be 33% instead of 50%. Also, Qatar had only 1 match with +2.5 and the percentage of +2.5 is 25% instead of 33%

This happens in all other groups 

![image](https://user-images.githubusercontent.com/114171785/205352765-591bc576-3533-4d4c-b931-6b9b4c92b7d8.png)

**Comment by jonsnowpt** [comment]
@Acard0so 

Was already reported.
