### ISSUE TITLE
Tournaments - Add fixtures links in the SEO

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#921]
The fixtures links should be added to the SEO:

Example:

https://scores.betarena.com/pt/futebol/holanda/eerste-divisie

This should be added to all tournaments.

![Image](https://user-images.githubusercontent.com/37311649/206898497-301637e4-98fb-42b4-8fb3-638816e29de2.png)

**Comment by jonsnowpt** [comment]
@migbash 

All SEO links are incorrect and also, all fixtures links stopped working, For example:

https://betarena-scores-platform.herokuapp.com/football/cote-d'ivoire/ligue-1

**Comment by migbash** [comment]
@jonsnowpt all is correct, and there were no `count` issues to begin with. I have made the `SEO` a bit clearer to read.

Please check again, fixtures are labelled as `FIXTURE: ...` with any available `TIP_LINK` right under the `FIXTURE: ...` link.

Counted `34`

**Comment by jonsnowpt** [comment]
@migbash 

Yes, they were mixed with the tips, overlooked that.

Anyway, you need to remove the expressions since they won't work in different languages.

**Comment by migbash** [comment]
@jonsnowpt updated
