### ISSUE TITLE
Translation `errors`

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#924]
**OBSERVATION**

<img src="https://user-images.githubusercontent.com/20924663/207259638-8abf38cc-3b69-4498-bc3b-da1ac6d8c39b.png" alt="drawing" width="250"/>

from **scores_fixture_probabilities_translations**

> should be `Away Team Win` ?

---

<img src="https://user-images.githubusercontent.com/20924663/207259819-f84c9ade-df88-4f5d-89f3-69fd078daf9a.png" alt="drawing" width="150"/>
from **scores_fixture_probabilities_translations**

`undefined` meaning that are not matching the way the `odds` are presented in `probabilities` of `historic_fixtures` `<key>` names.

For example:

<img src="https://user-images.githubusercontent.com/20924663/207261155-8cda2874-8d2c-43ce-93c1-544c91de86e1.png" alt="drawing" width="150"/>

from **scores_fixture_probabilities_translations**

<img src="https://user-images.githubusercontent.com/20924663/207261226-4b2e3773-948b-48df-b8c7-0f4045af219e.png" alt="drawing" width="150"/>

from **historic_fixtures**

**Comment by jonsnowpt** [comment]
@migbash corrected.
