### ISSUE TITLE
Fixtures Probabilities keep loading (POSTPONED MATCH ISSUE)

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#925]
The Stats has problems also:

![Image](https://user-images.githubusercontent.com/37311649/207374187-f841758f-0872-4a75-8321-1a63eda2a8aa.png)

https://betarena-scores-platform.herokuapp.com/football/2-de-mayo-paranaense-521186

https://betarena-scores-platform.herokuapp.com/football/aalen-st-pauli-99402

**Comment by migbash** [comment]
**ADDITIONAL NOTES**

- `no probabilities` exist for those fixtures - missing dynamic validation

**Comment by jonsnowpt** [comment]
@migbash 

The stats keep showing without any info:



![Image](https://user-images.githubusercontent.com/37311649/207416229-cedefe62-d291-4881-86f7-a255ab91fd19.png)

**Comment by migbash** [comment]
@jonsnowpt what is the `fixture URL` for this `empty` - `STATS` ?

**Comment by jonsnowpt** [comment]
@migbash 

We seem to be missing any info on this fixture. Can you check the following:

https://betarena-scores-platform.herokuapp.com/football/dauphins-noirs-kuya-sport-18712641

**Comment by migbash** [comment]
@jonsnowpt That fixture I had taken a look - it was `POSTPONED`. Reason for the missing data.

**Comment by migbash** [comment]
@jonsnowpt what was meant to be done for the `fix` on this issue ?

> https://scores.betarena.com/football/dauphins-noirs-kuya-sport-18712641

`NOTE` #877 has already been fixed on `this` sprint, anything else for `POSTPONED` that should be different **UI** ?

**Comment by jonsnowpt** [comment]
@migbash 

Just to remove the incidents widget, in these cases, since it will show anything does not add a value to be there.


![Image](https://user-images.githubusercontent.com/37311649/208681466-ccdfe97e-d4e6-4aa1-af78-212e0c1d629e.png)

**Comment by jonsnowpt** [comment]
@migbash 

This still has issues:

- [ ] Postponed information not visible
- [ ] Betting logo still available




![Image](https://user-images.githubusercontent.com/37311649/208988924-b7df5c6c-b7a0-48b9-a2b5-f9688cf7b717.png)

**Comment by jonsnowpt** [comment]
@migbash 

Is not respecting the translations:

Endpoint:

`scores_livescore_football_translations`
