### ISSUE TITLE
Fixtures elements disappearing

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#930]
https://user-images.githubusercontent.com/37311649/207417925-cbb3d86f-cc82-40b2-8ccb-542d19b52dde.mp4

**Comment by migbash** [comment]
@jonsnowpt I cannot replicate this issue - tried on all browser types and quick/slow resizing doesn't break it. Can you show me the `console` on `developer-tools` when this happens ?

**Comment by jonsnowpt** [comment]
@migbash 

It seems to happen at a specific time of the match; it happened on PROD and DEV yesterday in 2 different browsers; I will try to replicate it today. This task will be on hold.

**Comment by jonsnowpt** [comment]
Resolved.
