### ISSUE TITLE
Fixtures Lineups - Players Ratings during the match

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#934]
At this time, the player's ratings are only being shown after the match, but this information is available during the match and should be visible and updated through Firebase.

![Image](https://user-images.githubusercontent.com/37311649/207562201-20ddb95b-7c94-44b9-a8e4-290d0c4e58e3.png)

**Comment by jonsnowpt** [comment]
@migbash 

Not working.

**Comment by migbash** [comment]
@jonsnowpt updated.

**NOTE**

Many fixtures do not provide `ratings` of the players in `LIVE` fixtures from `Firebase`. 

Please check on `Firebase` - `livescores_now` for `LIVE` fixtures with `lineup` or `bench` ratings.
