### ISSUE TITLE
Fixtures future games

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#937]
Future games should have the date and not the score, also the featured odds in the scoreboard should not be visible when they do not exist.

This is probably because the TBA status is not defined.

https://scores.betarena.com/br/futebol/belarus-lithuania-18704268

![Image](https://user-images.githubusercontent.com/37311649/207803386-819c2b53-a370-4c7c-b4f2-d9dbd8e2d407.png)

**Comment by migbash** [comment]
@jonsnowpt the `featured by {bet site}` should also be hidden when `odds` not available? In the `scoreboard`?

![Image](https://user-images.githubusercontent.com/20924663/208440232-96fe0a0e-c751-4f5c-83f8-21ca8e1c5fd4.png)

**Comment by jonsnowpt** [comment]
@migbash 

Exactly.

**Comment by jonsnowpt** [comment]
@migbash 

The problem persists:


![Image](https://user-images.githubusercontent.com/37311649/208991802-7bcc8be6-aa46-4a34-bf0b-2ebf684fd64b.png)

**Comment by jonsnowpt** [comment]
@migbash 

Missing the translations "TBA"

`scores_livescore_football_translations`
