### ISSUE TITLE
Widget league_about allow the use of embed youtube videos

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#938]
We will need to allow embedding videos from Youtube in the content about the competitions, present in all tournaments.

Example:

![Image](https://user-images.githubusercontent.com/37311649/207813659-33053167-c7e6-453c-af5b-869c56ed99f3.png)

Code:

`<style>
  /* Mobile styles */
  @media only screen and (max-width: 600px) {
    .video-container {
      width: 100%;
      height: auto;
    }
  }

  /* Desktop styles */
  @media only screen and (min-width: 600px) {
    .video-container {
      width: 100%;
      height: 470px;
    }
  }
</style>

<div class="video-container"><iframe src="https://www.youtube.com/embed/_M57oak4cCE?modestbranding=1&rel=0&controls=0&showinfo=0&playsinline=0&vq=hd1080" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
`

The embed is added to the content; it not needed to be added to the code. We need the CSS to take effect.

As an alternative we can embed with Svelte:

https://embed.sveltethemes.dev/

We can test on:

https://scores.betarena.com/football/world/world-cup

**Comment by jonsnowpt** [comment]
@migbash 

The height does not seem correct:



![Image](https://user-images.githubusercontent.com/37311649/210846137-bce80782-b385-4ac9-97ad-5d4e3dbdf1c7.png)

**Comment by migbash** [comment]
@jonsnowpt what's the expected height of the `video-container` ? It's been defined as `height: auto;` in the `example` - causing this height`. What's the `expected` height?

**Comment by jonsnowpt** [comment]
@migbash 

Lets try 250px.
