### ISSUE TITLE
Codespaces Setup

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#939]
#### 📝 DESCRIPTION

We are going to start using codespaces for development. Each programmer will have an identical setup to make it easier and faster to develop. This way, the onboarding process is almost immediate and avoids making secure data available in local development environments.

---

#### 💻 CONFIGURATION

- [x] Create a pre-build codespace for future use  https://github.com/Betarena/scores/settings/codespaces
- [x] Create codespace on the Scores Repo from the DEV branch;
- [x] Install all dependencies through `npm`;
- [x] Setup the ENV secrets;
- [ ] Enable necessary settings for code quality;

![Image](https://user-images.githubusercontent.com/37311649/207895714-1dec993d-8024-47da-b4af-1e04633589d9.png)

![Image](https://user-images.githubusercontent.com/37311649/207896112-9f4dd681-1f8a-4a93-8f4b-f6b3a0066212.png)

---

**Comment by migbash** [comment]
**NOTES**

> `devcontainer.json` [documentation](https://containers.dev/implementors/json_reference/)
