### ISSUE TITLE
Fixtures lineups Penalty kicks

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#944]
The penalty kick goals should also appear on the lineup widget; for example, in this match, Lionel Messi scored a penalty kick goal, but that is not visible in the lineup field.

https://betarena-scores-platform.herokuapp.com/pt/futebol/argentina-croatia-18452327

**Comment by migbash** [comment]
**NOTES**

- [x] frontend
- [ ] cache

**Comment by jonsnowpt** [comment]
@migbash 

Do we need to deploy to prod to see this change?

**Comment by migbash** [comment]
**NOTES**

> Updated
