### ISSUE TITLE
Fixtures probabilities missing BTTS market

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#945]
https://soccer.sportmonks.com/api/v2.0/predictions/probabilities/fixture/18544611

https://scores.betarena.com/pt/futebol/birmingham-city-reading-18544611

![Image](https://user-images.githubusercontent.com/37311649/208094652-c55da857-07d3-42af-baa5-5cd559fae9ed.png)

**Comment by migbash** [comment]
**NOTE**

> Updated
