### ISSUE TITLE
Fixture unable to access

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#947]
https://scores.betarena.com/pt/futebol/porto-gil-vicente-18702955

**Comment by migbash** [comment]
@jonsnowpt can access now. Keeping this issue open for any other future issues with `accessing` fixtures.

Please provide the:

- `console.log` screenshot from `DevTools`
- and `fixture-page` screenshot itself

on future issues encounters for me to know the error origin.

**Comment by jonsnowpt** [comment]
Not happeing at this time. If it happens again a new issue will be open.
