### ISSUE TITLE
All Leagues Long Scroll

### ISSUE THREAD

**Issue by Acard0so** [Betarena/scores#949]
Example: https://scores.betarena.com/football/portugal/liga-portugal

When scrolling down in each league page, the scroll keeps going, and the page gets all white, with no content, needs a break where the content ends

![image](https://user-images.githubusercontent.com/114171785/208496845-30e7ebc2-7889-45e4-84d2-ec582ee0a2aa.png)

**Comment by migbash** [comment]
**NOTES**

> Issue identified, to large of a `SEO` block - declared height was not enough to keep it `hidden` / `out of view`.
