### ISSUE TITLE
Fixtures H2H General Corrections

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#958]
- [x] The color bar with the least positive results should have a different color as shown on the design;
- [x] Follow bet is missing the link to the betting site (Should be "no-follow");
- [x] The betting site logo is missing the link (Should be "no-follow");
- [x] The date is getting undefined;
- [x] The widget order is incorrect;
- [x] Add links in the previous fixtures (Links accessible for SEO) with the hover as shown on Figma;
- [x] On Firefox, the column fill is not working correctly;
- [x] Translations are not working;

![Image](https://user-images.githubusercontent.com/37311649/210843149-fd5e8f53-ec7a-4f2e-ba91-7932707f6f6a.png)

![Image](https://user-images.githubusercontent.com/37311649/210843742-de579b9a-9068-44f9-b4ff-e1da3d4ab279.png)

**Comment by migbash** [comment]
@jonsnowpt Translations are all the same `(all in EN)` on the `scores_fixtures_h2h_translations` - needs updating

**Comment by migbash** [comment]
**NOTES**

Can't replicate the `undefined` date value:


![Image](https://user-images.githubusercontent.com/20924663/211078742-225a6db7-7e97-4927-8a37-ea2d9c7120d7.png)

**Comment by migbash** [comment]
**NOTES**

> .../football/benfica-portimonense-18560211

**Comment by jonsnowpt** [comment]
@migbash 

Missing months translations and the follow bet button with an incorrect design.

scores_general_translations

![Image](https://user-images.githubusercontent.com/37311649/211289470-e1b47fc0-1419-4e34-9ec4-520ae73a305a.png)
