### ISSUE TITLE
Fixtures H2H wrong data

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#959]
The data here is not correct and the decimals should be corrected.

![Image](https://user-images.githubusercontent.com/37311649/210871471-af74f9de-b226-4a1c-b5f2-1f9a41f8b9ee.png)

**Comment by migbash** [comment]
**NOTES**

> ... /football/santa-clara-sporting-braga-18560207

**Comment by jonsnowpt** [comment]
@migbash 

Still having issues here:



![Image](https://user-images.githubusercontent.com/37311649/211160972-91580c38-0fec-4e7a-a014-0ee1aa92fe75.png)

**Comment by jonsnowpt** [comment]
@migbash 

Undefined date persists.

**Comment by migbash** [comment]
@jonsnowpt what browser are you using ?

**Comment by jonsnowpt** [comment]
@migbash 

Safari.

**Comment by migbash** [comment]
**NOTES**

> `Safari 15.6` does not support `timezone` based `dates` conversions with `new Date(-date-)`
✅ Solution:
Use the `timestamp` for `new Date()` calculations
