### ISSUE TITLE
INFRA Migration from Heroku to Hetzner

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#960]
#### 📝 DESCRIPTION

Since HEROKU has been very limiting for the goals of our project, we are migrating from their infra to Hetzner Cloud.

---

#### 📍 GOALS:

- [x]  Select the Cloud instance base configuration;
- [x]  Configure and activate the new Cloud instance;
- [x] Add GitHub Actions to send the repo code to the new machine;
- [x] Add HTTPS and confirm that everything is working as desired;
- [x] After all, checks have passed, change the domain DNS to point to the new server;

---

#### 💻 Cloud options:

https://www.hetzner.com/cloud

---

#### 🚀 How to configure Github Actions on Hetzner Cloud instances:

- https://github.com/marketplace/actions/hetzner-cloud-unofficial
- https://github.com/saitho/hetzner-cloud-action
- https://github.com/hetznercloud
- https://github.com/marketplace/actions/timdaub-hetzner-cloud-deploy-server-action
- https://docs.hetzner.com/
- https://docs.hetzner.cloud/#overview

---

#### 🔗 External Provider if necessary:

https://ploi.io/

**Comment by migbash** [comment]
**NOTES**

@jonsnowpt I think the `CX21` cloud instance is the best option for now for the `website` deployment for now

**Comment by jonsnowpt** [comment]
@migbash 

Access details to the new Instance sent.

**Comment by migbash** [comment]
**NOTES**

> @jonsnowpt need to pause the `DNS` for `scores.betarena.com` and point them to the `Hertzer Server` to generate the `SSL/TLS` certificates for `https://` to complete migration

**Comment by jonsnowpt** [comment]
@migbash 

Were you able to test GitHub Actions first?

**Comment by migbash** [comment]
@jonsnowpt 

Yes, I have - **Automatic Deploys** are working, need some adjusting for the `main - pushes` only, but no issues there.

**Comment by jonsnowpt** [comment]
@migbash 

All seems to be working.
