### ISSUE TITLE
Fixture H2H error TypeError

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#993]
https://scores.betarena.com/pt/futebol/persikabo-1973-dewa-united-18579288

TypeError: n.teams_data.find(...) is undefined

![Image](https://user-images.githubusercontent.com/37311649/213524200-b89a8c4b-2bef-4ce6-90e2-b365a1045197.png)

**Comment by migbash** [comment]
**NOTES**

> Unknown error, added catch methods to `hide` widget as without the `teams_data.find(...` data - the widget cannot work properly. `⏸️ validating`
