### ISSUE TITLE
Fixture LineUps Mobile

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#998]
In several matches the initial Lineups if the user is on the fixture section it will not show any data, only an empty field; this issue does not occur on the desktop version.

![Image](https://user-images.githubusercontent.com/37311649/213530244-cac01026-d468-45eb-94b0-860c84a40025.jpg)

**Comment by migbash** [comment]
**NOTES**

> Updated for `team short-code` correct display

> Fixture `Lineups`  updated `⏸️ validating`

**Comment by jonsnowpt** [comment]
https://betarena-scores-platform.herokuapp.com/football/leeds-united-manchester-united-18535195

Fixtures missing information:


![Image](https://user-images.githubusercontent.com/37311649/218793876-57c1be96-dc98-4edc-bfe2-3eb71a2d73fd.png)

**Comment by migbash** [comment]
**NOTES**

> Updated

**Comment by jonsnowpt** [comment]
@migbash 

The standings widget now its present twice.

https://betarena-scores-platform.herokuapp.com/football/leeds-united-manchester-united-18535195
