### ISSUE TITLE
Fixtures H2H "Follow bet" translations

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#999]
Translate the expression "Follow Bet," available on:

`scores_fixtures_h2h_translations`

![Image](https://user-images.githubusercontent.com/37311649/213530870-fb6c5da3-3dc9-417e-aeae-47494fba8832.png)

https://scores.betarena.com/football/arsenal-manchester-city-18535272

**Comment by migbash** [comment]
**NOTE**

> Updated
